### ISSUE TITLE
npm run local is ok, but docker run is not.

### ISSUE THREAD

**Issue by wujun4code** [parse-community/parse-dashboard#1000]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Docker version 18.09.2, build 6247962
- node v11.10.0
- npm v6.8.0
- parse-dashboard v1.3.5
- parse-server is ok when request with .NET sdk or js SDK

#### Steps to reproduce

```sh
parse-dashboard --dev --allowInsecureHTTP true --appId parse-app-id --masterKey parse-app-master-key@k8s  --serverURL "http://parse-server.myhost.io:31992" --appName Parse Sever
```

it is ok with the following  screen:

![image](https://user-images.githubusercontent.com/5119542/53220758-259a1400-36a1-11e9-9a54-d8a80057ee60.png)

but when docker run it with:

```sh
docker run -d -p 4040:4040 parseplatform/parse-dashboard --dev --allowInsecureHTTP true --appId parse-app-id --masterKey parse-app-master-key@k8s  --serverURL "http://parse-server.myhost.io:31992" --appName Parse Sever
```

there will be a blank screen:

![image](https://user-images.githubusercontent.com/5119542/53220804-5ed28400-36a1-11e9-944f-44683da6bf53.png)

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by wujun4code** [comment]
the error maybe caused by React with babel.

**Comment by dplewis** [comment]
This has been fixed via https://github.com/parse-community/Parse-SDK-JS/pull/740

New release soon

**Comment by wujun4code** [comment]
Thanks a lot. @dplewis 
Will the docker image take the latest version Parse-SDK-JS automatily?

**Comment by dplewis** [comment]
The dashboard merges new releases
