### ISSUE TITLE
Any reason for no recent releases?

### ISSUE THREAD

**Issue by swilsonian** [parse-community/parse-dashboard#1037]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
Hi all,
Looks like its been more than a year since 1.2.0(released Mar 6, 2018), but no recent releases added to npm since then.

Its odd to me that the dashbaord is still actively being maintained, but no recent releases.
I'm trying to build from master for the dev option, but having lots of issues.

I'd much rather just 'npm i' the latest release..

#### Logs/Trace

[parse-dashboard]# sudo npm run build

> parse-dashboard@1.2.0 build /usr/share/node/my-parse-server/node_modules/parse-dashboard
> NODE_ENV=production webpack --config webpack/production.config.js && webpack --config webpack/PIG.config.js

(node:11011) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 1ae32fa202571224b31b
Version: webpack 4.29.6
Time: 593ms
Built at: 2019-03-27 13:30:47
 4 assets
Entrypoint dashboard = dashboard.bundle.js
Entrypoint login = login.bundle.js
Entrypoint PIG = PIG.bundle.js
Entrypoint quickstart = quickstart.bundle.js
 [2] ./parse-interface-guide/routes.js 248 bytes {0} [built] [failed] [1 error]
 [3] ./dashboard/index.js 273 bytes {1} [built] [failed] [1 error]
 [4] ./login/index.js 267 bytes {2} [built] [failed] [1 error]
 [5] ./parse-interface-guide/index.js 352 bytes {0} [built]
[12] ./quickstart/index.js 238 bytes {3} [built] [failed] [1 error]
    + 8 hidden modules

ERROR in ./parse-interface-guide/routes.js 15:0
Module parse failed: Unexpected token (15:0)
You may need an appropriate loader to handle this file type.
| 
| module.exports = (
> <Router history={history}>
|   <div>
|     <Route path='/:component?' render={(props) => {
 @ ./parse-interface-guide/index.js 10:0-30 14:16-22

**Comment by omairvaiyani** [comment]
+1 Is there scope to add more maintainers?

**Comment by Tom-Fox1** [comment]
@parse-community/core-maintainers There have been 115 commits since the last release, I’m not aware of the release process for this, would someone be able to create a new release?

**Comment by acinader** [comment]
I'll give it a go.

**Comment by dplewis** [comment]
Can someone review https://github.com/parse-community/parse-dashboard/pull/984? I cleaned it up.

**Comment by acinader** [comment]
@omairvaiyani there is absolutely scope to add more maintainers!

please hit me up on https://parseopensource.slack.com/ if you have any bandwidth to help out!!

**Comment by acinader** [comment]
ok, I gave it a go.

1. I think that getting `npm audit fix` to run and work would be nice.  I tried.  And failed and I don't have the time to learn what's going enough to really fix it.

2. I merged in all of the packages that went in easily.

Would be awesome if we could get someone with familiarity with webpack and react to give this some love.❤️
