### ISSUE TITLE
The single app redirect does not keep the root path of the dashboard

### ISSUE THREAD

**Issue by Helmikku** [parse-community/parse-dashboard#1054]
- [x] You're running version >=1.0.23 of Parse Dashboard.
- [x] You're running version >=2.3.2 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse Dashboard 1.3.0
Parse Server 2.8.4
express 4.16.4
node 10.15.3

#### Steps to reproduce

```
const Application = require('express')();
const ParseDashboard = require('parse-dashboard');
const ParseServer = require('parse-server').ParseServer;
Application.use('/parse', new ParseServer ({ ... }));
Application.use('/dashboard', new ParseDashboard ({ ... }));
require('http').createServer(Application).listen(process.env.PORT || '80', () => {
	console.log('Parse Server is at your service.');
});
```

Then `http://localhost/dashboard/apps` will redirect to `http://localhost/apps/nameOfApp`

Any shortcut such as:

http://localhost/apps/nameOfApp/browser/_User => fails
http://localhost/dashboard/apps/nameOfApp/browser/_User => redirects to http://localhost/apps/nameOfApp/browser/_Installation

Thanks for your help

**Comment by zenz** [comment]
Same situation here.
Parse-Server:3.2.3
Parse-Dashboard:1.3.0

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/1100

Please update to the latest version of the dashboard

**Comment by grx7** [comment]
Can you re-open? Since parse/apps will redirect to parse/apps/app-name/browser/_Role 

Dahsboard 2.0.5
v10.19.0
