### ISSUE TITLE
Cannot filter by ACL column

### ISSUE THREAD

**Issue by hjneves** [parse-community/parse-dashboard#1056]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

The overall idea is to be able to filter data for a specific user ACL.

#### Environment Setup
- Parse Server 2.8.0
- Parse Dashboard 1.2.0

#### Steps to reproduce
Open an existing class or create a new one. Select Filter, try to select ACL column but it does not appear.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by dplewis** [comment]
Would this be something you would want to work on?

Can you query objects by ACL?

**Comment by hjneves** [comment]
I could work, but I'm not sure if I have the knowledge to do it.

**Comment by dplewis** [comment]
There are features that exist like https://github.com/parse-community/parse-dashboard/pull/724

You can copy that and follow [Contribution Guide](https://github.com/parse-community/parse-dashboard/blob/master/CONTRIBUTING.md) (will be updated soon)
