### ISSUE TITLE
Hide/Unhide Columns in Data Browser

### ISSUE THREAD

**Issue by talkaboutdesign** [parse-community/parse-dashboard#106]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=2.1.4 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Feature

Would be a neat feature is you can hide certain fields from showing up in the dashboard based on class. Example hide createdAt, updatedAt. I imagine you can click on the field at the top, and a drop down shows you the option to hide that column.

**Comment by peterdotjs** [comment]
@talkaboutdesign thanks for bringing up the feature request. Having a hide/unhide option would be nice for classes that have lots of columns. Clicking on the field currently toggles the ascending and descending order so collapsing the a specific column would need to be in a right click context menu or another option in the edit menu.

If you're interested in contributing I can point you in the right direction.

**Comment by AmbroiseCollon** [comment]
Cout you provide those pointers ? Thanks !

**Comment by sendsol** [comment]
bump
