### ISSUE TITLE
Middleware routing is broken

### ISSUE THREAD

**Issue by kajensen** [parse-community/parse-dashboard#1072]
Hi, thank you for the Parse server and this dashboard library. It has been great over the years on several projects.

I noticed an inconvenience issue when updating from  to 1.3.0 (latest release) from 1.2.x. 

When using the dashboard as middleware, the path route (ex: "/dashboard") is not preserved when navigating in the dashboard. When manually refreshing, the paths break and you have to restart anything you were doing by manually changing to the dashboard root ("/dashboard").

**Comment by dplewis** [comment]
A PR has been submitted. https://github.com/parse-community/parse-dashboard/pull/1070

**Comment by kajensen** [comment]
Wow! Awesome. Thank you for the quick response. 

Hope to see this in a future release soon.
