### ISSUE TITLE
Version 1.3.1 not released properly

### ISSUE THREAD

**Issue by TomWFox** [parse-community/parse-dashboard#1086]
The 1.3.1 release seems to have not been published on either npm or Docker Hub...
<img width="86" alt="Screenshot 2019-05-22 at 17 32 04" src="https://user-images.githubusercontent.com/13188249/58191929-855f8580-7cb7-11e9-9431-170664e04ed4.png">
It does sometimes take a while for the new version to be published to npm but it has been 18 hours so I'm guessing something is wrong.

The Docker build seems to have been failing since db559a8471fa48d1d0795706abe697d6b8dca544...
<img width="502" alt="Screenshot 2019-05-22 at 17 32 34" src="https://user-images.githubusercontent.com/13188249/58191959-97d9bf00-7cb7-11e9-9f0c-95370c766f99.png">

I'm not sure what's going on here, ideas? @acinader @dplewis

**Comment by dplewis** [comment]
I opened a PR for the docker issue. https://github.com/parse-community/parse-dashboard/pull/1087

For NPM, I'm not sure but looking at the travis logs there does seem like an issue. I'd recommend setting `skip-cleanup: true` in travis.yml

**Comment by TomWFox** [comment]
The Docker build still seems to be failing, I’m assuming there are some logs on Docker Hub but if they exist I can’t access them.

**Comment by dplewis** [comment]
I don't have access either. @acinader Can you help us out?

**Comment by acinader** [comment]
will try

**Comment by acinader** [comment]
no joy. @flovilmart can you help?

**Comment by zenz** [comment]
any updates?

**Comment by acinader** [comment]
@zenz no

I currently don't have credentials for the dockerhub parse account, which will take some attention to resolve.  

Also, the issue that is preventing publishing will need to be diagnosed.

I have not looked at in detail yet and it could be a few more days before I can.

If anyone has some time to diagnose, that could be helpful.

**Comment by zenz** [comment]
I tried to add 1.3.1 from github url today. with command
yarn add https://github.com/parse-community/parse-dashboard#1.3.1

it process was success without any warning.
But after a restart, while access the dashboard url, it just bring me a blank page.
and checking the errorlog, there's nothing.

**Comment by dplewis** [comment]
Dockerhub build is working again!

@TomWFox Can you do another release 1.3.2?

**Comment by TomWFox** [comment]
yep, I'll do it now

**Comment by dplewis** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/1100

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)
