### ISSUE TITLE
can't build on Windows

### ISSUE THREAD

**Issue by oallouch** [parse-community/parse-dashboard#1097]
@dplewis Could you do on the dashboard what you did on the server, which is using cross-env ?
Even if I don't use the dashboard, I'd like to contribute.

**Comment by dplewis** [comment]
I'll investigate it soon, unless you want to give it a shot?

**Comment by oallouch** [comment]
It's the same as what you've done on the server. But, if you really don't have time, I can try.

**Comment by dplewis** [comment]
I use a Mac, should get my hands on a windows computer soon
