### ISSUE TITLE
Unable to connect to server behind elb - https to http

### ISSUE THREAD

**Issue by LoganLC** [parse-community/parse-dashboard#1102]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [✓ ] You're running version >=1.0.23 of Parse Dashboard.

- [✓ ] You're running version >=2.3.2 of Parse Server.

- [✓ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
parse dashboard 1.3.0
parse server 3.3.0
Bitnami Stack with apache server
AWS application elastic load balancer

#### Steps to reproduce
The parse dashboard returns a blank white screen after logging in when https traffic is routed through an elb.  The elb is set to route traffic over http to my Bitnami instance.  The dashboard works perfectly when accessed by elb with http.  However, the dashboard is unable to connect to the server when I access it through the elb with https.  I have no problem accessing parse server through the elb over https so this must be a dashboard problem.  I have tried setting my dashboard config a number of different ways with trustProxy and allowInsecureHTTP but nothing seems to work.  I am using the exact same serverURL as my parse server which is working fine.  My server logs show that I am getting the http traffic but nothing is being posted.  My parse logs don't show anything because no connection is made to the server.

My server.js is:
var trustProxy = true;
var dashboard = new ParseDashboard({
  apps: [
    {
      appName: "My Bitnami Parse API", 
      appId: "XXXXX",
      masterKey: "XXXX",
      fileKey: "XXXX",
      production: true,
      serverURL: "http://XXXX:80/parse"
    }
  ],
  trustProxy: 1,
   users: [
    {
      user: "test",
      pass: "password"
    }
  ],
  useEncryptedPasswords: true
});

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by acinader** [comment]
if you open your console, do you see a js error?

fyi, I have run the dashboard via elb, so it should be doable unless we've introduced a regression recently?

**Comment by mtrezza** [comment]
Running the dashboard behind ELB on EB and works fine on 1.4.1 via http and https. This does not seem to be an issue regarding this product, I suggest you contact AWS technical support for ELB routing rules support.
