### ISSUE TITLE
Bad displayed filename

### ISSUE THREAD

**Issue by yagotome** [parse-community/parse-dashboard#1121]
Hello folks!

I realized that the filename [displayed in `BrowserCell`](https://github.com/parse-community/parse-dashboard/blob/c4e238ffacd025b9ebd447ec2216f39feb1fe84f/src/components/BrowserCell/BrowserCell.react.js#L61) is not like the original name of the file (the name after first `_`).

Then, I ended up finding this:

https://github.com/parse-community/parse-dashboard/blob/c4e238ffacd025b9ebd447ec2216f39feb1fe84f/src/lib/getFileName.js#L14-L18

According to [parse server's source](
https://github.com/parse-community/parse-server/blob/d83a0b680854f52ce30205d3558c0133d7f8cf19/src/Controllers/FilesController.js#L29) `offset` should be either `32` or `name.indexOf('_') + 1`, shouldn't it?

**Comment by douglasmuraoka** [comment]
@yagotome thanks for reporting the issue. Yes, this function seems to be outdated. Could you send us a PR to fix this?

**Comment by yagotome** [comment]
@douglasmuraoka , thanks for responding. Sure! I am going to send you a PR with that fix soon.

**Comment by douglasmuraoka** [comment]
Thank you @yagotome for your awesome PR! :)
