### ISSUE TITLE
Master fails to install graphql-playground

### ISSUE THREAD

**Issue by acinader** [parse-community/parse-dashboard#1131]
@douglasmuraoka 

I'm trying to put together a release to get your awesome fix and new feature out.

When I try to do a clean install on master I get this error:
```
npm ERR! Could not install from "node_modules/graphql-playground-react/codemirror-graphql@github:timsuchanek/codemirror-graphql#801ec32683c38d6dc0f8f7bc19014a111edc9ebd" as it does not contain a package.json file.
```

I opened an issue on the graphql-playground repo:

https://github.com/prisma/graphql-playground/issues/1052

I'll close this and release when resolved.

**Comment by douglasmuraoka** [comment]
@acinader looks like the problem was the `package-lock`. I've just created a brand new file and it is working now.

**Comment by acinader** [comment]
any interest in putting together the release?

**Comment by douglasmuraoka** [comment]
@acinader do you have some guideline to follow when launching new releases?

**Comment by acinader** [comment]
nothing formal, but it is pretty straight forward:

I think this should be 1.4.0 because we are adding non-breaking functionality

- create a pull request to get things ready
1. View the full changlog and update the CHANGELOG.md file
2. Set the version in package.json and then run npm install to generate the lock file

- Use github to create the release and follow the format of previous releases.  When you publish the release, travis will deploy it to npm (you can see the .travis.yml file to see how that is configured).

If you screw up somehow, don't sweat it, we can just do another release to fix anything.

Good luck!

@TomWFox fyi.

**Comment by douglasmuraoka** [comment]
@acinader @TomWFox pull request created #1134
