### ISSUE TITLE
npm WARN deprecated cryptiles@4.1.2 and boom@7.3.0

### ISSUE THREAD

**Issue by laticq** [parse-community/parse-dashboard#1137]
I'm trying to update the `parse-dashboard` to the latest version, but nothing happens because of the following errors:
```
npm WARN deprecated cryptiles@4.1.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). 
Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. 
Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
```

**Comment by davimacedo** [comment]
@laticq thanks for reporting. I also see the warnings but it is running for me besides the messages. Anyway, we need to fix it. @douglasmuraoka could you please take a look on this?

**Comment by douglasmuraoka** [comment]
I'll take a look into it now. Thanks for reporting @laticq :)

**Comment by douglasmuraoka** [comment]
@davimacedo @acinader looks like #1131 is back due to the `package-lock.json` change from #1138. To solve this locally, I had to update my `npm` version to `latest` and generate a brand new `package-lock.json`. However, now I'm not secure that It will solve this problem for good since any random build is capable of breaking it again.
Any thoughts? Should we update `npm` version from travis as well?

**Comment by davimacedo** [comment]
@douglasmuraoka and @acinader  please take a look at https://github.com/parse-community/parse-dashboard/pull/1143

@laticq in the meantime, you can install the latest version from the npm instead of the master branch

**Comment by Eolykab** [comment]
Getting this error. Working fine on my local computer. But not on the server. Was this issue resolved?

**Comment by acinader** [comment]
yes.  are you sure that your server is trying to npm install the latest version of the dashboard (2.0.4)?

**Comment by Eolykab** [comment]
Yes It is on the latest as well

**Comment by acinader** [comment]
can you post your npm debug log?

**Comment by Eolykab** [comment]
I checked on the server. Dokku was not pushing my commits for some reason. It is now working. Thanks
