### ISSUE TITLE
GraphQL Console API not working

### ISSUE THREAD

**Issue by Eolykab** [parse-community/parse-dashboard#1147]
I have upgraded Parse Dashboard and Parse server to get the GraphQL console but it does not seem to be working. 

What I have set:

![Screenshot from 2019-07-16 22 21 08](https://user-images.githubusercontent.com/16737946/61327081-6ba27080-a818-11e9-961b-f310eb5dd3d2.png)
![Screenshot from 2019-07-16 22 19 36](https://user-images.githubusercontent.com/16737946/61327115-7a892300-a818-11e9-9565-630dbb337259.png)

Error I am getting : 

![Screenshot from 2019-07-16 22 18 08](https://user-images.githubusercontent.com/16737946/61327135-8543b800-a818-11e9-80bb-9226ddb834e2.png)
![Screenshot from 2019-07-16 22 18 49](https://user-images.githubusercontent.com/16737946/61327144-8a086c00-a818-11e9-87d3-586fd75f245f.png)

Can you please advise on what I need to do?

**Comment by Eolykab** [comment]
It seems like the cannot reach or get /graphql endpoint is there anything am I missing?

**Comment by davimacedo** [comment]
You are mounting Parse Server as a middleware of an Express.js application, right? Can you please double check if you mounted GraphQL API as described in the link below?
http://docs.parseplatform.org/graphql/guide/#using-expressjs

**Comment by Eolykab** [comment]
I used these settings https://github.com/parse-community/parse-dashboard#graphql-playground

**Comment by davimacedo** [comment]
This is for the dashboard setup. You also need to setup Parse Server to mount the GraphQL API in addition to the REST API. Take a look in the link I sent you.

**Comment by Eolykab** [comment]
Thanks @davimacedo it is working like a charm.

**Comment by xiangdong9013** [comment]
I got the same question too! So ,what's the point?

**Comment by davimacedo** [comment]
@xiangdong9013 can you please share the setup that you are using for Parse Server and Parse Dashboard so I can help you?

**Comment by aacassandra** [comment]
@davimacedo 
why don't you post your answer here. maybe someone needs your answer here. like me i have followed the docs but still getting the error.

```
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2865938\n    at u (http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:1860351)\n    at Generator._invoke (http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:1860139)\n    at Generator.next (http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:1860780)\n    at $c (http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2307031)\n    at a (http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2307235)\n    at http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2307296\n    at new Promise (<anonymous>)\n    at http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2307175\n    at http://localhost:4040/dashboard/bundles/dashboard.bundle.js:2:2866223"
    }
  ]
}
```

**Comment by davimacedo** [comment]
The answer is actually described above. You only need to make sure that you have mounted the GraphQL API to Parse Server as well, according to the link below: http://docs.parseplatform.org/graphql/guide/#using-expressjs
