### ISSUE TITLE
Scroll on Logs page not working

### ISSUE THREAD

**Issue by edson-gaspar** [parse-community/parse-dashboard#1167]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server version: 3,5,0
Parse Dashboard: 1.4.1

#### Steps to reproduce
Go to Dashboard Logs page, the page not scroll when logs don't fit on page.

**Comment by davimacedo** [comment]
@alencarlucas can you please tackle this one? Can you please also test and make sure that the same problem is not happening in other screens?

**Comment by alencarlucas** [comment]
Sure! I'm working on this.

**Comment by davimacedo** [comment]
@edson-gaspar it seems that the bug is already fixed in the master branch. You should not have this problem in the next version. Meanwhile you can install from master.
