### ISSUE TITLE
PermissionsDialog state not updating

### ISSUE THREAD

**Issue by davimacedo** [parse-community/parse-dashboard#1182]
If you apply some changes in CLP and open the PermissionsDialog again, the state is still the previous one.

@alencarlucas @douglasmuraoka would any of you guys be able to tackle this one?

**Comment by alencarlucas** [comment]
I'm working on this!

**Comment by alencarlucas** [comment]
@davimacedo How we noticed, this issue is a server-side one and was fixed in [#5877](https://github.com/parse-community/parse-server/pull/5877)

**Comment by davimacedo** [comment]
Nice. Thanks for working on this!
