### ISSUE TITLE
Version 1.4.2 not released properly

### ISSUE THREAD

**Issue by TomWFox** [parse-community/parse-dashboard#1191]
@natanrolnik the version in package-lock.json is still 1.4.1 so the new version hasn’t been published to npm.

**Comment by TomWFox** [comment]
Well ignore me! It has now been published but the lock file should probably still be incremented.

**Comment by davimacedo** [comment]
@TomWFox I think it is better release a new one fixing it: https://github.com/parse-community/parse-dashboard/pull/1192

**Comment by natanrolnik** [comment]
Oh, I forgot to add it to the lock. My bad 😕

**Comment by natanrolnik** [comment]
Closed by #1192 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
