### ISSUE TITLE
Missing font in app list

### ISSUE THREAD

**Issue by natanrolnik** [parse-community/parse-dashboard#1194]
Not sure if anyone else noticed, but in the latest releases (1.4.0 or even earlier), the font used in the app list is not being displayed correctly.

@tomwfox and @davimacedo did you notice that?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by davimacedo** [comment]
I've just checked here and it looks good to me. Can you send a screenshot?

**Comment by natanrolnik** [comment]
Sure, @davimacedo!
Notice how the fonts in the apps list and "Your Apps" are different than the one in "Open Source Hub":

![Captura de Tela 2019-07-31 às 11 44 01](https://user-images.githubusercontent.com/1164565/62197501-9ba95200-b388-11e9-9379-906e2e21099f.png)

**Comment by davimacedo** [comment]
I got it. We can see [here](https://github.com/parse-community/parse-dashboard/blob/master/.github/dash-shot.png) that it was actually different in the past and it looked like better. @alencarlucas is this something that you could try to address?

**Comment by alencarlucas** [comment]
Sure! I'll take a look at this.
