### ISSUE TITLE
Logout button not working? 

### ISSUE THREAD

**Issue by rameshkec85** [parse-community/parse-dashboard#1198]
I have run parse dashboard locally provided on the instructions in Readme page. I have added configuration file with app and users information. Now i am able to see login page. But when i clicked on Logout button, it not redirecting to login page (still it is on dashboard page.). 

Do we need to configure it anywhere in the code ?

**Comment by davimacedo** [comment]
Can you please confirm the version that you are running?

**Comment by mtrezza** [comment]
Closing because I'm not able to reproduce this with the latest version of Parse Dashboard.
