### ISSUE TITLE
GraphQL Playground not loading

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-dashboard#1200]
When running the playground locally, I'm able to connect to the GraphQL server. Also when I postman into `/graphql`, everything work's fine. But if I load the playground through Parse Dashboard, I get `net::ERR_FAILED`.

I can confirm that the url and headers are all fine. Everything matches when loading playground directly vs. loading in Parse Dashboard.

**Comment by davimacedo** [comment]
@omairvaiyani I couldn't reproduce the problem. Do you mind to share the steps that you are using to run both parse server and parse dashboard? Are you using the CLI? Can you please also share the versions of node.js, npm, parse-server and parse-dashboard that you are running? If you use the following sequence, does it work?

```
$ npm install -g parse-server mongodb-runner
$ mongodb-runner start
$ parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test --mountGraphQL --mountPlayground
$ npm install -g parse-dashboard
$ parse-dashboard --dev --appId APPLICATION_ID --masterKey MASTER_KEY --serverURL "http://localhost:1337/parse" --graphQLServerURL "http://localhost:1337/graphql" --appName MyAppName
```

**Comment by omairvaiyani** [comment]
@davimacedo hey so sorry, this was definitely a (very edge-case) setup issue with my architecture!

**Comment by davimacedo** [comment]
glad to know it worked!
