### ISSUE TITLE
Scroll on API Console Page

### ISSUE THREAD

**Issue by camdagr8** [parse-community/parse-dashboard#1212]
If you run an API Console command that forces the page to scroll, it doesn't scroll. 
Looks like this is fixable by setting this css: `body { overflow-y: auto; }`

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
    "parse": "^1.11.1",
    "parse-dashboard": "^1.2.0",
    "parse-server": "^3.1.3",

#### Steps to reproduce
Run a console function that will force the page to scroll

**Comment by davimacedo** [comment]
This problem was solved recently. Can you please update the Parse Dashboard to the latest version and check again?

**Comment by TomWFox** [comment]
If you still experience this issue on the latest version let us know.
