### ISSUE TITLE
When creating a new Pointer field, classes are in arbitrary order

### ISSUE THREAD

**Issue by woodardj** [parse-community/parse-dashboard#1234]
When adding a new Column of type `Pointer`, the dropdown menu for Target Class is in some inscrutable order, should be alphabetical, or at least predictable.

<img width="569" alt="Screen Shot 2019-08-21 at 12 36 40" src="https://user-images.githubusercontent.com/557897/63434022-87ef8980-c424-11e9-853c-6619d935d9ad.png">

Parse Server 3.0, Parse Dashboard 1.3.3

**Comment by dplewis** [comment]
Would you like to open a PR and provide a fix?

**Comment by mtrezza** [comment]
I can confirm this issue still exists on version 3.2.0.
