### ISSUE TITLE
Feature request: Searchable Filters

### ISSUE THREAD

**Issue by christopherturinsky** [parse-community/parse-dashboard#1236]
As I'm working with parse dashboard on a daily basis I have some features/adaptions I would love to see being implemented ;) One of them is the following:

**Searchable Filter:**
As some of our collections have a lot of fields it would be nice to just type the first char(s) and get only the fields matching shown like in the image below.

![Bildschirmfoto 2019-08-23 um 08 53 08](https://user-images.githubusercontent.com/46715572/63572653-a15b1780-c583-11e9-8f43-38895fb9388f.png)

**Comment by TomWFox** [comment]
Could you split these feature requests into two separate issues and title them as such so we can more easily discuss/track these features?

Also we have a great team reviewing PRs on this repo now so feel free to have a stab at these features and ask for help if needed.
