### ISSUE TITLE
`npm run pig` return blank page on Windows

### ISSUE THREAD

**Issue by JeromeDeLeon** [parse-community/parse-dashboard#1266]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ /] You're running version >=1.0.23 of Parse Dashboard.

- [ /] You're running version >=2.3.2 of Parse Server.

- [ /] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Node: 10.16.3
Parse-dashboard: 2.0.1

#### Steps to reproduce
Fork master and install then do `npm run pig`

#### Logs/Trace
here's what I got after running `PIG`
> parse-dashboard@2.0.1 pig D:\Project\ReactJS\parse-dashboard-master
> http-server ./PIG -p 4041 -s & webpack --config webpack/PIG.config.js --progress --watch

![image](https://user-images.githubusercontent.com/32805276/64308401-b1371a80-cfcb-11e9-9ec3-f5a7370cc2ab.png)

**Comment by JeromeDeLeon** [comment]
`npm run dashboard` doesn't have this issue.

**Comment by dplewis** [comment]
I see there are two commands here.

`webpack --config webpack/PIG.config.js --progress --watch`
Does this build `/PIG` folder?

`http-server ./PIG -p 4041`
Does the server starts?

Sorry I don't have a windows computer.

**Comment by JeromeDeLeon** [comment]
yes, I have `PIG` folder, but I don't have any logs running after the two I mentioned above.
