### ISSUE TITLE
Filter tap not opening

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1271]
- [ X] You're running version >=1.0.23 of Parse Dashboard.

- [ X] You're running version >=2.3.2 of Parse Server.

- [ X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
parse dashboard 2.0.1
browser safari 12.1.2
browser chrome 76.0.3809.132 (Official Build) (64-bit)
macOS 10.14.6

#### Steps to reproduce
When clicking on the "Filter" tap in the data browser, the tab does not open. Other taps open just fine, e.g. when clicking the "Edit" button. Restarting the browser does not help.

This happens since upgrading parse dashboard from 1.4.3 to 2.0.1.
Possibly introduced with https://github.com/parse-community/parse-dashboard/pull/1229.

#### Logs/Trace
- (none)

**Comment by davimacedo** [comment]
it is actually not working for classes starting with "_". This PR should fix it: https://github.com/parse-community/parse-dashboard/pull/1275
