### ISSUE TITLE
The option to delete 1 or several rows is disabled.

### ISSUE THREAD

**Issue by skinner2012** [parse-community/parse-dashboard#1277]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [Yes ] You're running version >=1.0.23 of Parse Dashboard.

- [ Yes] You're running version >=2.3.2 of Parse Server.

- [Yes ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

The latest version of Parse Dashboard (2.0.1), and Parse and Parse-Server also are the latest. I upgrade them today.

#### Steps to reproduce

Choose 1 or 2 rows, the option (Edit -> Delete these rows) is disabled. 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by davimacedo** [comment]
This is a bug of last release that was already fixed [here](https://github.com/parse-community/parse-dashboard/pull/1276).

I've just prepared a new release [here](https://github.com/parse-community/parse-dashboard/pull/1278) that will be published as soon as possible with the fix.

**Comment by KeiroMidori** [comment]
Thank you so much !
