### ISSUE TITLE
When 2.0.3 will be released in npm? 2.0.2 has critical bugs with CLP dialog

### ISSUE THREAD

**Issue by Klucherev** [parse-community/parse-dashboard#1293]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [ ] You're running version >=2.3.2 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by TomWFox** [comment]
I’m happy to make a release today, @davimacedo what do you think?

**Comment by davimacedo** [comment]
Sure! Go for it.

**Comment by Klucherev** [comment]
Thank you very much!
