### ISSUE TITLE
Not able to delete row in class

### ISSUE THREAD

**Issue by Alicealpha** [parse-community/parse-dashboard#1305]
version = 2.0.3 of Parse Dashboard.
version = 3.9.0 of Parse Server.

**Cannot delete the specified row in clas**

![image](https://user-images.githubusercontent.com/18365427/65567376-96334700-df88-11e9-9cbf-c5d579ecf8b0.png)

**Comment by davimacedo** [comment]
Do you have any trigger in this class?

**Comment by Alicealpha** [comment]
Triggered button

**Comment by Alicealpha** [comment]
> Do you have any trigger in this class?

Triggered button

**Comment by davimacedo** [comment]
I think you misunderstood my question. Do you have a `beforeSave` or `afterSave` trigger in your cloud code for this class?
