### ISSUE TITLE
Incredibly slow install

### ISSUE THREAD

**Issue by ggrimbert** [parse-community/parse-dashboard#1320]
Hi, 

I am experiencing some problems with the last version of parse dashboard. The issue is that the ```npm install``` goes from 1 minute to 15.

With the version 1.2.0; ```npm install``` take 40 seconds with the dependencies below; but with the 2.0.3 version, it takes more than 15 minutes. 
It seems to hang on two tasks : 
- npm timing stage:loadIdealTree
- npm timing action:extract

Here are the full logs for the slow install.
[npmInstallParse.txt](https://github.com/parse-community/parse-dashboard/files/3675224/npmInstallParse.txt)

I can assure you that our internal repository doesn't slow down the network.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
 Ubuntu 16.04; node 8.11

#### Steps to reproduce
Use these dependencies : 
```json
"dependencies": {
    "express": "^4.15.3",
    "graphql": "14.5.3",
    "node-schedule": "^1.3.2",
    "parse-dashboard": "2.0.3",
    "parse-server": "3.9.0"
  },
  "devDependencies": {
    "tslint": "^5.10.0",
    "typescript": "3.5.3"
  }
```

#### Logs/Trace
```
08:24:48 npm http fetch GET 200 https://nexusm-repo-mob.apps.eul.sncf.fr/repository/npm-groupeaes/cross-fetch 184ms
08:32:27 npm info lifecycle codemirror-graphql@0.6.12~prepack: codemirror-graphql@0.6.12
08:32:27 npm info lifecycle codemirror-graphql@0.6.12~postpack: codemirror-graphql@0.6.12
08:32:27 npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 474675ms
08:32:27 npm timing stage:loadIdealTree Completed in 475124ms
08:32:28 npm timing stage:generateActionsToTake Completed in 510ms
[...]
08:32:41 npm http fetch GET 200 https://nexusm-repo-mob.apps.eul.sncf.fr/repository/npm-groupeaes/aws-sdk/-/aws-sdk-2.539.0.tgz 11225ms
08:40:03 npm timing action:extract Completed in 454523ms
08:40:05 npm timing action:finalize Completed in 1431ms
08:40:07 npm timing action:refresh-package-json Completed in 1900ms
```

**Comment by davimacedo** [comment]
I've just installed the dependencies in 20s:

```
added 737 packages from 1671 contributors in 21.253s
```

Can you share more details about your environment?

**Comment by ggrimbert** [comment]
We use Jenkins to install the dependencies, we don't have more informations about this environment.

**Comment by GSZS** [comment]
I also have the same situation in version 2.0.3, the installation takes a lot of time

**Comment by ggrimbert** [comment]
I don't know how but using an older version of npm the install is really faster

**Comment by dplewis** [comment]
It might come from puppeteer (used for testing) downloads chromium. You can use an environment variable to skip downloading it.

https://github.com/GoogleChrome/puppeteer/blob/v0.10.2/docs/api.md#environment-variables

**Comment by ggrimbert** [comment]
There's no trace of puppeteer in the install logs

**Comment by davimacedo** [comment]
Could you guys share the versions of npm and node.js that you are currently using?

**Comment by ggrimbert** [comment]
We use node v8.16.1; with npm v6.4.1
It's the version 4.6.1 that makes ths install faster
