### ISSUE TITLE
no warning dialog before deleting config parameter

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1323]
#### Issue
When deleting a Parse Config parameter by clicking on the trash icon <img width="43" alt="image" src="https://user-images.githubusercontent.com/5673677/66041140-6d2b2d00-e519-11e9-9062-432b75aa30e4.png"> the parameter is deleted without showing a warning dialog.

As it can happen that the trash icon is clicked by mistake, one wouldn't easily see which parameter has been deleted in a long list of parameters. There is also no built-in way to easily restore a key and value that has been deleted by mistake.

#### Suggested solution
Add a warning dialog for the user to confirm the deletion. Similar to the warning dialog when deleting a row.

<img width="554" alt="image" src="https://user-images.githubusercontent.com/5673677/66041327-e591ee00-e519-11e9-9825-727241328e5c.png">

The warning dialog should at least include the parameter's key name.

#### Environment Setup
- Parse Dashboard 2.0.3

#### Steps to reproduce
--

#### Logs/Trace
--

**Comment by davimacedo** [comment]
I like the idea. Would you be willed to add this one?

**Comment by mtrezza** [comment]
At the moment not, but maybe someone wants to pick it up.

**Comment by mtrezza** [comment]
reopen, PR in the works

**Comment by mtrezza** [comment]
@davimacedo can you reopen please, PR in the works

**Comment by davimacedo** [comment]
Sure!

**Comment by mtrezza** [comment]
PR merged

**Comment by mtrezza** [comment]
@davimacedo When can we expect the next release? I would like to see this feature added.

**Comment by davimacedo** [comment]
Go for it @TomWFox . We have a lot of good stuff here ready to be released.
