### ISSUE TITLE
Custom API Console URL

### ISSUE THREAD

**Issue by gregorskii** [parse-community/parse-dashboard#1325]
Hi there,

The API Console appears to use the app.serverURL to make requests from the client:

https://github.com/parse-community/parse-dashboard/blob/master/src/dashboard/Data/ApiConsole/request.js

I think this may be causing issues when running the dashboard in Docker.

Docker reports from the CLI side that it cannot connect to the serverURL at start:

```
WARNING, Unable to connect to 'http://localhost:9080/api'. Cloud code and push notifications may be unavailable!
```

If the serverURL is a host specific URL which is used by the console in the browser to make requests.

Is there a difference between the way parse makes requests on the node side versus the dashboard side?

Thanks for any help.

**Comment by davimacedo** [comment]
Your problem is not so clear to me. This log is actually written by Parse Server (not Parse Dashboard). Can you please share how you are initializing both Parse Server and Parse Dashboard?

**Comment by gregorskii** [comment]
Ya I think I was misunderstanding how the dashboard runs. It does not run in node other than serving it to the client.

Thanks.
