### ISSUE TITLE
Feature Request: use select when columns are "hidden"

### ISSUE THREAD

**Issue by mrmarcsmith** [parse-community/parse-dashboard#1330]
Now that we have the ability to hide certain columns it would be a cool performance boost to use the select value to only fetch the columns that aren't hidden. This would both reduce the amount of data sent to the dashboard and allow for "covered" queries in mongo that only use the RAM index to fulfill the request. 

In the case that we "un-hide" a column after loading we could display a [Please refresh to view value] box. once they refresh or reload the data would be there.

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/1694
