### ISSUE TITLE
Calls To Logs Endpoint Lead To High Cpu and Ram Usage Then Crash !!

### ISSUE THREAD

**Issue by bahaa-kallas** [parse-community/parse-dashboard#1333]
- [x] You're running version 2.0.3 of Parse Dashboard.

- [x] You're running version 3.9.0 of Parse Server.

- [x] I've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=).And didn't find anything related to my issue
#### Environment Setup
- i have parse server and dashboard running on the same server 
- i have 2 apps running on the same port without any problem and each app has its own logs folder
- dashboard is running on different port  

#### Steps to reproduce
when i try to review the logs through the dashboard the first tow times i hit the logs button everything is fine but after that if i wanted to review the page second time the server starts to hang and the ram usage slightly increase and the cpu usage becomes 99% and this continue until the server crashes
i discovered this issue in production so i tried to reproduce it in localhost and it turns out that its exist also when developing locally 
i see that each time i press on logs link (error or info) a new request is sent to 
`serverAddress/scriptlog?level=info&n=100`
the first two calls succeeded after short time but every call to this endpoint after that never exit pending state and then its fail (clicking 4 times on logs can be enough to crash parse server)
not only that. when this happens i look to the console and found it overwhelmed with infinite random logs that even prevents me from breaking the execution (in the end i do it through task manager locally and in production by restarting from pm2)
note : verbose is set to 0 (locally and in production)

**Comment by bahaa-kallas** [comment]
Update on the issue :
i  to change my setup locally to see why this happened 
i reverted back into the classical use case of parse server (one app only and running on its own process ) and the dashboard running on its process and definitely on different port 
the same issue still 
the calls to the log endpoint `serverAddress/scriptlog?level=info&n=100`
 cause the parse server process to eat the memory and the CPU and i have to kill it by the task manager 
any thoughts or little help would be very appreciated

**Comment by bahaa-kallas** [comment]
maybe i used the wrong repo to report this issue on 
i didn't realize that at that time when i opened the issue 
i think its Parse-server related issue, but why i opened it here at first because i triggered this behavior while i am using the dashboard.

**Comment by dplewis** [comment]
Thanks for posting. We can try to replicate this issue. 

You can try to use the [latest branch](https://github.com/parse-community/parse-server#want-to-ride-the-bleeding-edge) on the Server as a recent cache improvement has been made.

Can you post a heapdump for your process?

**Comment by bahaa-kallas** [comment]
i never made a heapdump before 
i searched on how to do it and i find a npm dependency for this matter 
the size of snapshot was 768 MB
i don't know how exactly i supposed to read the snapshot file and detect where is the problems 
this a screenshot of it :
![image](https://user-images.githubusercontent.com/53038640/67166961-d40f6980-f394-11e9-877e-4a5a79081f8e.png)
What i did to reproduce the problem:
i just opened the logs from the dashboard couple times (multiple requests to logs endpoint)
- i will check the latest branch tomorrow and see if the problem gone or still exist

**Comment by bahaa-kallas** [comment]
i checked the latest branch
the problem still exist. calls to logs endpoint makes the node process eats RAM and CPU

**Comment by bahaa-kallas** [comment]
@dplewis  any updates on this ? did you manage to reproduce it also ?

**Comment by bahaa-kallas** [comment]
closing because its no longer relevant for me but i am still not sure what is the problem
