### ISSUE TITLE
sudo npm install -g parse-dashboard : libraries warn deprecated

### ISSUE THREAD

**Issue by prempena** [parse-community/parse-dashboard#1336]
Hi,

I would like some help as I just applied the npm install as described in documentation. 

Here are my modules version :

Trying to install parse-dashboard@2.0.3

Current version is parse-server@3.9.0

#### Environment Versions
node --version is v10.16.3
npm --version is 6.9.0

#### Steps to reproduce

sudo npm install -g parse-dashboard

#### Logs/Trace

npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

npm WARN deprecated cryptiles@4.1.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

npm WARN deprecated bfj-node4@5.3.1: Switch to the `bfj` package for fixes and new features!
/usr/bin/parse-dashboard -> /usr/lib/node_modules/parse-dashboard/bin/parse-dashboard

npm WARN codemirror-graphql@0.6.12 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.

npm WARN graphql-language-service-interface@1.3.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm WARN graphql-config@2.0.1 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm WARN graphql-language-service-utils@1.2.2 requires a peer of graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm WARN graphql-import@0.4.5 requires a peer of graphql@^0.11.0 || ^0.12.0 || ^0.13.0 but none is installed. You must install peer dependencies yourself.

npm WARN react-codemirror@1.0.0 requires a peer of react@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

npm WARN react-codemirror@1.0.0 requires a peer of react-dom@>=15.5 <16 but none is installed. You must install peer dependencies yourself.

npm WARN graphiql@0.11.11 requires a peer of graphql@^0.6.0 || ^0.7.0 || ^0.8.0-b || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 but none is installed. You must install peer dependencies yourself.

Thank you for your help.

Pascal

**Comment by jzzhrqp** [comment]
me too,i can not run  npm install -g parse-dashboard.  it is just show me " fetchMetadata: sill resolveWithNewModule parse-dashboard@2.0.5 checking installable status" long long time

**Comment by danielsanfr** [comment]
Hello people. Thanks for the great job done at Parse.

I am getting the same warning, and I would like to know if it is possible to update lib graphql-playground-react.

**From what I looked at in the library repository she has already fixed this problem. I believe that it is only necessary to update the dependency.**

Below are some images that show the problem.

![Screenshot from 2020-06-02 16-08-45](https://user-images.githubusercontent.com/3621711/83559978-d4a3dd00-a4eb-11ea-892d-8aa179a67536.png)

![Screenshot from 2020-06-02 16-05-02](https://user-images.githubusercontent.com/3621711/83559974-d372b000-a4eb-11ea-8167-7ff06a9fc035.png)

**Comment by beiguancyc** [comment]
> me too,i can not run npm install -g parse-dashboard. it is just show me " fetchMetadata: sill resolveWithNewModule parse-dashboard@2.0.5 checking installable status" long long time

Me too

**Comment by dante-calderon** [comment]
Same here

**Comment by mtrezza** [comment]
Closing, since we have removed the dependency `parse-playground-react`. If the issue still exists in the latest version, please let us know and we can re-open this issue.
