### ISSUE TITLE
NPM Install Issue

### ISSUE THREAD

**Issue by danielchangsoojones** [parse-community/parse-dashboard#1352]
I'm getting this error whenever I try to run npm install --save:

`ERROR in ../node_modules/parse/lib/browser/LocalDatastore.js
Module not found: Error: Can't resolve '@babel/runtime-corejs3/core-js-stable/array/from' in '/Users/danieljones/Documents/Btown-Rides/btown-rides-parse-dashboard/node_modules/parse/lib/browser'
 @ ../node_modules/parse/lib/browser/LocalDatastore.js 7:35-94
 @ ../node_modules/parse/lib/browser/Parse.js
 @ ../node_modules/parse/index.js
 @ ./dashboard/Data/Browser/Browser.react.js
 @ ./dashboard/Dashboard.js
 @ `./dashboard/index.js`

My parse dashboard used to work, but now whenever I try to deploy to Heroku or install npm, then it just will keep throwing this error. I know that it's not deploying to Heroku because the npm packages can't install properly. I feel like this is probably a problem on my local machine or somehow my npm is messed up. But, I can't figure it out. I even forked a perfectly clean copy of the parse-dashboard and tried to run npm install --save. I still get the exact same error.

**Comment by acinader** [comment]
Hi @danielchangsoojones three bits of info you need to provide in order to get some help:

1. version of parse-dashboard
2. version of node
3. version of npm

I am using Parse Dashboard 2.0.4 on node v10.14.1 with npm 6.10.0

My guess is that you are trying to use version 2.0.3.  If so, upgrade and try again.

If you still have an issue, go ahead and reopen with the requested details.

**Comment by stepanic** [comment]
@acinader I made the [fork](https://github.com/stepanic/parse-dashboard) today and I have an idea to implement a vertical form for editing rows in the class.

I have followed this instruction:
https://github.com/parse-community/parse-dashboard/blob/master/CONTRIBUTING.md
but I got almost the same errors, like @danielchangsoojones 

1. I tried
```
$ nvm use
Now using node v8.11.4 (npm v5.6.0)

$ npm install
```

Also, I've tried to use `npm install` with the latest stable node
`Now using node v10.17.0 (npm v6.11.3)`
but the same issue exists

`npm install`
STDOUT and STDERR are attached here as `debug.out`
[debug.log](https://github.com/parse-community/parse-dashboard/files/3763854/debug.log)

**Comment by stepanic** [comment]
I can confirm that right now on version 2.0.5 at commit:
https://github.com/parse-community/parse-dashboard/tree/ef3f8d91fe7dddc4a2e356eee50079a5a7400bfb

With `node v12.13.1` and `npm v6.12.1`, I am able to start ParseDashboard
