### ISSUE TITLE
A pop-up to order columns more efficiently

### ISSUE THREAD

**Issue by omairvaiyani** [parse-community/parse-dashboard#138]
When classes have too many fields, it becomes really difficult to re-order columns in the current manner (dragging a column horizontally across the page). If a pop-up/modal was shown with just the fields in a vertical, draggable, list - it would be much easier to sort.

Bonus addition would be to export this order as a JSON, and import it to different Parse Apps (useful for development vs. production apps).

**Comment by peterdotjs** [comment]
We store the order of the columns in local storage so for most users it would be a one time cost. Are you finding yourself reordering frequently?

Using the existing [PIG components](https://github.com/ParsePlatform/parse-dashboard/tree/master/src/components]) you'll be able to build it. I can help point you in the right direction if you're interested in contributing.

**Comment by omairvaiyani** [comment]
Hi @peterdotjs, I do regularly re-order the fields, especially during early development on new projects. I did see the local storage object so I knew it wouldn't be too difficult to adjust. Can you double check that "PIG components" link, it's taking me to a 404. I'll have a crack at building it.

**Comment by drew-gross** [comment]
I fixed the link.

**Comment by mistahgandhi** [comment]
I know this is an old thread. But wanted to ask where is default column order stored locally so it can be changed for repeat use?

**Comment by Treverr** [comment]
I have the same issue, even on the latest version, if i close the browser and re-open it. The columns are not in the order i left them in last time.

**Comment by omairvaiyani** [comment]
Very nice!
