### ISSUE TITLE
Create Parse DashBoard with limited access

### ISSUE THREAD

**Issue by jihadkahil** [parse-community/parse-dashboard#1427]
is there any possibility to create a parse Dash-Board that show only limit classes!
for example, I have 7 class A,B, C, D, E, F, G
I want a user who able to access all of them such as Administrator and another User has access for Classes C F & G! (Only)
and is there any possibility to hide so filed such like username in the class _user

**Comment by davimacedo** [comment]
That's currently not possible but it would be a great new feature. Is this something that you'd be willed to work on?

**Comment by jihadkahil** [comment]
@davimacedo Yes! I need it! any suggestions?

**Comment by davimacedo** [comment]
Nice! Feel free to open a PR. I will be happy to review.
