### ISSUE TITLE
Blank screen when adding column Server 3.9.0, Dashboard 2.0.5

### ISSUE THREAD

**Issue by ashish-naik** [parse-community/parse-dashboard#1436]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ YES] You're running version >=1.0.23 of Parse Dashboard.

- [ YES] You're running version >=2.3.2 of Parse Server.

- [ YES] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Heroku
Dashboard v 2.0.5
Parse Server 3.9.0

#### Steps to reproduce
Go to any object
Click on Edit -> Add Column

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace. 

<img width="522" alt="Parse Dashboard error" src="https://user-images.githubusercontent.com/4936420/71641994-605dd700-2cca-11ea-98f1-9fd4c78ebc79.png">

```
<!DOCTYPE html>
--
  | <head>
  | <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
  | <base href="/"/>
  | <script>
  | PARSE_DASHBOARD_PATH = "/";
  | </script>
  | </head>
  | <html>
  | <title>Parse Dashboard</title>
  | <body>
  | <div id="browser_mount"></div>
  | <script src="/bundles/dashboard.bundle.js"></script>
  | </body>
  | </html>
```

I upgraded Parse Server to 3.9.0 after which tried to add column but get blank screen on clicking Add Column. Tried Chrome, Safari both. 
Clicking Delete Column brings up the popup to delete.

Please help.

Ashish

**Comment by ashish-naik** [comment]
@davimacedo Apologies but i didnt get any response so tagged you. Not sure who can help.

**Comment by ashish-naik** [comment]
@dplewis Could you please take a look at this?

**Comment by dplewis** [comment]
Sure I’ll take a look. I’m in the middle of updating to the latest.
