### ISSUE TITLE
Cell editor position is not taking hidden columns into account

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1437]
#### Steps to reproduce

1. Hide some columns using "Manage columns" option in Browser;
2. Double click on a cell in a column that supposed to be on the right side of some hidden column.

Cell editor seems to be taking hidden columns into account.
![image](https://user-images.githubusercontent.com/45104241/71763919-27984a80-2ee2-11ea-9e0a-46503f8c5491.png)

It's easy to run into state when editor is rendered off visible screen.

**Comment by 404-html** [comment]
Problem is still there.

**Comment by santiagosemhan** [comment]
@davimacedo there is a PR for this issue

**Comment by davimacedo** [comment]
I've just merged. Thanks for alerting me @santiagosemhan !
