### ISSUE TITLE
Empty dashdoard 

### ISSUE THREAD

**Issue by marad747** [parse-community/parse-dashboard#1460]
my dashboard empty(( http://prntscr.com/qu37ln Help 
i used this tutorial https://www.youtube.com/watch?v=4OOnFyXrRvI

**Comment by bernardohmr** [comment]
Hello, I think I have the same issue (check images below).

The network requests all respond with code 200. But the render breakes.

parse-dashboard: 2.0.5
parse-server: 3.9.0
express: 4.17.1

![image](https://user-images.githubusercontent.com/60656778/73749730-b34c0380-473a-11ea-8703-4247e4649afc.png)

![image](https://user-images.githubusercontent.com/60656778/73749808-daa2d080-473a-11ea-81e9-5763df477819.png)

**Comment by davimacedo** [comment]
Could you guys please share your package.json and config files?

**Comment by Meleuo** [comment]
hello
 I had the same problem
This is my dashboard profile
![image](https://user-images.githubusercontent.com/48749322/75758215-b1dc1e00-5d6e-11ea-9558-c8d051435771.png)

**Comment by davimacedo** [comment]
can you please also share your parse dashboard package.json file?

**Comment by edson-gaspar** [comment]
Hello,
I solved this issue on my Mac (safari & firefox) cleaning ALL related data stored on my browsers related to domain hosted parse dashboard (cookies, local storage, session storage, cache, etc).

On Safari you can go to Safari Menu -> Preferences -> Privacy -> Manage site data, them search for domain or localhost if is your case, select the desired domain and click on Remove All, after that, check all data and cache to be cleaned if necessary.

I think this cold be related to version and password authentication policy that was changed on parse server or something like that.

I hope this help you.

**Comment by CollinsWalker** [comment]
My one is also logged in and blank

```
{
  "_from": "parse-server",
  "_id": "parse-server@4.1.0",
  "_inBundle": false,
  "_integrity": "sha512-IxCL3cFhqGElmjxSXSsTraVd78gg3SOfSKM22ZXJmxYyxh8NpSE5zZawZIUU3/9r0S3LwGlMKRlkp9lt9a0f/Q==",
  "_location": "/parse-server",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "parse-server",
    "name": "parse-server",
    "escapedName": "parse-server",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/parse-server/-/parse-server-4.1.0.tgz",
  "_shasum": "72557487304a2c6c16f917772fcc269ce4580d43",
  "_spec": "parse-server",
  "_where": "/root",
  "bin": {
    "parse-server": "bin/parse-server"
  },
  "bugs": {
    "url": "https://github.com/parse-community/parse-server/issues"
  },
  "bundleDependencies": false,
  "collective": {
    "type": "opencollective",
    "url": "https://opencollective.com/parse-server",
    "logo": "https://opencollective.com/parse-server/logo.txt?reverse=true&variant=binary"
  },
  "dependencies": {
    "@apollographql/graphql-playground-html": "1.6.24",
    "@parse/fs-files-adapter": "1.0.1",
    "@parse/push-adapter": "3.2.0",
    "@parse/s3-files-adapter": "1.4.0",
    "@parse/simple-mailgun-adapter": "1.1.0",
    "apollo-server-express": "2.10.1",
    "bcrypt": "4.0.1",
    "bcryptjs": "2.4.3",
    "body-parser": "1.19.0",
    "commander": "4.1.1",
    "cors": "2.8.5",
    "deepcopy": "2.0.0",
    "express": "4.17.1",
    "follow-redirects": "1.9.1",
    "graphql": "14.6.0",
    "graphql-list-fields": "2.0.2",
    "graphql-relay": "^0.6.0",
    "graphql-tools": "^4.0.5",
    "graphql-upload": "10.0.0",
    "intersect": "1.0.1",
    "jsonwebtoken": "8.5.1",
    "ldapjs": "1.0.2",
    "lodash": "4.17.15",
    "lru-cache": "5.1.1",
    "mime": "2.4.4",
    "mongodb": "3.5.4",
    "node-rsa": "1.0.7",
    "parse": "2.11.0",
    "pg-promise": "10.4.4",
    "pluralize": "^8.0.0",
    "redis": "3.0.0",
    "semver": "7.1.3",
    "subscriptions-transport-ws": "0.9.16",
    "tv4": "1.3.0",
    "uuid": "3.3.3",
    "winston": "3.2.1",
    "winston-daily-rotate-file": "4.4.0",
    "ws": "7.2.1",
    "parse-dashboard": "2.0.5"
  },
  "deprecated": false,
  "description": "An express module providing a Parse-compatible API server",
  "devDependencies": {
    "@babel/cli": "7.8.4",
    "@babel/core": "7.8.6",
    "@babel/plugin-proposal-object-rest-spread": "7.8.3",
    "@babel/plugin-transform-flow-strip-types": "7.8.3",
    "@babel/preset-env": "7.8.6",
    "@parse/minami": "1.0.0",
    "apollo-cache-inmemory": "1.6.5",
    "apollo-client": "2.6.6",
    "apollo-link": "1.2.13",
    "apollo-link-http": "1.5.16",
    "apollo-link-ws": "1.0.19",
    "apollo-upload-client": "12.1.0",
    "apollo-utilities": "1.3.3",
    "babel-eslint": "10.1.0",
    "bcrypt-nodejs": "0.0.3",
    "cross-env": "7.0.0",
    "deep-diff": "1.0.2",
    "eslint": "6.8.0",
    "eslint-plugin-flowtype": "4.5.0",
    "flow-bin": "0.119.1",
    "form-data": "3.0.0",
    "gaze": "1.1.3",
    "graphql-tag": "^2.10.1",
    "husky": "4.2.3",
    "jasmine": "3.5.0",
    "jsdoc": "3.6.3",
    "jsdoc-babel": "0.5.0",
    "lint-staged": "10.0.8",
    "mongodb-runner": "4.8.0",
    "node-fetch": "2.6.0",
    "nyc": "15.0.0",
    "prettier": "1.19.0"
  },
  "engines": {
    "node": ">= 8"
  },
  "files": [
    "bin/",
    "lib/",
    "public_html/",
    "views/",
    "LICENSE",
    "PATENTS",
    "postinstall.js",
    "README.md"
  ],
  "funding": {
    "type": "opencollective",
    "url": "https://opencollective.com/parse-server"
  },
  "homepage": "https://github.com/parse-community/parse-server#readme",
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "license": "BSD-3-Clause",
  "lint-staged": {
    "{src,spec}/**/*.js": [
      "prettier --write",
      "eslint --cache",
      "git add"
    ]
  },
  "main": "lib/index.js",
  "name": "parse-server",
  "optionalDependencies": {
    "bcrypt": "4.0.1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/parse-community/parse-server.git"
  },
  "scripts": {
    "build": "babel src/ -d lib/ --copy-files",
    "coverage": "cross-env MONGODB_VERSION=${MONGODB_VERSION:=4.0.4} MONGODB_TOPOLOGY=${MONGODB_TOPOLOGY:=standalone} MONGODB_STORAGE_ENGINE=${MONGODB_STORAGE_ENGINE:=mmapv1} TESTING=1 nyc jasmine",
    "definitions": "node ./resources/buildConfigDefinitions.js",
    "dev": "npm run build && node bin/dev",
    "docs": "jsdoc -c ./jsdoc-conf.json",
    "lint": "flow && eslint --cache ./",
    "postinstall": "node -p 'require(\"./postinstall.js\")()'",
    "posttest": "cross-env MONGODB_VERSION=${MONGODB_VERSION:=4.0.4} MONGODB_TOPOLOGY=${MONGODB_TOPOLOGY:=standalone} MONGODB_STORAGE_ENGINE=${MONGODB_STORAGE_ENGINE:=mmapv1} mongodb-runner stop",
    "prepare": "npm run build",
    "pretest": "cross-env MONGODB_VERSION=${MONGODB_VERSION:=4.0.4} MONGODB_TOPOLOGY=${MONGODB_TOPOLOGY:=standalone} MONGODB_STORAGE_ENGINE=${MONGODB_STORAGE_ENGINE:=mmapv1} mongodb-runner start",
    "start": "node ./bin/parse-server",
    "test": "npm run testonly",
    "testonly": "cross-env MONGODB_VERSION=${MONGODB_VERSION:=4.0.4} MONGODB_TOPOLOGY=${MONGODB_TOPOLOGY:=standalone} MONGODB_STORAGE_ENGINE=${MONGODB_STORAGE_ENGINE:=mmapv1} TESTING=1 jasmine",
    "watch": "babel --watch src/ -d lib/ --copy-files"
  },
  "version": "4.1.0"
}
```
This is my parse server package.json file

[https://s1.ax1x.com/2020/03/26/GSYN4J.png](url)

How does this need to be addressed

**Comment by mao720** [comment]
My dashboard empty at first, 
when i start the dashboard ,i change the param  
>> --serverURL "http://localhost:1337/parse"
to
>> --serverURL "http://47.75.18.12:1337/parse"
 this issue gone.
Use your domain instead “localhost”.

**Comment by m4ary** [comment]
i have the same problem

**Comment by mtrezza** [comment]
I was able to reproduce this:

1. Clone repository (it has to be a new clone from the current master)
2. Delete `node_modules` and `package-lock.json`
2. npm install
2. Published to AWS
3. Dashboard launches as expected according to nodejs logs
4. Opening the dashboard URL redirects to `/login`
5. Page is blank:

       <!DOCTYPE html>
        <head>
          <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
          <base href="/"/>
          <script>
            PARSE_DASHBOARD_PATH = "/";
          </script>
        </head>
        <html>
          <title>Parse Dashboard</title>
          <body>
            <div id="login_mount"></div>
            
            <script id="csrf" type="application/json">"REMOVED"</script>
            <script src="/bundles/login.bundle.js"></script>
          </body>
        </html>
      
_(REMOVED by me)_

It works for my old fork but not the new fork, even though `package.json` and `parse-dashboard-config.json` are the same.

**Comment by mtrezza** [comment]
The reason why Parse Dashboard is showing a blank page when deploying to AWS Elastic Beanstalk is that these files are in `.gitignore`:

```
bundles/
Parse-Dashboard/public/bundles/
Parse-Dashboard/parse-dashboard-config.json
```

For AWS EB CLI this means that the files are not deployed as part of the application. The solution is to either remove the files from `.gitignore` or add a `.ebignore` file so that the AWS CLI ignores the `.gitignore` and deploys all files.

From the [docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-configuration.html#eb-cli3-ebignore): 

> If .ebignore isn't present, but .gitignore is, the EB CLI ignores files specified in .gitignore. If .ebignore is present, the EB CLI doesn't read .gitignore.
> 
> When .ebignore is present, the EB CLI doesn't use git commands to create your source bundle. This means that EB CLI ignores files specified in .ebignore, and includes all other files. In particular, it includes uncommitted source files.

That means that the repository is not out-of-the-box AWS EB CLI deployment compatible. Maybe we should remove the files from gitignore?

**Comment by PraveenMarapelly** [comment]
I had the same issue, try doing the following steps
In chrome
open Settings --> Go to Site settings -->Click on Insecure Content --> Click on "Add" button corresponding to "Allow" copy and paste your Public IPv4 DNS in the address box
it worked for me
