### ISSUE TITLE
Push notification details showing N/A

### ISSUE THREAD

**Issue by tutorbear** [parse-community/parse-dashboard#1474]
Hello there, My pushes are being received on my android device and opened too but sadly the push notification details in my dashboard is show N/A. Why is the like that ? I have attached a picture
![image](https://user-images.githubusercontent.com/50081302/74833968-b6eba700-5344-11ea-98b1-d41e0c261bdc.png)

**Comment by mtrezza** [comment]
Push opens are an Analytics feature. Analytics is not included in open source Parse Server.
