### ISSUE TITLE
Why does the login Dashboard display: Cannot GET

### ISSUE THREAD

**Issue by CollinsWalker** [parse-community/parse-dashboard#1492]
```
var express = require('express');
var ParseDashboard = require('parse-dashboard');

var dashboard = new ParseDashboard({
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "appName": "MyApp"
    }
  ]
});

var app = express();

// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);

var httpServer = require('http').createServer(app);
httpServer.listen(4040);
```
Why does it show Cannot GET?

**Comment by davimacedo** [comment]
Where do you see this error? Can you share the complete error stack?

**Comment by andresteves** [comment]
I have some screenshots if it helps.

Latest version of dashboard
![Captura de ecrã 2022-03-16, às 15 35 27](https://user-images.githubusercontent.com/645072/158628606-4d0e931e-92cc-411a-93a9-ebe53792e917.png)

1.2.0 version of dashboard
![Captura de ecrã 2022-03-16, às 15 35 51](https://user-images.githubusercontent.com/645072/158628614-a3e703f0-3def-4321-b040-15a48cdf6c5c.png)
