### ISSUE TITLE
How to Migrate the database? Settings options not shown in the dashboard the only options are Core and Push 

### ISSUE THREAD

**Issue by nvgomez11** [parse-community/parse-dashboard#1493]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Currently using the parse dashboard 2.0.5

I've seen videos about migration and they only enter in the dashboard, then settings then migration... but I enter the dashboard and I only have 2 options, Core and Push so how can I Migrate the database for production ?

**Comment by mtrezza** [comment]
The automated migration was a feature of hosted Parse.com.

Migrating a DB is not a feature of Parse Server, because actually it has nothing to do with it.
Migration happens between two DB providers.

From where to where do you want to migrate?

**Comment by nvgomez11** [comment]
I want to migrate from the parse database to the one you can use as an Addon in Heroku, mLab. 
According to this video, look at the minute 6:05:

https://www.youtube.com/watch?v=saETLm5nr8w&t=375s 

All I have to do is to go to parse-dashboard, then the app setting and finally migrate it to a external database. My problem is that when I enter to the dasboard I only see 2 options Core and Push. I'm not able to see the app settings. So, how can I enable this option? Or whats the new way to migrate to a external database? 

Thanks in advance. 

This is all I see in my dashboard.

![image](https://user-images.githubusercontent.com/14356508/76907220-4c5a5800-686b-11ea-98b2-c35b3f2c452a.png)

**Comment by mtrezza** [comment]
The reason why you don't see "App Settings" is because that option existed on hosted Parse.com.

Parse Server has since become open source. Non-essential features did not make it to open source. Database migration is one such feature.

More info [here](http://docs.parseplatform.org/parse-server/guide/#compatibility-with-parsecom).
