### ISSUE TITLE
How to logout of Dashboard in 1.4.3

### ISSUE THREAD

**Issue by omarojo** [parse-community/parse-dashboard#1505]
1.4.3 of the Dashboard has no LOGOUT button anywhere ?

![image](https://user-images.githubusercontent.com/995265/77727193-f9914680-6fb6-11ea-8736-ade2f88c5c20.png)

**Comment by mtrezza** [comment]
It should be at the bottom:

![image](https://user-images.githubusercontent.com/5673677/78688165-44835600-78f5-11ea-9811-a72728e3d2be.png)

If it isn't you can upgrade to 2.0.4 from where I took the screenshot.
