### ISSUE TITLE
Any reason for not forcing squash and merge?

### ISSUE THREAD

**Issue by TomWFox** [parse-community/parse-dashboard#1515]
I'm just working on the chnagelog for a new release and I noticed that the commit history is a bit messy. It turns out merge commit is allowed on this repo.

@dplewis @davimacedo any particular reason for this?

**Comment by dplewis** [comment]
This can sometimes happen if you are on mobile and the default can be merged instead of squash. I’ve seen it happen a few times. My devices are set to squash

**Comment by TomWFox** [comment]
Ah, good to know. We could disable merge commit so it's not used by mistake, it's easy to switch back on If needed.

**Comment by dplewis** [comment]
I agree

**Comment by TomWFox** [comment]
Done.
