### ISSUE TITLE
problem installing parse dashboard

### ISSUE THREAD

**Issue by marckkh** [parse-community/parse-dashboard#1528]
C:\node\dashboard>npm install parse-dashboard
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:

windows server 2012r2
 node version 12.16.2
npm version  6.14.4

**Comment by bash862** [comment]
Me too; some update? I found this same issue but don't explain how to resolve the error:
https://github.com/parse-community/parse-server/issues/6493

**Comment by davimacedo** [comment]
Can you please share your package.json?

**Comment by marckkh** [comment]
> 
> 
> Can you please share your package.json?

there is no package.json
package.json file is not generating
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\parseDashboard>npm install parse-dashboard
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-04-23T04_16_10_466Z-debug.log

C:\parseDashboard>

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'parse-dashboard'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.2
4 verbose npm-session 5f1daf2ecc2f1d49
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/parse-dashboard 155ms
8 http fetch GET 200 https://registry.npmjs.org/parse-dashboard/-/parse-dashboard-2.1.0.tgz 178ms
9 silly pacote tag manifest for parse-dashboard@latest fetched in 364ms
10 timing stage:loadCurrentTree Completed in 398ms
11 silly install loadIdealTree
12 silly install cloneCurrentTreeToIdealTree
13 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
14 silly install loadShrinkwrap
15 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
16 silly install loadAllDepsIntoIdealTree
17 silly resolveWithNewModule parse-dashboard@2.1.0 checking installable status
18 silly fetchPackageMetaData error for codemirror-graphql@github:timsuchanek/codemirror-graphql#details-fix Error while executing:
18 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData spawn git ENOENT
19 http fetch GET 304 https://registry.npmjs.org/csurf 125ms (from cache)
20 http fetch GET 200 https://registry.npmjs.org/@babel%2fruntime 161ms
21 http fetch GET 304 https://registry.npmjs.org/create-react-class 133ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/copy-to-clipboard 136ms (from cache)
23 http fetch GET 304 https://registry.npmjs.org/commander 141ms (from cache)
24 http fetch GET 304 https://registry.npmjs.org/body-parser 167ms (from cache)
25 silly pacote version manifest for create-react-class@15.6.3 fetched in 138ms
26 silly resolveWithNewModule create-react-class@15.6.3 checking installable status
27 silly pacote version manifest for commander@5.0.0 fetched in 149ms
28 silly resolveWithNewModule commander@5.0.0 checking installable status
29 silly pacote range manifest for copy-to-clipboard@^3.2.0 fetched in 145ms
30 silly resolveWithNewModule copy-to-clipboard@3.3.1 checking installable status
31 silly pacote version manifest for body-parser@1.19.0 fetched in 177ms
32 silly resolveWithNewModule body-parser@1.19.0 checking installable status
33 http fetch GET 304 https://registry.npmjs.org/connect-flash 164ms (from cache)
34 http fetch GET 200 https://registry.npmjs.org/csurf/-/csurf-1.11.0.tgz 64ms
35 silly pacote version manifest for connect-flash@0.1.1 fetched in 201ms
36 silly resolveWithNewModule connect-flash@0.1.1 checking installable status
37 http fetch GET 200 https://registry.npmjs.org/@babel/runtime/-/runtime-7.8.7.tgz 80ms
38 http fetch GET 200 https://registry.npmjs.org/history 67ms
39 silly pacote version manifest for csurf@1.11.0 fetched in 218ms
40 silly resolveWithNewModule csurf@1.11.0 checking installable status
41 silly pacote version manifest for history@4.10.1 fetched in 75ms
42 silly resolveWithNewModule history@4.10.1 checking installable status
43 http fetch GET 304 https://registry.npmjs.org/immutable 76ms (from cache)
44 http fetch GET 304 https://registry.npmjs.org/graphql 89ms (from cache)
45 silly pacote version manifest for @babel/runtime@7.8.7 fetched in 264ms
46 silly resolveWithNewModule @babel/runtime@7.8.7 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/express 167ms (from cache)
48 silly pacote version manifest for immutable@4.0.0-rc.9 fetched in 88ms
49 silly resolveWithNewModule immutable@4.0.0-rc.9 checking installable status
50 silly pacote version manifest for express@4.17.1 fetched in 182ms
51 silly resolveWithNewModule express@4.17.1 checking installable status
52 http fetch GET 200 https://registry.npmjs.org/graphql/-/graphql-14.6.0.tgz 48ms (from cache)
53 http fetch GET 304 https://registry.npmjs.org/js-beautify 69ms (from cache)
54 silly pacote version manifest for graphql@14.6.0 fetched in 150ms
55 silly resolveWithNewModule graphql@14.6.0 checking installable status
56 http fetch GET 304 https://registry.npmjs.org/package-json 63ms (from cache)
57 silly pacote version manifest for package-json@6.5.0 fetched in 64ms
58 silly resolveWithNewModule package-json@6.5.0 checking installable status
59 http fetch GET 200 https://registry.npmjs.org/js-beautify/-/js-beautify-1.11.0.tgz 37ms
60 http fetch GET 304 https://registry.npmjs.org/prismjs 33ms (from cache)
61 silly pacote version manifest for js-beautify@1.11.0 fetched in 117ms
62 silly resolveWithNewModule js-beautify@1.11.0 checking installable status
63 http fetch GET 200 https://registry.npmjs.org/prismjs/-/prismjs-1.20.0.tgz 94ms
64 http fetch GET 304 https://registry.npmjs.org/prop-types 91ms (from cache)
65 silly pacote version manifest for prop-types@15.7.2 fetched in 94ms
66 silly resolveWithNewModule prop-types@15.7.2 checking installable status
67 silly pacote version manifest for prismjs@1.20.0 fetched in 135ms
68 silly resolveWithNewModule prismjs@1.20.0 checking installable status
69 http fetch GET 304 https://registry.npmjs.org/query-string 32ms (from cache)
70 http fetch GET 200 https://registry.npmjs.org/react 32ms
71 http fetch GET 200 https://registry.npmjs.org/query-string/-/query-string-6.11.1.tgz 26ms
72 http fetch GET 200 https://registry.npmjs.org/react/-/react-16.13.1.tgz 26ms
73 silly pacote version manifest for query-string@6.11.1 fetched in 68ms
74 silly resolveWithNewModule query-string@6.11.1 checking installable status
75 silly pacote version manifest for react@16.13.1 fetched in 69ms
76 silly resolveWithNewModule react@16.13.1 checking installable status
77 http fetch GET 200 https://registry.npmjs.org/react-ace 27ms
78 http fetch GET 304 https://registry.npmjs.org/react-dnd 32ms (from cache)
79 http fetch GET 200 https://registry.npmjs.org/react-ace/-/react-ace-8.1.0.tgz 62ms
80 http fetch GET 200 https://registry.npmjs.org/react-dnd/-/react-dnd-10.0.2.tgz 57ms
81 silly pacote range manifest for react-ace@^8.0.0 fetched in 98ms
82 silly resolveWithNewModule react-ace@8.1.0 checking installable status
83 silly pacote version manifest for react-dnd@10.0.2 fetched in 98ms
84 silly resolveWithNewModule react-dnd@10.0.2 checking installable status
85 http fetch GET 304 https://registry.npmjs.org/react-dnd-html5-backend 30ms (from cache)
86 http fetch GET 304 https://registry.npmjs.org/react-dom 35ms (from cache)
87 http fetch GET 200 https://registry.npmjs.org/react-dnd-html5-backend/-/react-dnd-html5-backend-10.0.2.tgz 26ms
88 silly pacote version manifest for react-dnd-html5-backend@10.0.2 fetched in 98ms
89 silly resolveWithNewModule react-dnd-html5-backend@10.0.2 checking installable status
90 http fetch GET 200 https://registry.npmjs.org/react-dom/-/react-dom-16.13.1.tgz 67ms
91 silly pacote version manifest for react-dom@16.13.1 fetched in 109ms
92 silly resolveWithNewModule react-dom@16.13.1 checking installable status
93 http fetch GET 304 https://registry.npmjs.org/react-helmet 28ms (from cache)
94 http fetch GET 200 https://registry.npmjs.org/react-json-view 28ms
95 http fetch GET 200 https://registry.npmjs.org/react-helmet/-/react-helmet-6.0.0.tgz 42ms
96 http fetch GET 200 https://registry.npmjs.org/react-json-view/-/react-json-view-1.19.1.tgz 28ms
97 silly pacote version manifest for react-helmet@6.0.0 fetched in 80ms
98 silly resolveWithNewModule react-helmet@6.0.0 checking installable status
99 silly pacote range manifest for react-json-view@^1.19.1 fetched in 69ms
100 silly resolveWithNewModule react-json-view@1.19.1 checking installable status
101 http fetch GET 304 https://registry.npmjs.org/bcryptjs 822ms (from cache)
102 silly pacote version manifest for bcryptjs@2.3.0 fetched in 825ms
103 silly resolveWithNewModule bcryptjs@2.3.0 checking installable status
104 http fetch GET 304 https://registry.npmjs.org/react-redux 29ms (from cache)
105 http fetch GET 304 https://registry.npmjs.org/cookie-session 830ms (from cache)
106 silly pacote version manifest for cookie-session@2.0.0-beta.3 fetched in 832ms
107 silly resolveWithNewModule cookie-session@2.0.0-beta.3 checking installable status
108 http fetch GET 304 https://registry.npmjs.org/react-router 61ms (from cache)
109 http fetch GET 304 https://registry.npmjs.org/graphql-playground-react 701ms (from cache)
110 silly pacote version manifest for react-router@5.1.2 fetched in 71ms
111 silly resolveWithNewModule react-router@5.1.2 checking installable status
112 silly pacote version manifest for graphql-playground-react@1.7.20 fetched in 711ms
113 silly resolveWithNewModule graphql-playground-react@1.7.20 checking installable status
114 http fetch GET 200 https://registry.npmjs.org/react-redux/-/react-redux-5.1.2.tgz 48ms
115 http fetch GET 304 https://registry.npmjs.org/react-router-dom 67ms (from cache)
116 silly pacote version manifest for react-router-dom@5.1.2 fetched in 69ms
117 silly resolveWithNewModule react-router-dom@5.1.2 checking installable status
118 silly pacote version manifest for react-redux@5.1.2 fetched in 88ms
119 silly resolveWithNewModule react-redux@5.1.2 checking installable status
120 http fetch GET 304 https://registry.npmjs.org/semver 28ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/regenerator-runtime 49ms (from cache)
122 http fetch GET 200 https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.5.tgz 4ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/json-file-plus 669ms (from cache)
124 silly pacote version manifest for json-file-plus@3.2.0 fetched in 671ms
125 silly resolveWithNewModule json-file-plus@3.2.0 checking installable status
126 silly pacote version manifest for regenerator-runtime@0.13.5 fetched in 59ms
127 silly resolveWithNewModule regenerator-runtime@0.13.5 checking installable status
128 http fetch GET 200 https://registry.npmjs.org/semver/-/semver-7.3.2.tgz 25ms
129 silly pacote version manifest for semver@7.3.2 fetched in 57ms
130 silly resolveWithNewModule semver@7.3.2 checking installable status
131 http fetch GET 304 https://registry.npmjs.org/immutable-devtools 719ms (from cache)
132 http fetch GET 304 https://registry.npmjs.org/passport 691ms (from cache)
133 http fetch GET 304 https://registry.npmjs.org/passport-local 664ms (from cache)
134 http fetch GET 200 https://registry.npmjs.org/immutable-devtools/-/immutable-devtools-0.1.5.tgz 39ms
135 http fetch GET 200 https://registry.npmjs.org/parse 720ms
136 silly pacote version manifest for passport-local@1.0.0 fetched in 675ms
137 silly resolveWithNewModule passport-local@1.0.0 checking installable status
138 silly pacote version manifest for parse@2.12.0 fetched in 730ms
139 silly resolveWithNewModule parse@2.12.0 checking installable status
140 silly pacote version manifest for immutable-devtools@0.1.5 fetched in 774ms
141 silly resolveWithNewModule immutable-devtools@0.1.5 checking installable status
142 http fetch GET 200 https://registry.npmjs.org/passport/-/passport-0.4.1.tgz 32ms
143 silly pacote version manifest for passport@0.4.1 fetched in 728ms
144 silly resolveWithNewModule passport@0.4.1 checking installable status
145 timing stage:rollbackFailedOptional Completed in 0ms
146 timing stage:runTopLevelLifecycles Completed in 1432ms
147 silly saveTree mdashtest
147 silly saveTree `-- parse-dashboard@2.1.0
147 silly saveTree   +-- @babel/runtime@7.8.7
147 silly saveTree   | `-- regenerator-runtime@0.13.5
147 silly saveTree   +-- bcryptjs@2.3.0
147 silly saveTree   +-- body-parser@1.19.0
147 silly saveTree   +-- commander@5.0.0
147 silly saveTree   +-- connect-flash@0.1.1
147 silly saveTree   +-- cookie-session@2.0.0-beta.3
147 silly saveTree   +-- copy-to-clipboard@3.3.1
147 silly saveTree   +-- create-react-class@15.6.3
147 silly saveTree   +-- csurf@1.11.0
147 silly saveTree   +-- express@4.17.1
147 silly saveTree   +-- graphql-playground-react@1.7.20
147 silly saveTree   | +-- immutable@4.0.0-rc.9
147 silly saveTree   | +-- prop-types@15.7.2
147 silly saveTree   | +-- react-dom@16.13.1
147 silly saveTree   | +-- react-redux@5.1.2
147 silly saveTree   | `-- react@16.13.1
147 silly saveTree   +-- graphql@14.6.0
147 silly saveTree   +-- history@4.10.1
147 silly saveTree   +-- immutable-devtools@0.1.5
147 silly saveTree   +-- immutable@4.0.0-rc.9
147 silly saveTree   +-- js-beautify@1.11.0
147 silly saveTree   +-- json-file-plus@3.2.0
147 silly saveTree   +-- package-json@6.5.0
147 silly saveTree   +-- parse@2.12.0
147 silly saveTree   +-- passport-local@1.0.0
147 silly saveTree   +-- passport@0.4.1
147 silly saveTree   +-- prismjs@1.20.0
147 silly saveTree   +-- prop-types@15.7.2
147 silly saveTree   +-- query-string@6.11.1
147 silly saveTree   +-- react-ace@8.1.0
147 silly saveTree   +-- react-dnd-html5-backend@10.0.2
147 silly saveTree   +-- react-dnd@10.0.2
147 silly saveTree   +-- react-dom@16.13.1
147 silly saveTree   +-- react-helmet@6.0.0
147 silly saveTree   +-- react-json-view@1.19.1
147 silly saveTree   +-- react-redux@5.1.2
147 silly saveTree   +-- react-router-dom@5.1.2
147 silly saveTree   | `-- react-router@5.1.2
147 silly saveTree   +-- react-router@5.1.2
147 silly saveTree   +-- react@16.13.1
147 silly saveTree   +-- regenerator-runtime@0.13.5
147 silly saveTree   `-- semver@7.3.2
148 verbose stack Error: spawn git ENOENT
148 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
148 verbose stack     at onErrorNT (internal/child_process.js:469:16)
148 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:21)
149 verbose cwd C:\mdashtest
150 verbose Windows_NT 6.3.9600
151 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "parse-dashboard"
152 verbose node v12.16.2
153 verbose npm  v6.14.4
154 error code ENOENT
155 error syscall spawn git
156 error path git
157 error errno ENOENT
158 error enoent Error while executing:
158 error enoent undefined ls-remote -h -t ssh://git@github.com/timsuchanek/codemirror-graphql.git
158 error enoent
158 error enoent
158 error enoent spawn git ENOENT
159 error enoent This is related to npm not being able to find a file.
160 verbose exit [ 1, true ]

**Comment by marckkh** [comment]
@davimacedo

**Comment by davimacedo** [comment]
I've just successfully installed using this version of npm and node in Mac. I believe it is some problem happening in Windows when using npm to install packages from github. Could you please try to update git to the latest version and also share the version that you are using?

**Comment by bash862** [comment]
I have updated Git to the last version (git version 2.26.2.windows.1) and after that i tried to install the parse dashboard with npm and the installation completed without error.

**Comment by davimacedo** [comment]
Nice. Thanks for your feedback @bash862 . @marckkh  could you please confirm if it works for you as well?

**Comment by marckkh** [comment]
> 
> 
> Nice. Thanks for your feedback @bash862 . @marckkh could you please confirm if it works for you as well?


@davimacedo 
it works correctly after installing git in windows server 2012r2

many thanks

**Comment by marckkh** [comment]
@davimacedo  @bash862 
it works correctly after installing git in windows server 2012r2

many thanks

**Comment by davimacedo** [comment]
Nice, Thanks for the feedback.

**Comment by gregorskii** [comment]
This occurred for me when my Docker image (node-slim) did not have git.

**Comment by yuenlye** [comment]
This happens when I try to deploy to Google App Engine. Any idea how to resolve this?
