### ISSUE TITLE
The docker image generation has stopped

### ISSUE THREAD

**Issue by nangyal** [parse-community/parse-dashboard#1541]
Just a notice

The docker image generation has stopped
https://hub.docker.com/r/parseplatform/parse-dashboard/builds

and

The node js 8 had End Of life since 2019-12-31
https://github.com/nodejs/Release

maybe it is time to switch to node js 10 or even 12
https://github.com/parse-community/parse-dashboard/blob/master/Dockerfile

Regards
Norbert

**Comment by nstrelow** [comment]
Anything somebody can do here?
How can we start it again?

**Comment by difelice** [comment]
This might solve it too: https://github.com/parse-community/parse-dashboard/pull/1605

**Comment by difelice** [comment]
This was solved via https://github.com/parse-community/parse-dashboard/pull/1605
