### ISSUE TITLE
Any plan to refactor the project?

### ISSUE THREAD

**Issue by hrahimi270** [parse-community/parse-dashboard#1554]
Hi guys.
I'd take a look at the source code, I thought it would be better if refactor it with new approaches.
What do you think?
Do you accept PR for this?

**Comment by mtrezza** [comment]
Hi @hrahimi270, what specifically did you have in mind?

**Comment by hrahimi270** [comment]
Hi @mtrezza.
I thought maybe using new features of React.js like Functional Components and Hooks or Context API.
Mostly refactor the components I was thinking too.
