### ISSUE TITLE
Cannot set hours and minutes in Calendar popup

### ISSUE THREAD

**Issue by JeffGuKang** [parse-community/parse-dashboard#1563]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.
2.1.0

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

firefox, chrome

#### Steps to reproduce
<img width="605" alt="image" src="https://user-images.githubusercontent.com/216363/86876104-ebf36d00-c11e-11ea-9b5a-30d62721477c.png">

Calendar Popup just close when I try to change hours or minutes.

#### Logs/Trace

Notihng

Thanks for the great project.

**Comment by JeffGuKang** [comment]
It is possible edit the time by only editing text without using the calendar UI.

**Comment by motte** [comment]
I can confirm you can edit the time by only editing the text.  You can also _tab_ into the fields and edit the time.  Must be a bug in the date selector component.

**Comment by motte** [comment]
Clicking anything other than the current month's date causes the component to dismiss.  This could be an issue of scope in the onclick listener to dismiss event.  Does anybody know what react component this is off the top of their heads?
