### ISSUE TITLE
[Docker and npm] dashboard loading blank page

### ISSUE THREAD

**Issue by DevDorrejo** [parse-community/parse-dashboard#1574]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
npm install -g parse-dashboard: parse-dashboard
or 
docker run -d -p 4040:4040 parseplatform/parse-dashboard --dev
go to public IP
Appear Blank Screen

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.
![image](https://user-images.githubusercontent.com/7697566/87898157-6a071c00-ca1b-11ea-9a8e-093421df9395.png)

**Comment by DevDorrejo** [comment]
found that this error is how are the configuration on apache, but have not found how to configure the apache.

how can i enable dashboard to access from a subdomain?

if i create a tunnel with ssh -L, will work.

http://127.0.0.1:4040
![image](https://user-images.githubusercontent.com/7697566/88347841-c1f29b00-cd19-11ea-9cad-b1918338c337.png)


docker run -d --network=host parseplatform/parse-dashboard --appName Astian-Sync --appId appid --masterKey masterkey --serverURL http://localhost:1337/parse --allowInsecureHTTP true

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
#ServerAdmin webmaster@dummy-host.example.com
ServerName www.ds.astian.org
ServerAlias ds.astian.org

ProxyRequests Off
ProxyPreserveHost On
ProxyPass / http://localhost:4040
ProxyPassReverse / http://localhost:4040
#SSLProxyEngine on

<Proxy *>
Require all granted
</Proxy>

# if not specified, the global error log is used
ErrorLog /var/log/apache2/aservices/sync/ds_error_log
CustomLog /var/log/apache2/aservices/sync/ds_access_log combined

# don't loose time with IP address lookups
HostnameLookups Off
# needed for named virtual hosts
UseCanonicalName Off
# configures the footer on server-generated documents
ServerSignature On

SSLCertificateFile /etc/letsencrypt/live/ds.astian.org/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/ds.astian.org/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

**Comment by farzadi** [comment]
I have the same problem and it just shows a blank page 
![error](https://user-images.githubusercontent.com/3613087/91023204-7f1f2e00-e60b-11ea-83db-212ea962c35b.png)
