### ISSUE TITLE
Maintenance?

### ISSUE THREAD

**Issue by nstrelow** [parse-community/parse-dashboard#1602]
Hey is the dashboard still mainainend by anyone?

Most issues get just stale bots response.

6 open PRs

Docker builds fail since 2.1.0.

No new release for 3 fixes (maybe that is not needed).

Can anything be done to get this back up to speed?

**Comment by davimacedo** [comment]
It would be good to have more people helping to maintain this repo. Are you interested in helping?

**Comment by cbaker6** [comment]
@nstrelow though there hasn’t been an official release, you can access the latest updates on docker by using the “latest” tag which works fine from my usage. https://hub.docker.com/r/parseplatform/parse-dashboard/tags

**Comment by nstrelow** [comment]
Nice seeing some activity again.
Sadly I have not used dashboard in parse enough to make informed decisions on open PRs.
Thanks for doing your best :D
