### ISSUE TITLE
The last lines of the list are duplicated in my Dashboard. 

### ISSUE THREAD

**Issue by Amandinepm** [parse-community/parse-dashboard#1632]
Hello, 

✅ In Parse, in the Dashboard entry in browser section, when I filter via the domain tab and my screen is full screen, then I don't have any display problems. 

❌ In Parse, in the Dashboard entry in browser section, when I filter via the domain tab and my screen is not full screen, then I have a serious display problem. The last lines of the list are duplicated in my Dashboard. 

We are on 2.1.0 version of Parse Dashboard.
There are no log in my console. 

Thanks in advance. 
Amandine

**Comment by sadakchap** [comment]
Hi @Amandinepm, was not able to reproduce this issue. Could you please share more information about the issue or the steps to reproduce this issue.
