### ISSUE TITLE
Dashboard doesn't show object count

### ISSUE THREAD

**Issue by sagerio** [parse-community/parse-dashboard#1637]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

Parse Dashboard version: 2.1.0
Parse Server version: 4.5.0

#### Environment Setup

node version 12.20.1
OS Ubuntu 20.04.1

I don't know if I'm doing something wrong or it's a bug: The object count for every class is zero, although there are rows in the classes (see screenshot, also RestApi reports the lines). The classes and the data was added via the dashboard.

![dash](https://user-images.githubusercontent.com/29227014/103824681-b4855f00-5074-11eb-8333-d9ecb3f9bc2b.png)

![restapi](https://user-images.githubusercontent.com/29227014/103824693-b8b17c80-5074-11eb-9313-6580b73da0b2.png)

**Comment by sagerio** [comment]
Solved when using MongoDB instead of postgres as backend

**Comment by cyb3rko** [comment]
It also appears when you only refresh an empty class page and new rows get listed.
