### ISSUE TITLE
License

### ISSUE THREAD

**Issue by FELS-Zak** [parse-community/parse-dashboard#1644]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=1.0.23 of Parse Dashboard.

- [x ] You're running version >=2.3.2 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I have a question about the license of the DASHBOARD - it's not the BSD is it? Does that mean it can't be used as the basis of a commercial product?

**Comment by dplewis** [comment]
Its a BSD license.

https://github.com/parse-community/parse-dashboard/blob/master/LICENSE

You can use it in your commercial product. A lot of users have done this.

**Comment by FELS-Zak** [comment]
Thank you.The server is specified as bsd cannot see the same on the dashboard..But i really want to make sure :)Sent while mobile from a small screen with big fingers..excuse the typos
-------- Original message --------From: Diamond Lewis <notifications@github.com> Date: 19/01/2021  22:18  (GMT+00:00) To: parse-community/parse-dashboard <parse-dashboard@noreply.github.com> Cc: Zakir Hoosen <sourcecontrol@fuzzelogicsolutions.com>, Author <author@noreply.github.com> Subject: Re: [parse-community/parse-dashboard] License (#1644) 
Its a BSD license.
https://github.com/parse-community/parse-dashboard/blob/master/LICENSE
You can use it in your commercial product. A lot of users have done this.

**Comment by dplewis** [comment]
The Server has a BSD 3 Clause vs BSD license here

**Comment by FELS-Zak** [comment]
Ok  thank you !
