### ISSUE TITLE
Add array of files

### ISSUE THREAD

**Issue by vitalii-bulyzhyn** [parse-community/parse-dashboard#1648]
I've been using Parse-Dashboard for a couple of projects and there is a feature I really miss:

Sometimes I need to add few pictures to the entities in my db, and there is absolutely no problem with this. However there is no way to properly manage this kind of stuff on the parse-dashboard (it will be shown just as basic array of objects and you cannot modify it).

Is that is a feature worth adding?

**Comment by davimacedo** [comment]
Yes. I think so. Would you be willed to send a PR?

**Comment by vitalii-bulyzhyn** [comment]
Of course

**Comment by dblythy** [comment]
Already WIP at #1650 😊

**Comment by dblythy** [comment]
(Possible duplicate of #1627)
