### ISSUE TITLE
Add Security Check page

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1665]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation
The new [Security Check](https://github.com/parse-community/parse-server/issues/7246) feature of Parse Server currently writes weak security settings in the logs or returns them as JSON via REST request to `/security` endpoint.

- Human-reading the report in logs or as JSON is inconvenient
- Outputting the report in logs is already discouraged an regarded a weak security setting itself because it potentially exposes points of attack in the logs

### Feature / Enhancement Description
Add a Security Check page to Parse Dashboard that displays the report in a convenient UI.

The feature would send a request to the `/security` endpoint to receive the report in JSON format. The report schema is already described in https://github.com/parse-community/parse-server/pull/7247#issue-585913691. The page would display a table of that report, ideally with visual elements to highlight failed / successful security checks.

### Example Use Case
(none)

### Alternatives / Workarounds
Read reports in logs or manually via REST request.

### 3rd Party References
(none)

**Comment by dblythy** [comment]
I'm happy to work on this if no one is working on it!

**Comment by mtrezza** [comment]
That's great! This would significantly improve accessibility to the security state of Parse Server.

**Comment by dblythy** [comment]
Ok, no worries. Will post here!

**Comment by mtrezza** [comment]
We already have the log output of Security Checks on the server side in v5, so that is already a big step forward.

**Comment by dblythy** [comment]
Haven't had the time for this unfortunately, so if anyone wants it, go for it!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.28](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.28)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
