### ISSUE TITLE
dashboard fetchNextPage bug

### ISSUE THREAD

**Issue by dukejob** [parse-community/parse-dashboard#1668]
**master/src/dashboard/Data/Browser/Browser.react.js**
![微信截图_20210316210430](https://user-images.githubusercontent.com/66236989/111313372-3d370180-869b-11eb-9686-1858ea3e1094.png)

the **field** come from **ordering** (which may start with '-'，such as，'score' & '-score'）
but the last row data object do not have a field '-score'.
![微信截图_20210316211042](https://user-images.githubusercontent.com/66236989/111314182-1b8a4a00-869c-11eb-896a-2e575ba6943b.png)
which will lead the **comp** be **undefined**, and finally the next page data load error

**Comment by davimacedo** [comment]
Thanks for reporting @dukejob . Would you be willed to open a PR with the fix?

**Comment by mtrezza** [comment]
Maybe related to https://github.com/parse-community/parse-dashboard/issues/1551

Closing as this probably needs to be fixed as part of the larger issue of #1551.
