### ISSUE TITLE
Tag latest release docker images with release version in addition to 'latest'

### ISSUE THREAD

**Issue by evtimmy** [parse-community/parse-dashboard#1671]
Currently:
The latest release right now is 2.1.0 and on docker hub we only see last release '2.0.5' as well as 'latest'

Expected:
Docker hub should have '2.1.0' tagged image as well. This allows developers to have a fixed-version dependency on the most up-to-date release (at point of time when creating/testing the resource using the image).

**Comment by mtrezza** [comment]
I'm closing this. The latest release is on docker. There may be releases in between that are missing on docker, but unless someone really needs them, releasing the missing docker images doesn't have a high priority.
