### ISSUE TITLE
Deprecations and readiness for react 17+

### ISSUE THREAD

**Issue by romanbsd** [parse-community/parse-dashboard#1679]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Current parse-dashboard

#### Steps to reproduce
Check Chrome console.

#### Logs/Trace
Check Chrome console.

There're some parts of the code which use obsolete and legacy APIs, namely deprecated lifecycle, references and context APIs.
I started fixing all these (and other eslint) issues, made a pretty good progress so far (see https://github.com/parse-community/parse-dashboard/compare/master...romanbsd:fix_warnings for work in progress), and a pull request can be made, but I'll need someone to take over QA, since I don't even use all the functionality and less familiar with.
So, if someone is willing to help with testing, it can be done.

**Comment by mtrezza** [comment]
Hi @romanbsd, thanks for opening this issue and apologies for the lack of activity here. We would be very interested in someone pickup up the modernization fo the dashboard. Would you still be interested in pursuing this and if yes, please let me how we can support you.

**Comment by romanbsd** [comment]
My work (linked above) is in a pretty good shape, but needs a review. It needs some work, but it's mostly done.
So I can open a pull request and you can start reviewing the changes.

**Comment by mtrezza** [comment]
Sure, let's do that! There have been many PR merged in the dashboard lately, so it may take a bit of effort to rebase your PRs on the current master branch.

**Comment by damianstasik** [comment]
@romanbsd may I take this issue? I already started doing some work on this with string refs and `componentWillReceiveProps`/`componentWillMount` refactors and I could take the rest if you are okay with it.

**Comment by romanbsd** [comment]
Yeah, sure. I don't have time for that at the moment. But take a look here: https://github.com/parse-community/parse-dashboard/pull/1677/files
and especially here:
https://github.com/parse-community/parse-dashboard/pull/1761
It may have all the changes you need.

**Comment by mtrezza** [comment]
Closing in favor of https://github.com/parse-community/parse-dashboard/issues/1902
