### ISSUE TITLE
parse server display not working in windows-10 but working on a macOS

### ISSUE THREAD

**Issue by harshitmawandia** [parse-community/parse-dashboard#1681]
I recently set up a new bitnami parse server on my windows10 based laptop and found that when I logged in entering the user-id and password, I got a blank screen.

To check if there was a problem, I asked my friend to check it on his Mac and there the display seemed to be working fine.
Both of us used google chrome.

Can anyone suggest a solution??

**Comment by davimacedo** [comment]
Could you please share any error message that you see in the parse dashboard logs or in the web browser console or any more details you may have?

**Comment by harshitmawandia** [comment]
@davimacedo you could check it out here, it would be a great help, thanks!
[3.135.216.91-1618560011187.log](https://github.com/parse-community/parse-dashboard/files/6323443/3.135.216.91-1618560011187.log)

**Comment by harshitmawandia** [comment]
The problem was solved by changing the site settings. Thanks for your time by allowing insecure content.
