### ISSUE TITLE
Exclude fields from table. not just hide

### ISSUE THREAD

**Issue by itzharDev** [parse-community/parse-dashboard#1693]
any way to exclude fields from the parse dashboard (not only hiding, actually not getting this field data from dashboard query)?

something like select\exclude as exists in SDK.

**Comment by itzharDev** [comment]
in Browser.react.js

this lines just do the job:

    query.limit(MAX_ROWS_FETCHED);
    let columns = localStorage.getItem(`ParseDashboard:${VERSION}:${this.props.params.appId}:${source}`)
    if (columns) {
      columns = JSON.parse(columns)
      columns = columns.filter(clmn => !clmn.visible).map(clmn => clmn.name)
      for (let columnsKey in columns) {
        query.exclude(columns[columnsKey])
      }
    }

**Comment by davimacedo** [comment]
I think that it is something that could be added, but why do you need that?

**Comment by itzharDev** [comment]
I have a big collection in which I store base64 images in a field
I don't need to fetch this data on a browser
it couse my browser to load very slow and got stack in 100+ records

**Comment by davimacedo** [comment]
That makes sense. Do you want to open a PR for this?

**Comment by itzharDev** [comment]
ill send in few minutes

**Comment by itzharDev** [comment]
https://github.com/parse-community/parse-dashboard/pull/1694
