### ISSUE TITLE
Open pointer in new browser tab with [Cmd] click

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1711]
## Feature Suggestion

Open a pointer in a new browser tab when clicking on it while holding the [Cmd] button.

The purpose is that while the dashboard already allows to follow a pointer and jump back with the "Back" button, the previous page is newly fetched from the server and scrolled to top. So this type of navigation cannot be practically used to follow multiple pointers.

**Comment by mtrezza** [comment]
@sadakchap, @fn-faisal Would any of you interested in looking into this issue? It should be a fairly small PR.

**Comment by fn-faisal** [comment]
@mtrezza  Ok, I'll take a look at it.

**Comment by fn-faisal** [comment]
I have made a PR for this.
https://github.com/parse-community/parse-dashboard/pull/1757
