### ISSUE TITLE
Un-hidden columns contain empty fields

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1716]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.
- [x] You're running version >=2.3.2 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

## Issue
The PR https://github.com/parse-community/parse-dashboard/pull/1694 excluded hidden columns from being fetched from the server. When showing previously hidden columns, the values for the un-hidden fields are `(undefined)`, because their values have not been fetched. Clicking the "Reset" button loads the fields.

## Instructions

1. Hide a column with values
2. Click "Reload"
3. Un-hide column --> fields are empty
4. Click "Reload" --> fields contain values

**Comment by sadakchap** [comment]
Thanks @mtrezza for detailed instruction to reproduce the issue. But, I still could not reproduce the issue. could you please check below gif & tell me which step I am missing ?

#### Steps I followed - 
1. Hide a column with values
2. Hit refresh button
3. Un-hide that column --> still can see the values

![unhideCols](https://user-images.githubusercontent.com/44117648/119995202-f8a8da00-bfea-11eb-8da2-1794d1d1db60.gif)

**Comment by mtrezza** [comment]
Could you try to create a new column and it with that? Maybe it only happens for certain columns.

**Comment by sadakchap** [comment]
Still was not able to reproduce the issue.

**Comment by mtrezza** [comment]
This is what I see on Safari. Note that without refreshing, the column contains data after un-hiding it. But after refreshing, it does not contain data when un-hiding it. I am using branch https://github.com/parse-community/parse-dashboard/pull/1697/commits/2a4479a90d37cf930b01436f64a0b062d2331606.

I think the simple question is, if columns a not fetched when they are hidden, how would the data show in the column after un-hiding it? Or does un-hiding a column trigger a query?


https://user-images.githubusercontent.com/5673677/120074213-171ade00-c09c-11eb-99aa-c5926c8db222.mov

**Comment by fn-faisal** [comment]
I tried to reproduce this on Chrome, Safari browsers but could not reproduce this. I tried the master branch and the [commit](https://github.com/parse-community/parse-dashboard/commit/2a4479a90d37cf930b01436f64a0b062d2331606) but can't reproduce this.
It would be helpful if we had some more information regarding this like the devtools console, network request response for the refresh call.
Thank you.

**Comment by davimacedo** [comment]
What do you guys think about automatically refreshing the data everytime a new column is marked as visible?

**Comment by mtrezza** [comment]
Yes, that was my previous question:

> I think the simple question is (...) does un-hiding a column trigger a query?

**Comment by sadakchap** [comment]
Yes, no server request is going when the column is unhidden.

**Comment by sadakchap** [comment]
@mtrezza, I tried to add a breakpoint before exclude query. Please see the below gif.

![unhideExplained](https://user-images.githubusercontent.com/44117648/121729079-afd54300-cb0b-11eb-9a21-9b78c932927e.gif)

1. added a breakpoint, cleared the localstorage(as this is where we store column preference)
2. Hit refresh for the first time ( no column is hidden till now )
3. Hide a column, here we got key on localstorage which has hidden column visible set to false.
4. Hit refresh, see at breakpoint `columns` is still null.

From above gif, I think maybe some problem in getting column preference from localstorage as it is always null and `query.exclude` never got executed resulting in a request which is fetching all details.

Could you please try to reproduce this issue from clearing localstorage.

**Comment by sadakchap** [comment]
I think it is clear from above video, that we are unable to get columns from local storage. Here's the pr https://github.com/parse-community/parse-dashboard/pull/1734 for that.

**Comment by mtrezza** [comment]
> Yes, no server request is going when the column is unhidden.

Well, I think that is the simple explanation, isn't it? Where would the column data come from if a previous query excluded the field.

**Comment by sadakchap** [comment]
> Well, I think that is the simple explanation, isn't it? Where would the column data come from if a previous query excluded the field.

Yes but, the previous request actually never excluded the field. Please refer the video above once more. You can see the Network tab.

> The request should exclude the field, so that should not happen. That was the point of #1694. If you cannot reproduce the issue, you may not be using the current `master` branch where the PR has been merged.

I think I am using latest `master` branch. I also had put a debugger, you can see the code, it's from `master` branch.

**Comment by davimacedo** [comment]
@mtrezza can we close this one?

**Comment by mtrezza** [comment]
Yes, closed with https://github.com/parse-community/parse-dashboard/pull/1734
