### ISSUE TITLE
Can not create column name starting with numbers

### ISSUE THREAD

**Issue by sadakchap** [parse-community/parse-dashboard#1719]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

## Issue
Can not create columns name starting with numbers. It does not give any information about operation whether it failed or succeeded ( can not see new column added though )

#### Steps to reproduce

1. Click on "Add a column"
2. Enter column name starting with number
3. Can not see new Column

Please see below gif.
![newColumnError](https://user-images.githubusercontent.com/44117648/119982487-87fac100-bfdc-11eb-818c-cf816a1f2ec7.gif)

#### Logs/Trace
In network tab, the request is giving 105 error, saying invalid field name
![image](https://user-images.githubusercontent.com/44117648/119982760-e031c300-bfdc-11eb-9ccd-f6258396e62f.png)

**Comment by mtrezza** [comment]
Let's look at two separate issues:

a) Is the Parse Dashboard validation correct according to Parse Server?
b) What is the reason for Parse Server throwing the error?

For a):
The validation seems to be incorrect if Parse Server according to your example.


For b):
I don't think there is any limitation that prevents from using a key string that contains (or begins with) a number:
- JavaScript allows any string as key
- MongoDB allows any string as long as it doesn't interfere with reserves symbols, such as `$` or operators such as `.` in dot notation.

b)

**Comment by sadakchap** [comment]
It's seems like a validation Error for parse-server, in [schemaController.js](https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/src/Controllers/SchemaController.js#L979).

We also have a test case for this [here](https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/spec/schemas.spec.js#L2698).

**Comment by mtrezza** [comment]
I don't see a reason for prohibiting field names starting with a number.

Maybe the blame lines can give more insight into why this is prohibited.

**Comment by mtrezza** [comment]
I suggest to open an issue in the parse server repo for this and link to this issue, so we have the investigation in the right repo and for future reference. There may also be existing related issues in the server repo.

**Comment by davimacedo** [comment]
It looks it was done on purpose (https://github.com/parse-community/parse-server/blob/9ea355b4635226ae4da17c8cc5fb0321e3fdec5e/src/Controllers/SchemaController.js#L427) but I don't know the reason. I think we should merge this PR anyways, since it is the current status of Parse Server and the PR actually solves a current bug when someone try to create a field stating with a number.

**Comment by mtrezza** [comment]
OK, let's merge this and open @sadakchap would you mind opening an issue on Parse Server about this limitation?

**Comment by mtrezza** [comment]
closed via #1718
