### ISSUE TITLE
Add option to create a field after creating a class

### ISSUE THREAD

**Issue by fn-faisal** [parse-community/parse-dashboard#1726]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
It would be nice to allow the user to add fields after creating a class. Where the user has another option to either _Create class_ or _Create class and add columns_. Once the user chooses the _Create class and add columns_, the create a field dialog popsup with another option something similar to _Create field and add another field_ and upon choosing the second option, the field is created and the dialog remains open for the user to add fields until they close or select the first option

**Comment by mtrezza** [comment]
Thanks for suggesting.

Generally, to keep the codebase maintainable, we should avoid feature duplication. Unless it provides a clear benefit for usability to maintain multiple flows to achieve the same outcome.


If I understand your suggestion correctly, you want combine the following features into one modal view:
- create class
- add columns

Before we come to the conclusion of adding an additional flow, let's analyze the problem first, that is why you are not satisfied with the current flow and what it's shortcomings are in your view.

**Comment by fn-faisal** [comment]
The idea was to tie flows together to reduce user navigation. So that users can create a class and columns in one flow.
So when the users create a class, they can choose to continue adding columns in the same flow by allow the user to open the create column dialog with an additional button.
Something similar to flow below. The create buttons will simply close the dialogs while create and add buttons will continue the flow.

![CreateColumnFlow](https://user-images.githubusercontent.com/23558802/121882051-7843e200-cd29-11eb-85bc-5a50b4911011.jpg)

**Comment by mtrezza** [comment]
I think I understand what you are aiming for. I assumed you wanted to add a more complex dialog for column addition / management. But you are only suggesting to add a "Add a new column" button directly into the dialog for not having to click on the "Add column" button in the browser bar. I think that makes sense, as it saves 1 click.

**Comment by mtrezza** [comment]
Closed via #1728
