### ISSUE TITLE
Dashboard takes long time to open 

### ISSUE THREAD

**Issue by sadakchap** [parse-community/parse-dashboard#1746]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
- [x] You're running version >=2.3.2 of Parse Server.

### Issue
If the user has multiple apps in the dashboard, and a single one is failing, then the dashboard takes really long time to open(like 2-4 mins).

**Comment by mtrezza** [comment]
Can you please try whether this issue still exists in the latest release? I suspect https://github.com/parse-community/parse-dashboard/pull/1802 has fixed this issue.

**Comment by mtrezza** [comment]
Closing as this issue seems to be resolved.
