### ISSUE TITLE
the bold border is not covering the whole cell

### ISSUE THREAD

**Issue by fn-faisal** [parse-community/parse-dashboard#1753]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the [latest version of Parse Server](https://github.com/parse-community/parse-server/releases).
- [x] I can reproduce the issue with the [latest version of Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases).

### Issue Description
The border around the cell is no longer covering the whole cell when selecting a cell.
<img width="720" alt="Screenshot 2021-08-05 at 6 48 30 PM" src="https://user-images.githubusercontent.com/23558802/128361495-9303c841-2803-426e-8c6b-d4b65eaaa2ae.png">

### Steps to reproduce
Open a table in Database browser and click a cell. The border should appear but it does not cover the entire cell.

### Actual Outcome
The border appears smaller than the actual cell height.

### Expected Outcome
Upon clicking on a cell, the border should match the height of the column and cover the entire cell.

### Pull Request
https://github.com/parse-community/parse-dashboard/pull/1754

Dashboard
- Parse Dashboard version: `2.1.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome, Safari`
- Browser version: `92.0.4515.131`

**Comment by mtrezza** [comment]
Closed via #1754
