### ISSUE TITLE
Impossible to edit array of pointers in v2.2.0

### ISSUE THREAD

**Issue by johanarnor** [parse-community/parse-dashboard#1770]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
In v2.2.0 it's no longer possible to properly edit the value of an array containing pointers. https://github.com/parse-community/parse-dashboard/pull/1727 introduces a click action that overrides the standard in-place edit box.

I therefore tried to edit the data via the modal, but this would instead corrupt the data. The data is displayed like this (which if saved will corrupt the data)
```
[
  {"objectId": "3EAyCmr7BU"},
  {"objectId": "EAGB5dfkCe"}
]
```
instead of the actual raw format.
```
[
  {"__type":"Pointer","className":"Item","objectId":"3EAyCmr7BU"}, 
  {"__type":"Pointer","className":"Item","objectId":"EAGB5dfkCe"},
]
```
However this issue with the modal wasn't introduced in v2.2.0, since it's present in v2.1.0. Another interesting behaviour is that the whole object will be "inflated" (i.e. all fields will be populated) if you visit that object in the same browser tab prior to trying to edit the array of pointers.

Also, a CTRL+C puts "[object Object]" in the clipboard instead of the actual raw object.

### Expected Outcome
I'm not sure what a good solution would be here. Maybe just remove the click action to bring up the original edit box.

I've never used the modal, so I'm not really sure what's the expected outcome here.

**Comment by mtrezza** [comment]
@sadakchap Could you take a look at this?

**Comment by sadakchap** [comment]
Sure @mtrezza , Thanks!

**Comment by sadakchap** [comment]
Here's the pr https://github.com/parse-community/parse-dashboard/pull/1771

**Comment by mtrezza** [comment]
Closing via #1771
