### ISSUE TITLE
Remove tooltip for read-only date field

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1772]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

PR https://github.com/parse-community/parse-dashboard/pull/1688 introduces a change that shows a tooltip when trying to select the date string of a read-only date field (`updatedAt`, `createdAt`).

This is unusual because:

- It is contrary to how read-only spreadsheet or table cell elements work (allow to select, but in different visual state).
- It is contrary to how editable date fields can be interacted with, interfering with intuitive usability and work flow.
- It prevents the user from selecting and copying only a part of the date string.
- A tooltip is an intrusive UI element that should only be used if important information is displayed; in this case, it contains a description that the ctrl-c shortcut can be used copy a value.

### Steps to reproduce
1. Open any class in browser
2. Double click on `createdAt` read-only date field

### Actual Outcome
Shows tooltip.

### Expected Outcome

If a cell is read only, a cell or text field is usually displayed in a different visual style, still allowing the text to be selected but not edited.

Common UI design practice is to remove the "focus" indicator (ie. the element that highlights a selected cell). Given the existing design of Parse Dashboard, I suggest to just slightly gray out the background of the cell to make clear that it is non-editable.

![image](https://user-images.githubusercontent.com/5673677/130305411-5d464c63-85fe-4d62-bc36-9725c18338be.png)
(https://uxframework.pearson.com/c/inputs#states)

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `14.1.2`

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

**Comment by mtrezza** [comment]
@sadakchap Could you take a look at this? This is the continuation of our discussion in https://github.com/parse-community/parse-dashboard/pull/1688.

**Comment by sadakchap** [comment]
@mtrezza should we remove tooltip from only readonly && date fields or all readonly fields?

And if we remove tooltip will these styles give intuition about readonly field?
<img width="529" alt="image" src="https://user-images.githubusercontent.com/44117648/195750416-24a4db06-6651-4f5d-b04b-d04a2dde8bd9.png">

**Comment by mtrezza** [comment]
> And if we remove tooltip will these styles give intuition about readonly field?

See screenshot in https://github.com/parse-community/parse-dashboard/issues/1772#issue-983769711

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)
