### ISSUE TITLE
Layout issue in field containig array of pointers

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1775]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Layout issue affecting cells containing an array of pointers.

### Steps to reproduce

https://user-images.githubusercontent.com/5673677/131840859-6c808fdf-2d4b-48f4-b1e2-efcd4a0c9f54.mov

### Actual Outcome
- Border not visible when scrolling down in array of pointers
- Border not outlining whole cell

### Expected Outcome
- Border should be always visible, regardless of scrolling
- Border should outlining the whole cell, just like any other selected cell

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `14.1.2`

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

**Comment by sadakchap** [comment]
Here's the [pr](https://github.com/parse-community/parse-dashboard/pull/1776)!

**Comment by mtrezza** [comment]
Closed via #1776
