### ISSUE TITLE
Layout issue, Sidebar comes on top of modal

### ISSUE THREAD

**Issue by sadakchap** [parse-community/parse-dashboard#1777]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Sidebar comes on top of modal(big modals), due to which can not see modal content.

### Steps to reproduce

https://user-images.githubusercontent.com/44117648/131890670-c7bf8e64-9f52-456a-b9df-3c1f922bee68.mp4

This was issue came up in this Screen Resolution - 1366 x 768.

### Actual Outcome

-  Modal content not visible due to sidebar

### Expected Outcome

- Modal content should be on top of Sidebar, so that its content is visible.

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 92.0.4515.159`

Server
- Parse Server version: `n/a`
- Operating system: `n/a`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `n/a`

Database
- System (MongoDB or Postgres): `n/a`
- Database version: `n/a`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `n/a`

**Comment by mtrezza** [comment]
I think that's because I changed the sidebar `z-index` in https://github.com/parse-community/parse-dashboard/pull/1760/files#diff-beaf5f033a1bc7a22b0ff907b0c114ab47f21efd5ff140fe53fbe87f08f71654.

If the `z-index` is now changed again to fix this, the `API Console > JS Console` should be checked, because that overlapped the sidebar.

**Comment by mtrezza** [comment]
Closed via #1778
