### ISSUE TITLE
Wrong CLP shown after creating new class

### ISSUE THREAD

**Issue by sadakchap** [parse-community/parse-dashboard#1784]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Wrong CLP info is shown after creating new class for first time, Until reload. Classes are created with `Public read & write enabled` by default. But, after creating a new class dashboard is showing `Protected` CLP for that class.

### Steps to reproduce

https://user-images.githubusercontent.com/44117648/132239619-b508d900-7069-48b6-a87d-0ad1de8573bf.mp4

### Actual Outcome

 
Showing wrong CLP for new class. i.e., showing `Protected` CLP for new class which was created with `Public Read & write Enabled` CLP.

### Expected Outcome

Should show correct CLP for the newly created class as well.

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 92.0.4515.159`

Server
- Parse Server version: `4.10.3`
- Operating system: `Ubuntu`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote`

Database
- System (MongoDB or Postgres): `mongoDB`
- Database version: `3.6`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote`

**Comment by sadakchap** [comment]
Here's the [pr](https://github.com/parse-community/parse-dashboard/pull/1785)

**Comment by mtrezza** [comment]
Closed via #1785
