### ISSUE TITLE
Docker image doesn't work anymore with the MFA feature

### ISSUE THREAD

**Issue by Klaitos** [parse-community/parse-dashboard#1787]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The merge of the MFA feature https://github.com/parse-community/parse-dashboard/pull/1624 add some dependencies which need node 12 at leat. The docker image is built over node 8. The container can't be run anymore.

### Environment

Dashboard
- Parse Dashboard version: `FILL_THIS_OUT`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `FILL_THIS_OUT`
- Browser version: `FILL_THIS_OUT`

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

**Comment by mtrezza** [comment]
We would have to make a 3.0 release as bumping the min node version is breaking.

a) How could we have prevented this issue?
  Our CI needs a multi-environment setup, like parse server. Currently: 
  - the PR CI runs only on node 10.14
  - the release CI only on node 12
  
b) How do we resolve this issue?
  Maybe an opportunity to start a LTS trial also for dashboard

**Comment by Klaitos** [comment]
Hello @mtrezza,

I'm not surprise for a `latest` tag to be buggy, it was my mistake to use it in my docker-compose. I fixed my compose to stick the version to 2.0.5 to prevent future issues.

For your **b)** i think it's a good idea to release a last stable version of parse-dashboard 2.x without MFA and node 12.

For your **a)** i need to think more about it.

**Comment by mtrezza** [comment]
Anything below node 12 has actually reached its EOL, so we wouldn't even offer LTS for a dashboard 2.x version.
You discovered an interesting case that is not yet covered by out CI, if there is a way to prevent this, I'd like to add it to our CI.

So the plan is:
1. Update our CI to find a way to prevent this, at least with multiple node versions
2. Bump min node version to 12
3. Release dashboard 3.0

**Comment by mtrezza** [comment]
> The docker image is built over node 8. The container can't be run anymore.

@Klaitos How did you encounter the error? I am trying to fore-see that in the CI, but the docker builds without issues.
We this a runtime error when you tried to use the MFA auth feature?

**Comment by Klaitos** [comment]
Just try to run the container without any option.
` docker run  -p 8080:4040 -v "/path/to/parsedashboard.json:/src/Parse-Dashboard/parse-dashboard-config.json" parseplatform/parse-dashboard:latest`

<img width="1300" alt="Capture d’écran 2021-09-08 à 18 31 53" src="https://user-images.githubusercontent.com/644360/132548921-eaa632f9-610b-4135-87ea-5d8c91caa84e.png">


And with node 12 (builded on my laptop) :

<img width="1111" alt="Capture d’écran 2021-09-08 à 18 32 19" src="https://user-images.githubusercontent.com/644360/132548971-4ec8808a-067e-4107-ac28-1d7126281da1.png">

**Comment by Klaitos** [comment]
The build is ok, the issue at runtime

**Comment by Klaitos** [comment]
node 10 is the new minimal. See https://github.com/parse-community/parse-dashboard/pull/1788#discussion_r704605515

**Comment by mtrezza** [comment]
Got it, that's why the builds were pushed successfully. So we need a CI step that ensures that we don't have a dependency that requires a higher node engine than the parent package.

**Comment by mtrezza** [comment]
closed via #1788

**Comment by Klaitos** [comment]
Any chance to have 2.2 or recent tag uploading to the docker hub ? i do not want to use latest anymore for now, but 2.0.5 is quite old :)

**Comment by mtrezza** [comment]
I think we can do that, if you want to open just a short new issue so we don't forget.
