### ISSUE TITLE
Side bar above the relational popup on v2.2.0

### ISSUE THREAD

**Issue by jadsonlourenco** [parse-community/parse-dashboard#1798]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Side bar is above the relational popup, on desktop screen. 
![Issue](https://i.ibb.co/HVGc7q1/Screen-Shot-2021-09-13-at-14-59-49.png)

### Steps to reproduce
Run latest version 2.2.0

### Expected Outcome
Side bar bellow.

### Environment

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Brave`
- Browser version: `1.29.79 Chromium: 93.0.4577.63 (Official Build) (x86_64)`

Server
- Parse Server version: `4.5.0`
- Operating system: `Alpine Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Docker`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `remote`

**Comment by mtrezza** [comment]
Does this still occur with the dashboard of the master branch? An issue like this has been recently fixed.

**Comment by jadsonlourenco** [comment]
Yes, it's solved on the master branch, thank you.

**Comment by mtrezza** [comment]
Great, we plan to release a new version in the coming days.
