### ISSUE TITLE
Revert using objectId as tie breaker in infinite scrolling

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1799]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Since https://github.com/parse-community/parse-dashboard/pull/1706, creating an index to optimize dashboard queries requires compound indices including `objectId`. For example, when browsing a class sorted by `createdAt` a compound index `createdAt, objectId` is required. 

https://github.com/parse-community/parse-dashboard/blob/cb96799a97c23b407320fd5e8df079254f83ec0a/src/dashboard/Data/Browser/Browser.react.js#L650-L656

This approach requires special indices just for dashboard browsing. If an app is using a complex or resource intensive index, dashboard requires the same index plus the additional objectId in the index compound. I don't think this is a feasible solution, given the high cost of indices on a DB. Maybe we need to look for an alternative solution.

Additionally, #1706 broke existing "query optimization" and should have been treated as a breaking change. The reason this was released as non-breaking was that we didn't have the policy that a changelog entry has to be written as part of the PR back then. It was not noticeable without reading the PR discussion in detail that it was a breaking change. This should not happen anymore as we are now requiring a changelog entry with the PR.

### Steps to reproduce
1. Create new call
2. Browse class, sorted by `createdAt`
3. Query `createdAt, objectId` sent to server

### Actual Outcome
Dashboard currently paginates by issuing an entirely new query which requires to construct a complicated pagination mechanism (#1706), which creates the indexing issue described here.

### Expected Outcome
In MongoDB at least, the proper and resource efficient way to paginate is to use the query cursor, see [getMore](https://docs.mongodb.com/manual/reference/command/getMore/). That may require some changes on the server side, for example sending the cursor ID to dashboard as query results meta data. And not sure whether Postgres supports cursor based pagination.

In any case, I think we should revert #1706 ASAP and release as a fix, or at least the part that adds the object ID to the query, because that can render the dashboard unusable or cause stability issues for some deployments.

@sadakchap @davimacedo @Klaitos What do you think?

### Environment
n/a

Dashboard
- Parse Dashboard version: `2.2.0`, `master`

### Logs
n/a

**Comment by sadakchap** [comment]
@mtrezza, yeah.. we should revert #1706 . Could you please do that? And then we can tackle #1551 later separately (probably using [getMore](https://docs.mongodb.com/manual/reference/command/getMore/)).

**Comment by Klaitos** [comment]
I'm glad you changed your mind about it 🙂.

**Comment by mtrezza** [comment]
It's unfortunate that we need to revert it, because that opens the original scrolling issue again, and @sadakchap put some good work into fixing this. However, I think the implications we discovered now do not justify the type of fix.

**Comment by Klaitos** [comment]
Yes sure but I can't do it this week.

**Comment by Klaitos** [comment]
Done here https://github.com/parse-community/parse-dashboard/pull/1800

**Comment by mtrezza** [comment]
Closing via #1800
