### ISSUE TITLE
Performance issue on calculating classes count

### ISSUE THREAD

**Issue by Klaitos** [parse-community/parse-dashboard#1801]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
When computing class counts, the number of documents in each collection, displayed on the sidebar, we loop on each collection and set the state for each collection. This method call the render function of the dashboard, slowing down all the process.

### Steps to reproduce
With a parse-server with lots of collection (50+) : load the dashboard, try to navigate from the sidebar collection list.

### Actual Outcome
Few seconds on each click to load a new page

### Expected Outcome
It should be nearly instant

### Environment
Localhost parse server on MacOS with nodejs 14.7

Dashboard
- Parse Dashboard version: `2.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `93.0.4577.63`

Server
- Parse Server version: `4.10.3`
- Operating system: `MAC OS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.8`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

I'm preparing a demo and trying to open a PR for you

**Comment by Klaitos** [comment]
https://user-images.githubusercontent.com/644360/133608274-feab825d-933c-4a14-b0d3-f729226940f4.mov

After my first try fix : 


https://user-images.githubusercontent.com/644360/133608535-2418bb8a-8883-450c-abf4-6bb55892db88.mov

**Comment by mtrezza** [comment]
Amazing, thanks for opening this issue and submitting the PR!

**Comment by mtrezza** [comment]
Closing via #1802
