### ISSUE TITLE
Make selected text visible on the Edit modal title

### ISSUE THREAD

**Issue by jadsonlourenco** [parse-community/parse-dashboard#1831]
Sometimes we need to copy the objectId, now when we click on this row open the edit modal, but when selecting the text on this modal title, blue area, we can't see that the text is selected.

The fix is just to not set, or remove, this CSS:
```
::selection {
    color: white;
    background: #169cee;
}
```
So, will use the browser default style or set a different color for the background in this style.

Current:
![Screen Shot 2021-10-05 at 11 48 33](https://user-images.githubusercontent.com/1428013/136048245-1235b7e1-f25a-483b-bc45-dd870b2d7f5c.png)

Should be:
![Screen Shot 2021-10-05 at 11 48 41](https://user-images.githubusercontent.com/1428013/136049328-004dd9c6-d221-4276-a04e-afff0c19622c.png)

**Comment by mtrezza** [comment]
I think from a UI perspective, a copy icon next to the ID would be an expected control element. It also saves some clicks, as you don't have to double-click to select the text, then hit a shortcut to copy it.


Similar to:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/5673677/200064116-7c4daf43-ede7-415d-bdee-5fdd397619a9.png">

What do you think?

In general, the dashboard has some accessibility issues. The font sizes and text color to background color contrasts are sometimes not following accessibility standards. That is also the case with white text on light-blue background, or light-gray text on white background.

**Comment by jadsonlourenco** [comment]
I think that keeping the text without this "action icon" is better, keep the UI clean. If we want to copy the dates is easy, easy to use the mouse on the computer and select what the user wants, on mobile too.

Yes, about accessibility and even for design propose the dashboard can be better, the font size in some places, and other issues like #1832 to make the File UX better... 
We can make progress solving this issue with time, so, I think for now this one is good to have merged, and then we can open others to solve the accessibility.

**Comment by mtrezza** [comment]
I was able to reproduce the color issue you described in Chrome:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/5673677/200094049-f02cfa29-5e4f-424b-aa8c-5c84722d3d9a.png">


While in Safari it seems to override with default colors:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/5673677/200092608-99d95a34-69e3-4e0e-b077-286a6fdc0b5e.png">

I think we can treat this is a bug, thanks for opening the PR.
