### ISSUE TITLE
GraphiQL is missing header configuration

### ISSUE THREAD

**Issue by axelhildingson** [parse-community/parse-dashboard#1834]
### New Issue Checklist

- [X ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X ] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [X ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The old playground included the possibility to configure the header. I used it to change it to session-token instead of master key to test the query for a specific user. 

It looks like this feature is included in graphiql but is hidden.  

### Expected Outcome

<img width="317" alt="Screenshot 2021-10-06 at 09 38 48" src="https://user-images.githubusercontent.com/7069084/136160863-6fda7bce-ca25-4d1b-9f4b-9442b303111f.png">

<img width="679" alt="Screenshot 2021-10-06 at 09 44 13" src="https://user-images.githubusercontent.com/7069084/136161684-624c5c15-2e9b-4fbf-812b-3436f892acc1.png">

### Environment

Dashboard
- Parse Dashboard version: `3.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `chrome`

**Comment by dblythy** [comment]
Hey @axelhildingson! Thanks for submitting this issue. `GraphIQL` is a new feature added to resolve the issues that `GraphQLPlayground` was causing, so we appreciate you jumping in and trying it out!

Would you be willing to submit a PR fixing this?

**Comment by axelhildingson** [comment]
Thank you for fast answer!

I can take a look at it, when I have time it is not super prio at this moment.

**Comment by mtrezza** [comment]
Closing via #1836
