### ISSUE TITLE
Distinguish external from internal classes

### ISSUE THREAD

**Issue by davimacedo** [parse-community/parse-dashboard#1849]
### New Feature / Enhancement Checklist

- [ X ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X ] I have searched through [existing issues](https://github.com/parse-community/parse-server/issues?q=is%3Aissue).

### Current Limitation

It is currently possible to create a class called User and a class called _User. Both show up in Parse Dashboard with the name User and it causes confusion for some users when using Parse Server for the first time.

In addition to that, it is very confusing when we have to use _User or User throughout the sdks, endpoints, etc.

### Feature / Enhancement Description

I believe we should change Parse Server in such a way that User and _User point out to the same thing. So no matter if we send User, or _User, via the api, they will always refer to the _User class we currently have.

### Alternatives / Workarounds

An alternative could be simply disallow the developers to create a User class.

**Comment by damianstasik** [comment]
@mtrezza I tried to experiment with grouping classes visually and for now, it seems like showing the real name would be the simplest solution:

<img width="263" alt="Screen Shot 2021-10-20 at 15 56 04" src="https://user-images.githubusercontent.com/920747/138106972-e2701816-8e87-4a29-9f08-87ca0c1b3bb0.png">

Would you accept a PR with such change?

**Comment by mtrezza** [comment]
Sure, would you add a line to separate the internal classes, like in the screenshots in https://github.com/parse-community/parse-dashboard/issues/1849#issuecomment-886039636? I think it would be a helpful visual guide to faster identify internal classes.

**Comment by damianstasik** [comment]
@mtrezza yes, [the PR is ready](https://github.com/parse-community/parse-dashboard/pull/1878), and here is how it looks:

https://i.imgur.com/dzfhv7Z.png

The only thing that I am not sure about is the separator API, there are a few ways of doing it, I chose the one that could be reused in other lists if needed.

**Comment by mtrezza** [comment]
Looks perfect! I'll review.

**Comment by mtrezza** [comment]
Closing via #1878
