### ISSUE TITLE
App icon cropped on some resolutions

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1850]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Apps list view appears to not be fully responsive as on some resolutions icons are cropped:

<img width="310" alt="Zrzut ekranu 2021-10-11 o 11 04 51" src="https://user-images.githubusercontent.com/45104241/136764305-1ef52c49-9e36-4ae0-9a22-8aeaf62b7534.png">

### Steps to reproduce

The issue seems to be specific to mobile devices but the easiest way to reproduce it is to increase browser zoom with ctrl+.

### Actual Outcome
As shown in the image above.

### Expected Outcome

Preserve icon's original aspect ratio.

### Environment

Dashboard
- Parse Dashboard version: 3.2.1
- Browser (Safari, Chrome, Firefox, Edge, etc.): any
- Browser version: any

**Comment by mtrezza** [comment]
Closing via #1876
