### ISSUE TITLE
feature request: custom order of columns in the filter popup

### ISSUE THREAD

**Issue by vince1995** [parse-community/parse-dashboard#1883]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

We have some classes with a lot of columns. If we want to filter one of these classes, we use most of the time something like `email`, `objectId` or `userId`. If we open the filter popup we have to scroll down the entire list and search the correct column name.

### Feature / Enhancement Description

It would be really cool if there's a feature to change the order to our preferences. The `columnPreference` could be extended for this feature.

### Example Use Case

Add to the `columnPreference` a Boolean like `filterSortToTop`. Everything that is truthy will be on the top of the list.

**Comment by mtrezza** [comment]
Sounds very practical!

> Add to the columnPreference a Boolean like filterSortToTop. Tverything that is truthy will be on the top of the list.

How should the fields at the top be sorted among themselves - also alphabetically or in the order as specified in the config?

**Comment by vince1995** [comment]
In the PR #1884 I‘ve opened I sort them in the same order as in the `columnPreference` setting. I assume that this behavior is expected and prefered from other users. I mean we set that order for the DataBrowser, so that‘s a point also for the order in the filter popup.

**Comment by mtrezza** [comment]
Yes, sounds good!

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)
