### ISSUE TITLE
Add auto-complete typing to column dropdowns

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1891]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Currently, selecting a column from a list (dropdown) can only be done by scrolling through the list.

### Feature / Enhancement Description
Allow to type the column name with auto-complete, to make it easier to select the column. For example, even just typing the letter `u` makes it much faster to find the column `user`, than scrolling down and having to visually scan all column names.

As a visual aid, the entered filter string should also be highlighted (bold) in the filtered column name results.

### Example Use Case

Entering `obj` should filter the list by column names containing (not just starting with) that string:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/5673677/195983388-0c36a783-30af-4e15-ae0f-4ce21da90294.png">

### Alternatives / Workarounds
n/a

**Comment by sadakchap** [comment]
@mtrezza, just to confirm, we are referring to below dropdowns, correct?

#### When deleting a column.
<img width="541" alt="image" src="https://user-images.githubusercontent.com/44117648/195970557-eafb8eda-fd7c-4e13-9fd8-21f40dea57cb.png">

#### When using filter
<img width="550" alt="image" src="https://user-images.githubusercontent.com/44117648/195970576-94d21748-bcea-40cc-a496-aa0c20b96688.png">

**Comment by mtrezza** [comment]
Not in any of the "remove" dialogs, because there we want the user to explicitly enter the column or class name to confirm the deletion. The feature should be added only in the filter dialog (2nd screenshot above).

The typical UI control would be to filter the dropdown list as soon as the user starts typing, showing only the column names that contain (not just start with) the typed string. The user also needs to see what they currently typed, so the UI control becomes a mix of text field and drop down. A visual aid and nice-to-have would be to highlight portions of the text in the column names after which it is filtered.

Here is a quick mock-up:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/5673677/195983347-6566e688-729d-44b6-952e-ec1fdfe8799f.png">

**Comment by patelmilanun** [comment]
can we use this component parse-dashboard/src/components/Autocomplete/Autocomplete.react.js

![image](https://github.com/parse-community/parse-dashboard/assets/20059797/b85d4151-b4ba-4770-852f-1973a8a89705)

**Comment by mtrezza** [comment]
Good idea, maybe if that works, and can be styled aesthetically to fit the filter dialog?

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.17](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.17)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
