### ISSUE TITLE
Checking of new features in the latest dashboard version does not work

### ISSUE THREAD

**Issue by damianstasik** [parse-community/parse-dashboard#1893]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
[This condition](https://github.com/parse-community/parse-dashboard/blob/82b636a409fe5e916dad628e51fdedfaaae141ea/Parse-Dashboard/app.js#L13) will always be false, because `package-json` does not return custom properties by default.

### Steps to reproduce
Set a breakpoint or try logging `latestPackage.parseDashboardFeatures`.

### Actual Outcome
`latestPackage.parseDashboardFeatures` is `undefined`.

### Expected Outcome
`latestPackage.parseDashboardFeatures` should be an array.

### Environment
Node 14.17.3

Dashboard
- Parse Dashboard version: 3.2.1
- Browser (Safari, Chrome, Firefox, Edge, etc.): not relevant
- Browser version: not relevant

Server
- Parse Server version: not relevant
- Operating system: not relevant
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): not relevant

Database
- System (MongoDB or Postgres): not relevant
- Database version: not relevant
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): not relevant

**Comment by mtrezza** [comment]
Is the "latest features" even used? The only purpose of this seems to display an upgrade prompt, but I have never seen such a prompt. I wonder whether this that made it into the open source codebase but is really non-functional?

https://github.com/parse-community/parse-dashboard/blob/3bc8eece25fd76ea8d692eeb4555015afdde773f/src/dashboard/Apps/AppsIndex.react.js#L140-L147

We could possibly even remove the whole feature if it's not applicable to the open source version.

**Comment by damianstasik** [comment]
That could be due to the fact that `newFeaturesInLatestVersion` was always empty, even if there were new features in the latest version. If we would remove this thing completely it could be a non-breaking release due to this bug.

**Comment by mtrezza** [comment]
If this bug fix enables a "forgotten" feature, we should probably check how this feature behaves before merging. It could be too intrusive, break something else that is incompatible, or display incorrect information.

**Comment by damianstasik** [comment]
@mtrezza I removed the "Data Browser" entry from `package.json` and started the dashboard to look for the message and it shows at the bottom of the page if you enter apps index. It correctly listed the "new feature" and the link to the package on npmjs.com is correct.

<img width="999" alt="Screen Shot 2021-10-30 at 22 20 09" src="https://user-images.githubusercontent.com/920747/139557403-878343c7-115c-49d2-a0ec-82f48840a62a.png">

**Comment by mtrezza** [comment]
That's a pretty neat feature! So we can add a feature entry to package.json and all dashboard deployments will see that info?

**Comment by damianstasik** [comment]
Yes! The only problem is that dashboards without the #1894 would not see anything 😞

**Comment by mtrezza** [comment]
Well let's merge it then!

**Comment by mtrezza** [comment]
Closing via #1894.
