### ISSUE TITLE
Context menu not working for Number type of cells

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1914]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
An attempt of opening context menu on `Number` type of cell results in cell selected but menu not open.

### Steps to reproduce

1. Open browser, find a column with `Number` data type;
2. Right click on a non-empty cell in this column.

### Actual Outcome

Cell gets selected but context menu is not appearing. Following is logged in the browser console:
```
Uncaught TypeError: t.copyableValue.substr is not a function
    at dashboard.bundle.js:2
```

### Expected Outcome
Cell should became selected, context menu should open.

Dashboard
- Parse Dashboard version: `3.2.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `any`
- Browser version: `any`

Server
- Parse Server version: `any`
- Operating system: `any`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `any`

Database
- System (MongoDB or Postgres): `any`
- Database version: `any`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `any`

### Logs

none

**Comment by mtrezza** [comment]
Bug also exists in beta, needs to be ported
