### ISSUE TITLE
Opening the filter menu in data browser throws an error

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1915]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Opening the filter menu in data browser throws an error:

> TypeError: undefined is not an object (evaluating 't.currentApp.columnPreference[s]')

The page becomes blank.

### Steps to reproduce
1. open dashboard
2. open data browser
3. click on "Filter" menu

### Actual Outcome
page becomes blank

### Expected Outcome
filter menu should be displayed

### Environment

Dashboard
- Parse Dashboard version: `3.3.0-alpha.15`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`

### Logs
n/a

**Comment by mtrezza** [comment]
Bug also exists in beta, needs to be ported

**Comment by sadortun** [comment]
@mtrezza Chan you cherry-pick #1958  into 3.3.x patch ?

**Comment by mtrezza** [comment]
We only cherry-pick vulnerability fixes, due to the required effort. It was a small fix, so I think you could just add it to your fork until you upgrade to an official release that includes the fix.

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/1958
