### ISSUE TITLE
Deleting non-referenced files using dashboard

### ISSUE THREAD

**Issue by ishaan1995** [parse-community/parse-dashboard#194]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=2.1.4 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
### Feature

The ability to delete any files that are not referenced by any objects was a good feature of parse.com dashboard.
I would love to see this soon on open-source parse dashboard.It will remove the headache of using Rest api to delete using masterKey.
Thanks a lot

**Comment by drew-gross** [comment]
This is a good idea, but would probably require some server-side support to iterate over all known files.

**Comment by natanrolnik** [comment]
I opened a few days ago this issue in the parse-server repo - it's good to reference here:
https://github.com/ParsePlatform/parse-server/issues/1023
