### ISSUE TITLE
Use buttons instead of `javascript:` links

### ISSUE THREAD

**Issue by damianstasik** [parse-community/parse-dashboard#1941]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
We are now getting warning messages about usage of deprecated `javascript:` URLs:
```
Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:;".
```

### Steps to reproduce
Navigate between random pages and you will see this warning. The solution is to replace all of those links with proper buttons which would make the codebase one step closer to the modern React version.

### Actual Outcome
Warning

### Expected Outcome
No warning, no `javascript:` links in the code, no anchors in places where buttons should be used.

### Environment
All

Dashboard
- Parse Dashboard version: n/a
- Browser (Safari, Chrome, Firefox, Edge, etc.): n/a
- Browser version: n/a

Server
- Parse Server version: n/a
- Operating system: n/a
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): n/a

Database
- System (MongoDB or Postgres): n/a
- Database version: n/a
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): n/a

**Comment by mtrezza** [comment]
Closing via #1940
