### ISSUE TITLE
Add compatibility table to README

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#1956]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Missing Node.js compatibility info for Parse Dashboard.

### Feature / Enhancement Description
Add compatibility table to README for Node.js, similar to the one for [Parse Server](https://github.com/parse-community/parse-server#nodejs).

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by AshishBarvaliya** [comment]
@mtrezza The README has already has the compatibility table.

<img width="1012" alt="Screenshot 2023-04-25 at 9 11 06 PM" src="https://user-images.githubusercontent.com/49753983/234440852-90e9c1d3-313c-4895-8d8b-3110bc60b8c4.png">
