### ISSUE TITLE
Username not always displayed in top left menu

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-dashboard#1960]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

There's a extra text in the top left menu. See below:

<img width="304" alt="image" src="https://user-images.githubusercontent.com/8621344/145719695-ab8a4ec0-9454-420f-be72-457d123a6e82.png">

### Steps to reproduce

Use dashboard 4.0.0-Alpha.5

### Actual Outcome

Extra text in menu

### Expected Outcome

Older versions looked like:

<img width="310" alt="image" src="https://user-images.githubusercontent.com/8621344/145719747-e38f028e-a065-48c8-8ac3-5771fc10209e.png">

### Environment

Dashboard
- Parse Dashboard version: 4.0.0-Alpha.5
- Browser (Safari, Chrome, Firefox, Edge, etc.): Safari
- Browser version: 15.1

Server
- Parse Server version: 5.0.0-beta.4
- Operating system: Linux
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Local docker

Database
- System (MongoDB or Postgres): Postgres
- Database version: 14.1
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): Local

**Comment by mtrezza** [comment]
That's the username I guess.

**Comment by cbaker6** [comment]
> That's the username I guess.

I believe you are right as "parse" is the default account I have setup for testing on a docker localhost.

If it is the username, it doesn't seem to show up on my deployed servers that use multiple dashboards that share the same `PARSE_DASHBOARD_COOKIE_SESSION_SECRET`.

Below is the screenshot of the updated:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/8621344/145732142-37c44517-5270-4dff-911e-7268c778c192.png">

Both use a similar [configuration](https://github.com/netreconlab/parse-hipaa/blob/5c67974efbe92ed21e7a66f4fcc313e9209c5b1c/docker-compose.yml#L38-L43):

```bash
dashboard:
        image: parseplatform/parse-dashboard:4.0.0-alpha.5
        environment:
            PARSE_DASHBOARD_TRUST_PROXY: 1
            PARSE_DASHBOARD_COOKIE_SESSION_SECRET: AB8849B6-D725-4A75-AA73-AB7103F0363F # This should be constant across all deployments on your system
            MOUNT_PATH: /dashboard
```

The only difference is the one showing the username is a single instance on my local machine while the other are 3 instances connected behind a reverse proxy. The one behind a proxy also has 7 parse apps, while the single instance only has 1 app (goes straight to the app after login). It's also configure for multiple users while the single instance is configured for one.

Maybe one of the configurations is causing the username not to show? Maybe the username only works with one user or one app?

**Comment by mtrezza** [comment]
Maybe just a layout issue and the text is there but cut off?

**Comment by cbaker6** [comment]
Possible

**Comment by mtrezza** [comment]
Right click in the browser and look at the html code if you want to know for sure.

**Comment by cbaker6** [comment]
Seems to be a bug. When I don't see "parse" or a username, below is the browser code:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/8621344/146221172-785ae887-9250-4ee3-bff9-350379bb6b70.png">

When I do see "parse" or the username:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/8621344/146221484-f2b411d6-d791-4b94-9047-ee69e76bcb58.png">

Is there a flag somewhere that enables/disables this?

**Comment by mtrezza** [comment]
Good question, maybe it has been removed with some PR, or it has some built-in logic that hides the username on some conditions.

**Comment by cbaker6** [comment]
I can confirm the extra "parse" was indeed the username (I changed the username to see if dashboard display changed).

**Comment by mtrezza** [comment]
The dashboard user's password used to be displayed in the dashboard? It sounds quite unbelievable that such a functionality would make it into dashboard.

**Comment by cbaker6** [comment]
I meant username…

**Comment by mtrezza** [comment]
So issue can be closed?

**Comment by cbaker6** [comment]
No, the username doesn’t show up in the configuration I mentioned, so there seems to be a bug

**Comment by mtrezza** [comment]
Could you pin down in which config exactly this occurs? In your [comment](https://github.com/parse-community/parse-dashboard/issues/1960#issuecomment-991984080) above you mention several factors (cookie, single instance, multiple apps) but it's not clear which one of them, or all, or which combination of these cause the issue.
