### ISSUE TITLE
Can't export more than 10k rows as csv

### ISSUE THREAD

**Issue by sadakchap** [parse-community/parse-dashboard#1961]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

**export all rows** only exports first 10k objects or rows in csv.

### Feature / Enhancement Description

Should be able to export all data in a class.

### Example Use Case

1. user has a class with more than 10k data and wants to export all of the rows in an csv format.

### Alternatives / Workarounds

First export all data in a class as json format selecting **export this data** option from **Edit** menu. Then user have to convert that data to csv format.

**Comment by mtrezza** [comment]
That's a feature limitation, see https://github.com/parse-community/parse-dashboard/pull/1494 why.

The export approach for large datasets could be to use a DB pointer and export in batches. That is currently not supported and would be a new feature request. Until then, you could use mongo shell (or whatever your DB is) to export. 

However, the current 10k is an arbitrary limit. We could add ~~a config option~~ an export dialog field that allows to override the default of 10k.

Side note: the pointer based batch export functionality could be reused to solve the pagination issue https://github.com/parse-community/parse-dashboard/issues/1551. Currently, pointer functionality is not supported by Parse Dashboard at all.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
