### ISSUE TITLE
Import .CSV or .json file to an class

### ISSUE THREAD

**Issue by ArashM98** [parse-community/parse-dashboard#1974]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
i can't import an .csv or .json data to my locally db

### 3rd Party References
yes . i see the import command in back4app.com which is easy to work with

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/parse-dashboard/issues/307
