### ISSUE TITLE
Applying filters not working

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1991]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
When filtering the data URL changes but the browser doesn't refresh. It doesn't matter if filters are applied from filters section or context menu.

![broken-filters](https://user-images.githubusercontent.com/45104241/149220042-a8af279f-cd0b-4f5f-aa96-a91a3bb47c49.gif)

### Steps to reproduce
1. Go to data browser;
2. Click on "Filters";
3. Click on "Apply these filters";
----
1. Go to data browser;
2. Right click on a cell with data;
3. Click on a "Set filter...";
4. Pick any option.

### Actual Outcome
URL changes but nothing happens. Filter panel stays open.

### Expected Outcome
Data browser should refresh and show filtered data. I believe in first scenario filters panel should also close.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `any`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

**Comment by mtrezza** [comment]
I was able to reproduce this issue in 4.0.0-beta.1 and 4.0.0-alpha.5.

**Comment by 404-html** [comment]
This looks like a general problem with reading query string params as opening parse dashboard URL that contains filtering have no effect.

**Comment by mtrezza** [comment]
You could go back to see which PR introduced the issue. I suspect that is was a "refactor" PR that just made a minor dependency upgrade, but somehow is causing issues.

Unfortunately we do not have UI tests in dashboard to detect these issues before merging, and this is not the first time something like this happens. A few UI tests would be a big help in that regard.

**Comment by 404-html** [comment]
Git bisect pointed following commit: https://github.com/parse-community/parse-dashboard/commit/1ff105793fccda33efae1f3742e66b6c6ca213ef

**Comment by mtrezza** [comment]
@404-html There are a couple of similar looking issues where something in the UI is not working / has no effect:

- https://github.com/parse-community/parse-dashboard/issues/1994
- https://github.com/parse-community/parse-dashboard/issues/2006


In case of #2006 it started with version 3.3.0. Could you try to find out the earliest release that introduced the issue, so we can narrow down which commit introduced the issue.

**Comment by 404-html** [comment]
Hey @mtrezza, in my [previous comment](https://github.com/parse-community/parse-dashboard/issues/1991#issuecomment-1013663870) I pointed exact commit which introduced the issue.

**Comment by mtrezza** [comment]
@visualfanatic since you have more insight into https://github.com/parse-community/parse-dashboard/pull/1948, could you take a quick look at this issue here? it may be related to the React context API change, there are also [a few similar new issues](https://github.com/parse-community/parse-dashboard/issues/1991#issuecomment-1018489882) where an action in the UI has no effect, so I would assume it may be a `context` issue, which is one of the major changes in #1948.

**Comment by damianstasik** [comment]
@mtrezza There were some regressions caused by two of my recent refactors and I created a PR with fixes for the issues you mentioned.

**Comment by mtrezza** [comment]
Thanks @visualfanatic for the quick fix! I can confirm it fixes all 3 issues and I already merged the PR, released as `4.0.0-alpha-11`.
