### ISSUE TITLE
On first class open column sorting is always descending

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1992]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
![sorting-problem](https://user-images.githubusercontent.com/45104241/149221558-80ff9e33-d270-4278-b51e-11974047c39f.gif)

### Steps to reproduce
1. Go to data browser;
2. Browse any class;
3. Apply ascending sorting on any column;
4. Switch to different class;
5. Go back to the previous class;

### Actual Outcome
Sorting seems to be descending.

### Expected Outcome
Sorting should be ascending.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `4.10.4`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.11`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

**Comment by 404-html** [comment]
Problem still exists on recent 4.0.0-BETA.2.

**Comment by mtrezza** [comment]
@visualfanatic Would you mind taking a look at this too? It also seems to be related to the changes in context. If that is in fact the case, I think we would need a more thorough review of https://github.com/parse-community/parse-dashboard/pull/1948 to see whether there may be a conceptual issue with the change, or maybe a different pattern that should be applied to more places in that PR.

**Comment by damianstasik** [comment]
I checked `4.0.0-alpha.4` which was released before the context changes and it seems like data browser behaves the same. Could you confirm that @404-html?

**Comment by 404-html** [comment]
Thanks for checking @visualfanatic, and I can confirm that problem also exists on `4.0.0-alpha.4` version.
I ran git bisect and it pointed following commit: https://github.com/parse-community/parse-dashboard/commit/52c315adc64a5c64d21ba7a6bd8b33d501818ea9
Some of the logic could be indeed asynchronous, which looks kind of strange. Any idea @visualfanatic?

**Comment by damianstasik** [comment]
@404-html this one should fix the issue: https://github.com/parse-community/parse-dashboard/pull/2016

**Comment by AshishBarvaliya** [comment]
@mtrezza  Unable to reproduce the issue with the latest versions, indicating that the fix has already been implemented. Can you please verify this and proceed with closing the issue?

**Comment by mtrezza** [comment]
Thanks for pointing this out, I assume that https://github.com/parse-community/parse-dashboard/pull/2016 has indeed fixed the issue then.
