### ISSUE TITLE
Filters layout broken

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1993]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Looks like buttons in filters section somehow lost a margin.
![image](https://user-images.githubusercontent.com/45104241/149222489-39f55a13-ce41-4f6c-a064-098b0852d99d.png)

### Steps to reproduce
1. Go to data browser;
2. Click on "Filters";

### Actual Outcome
Buttons are very close to each other;

### Expected Outcome
There should be some gap between the buttons.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `4.10.4`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.11`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/parse-dashboard/issues/1959
