### ISSUE TITLE
Switching apps not working

### ISSUE THREAD

**Issue by 404-html** [parse-community/parse-dashboard#1994]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

![switching-apps-broken](https://user-images.githubusercontent.com/45104241/149223098-7a1080ab-4bc4-4178-929e-7e7f7aebe69f.gif)

### Steps to reproduce
1. Go to data browser;
2. Switch to different app;

### Actual Outcome
Data browser performs a refresh but it still shows data from original app.

### Expected Outcome
Chosen app should become selected and browser should show data from it.

### Environment

Dashboard
- Parse Dashboard version: `4.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `97.0.4692.71`

Server
- Parse Server version: `4.10.4`
- Operating system: `Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Google Cloud`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.4.11`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `MongoDB Atlas`

### Logs

Nothing gets logged in browser' dev tools.

**Comment by mtrezza** [comment]
Could this be related to https://github.com/parse-community/parse-dashboard/issues/1991?

**Comment by mtrezza** [comment]
@404-html Could you try to find out the earliest release that introduced the issue, so we can narrow down which commit introduced the issue.

**Comment by 404-html** [comment]
Later I will try to find exact commit with [git bisect](https://git-scm.com/docs/git-bisect) but my gut feeling is that the cause is the same like [here](https://github.com/parse-community/parse-dashboard/issues/1991#issuecomment-1013663870).
