### ISSUE TITLE
File upload in dashboard GUI is not working

### ISSUE THREAD

**Issue by Krolique-frontend** [parse-community/parse-dashboard#2006]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

 Hello everyone. Just tried latest dashboard version 3.3.0 and in Dashboard GUI file uploading don't work. Just nothing happens when trying to add or replace file in a `File` field of object.  No errors in dev tools console and no requests in dev tools network tab. I was using ver 2.1.0 before. It works there. tried 3.2.0 and 3.2.1 - everything works well. So I guess this problem started from 3.3.0 and newer.
Searched for the similar issues hoping find solution but didn't find anything. 
Below you can see screenshot examples of 3 different versions - 3.2.1, 3.3.0 and 4.0.0

#### how it works well on version 3.2.1 and older
![parse_dash_3_2_1](https://user-images.githubusercontent.com/60152072/150525212-98924d9d-f02a-479c-b43d-63633c4f6bc2.gif)

#### and how it not works
![parse_dash_3_3_0](https://user-images.githubusercontent.com/60152072/150525422-a9a80298-c10d-441b-abf2-d7a63ce3cf96.gif)
![parse_dash_4](https://user-images.githubusercontent.com/60152072/150525430-7947083c-5e15-4431-9ee7-3b34d4756373.gif)

### Steps to reproduce
1. Open dashboard
2. Browser tab select some schema with `File` field
3. Double-click on it to open file-upload dialog
4. Enjoy the result

### Actual Outcome
Nothing

### Expected Outcome
Expected to upload files via dashboard GUI

### Environment
Different projects with different parse-server and nodejs versions - all behaves equal
Docker: mongoDB, mongo-express, parse-server, parse-dashboard

Dashboard
- Parse Dashboard version: ^3.3.0 | 4
- Browser (Safari, Chrome, Firefox, Edge, etc.): Firefox | Chrome
- Browser version: FF 96.0 (64-bit) 

Server
- Parse Server version: 4.5.0 | 4.10.4
- Operating system: my: ubuntu 20.4.3 | docker: alpine linux 3.10 | 3.14
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): both local and remote

Database
- System (MongoDB or Postgres): mongoDB
- Database version: 4
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): both local and remote hosts

### Logs
no logs

**Comment by mtrezza** [comment]
Could this be related to https://github.com/parse-community/parse-dashboard/issues/1991?

Could you try to find out the earliest release that introduced the issue, so we can narrow down which commit introduced the issue. Before 3.3.0 release, there have been several alpha and beta releases and you can try.
