### ISSUE TITLE
Keep filter text when changing filter condition

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2029]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Changing the data browser filter field (e.g. `objectId`), or the filter condition (e.g. `equals`) clears the filter text.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/5673677/151663582-e943e034-251e-402e-b4e3-d6db7b7cdc13.png">

### Feature / Enhancement Description
The filter text should should not be cleared, to make it faster to change filter field or condition.

### Example Use Case
- A class may have multiple email field (e.g. `email1`, `email2`), so when searching for an email address only the field needs to be changed, without re-entering the email address.
- A user has entered the filter text and wants to correct the filter condition afterwards (e.g. from `equals` to `startsWith`), so only the condition needs to be changed, without re-entering the filter text.

### Alternatives / Workarounds
Re-enter filter text.

### 3rd Party References
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)
