### ISSUE TITLE
Custom views with predefined filters

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2041]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
There is no way to save a filter setting in dashboard. Every time a class is opened, the filter has to be newly applied.

### Feature / Enhancement Description
Allow to create custom views (new section in dashboard) that consist of a class with a pre-defined filter setting.

The views of a class could be accessible in an expandable sub menu of the class in the data browser:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/5673677/224445277-625074db-027e-48e2-9126-fd960d843fb6.png">

The benefit would be that the number of objects is immediately visible, without even opening the view. And the view can be accessed with 1 click, compared to a menu in the data browser of the class with a dropdown, which would require 3 clicks to navigate to.

### Example Use Case
Given a class `Product` that contains all products, it is possible to can create a view named `Chairs >100$` that shows the `Product` class with pre-defined filters for `product type: chair` and `price: >100`.

### Alternatives / Workarounds
Set filters manually ever ytime a class page is opened in data browser.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.12](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.12)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
