### ISSUE TITLE
Bug: Cannot read properties of null (reading 'forEach')

### ISSUE THREAD

**Issue by JasCodes** [parse-community/parse-dashboard#2049]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Can't add create/add relation from row. Please find attached image.

Dashboard
- Parse Dashboard version: `4.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Brave`
- Browser version: `Release Notes V1.35.104 for Mac (Feb 23, 2022)`

Server
- Parse Server version: `^4.10.4` &`^5.0.0-beta.7`
- Operating system: `MacOS 12.2.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local with remote mongo instance in docker`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest 5.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote in docker`

### Logs

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/1231593/155569184-ba53fb5c-446d-4b30-a3d9-8c38bb0ca109.png">

**Comment by JasCodes** [comment]
Just FYI if refresh the page then everything seems to be fine.

**Comment by mtrezza** [comment]
Could you add step-by-step instructions (1. / 2. / 3.) to reproduce the issue?

**Comment by pcg92** [comment]
Im having the same error, Im unable to add content to relations using the dashboard

    "parse-dashboard": "^4.1.1",
    "parse-server": "^5.2.1"

I have another bug, clicking on see relation I see 0 objetcs, I downgrade to 3.3.0 and the relations are visible, using 4.0.0 my relations are empty too

**Comment by c0sm1cdus7** [comment]
+1 can confirm, the relation is created, but relations are not visible on v4

**Comment by mtrezza** [comment]
Closing as duplicate of #2204
