### ISSUE TITLE
Applying filters with 'Enter' Keys

### ISSUE THREAD

**Issue by cyb3rko** [parse-community/parse-dashboard#2051]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
Applying filters is currently only possible by clicking the "Apply these filters" button with the mouse.

![image](https://user-images.githubusercontent.com/46033730/155752197-d8692a92-7aed-4141-8f36-566ae7168364.png)

### Feature / Enhancement Description
After filling in filter settings it would be cool if you could simply apply the filters either by pressing the normal "Enter" button or the "Enter" button in the numpad.

### Example Use Case
Sometimes I use many filters, it would be a lot easier if you could apply filters with the enter keys.

### Alternatives / Workarounds
Currently you have to apply filters by clicking the "Apply these filters" button with the mouse.

### 3rd Party References
It's the standard for confirming / applying nearly every action you perform in browsers, apps, whatever.

**Comment by davimacedo** [comment]
Hi @cyb3rko thanks for opening the issue. Would be interested in opening a PR with this improvement?

**Comment by cyb3rko** [comment]
Tbh I have never done web development and JavaScript is new to me, but I mean I can try to achieve something.

**Comment by cyb3rko** [comment]
Tbh I have never done web development and JavaScript is new to me, but I mean I can try to achieve something.

**Comment by davimacedo** [comment]
Give it a try and let me know if you need any help.

**Comment by cyb3rko** [comment]
Tbh I have never done web development and JavaScript is new to me, but I mean I can try to achieve something.

**Comment by cyb3rko** [comment]
Sorry, I don't even know how to test it locally if I would find any template for this online.
I have to give the work to somebody else.

**Comment by mtrezza** [comment]
That's alright, your feature suggestion was already helpful and I believe this "tiny feature" improves working with dashboard a lot.

**Comment by cyb3rko** [comment]
Yes, I use Parse Dashboard A LOT for development. Just using the enter key like on every other website / search field / button would be very nice.

**Comment by mtrezza** [comment]
I think it's actually a really simple PR, we already have key bindings like ESC, which you can take a look at to get an idea. Maybe a good topic to start with as your first PR 🙂

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/2256
