### ISSUE TITLE
Display more than 200 rows in parse dashboard

### ISSUE THREAD

**Issue by Sarun1001** [parse-community/parse-dashboard#2075]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

**Comment by Sarun1001** [comment]
**Current Limitation**

Only 200 rows are available by default

**Feature / Enhancement Description**

List all table rows in the dashboard itself without exporting to CSV

**Comment by mtrezza** [comment]
I don't think there is a 200 row limit but it's a phenomenon of this bug: https://github.com/parse-community/parse-dashboard/issues/1551

I'm closing this as a duplicate.
