### ISSUE TITLE
Cannot create audience by targeting pointer on push dashboard

### ISSUE THREAD

**Issue by dcdspace** [parse-community/parse-dashboard#210]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=2.1.4 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Latest version of dashboard from git
#### Steps to reproduce

I noticed that when creating an audience, there is a bug when the installation column type is a Pointer, in which I cannot enter the pointer's objectId. I edited this file `parse-dashboard/src/components/PushAudienceDialog/InstallationCondition.react.js` to present a text box for case Pointer just like String, but it was still not working properly.

For example, say each installation has a pointer to the `_User` class to send notifications to certain users. Normally I would create an audience where the pointer equals the object ID I want to send to, but a text field is not displayed for me to enter the object id. There also seems to be an issue with columns of type Date when creating audiences, as a date picker does not appear and instead the text field shows `[object Object]`. 

Thanks again for adding the push dashboard, it looks great!

**Comment by adirgan** [comment]
+1 Same here

**Comment by Treverr** [comment]
+1 Same here

**Comment by mtrezza** [comment]
Closing as this describes various issues from old versions of Parse Dashboard (~2016). We can reopen if if anyone still faces this issues in the latest version.
