### ISSUE TITLE
Config options like --port, --config are ignored since v4.1.1

### ISSUE THREAD

**Issue by bugra9** [parse-community/parse-dashboard#2112]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Can't start parse-dashboard with options like --port, --config.

- parse-dashboard `v4.1.0` is dependent on commander.js `v6.2.1`
- parse-dashboard `v4.1.1` is dependent on commander.js `v9.0.0`.

> https://github.com/tj/commander.js/releases/tag/v7.0.0
> Breaking: options are stored safely by default, not as properties on the command (https://github.com/tj/commander.js/pull/1409)
>  - this especially affects accessing options on program, use `program.opts()`
>  - revert behaviour with .storeOptionsAsProperties()

### Steps to reproduce

`./node_modules/.bin/parse-dashboard --port 4041`
### Actual Outcome

`The dashboard is now available at http://0.0.0.0:4040/`
### Expected Outcome

`The dashboard is now available at http://0.0.0.0:4041/`
### Environment

Dashboard
- Parse Dashboard version: `4.4.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Firefox`
- Browser version: `99.0.1`

Server
- Parse Server version: `5.2.1`
- Operating system: `Arch Linux`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.8`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

**Comment by piyushbeli** [comment]
It also does not take the config file into the consideration. that said it will always try to run with default settings.

**Comment by mtrezza** [comment]
Thanks for pointing this out, would you want to open a PR and try to fix this?

**Comment by mtrezza** [comment]
Closing via #2113
