### ISSUE TITLE
Command line arguments not working

### ISSUE THREAD

**Issue by vmkudrin** [parse-community/parse-dashboard#2130]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
parse-dashboard command ignores config arguments (--config, --port, --appId, etc.) after updating to 4.1.1. Version 4.0.0 works properly.

### Steps to reproduce
`parse-dashboard --port 3000`

### Actual Outcome

`The dashboard is now available at http://0.0.0.0:4040/`

### Expected Outcome

`The dashboard is now available at http://0.0.0.0:3000/`

### Environment

node 14.18.1
npm 6.14.15

Dashboard
- Parse Dashboard version: `4.1.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `15.2`

Server
- Parse Server version: `5.2.1`
- Operating system: `macOS 12.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.1`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

**Comment by mtrezza** [comment]
Duplicate of https://github.com/parse-community/parse-dashboard/issues/2112
