### ISSUE TITLE
cli parameters not recognised

### ISSUE THREAD

**Issue by anatolykopyl** [parse-community/parse-dashboard#2132]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Parameters supplied when running `parse-dashboard` are not used.

### Steps to reproduce

- Run `parse-dashboard --port 1337`

### Actual Outcome

```
The dashboard is now available at http://0.0.0.0:4040/
```

### Expected Outcome

```
The dashboard is now available at http://0.0.0.0:1337/
```

### Environment

Dashboard
- Parse Dashboard version: `4.1.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `all`
- Browser version: `all`

Server
- Parse Server version: `4.10.3`
- Operating system: `OSX Monterey (M1)`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.7`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

**Comment by mtrezza** [comment]
Duplicate of https://github.com/parse-community/parse-dashboard/issues/2112
