### ISSUE TITLE
4.1.1 claims I'm not using HTTPS while --trustProxy=1; 4.1.0 does not

### ISSUE THREAD

**Issue by mathieulb** [parse-community/parse-dashboard#2151]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Using Heroku, I need to run the app with `--trustProxy=1`, but it doesn't seem to work using Dashboard 4.1.1; the same cmdline option works with 4.0.0 and 4.1.0. 

While you're at it, you could add another option (e.g. `--trustProxy=2`) that would check the condition `req.header('x-forwarded-proto') !== 'https'` for determining whether to reject.

### Steps to reproduce
package.json :
{
  "name": "my-parse-dashboard",
  "version": "0.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "node ./index.js --config ./parse-dashboard-config.json --trustProxy=1",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "",
  "dependencies": {
    "parse-dashboard": "4.1.1"
  }
}

index.js :
require('parse-dashboard/Parse-Dashboard/index.js')

### Actual Outcome
"Parse Dashboard can only be remotely accessed via HTTPS" while accessing the server with a https url

### Expected Outcome
seeing the login screen then being able to login and use the app

### Environment

Dashboard
- Parse Dashboard version: 4.1.1
- Browser (Safari, Chrome, Firefox, Edge, etc.): Firefox
- Browser version: 100.0.1

Server
- Parse Server version: 5.2.0
- Operating system: Heroku-18 & Heroku-20
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): Mongo
- Database version: Unknown
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): ObjectRocket @ Heroku

**Comment by mtrezza** [comment]
Are you able to pin down the PR / commit that causes this issue in 4.1.1?

> While you're at it, you could add another option (e.g. --trustProxy=2) that would check the condition req.header('x-forwarded-proto') !== 'https' for determining whether to reject.

We'll only look at the bug report in this thread. If you want to make a feature suggestion, please open a new issue.

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/parse-dashboard/issues/2112
