### ISSUE TITLE
"Contains" field disappeared

### ISSUE THREAD

**Issue by mathieulb** [parse-community/parse-dashboard#2152]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
4.0.0 had a "string contains string" choice in Filter, which made a text field appear to the right of it. In 4.1.0, this is called just "contains" and it makes nothing appear.

### Steps to reproduce
Install 4.1.0 ; Click Filter ; click 2nd dropdown ; click "contains"

### Actual Outcome
no search field, but a blank space in its place (unlike "exists", "does not exist", "unique", which expand the 2nd drop down to the right edge). JS console contains no warnings. Inspecting this panel shows it has only 3 items : two dropdowns and the minus button, no search field.

### Expected Outcome
the same search field that exists in 4.0.0

### Environment

Dashboard
- Parse Dashboard version: 4.1.0
- Browser (Safari, Chrome, Firefox, Edge, etc.): Firefox 100.0.1 & Chrome 92.0

Server
- Parse Server version: 5.2.0
- Operating system: Heroku-20
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): Heroku

Database
- System (MongoDB or Postgres): MongoDB
- Database version: Unknown
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): ObjectRocket on Heroku

**Comment by mtrezza** [comment]
Should be fixed in [4.1.2-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/4.1.2-beta.1), can you confirm?

Duplicate of https://github.com/parse-community/parse-dashboard/issues/2131

**Comment by pcg92** [comment]
Why has it disappeared in version 8.1.0? Regex is a pain — this was really useful.

**Comment by mtrezza** [comment]
The constraint "contains" was a subset of "matches regex" it has been replaced with. It didn't make sense to keep both. While "contains" had some undocumented, arbitrary regex limitations built into it, "matches regex" is free of those limitations and more versatile, but it requires you to understand how regex syntax works. This is usually necessary anyway to predict the impact of a query in terms of query plan execution, especially coll / index scan.
