### ISSUE TITLE
Flags are not recognized when parse-dashboard starts - version 4.1.1

### ISSUE THREAD

**Issue by charles-ramos** [parse-community/parse-dashboard#2159]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x]  I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
When trying to run the parse-dashboard by passing the flags, such as appId, masterKey and others, they are not recognized by the command.

### Steps to reproduce
To reproduce this issue, install parse-dashboard and run:
```parse-dashboard --dev --appId yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName```

### Actual Outcome
The URL, after running the command is `http://0.0.0.0:4040/apps/hello`.

### Expected Outcome
It should be `http://0.0.0.0:4040/apps/optionalName`.

After some investigation, I noticed that it's getting the data from the [parse-dashboard-config.json](https://github.com/parse-community/parse-dashboard/blob/4ffd6fc6e3fd74f0288a08547fe5456b8d64f6b1/Parse-Dashboard/parse-dashboard-config.json) file, and when I put my credentials in this file, it worked by just running the `parse-dashboard` without any flags. 

### Environment

Dashboard
- Parse Dashboard version: `4.1.1`

**Comment by mtrezza** [comment]
Closing as duplicate of https://github.com/parse-community/parse-dashboard/issues/2112
