### ISSUE TITLE
Fix the label "Show All" in menu Manage Columns to show it in one line

### ISSUE THREAD

**Issue by MrMartinR** [parse-community/parse-dashboard#2187]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The label "Show All" in menu Manage Columns overflows the button container

### Steps to reproduce
Open Manage Columns Menu

### Actual Outcome
The "Show All" label overflows the button container

### Expected Outcome
Show the label in one line of text
### Environment
Any

Dashboard
- Parse Dashboard version: `4.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `all`
- Browser version: `any`

Server
- Parse Server version: `5`
- Operating system: `any`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `any`

Database
- System (MongoDB or Postgres): `Postgres`
- Database version: `14`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

**Comment by mtrezza** [comment]
Closing via #2208
