### ISSUE TITLE
Related records in context menu ambiguous

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2191]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Right clicking on a pointer in the data browser shows the menu "Get related records" where it lists all classes with a pointer of the same class. If a class has multiple pointers of the same class, the class shows up multiple times in the list, without indication which fields is referenced with each entry.

### Steps to reproduce
1. Create class `Test` with 2 pointer fields for class `_User`: `userA`, `userB`.
2. Open class `_User`.
3. Right click on `objectId` > `Get related records`.

### Actual Outcome
There are two entries in list for `Test` class without indication which entry corresponds to `userA` and which to `userB`.

### Expected Outcome
There are two entries in list for `Test` class with the field name next to it, for example:
- `Test - userA`
- `Test - userB`

### Environment

Dashboard
- Parse Dashboard version: `4.1.2`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)
