### ISSUE TITLE
Trivial UI layout issues

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2199]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
There are many trivial layout issues in the UI.

### Steps to reproduce
Examples:

Incorrect button position:
![image](https://user-images.githubusercontent.com/5673677/177048598-a39c1fa3-2876-4fea-a354-58a75f658efd.png)
![image](https://user-images.githubusercontent.com/5673677/177048664-2771f5c1-d4cf-458b-82f1-eee6db9a30b7.png)

Parse Dashboard version and user text block not vertically centered with logo:
![image](https://user-images.githubusercontent.com/5673677/177048603-f2e48e92-29a6-4021-a70d-e47fef7c7ca4.png)

Incorrect button spacing:
![image](https://user-images.githubusercontent.com/5673677/177048614-21d7afac-9833-4dcf-8842-8c4700baaf6e.png)

"Show all" cut off:
![image](https://user-images.githubusercontent.com/5673677/177048646-89804734-07dd-4dc0-9692-10e59777ad51.png)

"Add column & continue" should be in the middle, "Add column" should be on the very right:
![image](https://user-images.githubusercontent.com/5673677/177048703-a0220dce-eb1a-413c-a756-509d12f8b945.png)

There may be a few more, so when fixing these it would be good to browser through the dashboard a bit more.

### Actual Outcome
n/a

### Expected Outcome
n/a

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `Version 15.5 (17613.2.7.1.8)`

**Comment by mtrezza** [comment]
@MrMartinR This may be an interesting one for you, since you are already on a clean-up spree

**Comment by MrMartinR** [comment]
Hi! I'll check at night or tomorrow

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0)
