### ISSUE TITLE
Add Node 18 support

### ISSUE THREAD

**Issue by MrMartinR** [parse-community/parse-dashboard#2205]
### New Feature / Enhancement Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation
n/a

### Feature / Enhancement Description
Include the current (soon active) version of NodeJS version 18

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

### 3rd Party References
n/a

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-dashboard/pull/2206
