### ISSUE TITLE
Change row batch deletion confirmation entry

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2239]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

This is a UX issue. The confirmation dialog to delete selected rows, to delete all rows and to delete the whole class require to enter the class name. All 3 dialogs look similar. The issue is that the dialogs may be mistaken for each other. Also the buttons in the menu to perform these actions are next to each other.

<img width="212" alt="Screen Shot 2022-08-16 at 11 38 04" src="https://user-images.githubusercontent.com/5673677/184848418-b155af28-8db6-4778-8eed-0ee034e7a6d5.png">

<img width="538" alt="Screen Shot 2022-08-16 at 11 30 37" src="https://user-images.githubusercontent.com/5673677/184846963-f94a5f50-7e3f-48bb-b631-9c5fbccf550a.png">

<img width="538" alt="Screen Shot 2022-08-16 at 11 24 38" src="https://user-images.githubusercontent.com/5673677/184846319-8da224ce-70d7-4b9c-9129-9418a98e6d5b.png">

<img width="539" alt="Screen Shot 2022-08-16 at 11 24 28" src="https://user-images.githubusercontent.com/5673677/184846332-6625ddb5-fa22-40f0-a6b2-f62ca79fe8a6.png">

### Steps to reproduce
1. Delete selected rows 
2. Delete all rows
3. Delete class

### Actual Outcome
Described above

### Expected Outcome

Make the dialogs more distinguishable, for example:

- The dialog to delete N rows should not request to enter the class name but the word "delete selected"
- The dialog to delete all rows should not request to enter the class name but the word "delete all".
- The dialog to delete the whole class should stay as is and request to enter the class name.

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`

### Logs
n/a

**Comment by sadakchap** [comment]
@mtrezza Can I please take a stab at this issue?

**Comment by mtrezza** [comment]
Please feel free, it doesn't seem that anyone is working on this as there's no comment

cc @Magdaraa

**Comment by sadakchap** [comment]
Thank you @mtrezza . Here's the pr https://github.com/parse-community/parse-dashboard/pull/2319. Please let me know about your thoughts.

**Comment by mtrezza** [comment]
Closing via #2319
