### ISSUE TITLE
Dashboard filters does not work anymore on parse-server v5.2.4

### ISSUE THREAD

**Issue by Simone-cogno** [parse-community/parse-dashboard#2240]
### New Issue Checklist

- [ x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The filter does not work in the browser view, always empty list of records.

### Steps to reproduce
Install parse-server version 5.2.4 and parse-dashboard 4.1.4. Try to filter objects.

### Actual Outcome
No records are shown, regardless of the filter that I choose.

### Expected Outcome
Filtered list of records

### Environment
NODE_ENV: stage
--allowInsecureHTTP 

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 104.0.5112.101 (Official Build) (x86_64)`

Server
- Parse Server version: `5.2.4`
- Operating system: `Ubuntu 16.04.2 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `4.2.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs
34|Parse server  | 2022-08-17 09:35 +00:00: 2022-08-17T09:35:10.522Z - error: Uncaught internal server error. this._mongoCollection.countDocuments is not a function level=error, message=Uncaught internal server error. this._mongoCollection.countDocuments is not a function, stack=TypeError: this._mongoCollection.countDocuments is not a function
34|Parse server  |     at MongoCollection.count (/home/ubuntu/co-parse-server/node_modules/parse-server/src/Adapters/Storage/Mongo/MongoCollection.js:114:50)
34|Parse server  |     at /home/ubuntu/co-parse-server/node_modules/parse-server/src/Adapters/Storage/Mongo/MongoStorageAdapter.js:745:20
34|Parse server  | From previous event:
34|Parse server  |     at MongoStorageAdapter.count (/home/ubuntu/co-parse-server/node_modules/parse-server/src/Adapters/Storage/Mongo/MongoStorageAdapter.js:744:8)
34|Parse server  |     at /home/ubuntu/co-parse-server/node_modules/parse-server/src/Controllers/DatabaseController.js:1261:39
34|Parse server  | From previous event:
34|Parse server  |     at /home/ubuntu/co-parse-server/node_modules/parse-server/src/Controllers/DatabaseController.js:1220:14
34|Parse server  | From previous event:
34|Parse server  |     at /home/ubuntu/co-parse-server/node_modules/parse-server/src/Controllers/DatabaseController.js:1180:10
34|Parse server  | From previous event:
34|Parse server  |     at DatabaseController.find (/home/ubuntu/co-parse-server/node_modules/parse-server/src/Controllers/DatabaseController.js:1165:59)
34|Parse server  |     at RestQuery.runCount (/home/ubuntu/co-parse-server/node_modules/parse-server/src/RestQuery.js:686:31)
34|Parse server  |     at /home/ubuntu/co-parse-server/node_modules/parse-server/src/RestQuery.js:215:19
34|Parse server  | From previous event:

**Comment by Simone-cogno** [comment]
By look at the http calls done by the parse-dashboard in the background I see that this request is throwing an error:
```
curl 'https://xxx.yyy.com/api/classes/XXX'
-H 'accept: /'
-H 'cache-control: no-cache'
-H 'content-type: text/plain'
-H 'pragma: no-cache'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'sec-gpc: 1'
--data-raw $'{"where":{"xxx":false},"limit":0,"count":1,"_method":"GET","_ApplicationId":"xxxx","_ClientVersion":"js3.4.2","_MasterKey":"xxxx","_InstallationId":"xxxx"}'
--compressed
```

While this one does not throw an error:
```
curl 'https://xxx.yyy.com/api/classes/XXX'
-H 'accept: /'
-H 'cache-control: no-cache'
-H 'content-type: text/plain'
-H 'pragma: no-cache'
-H 'sec-fetch-dest: empty'
-H 'sec-fetch-mode: cors'
-H 'sec-fetch-site: cross-site'
-H 'sec-gpc: 1'
--data-raw $'{"where":{"xxx":false},"limit":0,"_method":"GET","_ApplicationId":"xxxx","_ClientVersion":"js3.4.2","_MasterKey":"xxxx","_InstallationId":"xxxx"}'
--compressed
```

Removing the `count: 1` seem to solve the issue.

Will it be possible fix this issue easily? It will be enough to remove the count operations on queries.

**Comment by mtrezza** [comment]
Closing as this needs to be fixed server side, see https://github.com/parse-community/parse-server/issues/8127.
