### ISSUE TITLE
Object count always zero 

### ISSUE THREAD

**Issue by nangyal** [parse-community/parse-dashboard#2247]
### Issue Description

Object count always zero when I use Postgres db

### Environment

Dashboard
- Parse Dashboard version: 4.2.0-ALPHA.4
- Browser : Chrome

Server
- Parse Server version: 5.2.4
- Operating system: Docker / Debian

Database

- System:  Postgres

![Screenshot 2022-08-30 232216](https://user-images.githubusercontent.com/15214137/187546326-3e1daf30-4a0a-47e1-b1e8-ec94ff7b502c.png)

**Comment by dplewis** [comment]
There is a known issue with Postgres called slow counting. Counting can be an expensive operation so we provide an estimate count to allow for scalability.

See the conversation [here](https://github.com/parse-community/parse-server/pull/5330).

**Comment by mtrezza** [comment]
Closing this as known limitation.
