### ISSUE TITLE
Context menu not scrollable

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2265]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

If a context menu is higher the the window height, it's not scrollable.

For example, if the list of related records is higher than the window height:

![](https://user-images.githubusercontent.com/4974769/190117241-c6a22cc9-ca85-43c0-91af-64482a18a420.png)

### Steps to reproduce
1. Open a long list of related records and resize browser window height to be smaller than the list height.

### Actual Outcome

List should be scrollable in some way (auto-scroll when on first / last visible entry, or via mouse -> mind how to use that on touch UIs)

### Expected Outcome

List is cut off.

### Environment

Dashboard
- Parse Dashboard version: `[4.2.0-alpha.11](https://github.com/ParsePlatform/parse-dashboard/compare/4.2.0-alpha.10...4.2.0-alpha.11)`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari, Chrome`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.15](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.15)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)
