### ISSUE TITLE
File upload dialog keeps popping up

### ISSUE THREAD

**Issue by Sarun1001** [parse-community/parse-dashboard#2268]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

FileUpload Window popup keeps displaying when selecting a file to upload.
It's popping up after we select a file and select open, and the file that was previously selected is not uploaded or not in selection
it's happening in a single class file where I added 3 file columns one after the other, Classes with only 1 file column are working fine 
Video of the bug
https://www.veed.io/view/35015126-5358-4be9-9437-c63f5e151a94

### Steps to reproduce

Create a class add multiple columns of file types together & try to upload to it

### Actual Outcome

FileUpload popup keeps creating after 
### Expected Outcome

Close file selection popup & starts uploading

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `105.0.5195.125 (Official Build) (x86_64)`

Server
- Parse Server version: `5.2.5`
- Operating system: `Ubuntu 22.04.1 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote-AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.12`
- Node version `v18.1.0`
- FileAdapter - s3 (aws)
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs

No logs or error messages on the browser

**Comment by Sarun1001** [comment]
PS : This bug is only visible when we add multiple columns with file data type

**Comment by Sarun1001** [comment]
Does it have anything to do with the latest node version ? I'm on Node version v18.1.0 
Parse Server version: 5.2.5
Parse Dashboard version: 4.1.4
Is this v4.1.4 fully support node 18 ?

**Comment by mtrezza** [comment]
Thanks for reporting; I don't think such a bug would be related to Node, but who knows.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-alpha.16](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-alpha.16)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [4.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/4.2.0)
