### ISSUE TITLE
Relations are not displaying - Need to reload page to populate

### ISSUE THREAD

**Issue by Sarun1001** [parse-community/parse-dashboard#2269]
### New Issue Checklist

- [x ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x ] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x ] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Relations are not displaying while we click on them, it redirects to relations view but values are not populating, If we clicks reload values are generating.

Video -- https://www.veed.io/view/c3f595cc-a17e-49ac-9ec7-562e1b92eb81

### Steps to reproduce

Add relation in a class --> Add values -->Click view relation

### Actual Outcome

Empty views in relation view

### Expected Outcome

Display associated relation values

### Environment

Dashboard
- Parse Dashboard version: `4.1.4`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `105.0.5195.125 (Official Build) (x86_64)`

Server
- Parse Server version: `5.2.5`
- Operating system: `Ubuntu 22.04.1 LTS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `remote-AWS`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.12`
- Node version `v18.1.0`
- FileAdpater - s3 (AWS)
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `AWS`

### Logs

No logs or error messages on the browser

**Comment by cbaker6** [comment]
Duplicate #2171
