### ISSUE TITLE
Using browser navigation clears data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2310]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Navigating using the web browser's "back" and "forward" buttons doesn't shows empty table in the data browser. The data browser briefly shows a loading screen, then the rows in the data browser, then clears the data browser.

It also seems that the dashboard is at times completely reloading itself. This causes the whole dashboard to be reloaded from the server, which seems unnecessary.

It seems, this bug has been introduced with https://github.com/parse-community/parse-dashboard/pull/2273.

### Steps to reproduce

Navigate by clicking on a pointer in a row in the data browser, then again on a pointer, thus drilling down in the data hierarchy. Then navigate back and forth using the web browser buttons.

### Actual Outcome

The data browser is empty.

### Expected Outcome

The data browser should show the correct data.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0-alpha.3`

**Comment by mtrezza** [comment]
@magdaraa In case you are interested in taking a look at this.

**Comment by Magdaraa** [comment]
Hey, thank you for your suggestion. I have just started:  https://github.com/parse-community/parse-dashboard/issues/2239
I'm happy to look into that next.

**Comment by mtrezza** [comment]
We'll revert https://github.com/parse-community/parse-dashboard/pull/2273 if this issue isn't fixed soon.

**Comment by mtrezza** [comment]
@Magdaraa it seems that the issue is not caused by #2273 but by https://github.com/parse-community/parse-dashboard/pull/2275, but we don't know yet.

**Comment by mtrezza** [comment]
This bug currently blocks the beta release

**Comment by mtrezza** [comment]
Closing via #2317
