### ISSUE TITLE
No Data message hidden in wide data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2325]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When applying a filter in the data browser that returns no records, the "No Data" message is in the center of the scrollable table. If the table is very wide (i.e. lots of columns), that message is not visible and it's unclear to the user what the state of the search is:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/5673677/195982117-1b3a36f1-4851-46ca-ab80-8203479bcf71.png">

### Feature / Enhancement Description

If there are no records, the "No Data" message should always stay centered in the viewport, i.e. it should not be part of the data table but like an overlay over the data table. That way it is always visible, regardless of the current scroll position of the data table.

### Example Use Case
n/a

### Alternatives / Workarounds
n/a

**Comment by 404-html** [comment]
Looks like this is no longer the case and it can be closed.

![parse-no-data-overlay](https://user-images.githubusercontent.com/45104241/209582994-9510f3f6-0643-4d16-a8a2-745565a85049.gif)

**Comment by mtrezza** [comment]
Oh, in what PR has this been fixed? I just had a look at `5.1.0-alpha.1` on Safari, and the issue still exists; I see the same version in your screen recording.

**Comment by 404-html** [comment]
I can confirm the problem exists on Safari 16.0 (17614.1.25.9.10, 17614)
The video from my previous comment was on Chrome 108.0.5359.124.

**Comment by mtrezza** [comment]
Even better, then it may just be a change in the CSS that is needed

**Comment by damianstasik** [comment]
@mtrezza it indeed was a simple CSS change, please take a look at #2387

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.10](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
