### ISSUE TITLE
Copy shortcut disabled in data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2331]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

It's not possible anymore to copy the value of a field without editing its value.

### Steps to reproduce

1. Open data browser
2. Select an `objectId` field of a row (single click, not double click)
3. Press key shortcut to copy the value (Ctrl+C)

### Actual Outcome

Value not copied to clipboard.

### Expected Outcome

Value copied to clipboard.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0-beta-1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`

**Comment by dblythy** [comment]
I'm not observing this issue @mtrezza, any ideas?

**Comment by mtrezza** [comment]
Let me check again, maybe it has been fixed already...

**Comment by mtrezza** [comment]
Closing, can't reproduce this anymore
