### ISSUE TITLE
Remove limitation to refresh Cloud Jobs list only after 30 seconds

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2333]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

There is currently a limitation in which the "Refresh" button in the Cloud Jobs table is disabled if less than 30 seconds passed since the last refresh.

A user may expect the status to update in real time, as is common in modern dashboards. The limitation of allowing to manually refresh only every 30 seconds can be even more frustrating from a UX perspective.

### Feature / Enhancement Description

Remove that limitation.

### Example Use Case
n/a

### Alternatives / Workarounds

Refresh whole page.

### 3rd Party References
n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.0.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.0.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
