### ISSUE TITLE
Add remote config history

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2339]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When changing any value in Remote Config, the previous value is lost without any possibility to undo the change. That means that any user mistake can lead to information irreversibly lost.

### Feature / Enhancement Description

Add a history of the remove config changes. The feature in its most basic form should allow to see a history of previous values. In a more advanced form it could allow to roll back to previous values.

The remote config history could be stored locally on the browser side as a basic functionality. As an improvement, the config history should be stored server side, see https://github.com/parse-community/parse-dashboard/issues/2555.

### Example Use Case
n/a

### Alternatives / Workarounds
Implement a custom solution in Cloud Code trigger (this requires feature https://github.com/parse-community/parse-server/issues/8267 to be implemented)

**Comment by patelmilanun** [comment]
u mean this one right? https://github.com/parse-community/parse-dashboard/blob/alpha/src/dashboard/Data/Config/Config.react.js. The "Dynamically configure your app" section of parse dashboard right? @mtrezza

**Comment by mtrezza** [comment]
Yes

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.7](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.7)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
