### ISSUE TITLE
Delete class and delete all rows not working

### ISSUE THREAD

**Issue by ghost** [parse-community/parse-dashboard#2342]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Can't delete empty classes and can't delete all rows

### Steps to reproduce

Click on 'Edit' -> 'Delete all rows' -> Enter class name

### Actual Outcome

Button 'Delete' is disables even if the class name was entered correctly

### Expected Outcome

Button 'Delete' is active and clickable 

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `16.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `107.0.5304.87`
- OS: `macOS 13.0`

Server
- Parse Server version: `5.2.5`, `5.2.7`, `5.3.1`
- Operating system: `docker-image node:18-alpine`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `k8s`

Database
- System (MongoDB or Postgres): `mongoDB`
- Database version: `5.0.11`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `k8s`

**Comment by 404-html** [comment]
@Mammut-Felix with https://github.com/parse-community/parse-dashboard/pull/2319 we've changed how delete all rows gets confirmed. Instead of class name you now need to enter "delete all"

![image](https://user-images.githubusercontent.com/45104241/209583351-a46e8450-55b7-4b71-aa3c-29cd13296248.png)

Please let us know if this wasn't the case - we will re-open the issue then.

**Comment by ghost** [comment]
@404-html You are absolutely right. Sorry I missed the change.
