### ISSUE TITLE
Server not reachable: unauthorized: master key is required

### ISSUE THREAD

**Issue by zhangwb1996** [parse-community/parse-dashboard#2349]
Hello!
i install parse-dashboard and parse-server on ubuntu server according to [Deploying on AWS EC2 Ubuntu using PostgreSQL](https://docs.parseplatform.org/parse-server/guide/#deploying-on-aws-ec2-ubuntu-using-postgresql).then, parse-dashboard works well.
Then i install parse-server from source code and run `npm start -- --appId UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV --masterKey BOyE27IdB8GKT0Jw5nTUmqoSWDfBAdc6PCOwCwqM --databaseURI postgres://postgres:123456@192.168.101.104:5432/postgres --serverURL http://192.168.101.5:1337/parse` on windows, parse-server startup without any error. 
But when i restart parse-dashboard and login,the parse-server from source show one Error:
```
Error: unauthorized: master key is required
    at promiseEnforceMasterKeyAccess (C:\...\parse-server\lib\middlewares.js:450:19)
    at C:\...\parse-server\lib\PromiseRouter.js:85:20
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
and the page of parse-dashboard show: Server not reachable: unauthorized: master key is required
![image](https://user-images.githubusercontent.com/41967295/206537916-6620ca5c-df3a-4a91-9fc6-e48cfc1da13d.png)

there are json files:
parse-dashboard-config.json on ubuntu server
```
{
  "apps": [
    {
      "serverURL": "http://192.168.101.104:1337/parse",
      "graphQLServerURL": "http://192.168.101.104:1337/graphql",
      "appId": "01",
      "masterKey": "12345678",
      "appName": "parse-server-app",
      "allowInsecureHTTP": "true",
      "iconName": "",
      "primaryBackgroundColor": "",
      "secondaryBackgroundColor": ""
    },
    {
      "serverURL": "http://192.168.101.5:1337/parse",
      "graphQLServerURL": "http://192.168.101.5:1337/graphql",
      "appId": "UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV",
      "masterKey": "BOyE27IdB8GKT0Jw5nTUmqoSWDfBAdc6PCOwCwqM",
      "appName": "parse-server-from-source",
      "allowInsecureHTTP": "true",
      "iconName": "",
      "primaryBackgroundColor": "",
      "secondaryBackgroundColor": ""
    }
  ],
 "users": [{
                "user": "admin",
                "pass": "123456",
                "apps": [{"appId": "01"},{"appId": "UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV"}]
        }],
  "iconsFolder": "public",
  "trustProxy": 1
}

```
config.json on ubuntu server
```
{
  "serverURL": "http://192.168.101.104:1337/parse",
  "appId": "01",
  "masterKey": "12345678",
  "appName": "parse-server-app",
  "cloud": "./cloud/main",
  "databaseURI": "postgres://postgres:123456@localhost:5432/postgres"
}
```

config.json from source on windows,(maybe it doesnt work)
```
{
  "serverURL": "http://192.168.101.5:1337/parse",
  "appId": "UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV",
  "masterKey": "BOyE27IdB8GKT0Jw5nTUmqoSWDfBAdc6PCOwCwqM",
  "appName": "parse-server-from-source",
  "cloud": "./cloud/main",
  "databaseURI": "postgres://postgres:123456@192.168.101.104:5432/postgres"
}
```

**Comment by dblythy** [comment]
You might need to set masterKeyIps depending on your Parse Server version

https://github.com/parse-community/parse-server/issues/8316

**Comment by zhangwb1996** [comment]
@dblythy Thanks for your answer.

Maybe，i have solved this error by run `npm start` in the dir generated after run bootstrap.sh. 
```
PS C:\...\parse-server\parse-server-from-source> npm start

> start
> parse-server config.json
> .....
```

This error occurred, when i run npm in  parse-server
```
PS C:\...\parse-server> npm start -- --appId UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV --masterKey BOyE27IdB8GKT0Jw5nTUmqoSWDfBAdc6PCOwCwqM --databaseURI postgres://postgres:123456@192.168.101.104:5432/postgres --serverURL http://192.168.101.5:1337/parse 

> parse-server@6.0.0-alpha.13 start
> node ./bin/parse-server --appId UE7SmtidKby874Q8l2Vaq0FWFu5k6lcUiPisAEnV --masterKey BOyE27IdB8GKT0Jw5nTUmqoSWDfBAdc6PCOwCwqM --databaseURI postgres://postgres:123456@192.168.101.104:5432/postgres --serverURL http://192.168.101.5:1337/parse 
> ....
```

**Comment by zhangwb1996** [comment]
> You might need to set masterKeyIps depending on your Parse Server version
> 
> [parse-community/parse-server#8316](https://github.com/parse-community/parse-server/issues/8316)

Thanks, i solved it by adding the startup param: `--masterKeyIps 192.168.101.5`
![image](https://user-images.githubusercontent.com/41967295/206645213-fd1cd466-c9b4-4edf-8dc0-7341aff0d58e.png)

**Comment by mtrezza** [comment]
Can we improve anything in the error message here to make this clearer for the developer? I think this is the 3rd issue I came across recently where `masterKeyIps` was not set properly.

**Comment by dblythy** [comment]
Could we add a log to the server side such as `attempted to connect with a valid masterKey but from an invalid IP: ip. Add ip to config option masterKeyIps to allow this request`

**Comment by mtrezza** [comment]
Yes, I think it's good to keep it deliberately ambiguous and only log server side.

> Request using master key rejected as the request IP address '1.2.3.4' is not set in Parse Server option 'masterKeyIps'.

**Comment by mtrezza** [comment]
@zhangwb1996 just a note that your post above includes sensitive information such as master key; if you decide to publish your app it would be good to change these keys.

**Comment by zhangwb1996** [comment]
> @zhangwb1996 just a note that your post above includes sensitive information such as master key; if you decide to publish your app it would be good to change these keys.

its ok, this is a demo for starting parse-server

**Comment by zhangwb1996** [comment]
this error occured again today, 

solved by adding a matched startup param:  `--clientKey XXXXXXXX`

**Comment by mtrezza** [comment]
This will be fixed by https://github.com/parse-community/parse-server/issues/8351

**Comment by mtrezza** [comment]
Closing via https://github.com/parse-community/parse-server/issues/8351
