### ISSUE TITLE
Docker image doesn't conform to best practices

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-dashboard#2351]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The Dockerfile currently doesn't conform to the [docker best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) or [alpine recommendations](https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md). This results in a larger than necessary compressed/decompressed image.

### Feature / Enhancement Description

Conform to best practices.

### Example Use Case

Create an image from this image.

### Alternatives / Workarounds

Use bloated image as is.

### 3rd Party References

Noted in limitation links.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
