### ISSUE TITLE
Logging in without a password throws syntax error

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-dashboard#2367]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
![Screenshot 2023-01-25 at 1 57 30 pm](https://user-images.githubusercontent.com/4974769/214470525-5e55aa84-6510-4610-b40c-19b3b26ea22a.png)

### Environment

Dashboard
- Parse Dashboard version: `FILL_THIS_OUT`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `FILL_THIS_OUT`
- Browser version: `FILL_THIS_OUT`

Server
- Parse Server version: `FILL_THIS_OUT`
- Operating system: `FILL_THIS_OUT`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `FILL_THIS_OUT`

Database
- System (MongoDB or Postgres): `FILL_THIS_OUT`
- Database version: `FILL_THIS_OUT`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `FILL_THIS_OUT`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
