### ISSUE TITLE
Redirect to initial URL when authentication is needed

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-dashboard#2368]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When accessing a saved dashboard url, such as: 

http://localhost:4040/apps/appId/browser/_User?filters=%5B%7B%22field%22%3A%22emailVerified%22%2C%22constraint%22%3A%22exists%22%7D%5D

If authentication is needed, the original url is lost.

### Feature / Enhancement Description

Add 'redirectURL' feature that routes to original requested URL on login.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
