### ISSUE TITLE
Skip unnecessary builds in CI

### ISSUE THREAD

**Issue by damianstasik** [parse-community/parse-dashboard#2390]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
The main CI workflow can be optimized by skipping unnecessary builds.

### Actual Outcome
Most of the jobs take at least 2 minutes.

### Expected Outcome
The same jobs should take around 1 minute (which can be cut even more later).

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.1.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.1.0)
