### ISSUE TITLE
Allow settings page to build Parse Dashboard configuration

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-dashboard#2405]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Certain features, such as the Dashboard option `ColumnPreferences` are directly build in Parse Dashboard, however there is no way to export them.

### Feature / Enhancement Description

Add a dashboard settings page that helps building static Dashboard configuration

**Comment by mtrezza** [comment]
Good idea!

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
