### ISSUE TITLE
Application crash when email field is > 25 characters

### ISSUE THREAD

**Issue by israeloriente** [parse-community/parse-dashboard#2410]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
Application causes a problem when we try to enter more than 25 characters in the email field.

### Steps to reproduce
**⚠️ To reproduce the error you need to open a modal to create a new user by clicking here (objectId) ⚠️**
<img width="201" alt="image" src="https://user-images.githubusercontent.com/31784632/228904123-3b2ff50c-c4a0-4f13-9ab7-06f98da7ea39.png">

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/31784632/228902426-3c6ac3fd-0ac2-4d87-9a02-4794a39b7c55.gif)

### Actual Outcome
**Uncaught TypeError: Cannot read properties of null (reading 'current')**
<img width="504" alt="image" src="https://user-images.githubusercontent.com/31784632/228902661-3305e444-8e57-4e09-81c6-b89cb634eb8a.png">

### Expected Outcome
Do not cause any error

### Environment
![image](https://user-images.githubusercontent.com/31784632/228902906-48cdeeb8-41c9-4138-8193-c5d1b29deacb.png)

Dashboard
- Parse Dashboard version: `^5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.110 (Official Build) (arm64)`

Server
- Parse Server version: `^5.4.3`
- Operating system: `macOS Ventura 13.3 (22E252)`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `v6.0.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

**Comment by AshishBarvaliya** [comment]
@israeloriente Could you kindly attempt to replicate the issue at your end? as I am currently testing in these particular versions(parse-server: 6.1.0-alpha.7 & parse-dashboard: 5.1.0-alpha.13) and working fine now. If it is working properly now, we can proceed with closing this issue.

**Comment by israeloriente** [comment]
https://github.com/israeloriente/parse-server-issue-2410

https://user-images.githubusercontent.com/31784632/230764752-8cf373e3-1cb6-4a99-b927-dd7bb908fb21.mov

**Comment by AshishBarvaliya** [comment]
@mtrezza After testing it with the latest stable version of `parse-dashboard (5.1.0)`, it appears to be functioning correctly. 
@israeloriente Can you please verify this for confirmation?

**Comment by israeloriente** [comment]
Yes, it has been corrected using:
![image](https://github.com/parse-community/parse-dashboard/assets/31784632/c8f27ead-02c4-40c1-8028-c3fdca29d8a7)
