### ISSUE TITLE
Dashboard crash when attempting to create a field with type "Object"

### ISSUE THREAD

**Issue by keanallen** [parse-community/parse-dashboard#2411]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Dashboard crashes when I tried to create a field "Object" data type.

### Steps to reproduce

Try to create a new field with data type of "Object"

### Actual Outcome

Dashboard turns into  blank screen

### Expected Outcome

I should be able to create a new field

### Environment

Windows 11 x64

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser: `Chrome`
- Browser version: `111.0.5563.147`

Server
- Parse Server version: `6.0.0`
- Operating system: `FILL_THIS_OUT`
- Local or remote host: `localhost`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `localhost`

### Logs

Browser log:
```javascript
dashboard.bundle.js:2 TypeError: Cannot read properties of null (reading 'current')
    at i.value (dashboard.bundle.js:2:2456991)
    at xo (dashboard.bundle.js:2:1635810)
    at Ba (dashboard.bundle.js:2:1654403)
    at ws (dashboard.bundle.js:2:1690950)
    at fl (dashboard.bundle.js:2:1682425)
    at dl (dashboard.bundle.js:2:1682350)
    at rl (dashboard.bundle.js:2:1679380)
    at dashboard.bundle.js:2:1631153
    at t.unstable_runWithPriority (dashboard.bundle.js:2:1841656)
    at Hi (dashboard.bundle.js:2:1630862)

```

**Comment by cbaker6** [comment]
Duplicate #2373
