### ISSUE TITLE
When the input field is converted into a text area, the cursor jumps to the start

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2412]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

When the input field is converted into a text area, the cursor jumps to the start. 
![error](https://user-images.githubusercontent.com/49753983/230702275-854792ef-3ef6-4c79-be27-6e6bf4995c3a.gif)

### Steps to reproduce

Modify any field that contains a string data type.

### Actual Outcome

moving cursor to start

### Expected Outcome

It should not move the cursor.

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `latest`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `latest`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

NA

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.6](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.6)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
