### ISSUE TITLE
Showing "No data to display" for the _Role section, even though there are Roles present.

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2415]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The message "No data to display" is appearing for the Role section, even though there are Roles present. also not showing any rows in the table.

### Steps to reproduce

1. Create couples of Roles in the _Role secion.

2. Click on "View relation" for any columns users or roles.
<img width="1421" alt="Screenshot 2023-04-10 at 11 08 15 AM" src="https://user-images.githubusercontent.com/104055123/230930913-4bf1c2a1-bd82-448c-a3b8-1c50ed704e0a.png">

3. Click on back icons to go to the main table.
<img width="1252" alt="Screenshot 2023-04-10 at 11 08 43 AM" src="https://user-images.githubusercontent.com/104055123/230931510-3e87b1de-c877-49b1-bc6f-c4e04181c6ac.png">

4. Showing no rows with message "No data to display".
<img width="1424" alt="Screenshot 2023-04-10 at 11 09 07 AM" src="https://user-images.githubusercontent.com/104055123/230932493-3486d8a8-b83d-4c2d-9361-2ff9fc1f7359.png">

### Actual Outcome

Showing no rows with message "No data to display".

### Expected Outcome

During the 4th step, it is expected to display all the rows in a manner similar to the image shown in step 2.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64)`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local`

### Logs

NA

**Comment by patelmilanun** [comment]
I'll pick this one up as im able to reproduce it

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
