### ISSUE TITLE
The back button disappears when I refresh the page.

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2417]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The back button disappears when I refresh the page on the _Role page.

### Steps to reproduce

1. Go to _Role
2. Click on "View Relation"
<img width="1421" alt="230930913-4bf1c2a1-bd82-448c-a3b8-1c50ed704e0a" src="https://user-images.githubusercontent.com/49753983/231642114-6406282b-769d-4faa-8753-e5c942402e37.png">

3. You will see this page with back button.
<img width="1424" alt="Screenshot 2023-04-12 at 11 34 31 PM" src="https://user-images.githubusercontent.com/49753983/231642670-38b4bcfa-396b-4d0b-a481-9db59e343320.png">

4. Now refresh the page, You will see the same page without back button.
<img width="1437" alt="Screenshot 2023-04-12 at 11 37 47 PM" src="https://user-images.githubusercontent.com/49753983/231642922-e75fe9e2-ed21-4a04-87f4-dac9d7ea9cbd.png">

### Actual Outcome

The back button disappears when I refresh the page.

### Expected Outcome

The back button should remain visible.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
