### ISSUE TITLE
The uploaded file is not being displayed in the _Product class.

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2418]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

The uploaded file is not being displayed in the default _Product class.

### Steps to reproduce

![CPT2304132340-1068x670](https://user-images.githubusercontent.com/49753983/231935793-35d87c4f-bbb8-45c1-8007-b4c36acbd854.gif)

### Actual Outcome

hidden file name

### Expected Outcome

It should show the file name just like for other classes.
<img width="535" alt="Screenshot 2023-04-13 at 11 36 19 PM" src="https://user-images.githubusercontent.com/49753983/231935439-2e73eddf-4e2a-4279-a69e-0b3aabc2274b.png">

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

**Comment by alceil** [comment]
Can i work on this @mtrezza ?

**Comment by mtrezza** [comment]
Sure, please go ahead, it doesn't seem that anyone else has opened a PR so far.

**Comment by AshishBarvaliya** [comment]
This issue is not confined to a specific class(_Product); The problem arises when an object is not saved, preventing the image from being uploaded to the database. As a result, the status remains as 'Uploading...' until the object is saved or added, at which point the filename (along with the uploaded URL) becomes visible. Once the object is successfully saved, everything functions perfectly. We are effectively handling the rest of the data types, saving them to the state and displaying them in the UI. However, we need to address the file handling aspect, such as displaying the file name only without allowing direct access to the URL.
ex.
Uploading after save(No updates required here): 
<img width="285" alt="Screenshot 2023-06-20 at 6 47 24 PM" src="https://github.com/parse-community/parse-dashboard/assets/49753983/ef1dd1ec-07c0-45ff-91e6-129e1d11f6b0">

Uploading before save(proposed solution): 
<img width="249" alt="Screenshot 2023-06-20 at 6 51 54 PM" src="https://github.com/parse-community/parse-dashboard/assets/49753983/f3555954-32ba-49ab-ae00-07dc24d03753">

@mtrezza

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.27](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.27)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
