### ISSUE TITLE
Throwing error when selecting `Object` datatype for a column.

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2419]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Throwing error when selecting `Object` datatype for a column.

### Steps to reproduce

1. Go to any class (ex. _Role)
2. Click on 'Add a new column'
3. Choose `Object` datatype
<img width="445" alt="Screenshot 2023-04-14 at 12 16 11 AM" src="https://user-images.githubusercontent.com/49753983/231940327-d3a0f59e-9da8-4326-ba82-b6af63a001d8.png">

### Actual Outcome

Breaking the page and throwing console error.

### Expected Outcome

Should not throw errors.

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a
Dashboard.bundle.js:2 TypeError: Cannot read properties of null (reading 'current')
    at i.value (dashboard.bundle.js:2:2456991)
    at xo (dashboard.bundle.js:2:1635810)
    at Ba (dashboard.bundle.js:2:1654403)
    at ws (dashboard.bundle.js:2:1690950)
    at fl (dashboard.bundle.js:2:1682425)
    at dl (dashboard.bundle.js:2:1682350)
    at rl (dashboard.bundle.js:2:1679380)
    at dashboard.bundle.js:2:1631153
    at t.unstable_runWithPriority (dashboard.bundle.js:2:1841656)
    at Hi (dashboard.bundle.js:2:1630862)
n

**Comment by mtrezza** [comment]
Amazing how you are finding these bugs! Well done

**Comment by Rijak2005** [comment]
Is there any fix for this?

**Comment by patelmilanun** [comment]
After trying to re-produce this bug I can see that it's happening only for the current stable version which is 5.0.0 and not for the 5.1.0-alpha.13 which is latest un-stable version. So maybe this will get resolved when the alpha merged into stable, and we can close this issue at that time.

**Comment by AshishBarvaliya** [comment]
@mtrezza You can close this issue since it is not reproducible with  `parse-dashboard@5.1.0`.
