### ISSUE TITLE
After applying the filters, the placement of the date picker is changing.

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2424]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

After applying the filter, the placement of the date picker is changing.

### Steps to reproduce

![CPT2304151835-1432x694](https://user-images.githubusercontent.com/49753983/232256233-7178acb7-c51c-4848-aaba-8b67cc9e9ed6.gif)

### Actual Outcome

the placement of the picker is wrong.

### Expected Outcome

<img width="823" alt="Screenshot 2023-04-15 at 6 44 55 PM" src="https://user-images.githubusercontent.com/49753983/232256240-274fc18e-75ce-4f94-b748-53aa74fab077.png">

### Environment

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `MongoDB 5.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Remote`

### Logs

n/a

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.4](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.4)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
