### ISSUE TITLE
Add row with modal causes crash in `BrowserCell.react.js`

### ISSUE THREAD

**Issue by TravisHeaver** [parse-community/parse-dashboard#2426]
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description
When adding a new row via the modal then selecting a field to add where the class being added has a field type array (of pointers) the app crashes

### Steps to reproduce
create 3 classes class A which has an array of pointers to class B, and class C which points to class A. 
In class C select edit => add a row with modal

### Actual Outcome
White screen with the crash:
`(anonymous function) (bind.js:7)
(anonymous function) (BrowserCell.react.js:194:116)
map
renderCellContent (BrowserCell.react.js:184:137)
componentDidMount (BrowserCell.react.js:540)
commitLifeCycles (react-dom.development.js:19814)
commitLayoutEffects (react-dom.development.js:22803)
callCallback (react-dom.development.js:188)
dispatchEvent
invokeGuardedCallbackDev (react-dom.development.js:237)
invokeGuardedCallback (react-dom.development.js:292)
commitRootImpl (react-dom.development.js:22541)
commitRootImpl
unstable_runWithPriority (scheduler.development.js:653)
commitRoot (react-dom.development.js:22381)
finishSyncRender (react-dom.development.js:21807)
performSyncWorkOnRoot (react-dom.development.js:21793)
performSyncWorkOnRoot
(anonymous function) (react-dom.development.js:11089)
unstable_runWithPriority (scheduler.development.js:653)
flushSyncCallbackQueueImpl (react-dom.development.js:11084)
flushSyncCallbackQueue (react-dom.development.js:11072)
scheduleUpdateOnFiber (react-dom.development.js:21199)
enqueueSetState (react-dom.development.js:12639)
(anonymous function) (react.development.js:471)
_callee3$ (ObjectPickerDialog.react.js:245)
tryCatch (regeneratorRuntime.js:53)
(anonymous function) (regeneratorRuntime.js:135)
asyncGeneratorStep (asyncToGenerator.js:9)
_next (asyncToGenerator.js:28)`

### Expected Outcome
You should be able to add the new row

### Environment
5.0.0

Dashboard
- Parse Dashboard version: `5.0.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `all browsers`
- Browser version: `safari 16.4`

Server
- Parse Server version: `5.2.8`
- Operating system: `Mac OS 13.3.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `5.0.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

### Logs
N/A

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.9](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
