### ISSUE TITLE
Browse to users and roles from PermissionsDialog

### ISSUE THREAD

**Issue by FransGH** [parse-community/parse-dashboard#2435]
### New Feature / Enhancement Checklist

- [ X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [ X] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The PermissionsDialog current only shows the objectId and/or name of users and roles.
To quickly see user or role details a manual lookup in the respective classes is needed.
Selection and copy/paste of the objectId role name does not seem to be possible.
And even if it would, it would still be manual overhead for the simple task of traversing roles.

### Feature / Enhancement Description

Make user and roles in the PermissionsDialog clickable and show the object in the browser.
Ideally this would happen in a 2nd browser window (tab) so the PermissionsDialog remains open for the selected class/object.

Even better would be a dedicated UI to traverse the ACL tree (role -> users/subroles) within the PermissionsDialog or some new dialog. This is however outside the scope of this feature request.

### Example Use Case

1) create a few roles with multiple users and subroles
2) add multiple users and subroles to each subrole
3) select any class/object and add the top level roles to the ACL
4) while inspecting the ACL, click on any user or role to browse that item in a new window

### Alternatives / Workarounds

none (manual copy/paste doesn't work as text selection is disabled)
it's effectively not possible to quickly traverse an ACL

### 3rd Party References

Not investigated as this is relative basic/simple request.

**Comment by FransGH** [comment]
Can't comment yet on the PR so post it here:

The way the url is composed is a bit hackie and will clearly fail if the current location is not ../browser/..
Didn't dive that deep into the code to get a clean base url but happy with suggestions!

**Comment by mtrezza** [comment]
> Can't comment yet on the PR so post it here

How so?

**Comment by FransGH** [comment]
don't know, got an error an moved on.  now it worked so deleted the comment here (this one can also be deleted)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
