### ISSUE TITLE
Identify and mark invalid users and roles in Permissions Dialog

### ISSUE THREAD

**Issue by FransGH** [parse-community/parse-dashboard#2437]
### New Feature / Enhancement Checklist

- [X] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [X] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [X] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

An object might have invalid user or role references. Currently the Permissions Dialog checks if all are valid. If one is invalid, all the entries are shown without their name (users) or object id (roles). It is first all confusing why sometimes the names/id's don't appear and 2nd it would be helpful to quickly identify invalid entries.

### Feature / Enhancement Description

Always show the name (for users) and id (for roles) for valid entries. 
Mark invalid entries as invalid (not found) with a clear visual distinction.

### Example Use Case

A role or user gets deleted while it is still used in an ACL.
1) create an object with anther user or role in the ACL
2) delete the referred user or role
3) see that the user name or role id no longer appears for any of the ACL entries, including the valid ones

### Alternatives / Workarounds

None

### 3rd Party References

N/A

**Comment by mtrezza** [comment]
Closing via #2436
