### ISSUE TITLE
Missing config parameter option master key required

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2439]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

It's not possible anymore to set a config option as "master key required". The dialog originally contained such an option. At some point it got lost it seems.

See https://github.com/parse-community/parse-dashboard/pull/1233#issuecomment-523394095.

The current workaround is to go directly manipulate the option in the DB collection `_GlobalConfig`.

### Steps to reproduce

Config > Add new parameter

### Actual Outcome

No option to set parameter to require master key.

### Expected Outcome

Should have option as in screenshot in https://github.com/parse-community/parse-dashboard/pull/1233#issuecomment-523394095.

### Environment

Dashboard
- Parse Dashboard version: `5.1.0`

**Comment by mtrezza** [comment]
Looking at the logs, its seems that the `serverInfo` endpoint is inaccessible:

> [Error] Could not connect to the server.
> [Error] XMLHttpRequest cannot load http://localhost:1337/parse/serverInfo due to access control checks.
> [Error] Failed to load resource: Could not connect to the server. (serverInfo, line 0)

It's trying to access `localhost` instead of the actual server domain. I was able to replicate the issue locally with a connection to a remote server.

The request is formed via `Parse._request`, which is provided by the Parse JS SDK, so there may be an issue there.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.10](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.10)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
