### ISSUE TITLE
Allow classPreferences to be set in dashboard config

### ISSUE THREAD

**Issue by dblythy** [parse-community/parse-dashboard#2454]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

New feature views need to be added on every device, there is no way to keep filters persistent.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.13](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.13)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0)
