### ISSUE TITLE
Remember last opened class is data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2458]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When navigating away from the data browser and the back to it, an empty page is displayed before a class is selected. This is a new, recent behavior, but the previous one was also not ideal, which just opened the first class, i.e. `_Installation`.

### Feature / Enhancement Description

Remember the last opened class in data browser and re-open it when navigating back to the data browser.

### Example Use Case

1. In data browser, open class `_User`.
2. In nav bar, click on "Web Hooks".
3. In nav bar, click on "Data Browser".
4. The `_User` class should be automatically opened, maybe even with the last used filter.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.16](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.16)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
