### ISSUE TITLE
Allow to paste coordinates tuple in data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2462]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

While it's possible to select a geo point field in the data browser and copy its content tuple (long, lat), it's not possible to paste the tuple. This makes it difficult to copy a location from one field and paste it into another field as long and lat need to be pasted individually in two separate text fields.

https://github.com/parse-community/parse-dashboard/assets/5673677/1d451abc-63c8-4b8e-9538-6fa844ea6c3d

### Feature / Enhancement Description

Allow to paste the copies geo point in a single step into a geo point field.

### Example Use Case

1. In data browser select a geo point field.
2. Copy the field value Crtl+C; adds  `(12.345, 12.345)` to the pasteboard.
3. Select another geo point field, double click and use Crtl+V to paste `(12.345, 12.345)`.

### Alternatives / Workarounds
Copy and paste long and lat separate to a new geo field.

**Comment by mtrezza** [comment]
Changed this to "bug" since it turns out pasting coordinates was an existing feature that broke at some point.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.18](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.18)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
