### ISSUE TITLE
Add linting to repository

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2467]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The code is not (properly) linted, causing varying code styles.

### Feature / Enhancement Description

Enforce proper lint rules.

**Comment by patelmilanun** [comment]
I think for code style we should use something like prettier or any such code formatter. Doing formatting with linter is very bad idea mostly because of performance. I do have a video suggestion to not use linter as formatter. If u want I can post it here.

**Comment by mtrezza** [comment]
We use both prettier and eslint as the default across repos in this org.

**Comment by patelmilanun** [comment]
Basically we setup a prettier formatting step in our CI so when somebody is pushing code that is not formatted correctly our CI will yell at him.

**Comment by patelmilanun** [comment]
I don't see prettier anywhere in the dashboard repo.

**Comment by mtrezza** [comment]
You could look at the parse server repo for how we use eslint and prettier:

- https://github.com/parse-community/parse-server/blob/alpha/.eslintrc.json
- https://github.com/parse-community/parse-server/blob/alpha/.github/workflows/ci.yml (see `check-lint`)
- https://github.com/parse-community/parse-server/blob/alpha/.prettierrc

**Comment by patelmilanun** [comment]
ok but we dont have a dedicated step for checking formatting right ? or linter is doing that?

**Comment by mtrezza** [comment]
Yes, it's in the CI, see the 2nd point

**Comment by mtrezza** [comment]
Dashboard already has a lint check in the CI, see
https://github.com/parse-community/parse-dashboard/actions/runs/5315803113/jobs/9624609903?pr=2463

But it seems the rules are different, because it doesn't seem to enforce leading spacing and code structure for example: 
https://github.com/parse-community/parse-dashboard/pull/2466#discussion_r1234376813

I would compare the lint rules with those of parse sever, which are the best maintained of all repos I assume.
