### ISSUE TITLE
The file extension is hidden beneath the icon within the file cell in the edit modal

### ISSUE THREAD

**Issue by AshishBarvaliya** [parse-community/parse-dashboard#2470]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

<img width="285" alt="Screenshot 2023-06-20 at 6 47 24 PM" src="https://github.com/parse-community/parse-dashboard/assets/49753983/1c2bc71e-c139-4fbe-acb8-3ad7d8a8042c">

### Steps to reproduce

Upload any file.

### Actual Outcome

The file extension is hidden.

### Expected Outcome

The file name along with its extension should be clearly visible.

Dashboard
- Parse Dashboard version: `5.1.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Chrome`
- Browser version: `Version 111.0.5563.146 (Official Build) (arm64)`

Server
- Parse Server version: `5.4.3`
- Operating system: `MacOS `
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Local`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.26](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.26)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
