### ISSUE TITLE
Header row not scrolling with data rows in data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2475]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Header row in data browser is not aligned with the data rows below.

<img width="803" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/5673677/e3b8af53-e481-4828-b9b0-dae26e1e5d36">

The same (or similar) issue also happens with the vertical scroll position.

This bug was likely introduced by this PR, where the issue was first [observed](https://github.com/parse-community/parse-dashboard/pull/2457#issuecomment-1586114868):
- https://github.com/parse-community/parse-dashboard/pull/2457

### Steps to reproduce

The reproduce the issues with the steps below, it is necessary that the classes contain >= 3x more rows and columns than fit in the browser window. 

Horizontal scroll issue:

1. Open Installation class and scroll to the very right
2. Open User class

Vertical scroll issue:

1. Open Installation class and scroll down a few pages
2. Open User class (if this class only contains 1 class, the scroll position from the Installation class is preserved and one has to scroll up white space to get to the first row)

### Actual Outcome

The _User class shows the header row misaligned with the data rows.

### Expected Outcome

Rows should be aligned.

### Environment

Dashboard
- Parse Dashboard version: `5.2.0-alpha.19`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`

**Comment by mtrezza** [comment]
@AshishBarvaliya, @damianstasik, @patelmilanun Does anyone want to look into this bug? It started to occur only recently, so if you go back the last few alpha versions it should be easy to find out which PR caused it. The bug is currently making the alpha versions of Parse Dashboard unusable and is blocking the release pipeline; wen cannot release a beta version until this is fixed.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.21](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.21)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
