### ISSUE TITLE
Add refresh button to Cloud Config

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2479]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The Cloud Config page can only be refreshed with a browser refresh.

### Feature / Enhancement Description
Add refresh button to Cloud Config page, like on the Jobs page.

**Comment by patelmilanun** [comment]
can u tell me how this is helpful. I mean are we changing this parameter programatiacally somewhere?

**Comment by mtrezza** [comment]
Yes, the params can be changed programmatically; or you can just have 2 browser windows open with the Cloud Config page, update in one of them, then a few minutes later forget about which Cloud Config page has the latest values. To be sure you could refresh.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.2.0-alpha.22](https://github.com/parse-community/parse-dashboard/releases/tag/5.2.0-alpha.22)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0)
