### ISSUE TITLE
Indicate refresh status on CloudConfig page

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2494]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

https://github.com/parse-community/parse-dashboard/pull/2480 added a Refresh button to refresh the CloudConfig. However, it's not clear what the refresh status is after clicking the button. A refresh can complete successfully, still be ongoing (slow network) or fail. In either case there wouldn't be any indication of that.

### Feature / Enhancement Description

The simplest indication would probably be using the pop-up message to show success or fail, incl. the error message.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.3.0-alpha.2](https://github.com/parse-community/parse-dashboard/releases/tag/5.3.0-alpha.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0)
