### ISSUE TITLE
Add relational filter conditions

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2496]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

The filter dialog in the data browser currently only allows to filter for fields in the current class. It's not possible to add a filter condition that relates to another class.

### Feature / Enhancement Description

Add filter conditions that relate to other classes. Since Parse Dashboard knows the entire schema, it also knows which other classes have a pointer to the currently displayed class; it can use that information to allow for filtering by fields of these related classes. 

The filter dialog could be extended with a drop-down for related classes and its fields.

### Example Use Case

A user in the `_User` class may have
- purchases in a `Purchase` class with a `_User` pointer field
- transactions in a `Transaction` class with a `_User` pointer field

To filter all users who
- made purchases of shoes (in `Purchase` class)
- with a transaction using a credit card (in `Transaction` class)

The filter dialog could look like this:

<img width="679" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/5673677/6fec02dc-a53d-47ca-96a6-9eeca8bee09b">

### Alternatives / Workarounds
n/a

**Comment by vardhan0604** [comment]
@mtrezza, is bounty still available for this issue?

**Comment by mtrezza** [comment]
@vardhan0604 sure, please feel free to go ahead and submit a PR

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.9](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.9)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
