### ISSUE TITLE
Add descriptive statistics to data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2506]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Currently it's not possible to see descriptive statistics in the data browser. Instead, to calculate the sum of two fields they have to calculated manually, or the data has to be exported to processed.

### Feature / Enhancement Description

Add a feature that:
- Allows to select cells in the data browser across rows and columns.
- Calculates and displays common descriptive statistics about the selected cells, like "Sum", "Mean", "p99".

### Example Use Case

This should work similar to a spreadsheet program where cells can be selected and these statistics are displayed. 

<img width="253" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/5673677/1daabbbc-c27b-4411-a293-6c9845faccd1">

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.7](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.7)

**Comment by mtrezza** [comment]
https://github.com/parse-community/parse-dashboard/pull/2529 may have to be removed, due to https://github.com/parse-community/parse-dashboard/issues/2530.

**Comment by mtrezza** [comment]
Closing as https://github.com/parse-community/parse-dashboard/issues/2530 has been fixed, and https://github.com/parse-community/parse-dashboard/pull/2529 does not need to be reverted.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
