### ISSUE TITLE
"Open pointer in new tab" doesn't work when dashboard is installed in a folder

### ISSUE THREAD

**Issue by mathieulb** [parse-community/parse-dashboard#2509]
### New Issue Checklist
- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

"Open pointer in new tab" doesn't work when dashboard is installed in a folder

### Steps to reproduce

Have an Express server in which ParseDashboard is assigned to a subfolder instead of directly '/':

    app.use('/dashboard', new ParseDashboard(dashboardConfig))

Go in a class with a pointer column, right click on a cell, choose "Open pointer in new tab"

### Actual Outcome

Cannot GET /apps/my-app/browser/MyClass

### Expected Outcome

A browser window opening the url `/dashboard/apps/my-app/browser/MyClass?filters=...`

### Environment

Dashboard
- Parse Dashboard version: `5.2.0`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Firefox`
- Browser version: `119`

Server
- Parse Server version: `6.3.1`
- Operating system: `Heroku Linux 22`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `Heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `3.6.12`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Heroku`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.5](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.5)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
