### ISSUE TITLE
Dashboard crashes if Parse Server script returns object

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2517]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Dashboard crashes if Parse Server script returns object instead of string.

### Steps to reproduce

1. Create a Cloud Function that returns an object `return { status: 'ok'}`.
2. Run a script on a row in the data browser.

### Actual Outcome

Dashboard crashes.

### Expected Outcome

Dashboard should display the returned object.

Dashboard
- Parse Dashboard version: `5.4.0-alpha.1`

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
