### ISSUE TITLE
How about add query custom authData in parse dashboad?

### ISSUE THREAD

**Issue by badboy-tian** [parse-community/parse-dashboard#2520]
### New Feature / Enhancement Checklist

- [ ] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [ ] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

can not custom query authData
### Feature / Enhancement Description

query authData in dashboard
<img width="767" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/2835129/d2e5dcd0-50ba-400b-bb18-69a693a6c4c4">

<img width="566" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/2835129/6e89294e-0dfb-428e-8454-77f2ce069081">

**Comment by mtrezza** [comment]
This is already supported with `key equals`, for example `{"facebook.id": "123"}`.

**Comment by badboy-tian** [comment]
can not work in parse dashboard.

**Comment by badboy-tian** [comment]
> This is already supported with `key equals`, for example `{"facebook.id": "123"}`.

![111Untitled](https://github.com/parse-community/parse-dashboard/assets/2835129/4bbf70c4-5147-495a-8ff6-e372b33372af)

can not work in parse dashboard.
