### ISSUE TITLE
Using Postgres with Docker. Total entry count per class doesn't show.

### ISSUE THREAD

**Issue by jaysonng** [parse-community/parse-dashboard#2523]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

On the left side of ParseDashboard where it shows all the classes, it should show how many entries there are per Class. However when using Postgres (on docker - not sure if this is partly the problem) it always shows 0. Sometimes it updates when you enter data but on reloading, it goes back to 0. 

### Steps to reproduce

Install dashboard using postgres. 

### Actual Outcome

0 entry counts

### Expected Outcome

Shows the total count per class like when i was using mongodb. 

### Environment

Dashboard
- Parse Dashboard version: `5.3`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `17.1`

Server
- Parse Server version: `6.4`
- Operating system: `6.4`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local`

Database
- System (MongoDB or Postgres): `postgres`
- Database version: `15.4`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `local`

**Comment by cbaker6** [comment]
The reason is the Parse server is using particular Postgres methods to estimate count, once you add more data it will update. Note this has nothing to do with docker. See my comments and discussion here https://github.com/parse-community/parse-server/issues/8502#issuecomment-1567140269

**Comment by mtrezza** [comment]
Closing as it's described in https://github.com/parse-community/parse-server/issues/8502

**Comment by jaysonng** [comment]
Can we not have "0" instead of showing "0" then?
