### ISSUE TITLE
Columns keeps getting reordered. Don't know why.

### ISSUE THREAD

**Issue by jaysonng** [parse-community/parse-dashboard#2525]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Class columns keeps getting reordered. 

### Steps to reproduce

logging in to Parse Dashboard, columns get reordered for no particular reason.

### Actual Outcome

random column order

### Expected Outcome

Columns should stay where placed either when dragged or under "manage columns"

### Environment

Dashboard
- Parse Dashboard version: `5.3`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `17.1`

Server
- Parse Server version: `6.4`
- Operating system: `MacOS Sonoma 17.1.1`
- Local or remote host (AWS, Azure, Google Cloud, Heroku, Digital Ocean, etc): `local and heroku`

Database
- System (MongoDB or Postgres): `MongoDB`
- Database version: `6.0`
- Local or remote host (MongoDB Atlas, mLab, AWS, Azure, Google Cloud, etc): `Local and mongodb atlas`

**Comment by mtrezza** [comment]
Could you try to replicate that in the latest dashboard version (currently [5.4.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.3))? You could also try with different browsers and since this is website data based, it probably won't store column order in "private browsing". I'm closing for now this as it lacks sufficient details to replicate, such as a detailed step-by-step guide. We can re-open if you have more information on the issue to confirm that it's a bug.

**Comment by jaysonng** [comment]
> Could you try to replicate that in the latest dashboard version (currently [5.4.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.3))? You could also try with different browsers and since this is website data based, it probably won't store column order in "private browsing". I'm closing for now this as it lacks sufficient details to replicate, such as a detailed step-by-step guide. We can re-open if you have more information on the issue to confirm that it's a bug.

I used Safari's normal browser and not the private window. I'll go and try 5.4.0-alpha.3 as soon as I can and see if that helps.

thanks!
