### ISSUE TITLE
Config page is blank

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2530]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Config page cannot be opened; error:

<img width="643" alt="image" src="https://github.com/parse-community/parse-dashboard/assets/5673677/b157b7bb-4694-4dbd-8010-03e67fe50cfa">

Error has been introduced with PR https://github.com/parse-community/parse-dashboard/pull/2529.

### Steps to reproduce

1. Open config page.

### Actual Outcome

Page stays blank; error logged.

### Expected Outcome

Config page displays.

### Environment

Dashboard
- Parse Dashboard version: `5.4.0-alpha.7`

**Comment by mtrezza** [comment]
Hi @AshishBarvaliya, would you take a look at this? Otherwise we have to reverse https://github.com/parse-community/parse-dashboard/pull/2529 and remove the feature from the dashboard for now.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [5.4.0-alpha.8](https://github.com/parse-community/parse-dashboard/releases/tag/5.4.0-alpha.8)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
