### ISSUE TITLE
Add support for node 20

### ISSUE THREAD

**Issue by cbaker6** [parse-community/parse-dashboard#2533]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

Node 20 is not tested in the CI. In addition, node versions 14 and 16 are no longer supported by node

### Feature / Enhancement Description

Add support for node 20 and drop support for node 14 and 16

### Example Use Case

Use dashboard on latest node.

### Alternatives / Workarounds

Devs run and test on their own.

### 3rd Party References

https://nodejs.org/en/about/previous-releases

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
