### ISSUE TITLE
Dashboard scrolls when selecting row in data browser

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2545]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Dashboard scrolls when selecting row in data browser. This has only been observed when a filter is set.

Uploading recording.mov…

### Steps to reproduce

1. Open dashboard collection in data browser; collection needs to be large enough so it contains enough rows to scroll multiple pages; e.g. see screen recording which uses 300 rows.
2. Set filter "objectId exists".
3. Select a row without scrolling down.
4. Scroll down at least 2 pages and select a row --> data browser jump-scrolls up.

### Environment

Dashboard
- Parse Dashboard version: `6.0.0-alpha.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari`
- Browser version: `Version 17.4.1 (19618.1.15.11.14)`

**Comment by devbymak** [comment]
I tried doing steps but didn't see jump-scrolls up, can you upload the record?

**Comment by mtrezza** [comment]
Sometimes I can't get it to replicate neither. I believe it has something to do with:
- how many items are filtered out in between the visible rows
- the scroll position you are at when you set the filter
- maybe something in the cache

You'd have to play around a bit.

1. Create class "Test".
2. Open the JS console and run: 
    ```js
    const objs = [];
    
    for (let i=0; i<1000; i++) {
      const obj = new Parse.Object('Test');
      objs.push(obj);
    }
    
    await Parse.Object.saveAll(objs);
    ```
3. Set filter "objectId exists".
4. Select individual rows --> view scrolls

I'll post a comment if I managed to pin it down.

**Comment by devbymak** [comment]
Actually, I realized that when a cell is selected and we scroll down to select a row, the row isn't properly selected(selected objectId is different), and the scroll jumps back up. Is that correct?

**Comment by mtrezza** [comment]
Yes that sounds like the issue I tried to describe here. It seems to be difficult to reproduce with only a few rows in a class, although I managed to do it sometimes with only 100 - 1k rows. But it occurs reliably in classes with a large number of rows and a filter set.

Could you share a video of what you observed?
