### ISSUE TITLE
Select rows by pressing and dragging cursor over checkboxes

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2546]
### New Feature / Enhancement Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).

### Current Limitation

When selecting rows, each checkbox requires a separate click. This is tedious when streaks of adjacent rows need to be selected.

### Feature / Enhancement Description

Select multiple adjacent rows by clicking in one checkbox, hold the mouse key and drag the mouse cursor down. All checkboxes underneath the drag path of the cursor should change to the state of the first checkbox. That means, if the first checkbox changed from unselected to selected, the all dragged-over checkboxes should end up being selected as well.

### Alternatives / Workarounds

Status quo, where each checkbox needs to be clicked individually.

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.3](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.3)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
