### ISSUE TITLE
Descriptive stats not showing

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#2574]
### New Issue Checklist

- [x] I am not disclosing a [vulnerability](https://github.com/parse-community/parse-server/blob/master/SECURITY.md).
- [x] I am not just asking a [question](https://github.com/parse-community/.github/blob/master/SUPPORT.md).
- [x] I have searched through [existing issues](https://github.com/parse-community/parse-dashboard/issues?q=is%3Aissue).
- [x] I can reproduce the issue with the latest versions of [Parse Server](https://github.com/parse-community/parse-server/releases) and [Parse Dashboard](https://github.com/parse-community/parse-dashboard/releases). 

### Issue Description

Descriptive stats as introduced by https://github.com/parse-community/parse-dashboard/pull/2529 are not showing in parse-dashboard 6.0.0-beta.1.

### Steps to reproduce

1. Select 2 adjacent number cells.
2. Stats display not showing.

### Environment

Dashboard
- Parse Dashboard version: `6.0.0-beta.1`
- Browser (Safari, Chrome, Firefox, Edge, etc.): `Safari `
- Browser version: `17.5 (19618.2.12.11.6)`

**Comment by mtrezza** [comment]
@AshishBarvaliya maybe interesting for you...

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-alpha.11](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-alpha.11)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0-beta.2](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0-beta.2)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [6.0.0](https://github.com/parse-community/parse-dashboard/releases/tag/6.0.0)
