### ISSUE TITLE
Feature Request: Support readonly user accounts

### ISSUE THREAD

**Issue by mattgoldspink** [parse-community/parse-dashboard#259]
I'd like to give access to some people to see the data but not modify it. It'd be great if there was a way to just provide a readonly user account so they can see the data, filter tables, etc but not modify or delete anything.

**Comment by drew-gross** [comment]
This is a good idea, but it won't be simple to implement. Parse Dashboard uses an app's master key to access data on the dashboard, and since the master key allows writes, we would need a new type of key that only allows reads. We'd welcome some help with implementing it!

**Comment by skimgosu** [comment]
Using clientKey reveals data that's only publicly viewable? But never mind... That would kinda be like a pandora's box.

**Comment by dplewis** [comment]
This has been addressed. 

https://github.com/parse-community/parse-dashboard#use-read-only-masterkey
