### ISSUE TITLE
Node 22 support missing in package.json

### ISSUE THREAD

**Issue by TomKremer** [parse-community/parse-dashboard#2614]
Hello,
6.0.0 did bring Node 22 support, this could also be updated in the package?
https://github.com/parse-community/parse-dashboard/blob/408154bc947b9e4507f4cf393ff742ee53f7a66f/package.json#L142

**Comment by mtrezza** [comment]
Well spotted, the updated engine range should exclude node 21, since we don't support non-LTS versions.
