### ISSUE TITLE
Deleted pointer still visible on refresh

### ISSUE THREAD

**Issue by tanmays** [parse-community/parse-dashboard#272]
Using parse-server 2.2.7 and latest parse-dashboard master branch. 

**Issue**: 

Any pointer in a pointer based column after being deleted will still be visible even after clicking the refresh button. 

**Steps to reproduce**: 
1. Assign any point to a field and open Parse Dashboard, you should see the pointer. 
2. Now delete that pointer using Cloud Code (or any SDK)
3. Click refresh button on Dashboard and the value will still be visible

You need to refresh the entire page for that value to be updated.

**Comment by drew-gross** [comment]
Interesting discovery. Checking the network traffic clearly shows the response does not include the pointer, so the issue is in the client-side update. Will investigate.

**Comment by drew-gross** [comment]
I believe fixing this will require updating the Parse SDK to version 1.7.1 which includes https://github.com/ParsePlatform/Parse-SDK-JS/pull/206
