### ISSUE TITLE
Suggestion: If no push variables set in parse server, display link to Push setup

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-dashboard#289]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ x] You're running version >=2.1.4 of Parse Server.
- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Latest Parse Dashboard
#### Steps to reproduce

N/A

Right now when you install the dashboard and click on push it seems like you would be able to send a push though the system, one recommendation would be if no push adaptor is set in the parse server index.js display html page when clicking the push from the dashboard to provide a link to setting up push in parse server.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Good idea! That would be much more useful than just now showing the push tab.

**Comment by gateway** [comment]
I can see what I can do, juggling way to much between our startup and first iOS app so even breath at times.. Just thought I would make the suggestion.

**Comment by drew-gross** [comment]
Of course :) I think this would be a good first PR for anyone wanting to get started with a contribution to Parse Dashboard.

**Comment by zuymanto** [comment]
Still Open as GFPR ?

**Comment by drew-gross** [comment]
Yep.

**Comment by drew-gross** [comment]
Unless @gateway is making progress.

**Comment by gateway** [comment]
Sorry guys, pulling a sprint here at the office things are crazy.. no time to look @zuymanto if you want to grab it please do.
