### ISSUE TITLE
How can I deploy this project straight to AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by juliusbtesh** [parse-community/parse-dashboard#301]
I have tried uploading and deploying this into a node.js environment but I get a "Health" degraded (red) with errors. Is it possible to deploy this package into EB or not?

**Comment by chathaw** [comment]
I'm running into the same thing. Tried with docker too, without any luck (although I'm no expert on docker).

**Comment by cherukumilli** [comment]
# parse-dashboard-example
If anyone is interested then please check out and give me feedback about my **parse-dashboard-example** project. It is similar to the **parse-server-example**.

Please check it out at: `https://github.com/cherukumilli/parse-dashboard-example`

**Comment by D34thStalker** [comment]
Thank you @cherukumilli , I have actually got this one working ( I believe both of those working ) when I came across them not too long ago. The only issue I am having is that I don't think they are on the latest versions from the official repositories and I wouldn't know how to get them to always be on the latest either.

**Comment by chathaw** [comment]
@D34thStalker What version of parse-dashboard did you get working?

**Comment by D34thStalker** [comment]
@chathaw I don't know the version because it doesn't show it. Its whatever version is included in the above post from @cherukumilli . In order to get that one working with AWS, I downloaded the zip and changed the index.js file to have the correct information regarding my parse server domain and app info and it worked.

**Comment by D34thStalker** [comment]
@chathaw I have just deployed the package in the above repository and it is working with v1.0.10. If you want instructions for what I did, you can email me.

**Comment by diego-vieira** [comment]
@D34thStalker instead of sending you an email you could send the steps to this issue ;)

**Comment by D34thStalker** [comment]
Alright, I'll try to elaborate as best as possible: @diego-vieira 

I downloaded the files from here https://github.com/cherukumilli/parse-dashboard-example
In AWS EB, on the web panel (You don't have to do this through the terminal), you could create an Application and then an environment containing a Node.js configuration
In the software configuration of this environment, I used these environment variables (to pass through to the js script);
APP_ID
APP_NAME
MASTER_KEY
SERVER_URL

Set the properties to your correct values.
Once the environment is set up, you can get the files from earlier ready to deploy.
Here is an updated index.js file, the one that I am currently using. 
[index.js.zip](https://github.com/ParsePlatform/parse-dashboard/files/263314/index.js.zip)

*When you make a zip file to deploy into AWS EB, you must make sure that there is no parent folder - the zip that you create should be by selecting all the files/folders that you see above - see pic for reference
<img width="399" alt="screen shot 2016-05-13 at 9 21 20 am" src="https://cloud.githubusercontent.com/assets/4066122/15249138/14e1dd9e-18ec-11e6-854b-882703825cc5.png">
*

Now that you have the zip ready to go, just go back to the AWS EB Environment and deploy the zip. Once it completes , if you have all the configurations set properly, it should be ready to use.

**Comment by diego-vieira** [comment]
@D34thStalker sweet, worked like a charm. kudos.

**Comment by alvajindia** [comment]
You can run it on the same instance where you run your parse server. You just need to edit the index.js file in the parse server to add parse dashboard configuration, and add the parse-dashboard to package.json in dependencies.

**Comment by JordannGeorge** [comment]
How do you find the info for the following?

APP_ID
APP_NAME
MASTER_KEY
SERVER_URL

**Comment by flovilmart** [comment]
You set them on based on your parse-server setup.
