### ISSUE TITLE
For some of my App Dashboard not working for _User class

### ISSUE THREAD

**Issue by hafizapp** [parse-community/parse-dashboard#330]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=2.1.4 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

On real parse.com server and also on our hosted parse server dashboard not working for _User class. All class data showing on the dashboard but when I click the _User class then it now showing any data and also after clicking _User class then it behaves like unexpected. I have attached a video.
I have fetched same issue on real website as well as hosted parse dashboard.

https://www.dropbox.com/s/z5qoopf6rm7gln2/Parse%20Dashboard%20error.mov?dl=0
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by bohemima** [comment]
Can you have a look at both the parse-server logs (run it with VERBOSE=1) and the developer tools when visiting the dashboard. Paste relevant lines to help troubleshooting.

**Comment by hafizapp** [comment]
@bohemima 
I am sorry, I am talking about the parse.com website dashboard, not self hosted parse dashboard.

**Comment by bohemima** [comment]
This repo is for the self-hosted parse-dashboard but my point still stands, have a look at the developer tools and see if there are any hints in there (eg javascript errors, 404's, 501's, etc)

Please report any errors on the hosted parse.com at https://parse.com/help - "Contact us" / "Other" - Choose your app

**Comment by peeinears** [comment]
I get the same thing. Here's the error I see in the console:

From **invariant.js** line **38**:
> Uncaught Invariant Violation: Objects are not valid as a React child (found: Tue Apr 05 2016 12:45:50 GMT-0700 (PDT)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `BrowserCell`.

The request to `classes/_User` comes back with a 200 status and the JSON looks fine...

**Comment by peeinears** [comment]
Strange thing is when I run a local instance parse-server pointed at my mLab db and then point parse-dashboard at parse-server, it works fine. The only differences I notice between the Parse.com `classes/_User` response and the parse-server `classes/_User` response are:

**Comment by peeinears** [comment]
Strange thing is when I run a local instance parse-server pointed at my mLab db and then point parse-dashboard at parse-server, it works fine. The only differences I notice between the Parse.com `/classes/_User` response and the parse-server `/classes/_User` response are:

- Objects' attributes from Parse.com are ordered alphabetically whereas parse-server always serves an object's "objectId" attribute first and any pointers are last.
- Parse.com serves JSON gzipped and parse-server does not.
