### ISSUE TITLE
Newly created class is missing metadata, not viewable in Parse.com dashboard

### ISSUE THREAD

**Issue by mtrezza** [parse-community/parse-dashboard#340]
#### Environment Setup

parse dashboard 1.0.11, parse server 2.2.9
#### Steps to reproduce
1. in the self-hosted parse dashboard create a custom class
2. add a data row
3. in parse.com hosted dashboard and try to view class -> class columns are displayed but no data rows
4. in self-hosted parse dashboard click on "security", uncheck public read/write and save changes
5. click again on "security", check read/write and save changes
6. in parse.com hosted dashboard try to view class again -> data rows are displayed
#### Logs/Trace

The reason is that after class creation the class definition in the database collection "_SCHEMA" is missing the field "_metadata". Setting the ACL for the class creates missing field so the data is viewable in the parse.com dashboard.

**Comment by drew-gross** [comment]
This is an issue with Parse Server, not Parse Dashboard. I'll open an issue over there and link it here.
