### ISSUE TITLE
Broken file names in Files columns while using S3 bucket

### ISSUE THREAD

**Issue by aryelevin** [parse-community/parse-dashboard#351]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [V] You're running version >=2.1.4 of Parse Server.
- [V] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Parse Server 2.2.9
Dashboard 1.0.11
S3 bucket as files store
#### Steps to reproduce

Upload file using dashboard
After the upload done see file name with missing first 4 characters
The issue is because the substring of 37 characters, but in case the S3 (at least, i don't know about other file store services) the uuid of the file generated is missing the dashes, so the length of the uuid is 33 instead 37.

Possible solution is to avoid the length based calculation, and use indexOf("_"), and this will be a good solution for it, but needs to check first if tfss is found, since there, theres no "_" separating the name from the uuid.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Sounds like you've got a potential solution, think you could submit a PR?

**Comment by Kkhattab** [comment]
@aryelevin can you elaborate on what you mean by use indexOf? My app is an iOS app on Parse SDK 1.13. Would the way I save the files changes in my swift code?

**Comment by aryelevin** [comment]
@drew-gross I'll be very happy to do it.

**Comment by Kkhattab** [comment]
@aryelevin can you share your code fixes in the comments here?

**Comment by quaz3l** [comment]
@aryelevin any update on this?

**Comment by Kkhattab** [comment]
@drew-gross any update on this issue?

**Comment by grassland-curing-cfa** [comment]
Has this bug been already fixed?
I am with Parse-server 2.2.12 and deployed to Heroku + mlab. I am still having the same issue... ...

**Comment by pawelkata** [comment]
I'm experiencing the same issue, too.

**Comment by xinzhe1219** [comment]
I am experiencing the same issue.
