### ISSUE TITLE
Suggestion: Manage mongoDB index with dashboard

### ISSUE THREAD

**Issue by kmshiori** [parse-community/parse-dashboard#352]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ O ] You're running version >=2.1.4 of Parse Server.
- [ O ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Right now, most people finished migration to self-host DB/Server.
From now on, the database index manage will become a task can not be ignored, it directly affect the database performance.

One recommendation would be supporting database index managing in dashboard.
The whole class lifecycle (creation, optimization...) could be managed in a place.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
This is a good idea and definitely something we want to support. It will need some big changes from Parse Server first, that I am in the middle of, so it's more of a long term feature.

**Comment by natario1** [comment]
@drew-gross have you kept working on this? It would be great!

**Comment by dplewis** [comment]
@flovilmart I was thinking about getting started on this after the next update. I'm not very good with react tho. I was going to base it off MLab and how they do indexes. Have you guys internally discussed this?

**Comment by flovilmart** [comment]
Uhm, we didn't get started nor discussed the implications / UI of it, that's an interesting project to learn react though :) mLab has a textual inference, if it's just to replicate it, let's not really do that then. I believe we can do better :) we could start with some UX / mocks of what it could look like.

**Comment by dplewis** [comment]
We could do a new tab `Indexes` next to Logs, Jobs, Config etc or we could add it to the data browser toolbar under each class like `View Indexes` button next to Add Row, Filter, Edit etc. 

List all indexes and their name for a class.
Can't edit indexes, only remove and add.
Adding will be a popup where you select the Field (prepopulated) and Value (1,-1,'Text','2dsphere'), Add more than one for a compound index.

Can't delete special indexes like _id / objectId (any others?)
Can't access indexes from certain classes?

Did I miss anything?

**Comment by flovilmart** [comment]
I would go for the data browser option, between `security` and `edit`.

A single popup modal with all the indexes + a way to add more indexes.

**Comment by dplewis** [comment]
Great Plan!

**Comment by flovilmart** [comment]
@dplewis do we need more work on the JS SDK, I don't remember :)

**Comment by dplewis** [comment]
As far as indexes? I don’t think so. It’s just 2.7.1 release  still uses JS SDK 1.10.2

**Comment by regalstreak** [comment]
Any update on the index feature?

**Comment by dplewis** [comment]
@flovilmart I have some IRL stuff to take care of. In the meantime, I've started on this feature. 

Still waiting on https://github.com/parse-community/parse-server/pull/4629

I have a branch https://github.com/dplewis/parse-dashboard/tree/index

Feel free to finish, I'll have some time in the next few weeks.

**Comment by segevfiner** [comment]
This is closed yet I don't actually see the feature in parse-dashboard 5.4.0...
