### ISSUE TITLE
--allowInsecureHttp environment variable and command line parameter ignored when using Parse Dashboard as middleware

### ISSUE THREAD

**Issue by alexargo** [parse-community/parse-dashboard#361]
If you run Parse Dashboard as middleware, the environment variable and command line parameters for allowInsecureHttp are ignored. There is a separate middleware constructor for it, but the other methods should probably work too.

**Comment by darkkiss** [comment]
Yes, because you just need to call it last:

```
var dashboardSecure = false;
new ParseDashboard({
        apps: [{
        }],
        users: [{
        }],
    }, dashboardSecure)
```

**Comment by diego-vieira** [comment]
good point, but once you go on production you should always use https.

Try this tho
https://github.com/ParsePlatform/parse-dashboard/issues/429#issuecomment-228044643
