### ISSUE TITLE
Configure a user to access Parse Dashboard remotely

### ISSUE THREAD

**Issue by kemelzaidan** [parse-community/parse-dashboard#371]
No matter what I do, I always get "Configure a user to access Parse Dashboard remotely".

I am using parse-server 2.2.9 and parse-dashboard 1.0.12. 

i have reviewed my `parse-dashboard-config.json` a thousand times, but it seems fine. The dashboard is running since I see this message, but no matter how I configure the user, it keeps telling me to "Configure a user to access Parse Dashboard remotely". That's my `parse-dashboard-config.json`

```
{
    "apps": [
        {
        "serverURL": "https://my-paas.provider.com.br/parse",
        "appId": "testingApp",
        "masterKey": "mySecretKey",
        "testName": "TEST APP"
        }
    ],
    "users": [
        {
        "user": "kemel",
        "pass": "teste1234"
        }
        ]
}
```
#### Environment Setup

```
$ env
OPENSHIFT_GEAR_MEMORY_MB=1024
XDG_SESSION_ID=c21
HOSTNAME=node91295-parse-server.jelasticlw.com.br
SHELL=/bin/bash
TERM=xterm
HISTSIZE=1000
OPENSHIFT_NODEJS_PATH_ELEMENT=/.node_modules/.bin
OPENSHIFT_TMP_DIR=/opt/nodejs/tmp
OPENSHIFT_REPO_DIR=/opt/repo/
OPENSHIFT_NODEJS_PORT=8080
OLDPWD=/lib/node_modules/parse-dashboard/bin
OPENSHIFT_CLOUD_DOMAIN=node91295-parse-server.jelasticlw.com.br
USER=jelastic
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:
OPENSHIFT_NODEJS_HTTP=0.0.0.0
MAIL=/var/spool/mail/jelastic
PATH=/opt/repo//ROOT/node_modules/.bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin:/opt/repo/versions/0.x_5.x/bin
OPENSHIFT_NODEJS_LOG_DIR=/opt/repo//logs/
PWD=/opt/repo/ROOT
OPENSHIFT_APP_DNS=node91295-parse-server.jelasticlw.com.br
LANG=en_US.UTF-8
OPENSHIFT_NODEJS_IP=0.0.0.0
OPENSHIFT_GEAR_DNS=node91295-parse-server.jelasticlw.com.br
OPENSHIFT_CARTRIDGE_SDK_BASH=/var/lib/jelastic/libs/cartridge-sdk.lib
PS1=\[\033[01;32m\]\u@\h\[\033[01;34m\] \w $\[\033[00m\] 
HISTCONTROL=ignoredups
SHLVL=1
HOME=/opt/repo
OPENSHIFT_NODEJS_PID_DIR=/opt/repo//run/
OPENSHIFT_APP_NAME=nodejs
OPENSHIFT_DATA_DIR=/opt/nodejs/data
LOGNAME=jelastic
OPENSHIFT_GEAR_UUID=28dcb75aa1cf4f5ebc6bc36b90c9b1da
OPENSHIFT_APP_UUID=8759da7ec335417aa47e258c1cee0c5c
OPENSHIFT_NODEJS_VERSION=0.x_5.x
LESSOPEN=||/usr/bin/lesspipe.sh %s
OPENSHIFT_NODEJS_HTTP_PORT=8080
OPENSHIFT_NODEJS_DIR=/opt/repo/
HISTTIMEFORMAT=%F %T 
_=/bin/env
```
#### Logs/Trace

> Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

I have installed the dashboard as a global npm package. How to run `npm run dev`???

**Comment by drew-gross** [comment]
In this case you don't need to use `npm run dev`. Instead, can you open `Parse-Dashboard/app.js` in the location where you installed Parse Dashboard and add some `console.log` statements around line 63?

**Comment by deada92** [comment]
try to output some logs at https://github.com/ParsePlatform/parse-dashboard/blob/master/Parse-Dashboard/app.js#L82 to check if it may also a local request issue..

**Comment by kemelzaidan** [comment]
I'd love to, but I'm using a PaaS provider and I can't change it for global packages since I don't have privileges to. Is there any other way?

**Comment by kemelzaidan** [comment]
Is there a way to pass the user and pass as an argument on the command line?

**Comment by bertalanimre** [comment]
Any update on this? I'm getting the same error when I try to connect to a remote installed server.

**Comment by kanersan** [comment]
I have the same issue too. Any news/progress/solution?

**Comment by fkawasaki** [comment]
It happened the same issue for me and it resolved following flow.
1.update latest parse-dashboard
2.update configure format
->add “apps” field(please refer to ‘Separating App Access Based on User Identity’)
https://github.com/ParsePlatform/parse-dashboard
3.check the file path and start parse-dashboard
->in my case, after update parse-dashboard, the configure file path had changed(version value is from v6.2.0 to v6.9.2)

**Comment by kanersan** [comment]
I was able to get this working. Here is my config info. Some variables are hidden (with ******) of course for security reasons.

var trustProxy = true;
var appId = "********";
var masterKey = "*******";
var dashboard = new ParseDashboard({
  "apps": [
    { 
      "serverURL" : "https://******.******.com/parse",
      "appId": process.env.APP_ID || appId,
      "masterKey": masterKey,
      "appName": process.env.APP_NAME || "bookupapp"
    }
  ],
  "users": [
  	{
  		"user":"kanersan@gmail.com",
  		"pass":"**********"
  	},
  	{
  		"user":"grantarp@yahoo.com",
  		"pass":"**********"
  	}
  ],
  "trustProxy": 1
});

**Comment by a-jiang** [comment]
最近遇到这个问题无论parse-dashboard-config.json 这个设置的多么正确都无法通过域名访问parse dashboard。经过不懈努力，发现使用parse-dashboard --config parse-dashboard-config.json出现错误“your config is missing”。我的parse dashboard是通过npm安装的。我把 parse-dashboard-config.json拷贝到 C:\Users\Administrator\AppData\Roaming\npm\node_modules\parse-dashboard\bin。然后CD到这个目录下，执行parse-dashboard --config parse-dashboard-config.json --allowInsecureHTTP=1，成功了，success!
