### ISSUE TITLE
"Which platforms should be included?" list is empty, audience always 0

### ISSUE THREAD

**Issue by jockegbg** [parse-community/parse-dashboard#380]
When creating a new audience the "Which platforms should be included?" is empty resulting in all conditions returns 0 audience.

In Core -> Browser -> Installation I see all my records and deviceType has correct value.

When I try and send push from API, even though I'm sending to a deviceToken it doesn't get delivered.

What could be the reason?

**Comment by jockegbg** [comment]
I see that it says "No registered devices" but I have over 1000 records in installations. When I go to Send Push from Dashboard I see this message

This notification will be sent to 1028 devices. It will be sent immediately. 

But it says failed when sending no deviceType selected.

**Comment by drew-gross** [comment]
To help us debug this, can you include the exact request and response in Parse Server? (you can see this in the logs using `VERBOSE=1` environment variable)
