### ISSUE TITLE
Two views of User class

### ISSUE THREAD

**Issue by jkassis** [parse-community/parse-dashboard#388]
In the Parse.com hosted version of Dashboard, I see the User class listed twice. One listing reports approx 32k users, as expected. The other shows roughly 302, but seems to page infinitely. I'm wondering if there are some mixed up references here. And I'm worried that this might affect my Parse.com migration.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=2.1.4 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Parse Application ID QdJT3PVnZjCHXkQ6dFnJtY0k872qb6phSJBtEJxw
#### Steps to reproduce

Log in to Developer Console.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by drew-gross** [comment]
Can you post the response to the schemas endpoint? The built in User class is stored as `_User` in the db, and there may be an additional user created class called `User`, you may want to check that.
