### ISSUE TITLE
Blank screen from npm run

### ISSUE THREAD

**Issue by alehkudrevich** [parse-community/parse-dashboard#400]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=2.1.4 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Hello.

When I use **parse-dashboard** all work good. But when I try to use **npm start** server displays blank screen with console error like in [#75](https://github.com/ParsePlatform/parse-dashboard/issues/75)

> npm start --config ./Parse-Dashboard/parse-dashboard-config.json --allowInsecureHTTP=1

**Comment by drew-gross** [comment]
Why do you want to use `npm start` if `parse-dashboard` works fine for you?

**Comment by alehkudrevich** [comment]
Because this problem repeats with another methods. I can't start dashboard with `forever srevice` to autostart with server. Thanks.

**Comment by drew-gross** [comment]
Ah OK. Try `npm run dashboard` instead, or add the dashboard to your own express app.
