### ISSUE TITLE
Upload File Error

### ISSUE THREAD

**Issue by aggarwal23deepak** [parse-community/parse-dashboard#416]
i m not able upload any kind of file through parse dashBoard

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ ] You're running version >=2.1.4 of Parse Server.
- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by cleever** [comment]
Do you have your javascript key set?

If so, I got my file upload working by putting the javascriptKey in the configurations settings.

```
{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "appName": "MyApp"
      "javascriptKey": "javascriptKey"
    }
  ]
}
```

**Comment by kevalshah09** [comment]
I tried adding javascriptKey but file upload still doesn't work for me. I have hosted parse dashboard on heroku . And using mongoDb as backend. Do I need to configure anything else?
