### ISSUE TITLE
User conflict with _User

### ISSUE THREAD

**Issue by robertodias180** [parse-community/parse-dashboard#420]
Dashboard 1.0.14
Server 2.2.13

On PARSE.com i had a table called User (i know it was bad, but it was my first app with parse and i did not knew about _User table). The problem is that on the Parse Dashboard the data from User wont appear, being switched by the _User table data. But if i use the API Console the correct data will appear.

I there any workaround for this?

**Comment by davimacedo** [comment]
I recommend you keep just _User. Try to access mongodb, migrate data from User to _User and delete User collection and from _SCHEMA.

**Comment by robertodias180** [comment]
The problem is that i am currently using PARSE.com and parse server and if i change thing on mongo the users that have the old app version wont be able to connect.
