### ISSUE TITLE
Separating App Access Based on User Identity: Incorrect docummentation

### ISSUE THREAD

**Issue by Pikorua** [parse-community/parse-dashboard#427]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [X] You're running version >=2.1.4 of Parse Server.
- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Setup 2 app and 2 users in parse-dashboard-config.json
#### Steps to reproduce

Read and follow the steps from the documentations: 

> "Separating App Access Based on User Identity
> 
> If you have configured your dashboard to manage multiple applications, you can restrict the management of apps based on user identity.
> 
> To do so, update your parse-dashboard-config.json configuration file to match the following format:
> 
> {
>   "apps": [{"...": "..."}],
>   "users": [
>      {
>        "user":"user1",
>        "pass":"pass1",
>        "apps": [{"appId1": "myAppId1"}, {"appId2": "myAppId2"}]
>      },
>      {
>        "user":"user2",
>        "pass":"pass2",
>        "apps": [{"appId1": "myAppId1"}]
>      }  ]
> }
> The effect of such a configuration is as follows:
> 
> When user1 logs in, he/she will be able to manage appId1 and appId2 from the dashboard.
> 
> When user2 logs in, he/she will only be able to manage appId1 from the dashboard."

When set up based on this, parse dashboard is showing an error "You Don't have any apps" (but that is not the case I actually setup 2 apps and 2 user, if I don't restrict the users and let them both access both apps then I can see those apps.

The information provided regarding the restrictions is incorrect. After some fiddling around it turns out that:

"apps": [{"appId1": "myAppId1"}, {"appId2": "myAppId2"}] and "apps": [{"appId1": "myAppId1"}] are incorrect. 

They should be:

"apps": [{"appId": "myAppId1"}, {"appId": "myAppId2"}] and "apps": [{"appId": "myAppId1"}] 

The doco should then be:

> "Separating App Access Based on User Identity
> 
> If you have configured your dashboard to manage multiple applications, you can restrict the management of apps based on user identity.
> 
> To do so, update your parse-dashboard-config.json configuration file to match the following format:
> 
> {
>   "apps": [{"...": "..."}],
>   "users": [
>      {
>        "user":"user1",
>        "pass":"pass1",
>        "apps": [{"appId": "myAppId1"}, {"appId": "myAppId2"}]
>      },
>      {
>        "user":"user2",
>        "pass":"pass2",
>        "apps": [{"appId": "myAppId1"}]
>      }  ]
> }
> The effect of such a configuration is as follows:
> 
> When user1 logs in, he/she will be able to manage appId1 and appId2 from the dashboard.
> 
> When user2 logs in, he/she will only be able to manage appId1 from the dashboard."
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by diego-vieira** [comment]
@Pikorua a PR is welcomed

**Comment by Pikorua** [comment]
At the risk of sounding stupid, I have no clue how to do that.
It took me already a while to just figure out what you were trying to say...

**Comment by diego-vieira** [comment]
@Pikorua ping me at diego[at]vieira[dot]uk and I'll tell you how to send a PR.
