### ISSUE TITLE
Parse dashboard not loading

### ISSUE THREAD

**Issue by newdev7** [parse-community/parse-dashboard#431]
Hi,
I have deployed the parse server on heroku using the parse-server-example. I want to deploy the parse-dashboard also in the same server.

I tried to install the dashboard locally by using the following command.

`npm install -g parse-dashboard`
`parse-dashboard --appId yourAppId --masterKey yourMasterKey --serverURL "https://appName.herokuapp.com/parse" --appName appName`

When I run this command it says,
The dashboard is now available at http://0.0.0.0:4040/

The dashboard loads when I enter that local host in my browser.

I tried to deploy the dashboard by creating a new project in heroku by following the steps given in the below link.
http://android-kill-the-what.blogspot.in/2016/05/heroku-deploy-parse-dashboard-step.html
The dashboard loads now also when I enter https://appName.herokuapp.com/ in my browser.

I tried to deploy the dashboard in the same server where I deployed the parse-server.

Cloned the parse-server-example project from https://github.com/ParsePlatform/parse-server-example .

In the package.json, I added 'parse-dashboard' as dependency.

```
"dependencies": {
   ...
   "parse-dashboard": "1.0.14"
}
```

In the index.js file, I added the dashboard settings.

```
...
var ParseDashboard = require('parse-dashboard');
...
var dashboard = new ParseDashboard({
  "apps": [
    {   // serverURL, appId, masterKey are same as ParseServer's settings
      "serverURL": "https://appName.herokuapp.com/parse",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "appName": "appName"
    }
  ],
  "users": [
     {
       "user": username,
       "pass": password
     }
   ]
});
...
// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);
...
```

After adding these codes, I ran `npm install` command in terminal.
After that add, commit and pushed to heroku.

The parse-server works but parse-dashboard not loading. 

In Safari, when I enter https://appName.herokuapp.com/ it shows
`I dream of being a website.  Please star the parse-server repo on GitHub!`

But when I enter https://appName.herokuapp.com/dashboard it asks me username and password. After I entered those details, three color balls spins around. Nothing happened after that.

Is there anything am missing?
Thanks.

**Comment by stevecarlton** [comment]
Seeing this issue as well on Heroku but just started to dig around. I am presented with the login and seems like I am validated but just get the three colored ball loading screen.

**Comment by stevecarlton** [comment]
Not sure if this helps or not as I am a hobbyist, but my issue was that I had placed the config file in the wrong place. Once I moved my config file to node_modules/parse_dashboard/Parse-Dashboard then I was able to connect just fine.

**Comment by newdev7** [comment]
@stevecarlton Did you deploy both the parse-server and parse-dashboard in the same server?

The parse-dashboard config file is in the directory node_modules/parse-dashboard/Parse-Dashboard.
Also the dashboard settings was given in the index.js file.

```
|-- home 
|    |-- index.js
|    |-- package.json
|    |...
|    |-- node_modules
|    |    |-- parse-server
|    |    |-- parse-dashboard
|    |    |    |-- parse-dashboard-config.json
|    |    |    |...
|    |    |...
|    |-- public
|    |...
```
This is my project structure. Is your project structure similar to this?

**Comment by 5amfung** [comment]
I also following the instruction on `README.md` to run both Parse Server and Parse Dashboard on the same server/port.  After I go to `/dashboard`, all I see is the 3 bouncing color balls, but if I run the dashboard separate, the dashboard works.  Something is missing.

**Comment by dgsmith** [comment]
I'm having a similar issue, from my heroku logs, it looks like it is requesting the config file? Even though I supplied the settings when created?

```
016-06-30T17:25:26.906803+00:00 heroku[router]: at=info method=GET path="/dashboard/parse-dashboard-config.json" host=grayson-parse-test.herokuapp.com request_id=0e22f176-3fce-4248-a9cf-383076f95742 fwd="50.120.84.136" dyno=web.1 connect=1ms service=3ms status=304 bytes=145
```

* I have both parse-server and parse-dashboard in one heroku app, both as middleware.
* I am *not* using a configuration file, just specifying the configuration in my `index.js` file.
* I do not have a `procfile`.
* I haven't run `npm install` in my heroku/git repo -- I assume heroku does that for me.

**Comment by rhaning** [comment]
My app is hosted on AWS but I had a similar issue of the dashboard not loading and just showing the bouncing color balls. I added the "javascriptKey" and "restKey" to my config and that fixed it for my setup.

**Comment by harryjamesuk** [comment]
Also had this issue - seems passing the parameters did not work and I had to manually enter them in **parse-dashboard-config.json** so that the dashboard loaded up correctly.

**Comment by newdev7** [comment]
I removed all the unwanted dependencies in the package.json and unwanted code in the index.js file and tested it locally. Now its working. Just check your index.js file thoroughly. There may be an error in index.js file that will stop loading the parse-dashboard.

**Comment by 5amfung** [comment]
I finally got it working by simply specifiying all the other keys even though I don't use them.  I didn't use `parse-dashboard-config.json` neither.

```
var dashboard = new ParseDashboard({
    apps: [
        {
            serverURL: SERVER_URL,
            appId: APP_ID,
            masterKey: MASTER_KEY,
            javascriptKey: "NOT USED",
            restKey: "NOT USED",
            appName: APP_NAME,
            production: true
        }
    ],
    users: [
        {
            user: 'admin',
            pass: 'password'
        }
    ]
});

// ...
app.use('/dashboard', dashboard);
```

**Comment by natario1** [comment]
Same here.

**Comment by natario1** [comment]
I have spent some time getting into this issue. In my case, dashboard gets stuck at the rolling balls. Then, after about 2 minutes, it finally gets in, but saying “server not reachable: unable to connect to server”. There must be some issue with the connection to my parse-server, which is strange because I can connect to it from the Android SDK.

I could not find anything wrong in app.js or index.js. app.js is called with the right serverURL, and when I try to visit the dashboard, parse-dashboard-config.json is requested and again the right serverURL is returned.

Then we probably go down to dashboard.bundle.js but that is minified and I can’t see anything.
@drew-gross could you point me in the right direction? 

parse-server also is not logging anything about it.

**Comment by lebj08** [comment]
Hi All

Im quite new to all of this. I followed this tutorial:
 _https://www.codementor.io/nodejs/tutorial/deploy-parse-dashboard-on-heroku_
But I am always getting an 'Application Error'. The logs spit out this:

_2016-10-25T15:06:58.667178+00:00 heroku[web.1]: State changed from crashed to starting
2016-10-25T15:07:00.162760+00:00 heroku[web.1]: Starting process with command `./node_modules/.bin/parse-dashboard --config ./parse-dashboard-config.json --allowInsecureHTTP`
2016-10-25T15:07:02.418276+00:00 app[web.1]: undefined:6
2016-10-25T15:07:02.418292+00:00 app[web.1]:       "appId": “my app”
2016-10-25T15:07:02.418293+00:00 app[web.1]:                ^
2016-10-25T15:07:02.418294+00:00 app[web.1]: 
2016-10-25T15:07:02.418295+00:00 app[web.1]: SyntaxError: Unexpected token “
2016-10-25T15:07:02.418295+00:00 app[web.1]:     at Object.parse (native)
2016-10-25T15:07:02.418296+00:00 app[web.1]:     at exports.parse (/app/node_modules/rc/lib/utils.js:15:17)
2016-10-25T15:07:02.418297+00:00 app[web.1]:     at addConfigFile (/app/node_modules/rc/index.js:31:20)
2016-10-25T15:07:02.418297+00:00 app[web.1]:     at module.exports (/app/node_modules/rc/index.js:47:20)
2016-10-25T15:07:02.418298+00:00 app[web.1]:     at module.exports (/app/node_modules/registry-url/index.js:3:24)
2016-10-25T15:07:02.418299+00:00 app[web.1]:     at module.exports (/app/node_modules/package-json/index.js:10:15)
2016-10-25T15:07:02.418300+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/parse-dashboard/Parse-Dashboard/app.js:11:1)
2016-10-25T15:07:02.418300+00:00 app[web.1]:     at Module._compile (module.js:413:34)
2016-10-25T15:07:02.418301+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:422:10)
2016-10-25T15:07:02.418301+00:00 app[web.1]:     at Module.load (module.js:357:32)
2016-10-25T15:07:02.546875+00:00 heroku[web.1]: State changed from starting to crashed
2016-10-25T15:07:02.509687+00:00 heroku[web.1]: Process exited with status 1_,

Please help if you can.

**Comment by steven-supersolid** [comment]
Can you post your parse-dashboard-config.json file?

**Comment by lebj08** [comment]
Hi there, in follow up to the my previous comment, this is the parse dashboard config file JSON


{
  "apps": [
    
    {
      "serverURL": "https://myapp.herokuapp.com/parse",
      "appId": “appId”,
      "masterKey": “mKey”,
      "appName": "My Parse Server App"
    }
  ],
  "users": [
    {
      "user":"user1",
      "pass":"pass"
    }
  ]
}

**Comment by spagnolodesign** [comment]
Hello,

I'll might find a solution about it! 
You should start the Parse sever and the Dashboard on the same port by allowing non secure HTTP request. Here an example:

```
var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var ParseDashboard = require('parse-dashboard');

var path = require('path');

var allowInsecureHTTP = false

var api = new ParseServer({
   //YOUR PARSE SETTINGS
});
var dashboard = new ParseDashboard({
 //YOUR DASHBOARD SETTINGS
}, allowInsecureHTTP);   

var app = express();

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

// Serve dashboard
app.use('/dashboard', dashboard);
```

In case was very helpful look at the console when the loader screen was keep moving. I found the answer by looking the errors.
