### ISSUE TITLE
Dashboard is blank without mountPath

### ISSUE THREAD

**Issue by majidhassan** [parse-community/parse-dashboard#440]
Hello,

I'n trying to run parse-dashboard using SSL. I use the following command:

`parse-dashboard --appId <my-app-id> --masterKey <my-master-key> --serverURL <my-server> --port 4040 --sslKey <path-to-ssl-key> --sslCert <path-to-ssl-cert> --appName myApp`

And I get the log message that:

`The dashboard is now available at https://0.0.0.0:4040/`

On my Nginx sites-enabeld/default file I have the following proxy pass for /dashboard:

`proxy_pass https:/localhost:4040/;`

Yet, when I go to https://mydomain/dashboard I get a blank page. The browser correctly recognizes the tab as "Parse Dashboard", but I only get the blank screen.

When I run the command with `--mountPath /dashboard` and change my Nginx proxy pass accordingly it works.

Any ideas, what might be going wrong?
#### Environment Setup

parse-server: 2.2.14
parse-dashboard: 1.0.14
machine: Ubuntu 14.04 on DigitalOcean

**Comment by RafaRuiz** [comment]
Same problem here

**Comment by majidhassan** [comment]
@RafaRuiz I don't recall what exactly was causing this issue. Could you share your nginx conf, index.js or ecosystem.json?

**Comment by seeya** [comment]
Set the mountPath parameter to /dashboard and it'll fix the relative path issue you're facing. It'll be better if you can show any error logs using chrome developer tools.

**Comment by timam** [comment]
Today I faced the same issue fixed with following nginx configuration

server {
    listen 80;
    server_name dashboard.example.com;

        location / {
                proxy_pass http://localhost:4040;
        }

}
