### ISSUE TITLE
Parse Logs

### ISSUE THREAD

**Issue by pixelbendr** [parse-community/parse-dashboard#441]
How do I see my error logs on the dashboard. My parse server is hosted on Heroku? Regards.

**Comment by grassland-curing-cfa** [comment]
+1 Same here.
My Parse server is also deployed on Heroku. The Dashboard run locally is unable to show Info logs or Error logs. Is the info/error log shown on the Dashboard supposed be the same as on Heroku's Log console?

**Comment by ritterb82** [comment]
+1 Same question.

My Parse server is deployed on AWS.
