### ISSUE TITLE
Support of rows/paging function on Dashboard

### ISSUE THREAD

**Issue by grassland-curing-cfa** [parse-community/parse-dashboard#448]
Any roadmap for having the "rows/page" function on Dashboard?
Also, the Dashboard does not tell how many rows are currently shown. It's also very difficult to tell how many rows are returned from a query as well.

**Comment by flovilmart** [comment]
There is no roadmap for that and I believe the dashboard is implemented with infinite paging. So the page size don't really matter in that case as there is no 'page'.
What did you had in mind?

**Comment by grassland-curing-cfa** [comment]
I believe it'd be really useful that it is able to show the number of rows returned from a query that one runs off the "Filter" command. At the moment there is no way to tell exactly how many rows are returned if the number is extremely large.

**Comment by flovilmart** [comment]
That Would imply running a count on those queries; but that's feasible. We welcome pull requests if you feel you want that feature sooner than later.

**Comment by grassland-curing-cfa** [comment]
Any update or work progress on this issue? Thanks.

**Comment by alvaroOSA** [comment]
I propose to close this issue since the infinite paging is the accepted design, and follow the Count feature suggestion in issue #334

**Comment by pablo-gonzalez** [comment]
Hi. I have recently migrated my app from Parse. Thank you for your great work.

I agree that it would be very useful to have at least the row count when you filter a collection using conditions.
