### ISSUE TITLE
Heroku Procfile uses incorrect paths

### ISSUE THREAD

**Issue by benpackard** [parse-community/parse-dashboard#459]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [x] You're running version >=2.1.4 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

When deploying `parse-dashboard` to Heroku using the included `Procfile`, the Heroku logs report 
`./node_modules/.bin/parse-dashboard: No such file or directory`. Indeed, the correct location seems to be `bin/parse-dashboard`.

Next, Heroku logs that `Your config file is missing. Exiting.`. The `Procfile` is using `./parse-dashboard-config.json` but the correct location is seemingly `Parse-Dashboard/parse-dashboard-config.json`

Disclosure: I know next to nothing about node, Procfiles, or Heroku. But these two changes to the `Procfile` seems to have resolved my issues deploying the dashboard.

If someone can confirm that what I am doing is correct I will create a PR with the path changes.

**Comment by drew-gross** [comment]
Seems legit to me.

**Comment by MinkiPan** [comment]
Hi, I have the same issue on heroku,
bash: ./node_modules/.bin/parse-dashboard: No such file or directory
I tried the solution approach above but still doesn't work, can someone explain me why he cant find the node modules?
