### ISSUE TITLE
PFFile profile image name won't save correctly, Missing PFFiles after migration. Parse Dashboard Naming bug

### ISSUE THREAD

**Issue by alexrmacleod** [parse-community/parse-dashboard#464]
I save a user with a profile picture like so 

`

```
let imageData: NSData = UIImagePNGRepresentation(profilePictureImageView.image!)!
        let profilePicture: PFFile = PFFile(name: "profile.png", data: imageData)!
        self.user.profilePicture = profilePicture

        self.user.saveInBackground().continueWithBlock({
            (task: BFTask!) -> AnyObject! in
            if task.completed {
```

`

But in the parse dashboard it shows up like the below screenshot, as you can see 2 user profile_pictures are named 'ile.png' INCORRECT.... The last user_name and profile_picture was from before I migrated to parse server. Strangely all the users created before the migration to parse server, their profile_pictures are missing. And the new profile pictures aren't named correctly. 

![screen shot 2016-07-15 at 12 30 14 am](https://cloud.githubusercontent.com/assets/7895493/16847475/cd13bc6c-4a23-11e6-803f-462453d447e6.png)

Also on my model when I get the image from newly created users post the parse server migration the below does work. So maybe theres a PFFile naming bug on the new parse dashboard. 

`

```
      var profilePicture: PFFile {
        get {
          return objectForKey("profile_picture") as! PFFile
        }

        set {
          setObject(newValue, forKey: "profile_picture")
        }
      }
```

`

**Comment by phalladar** [comment]
I'm also seeing this.
