### ISSUE TITLE
Object not found

### ISSUE THREAD

**Issue by alex290796** [parse-community/parse-dashboard#474]
#### Environment Setup

windows server 2012 r2 with mongodb 3.0 parse-server 2.2.7
#### Steps to reproduce

I launch a mongoimport.exe --db dev -u myuser -p mypass -c mycollection --type csv --headerLine --file file/path.csv
it imports the file with success, but when i try to modify an object i get an error 101 object not found (in Xcode, in rest api and in dashboard). Also if I try to filter by an objectId it found nothing

p.s I noticed that when I mongoimport it make a objectId with more than 10 characters.

Sorry if i wrong something i'm new here.

**Comment by genhau** [comment]
I encountered similar error when importing backup data directly into mongodb. I managed to resolve this issue by adding _id field into each record with same value as objectId, ex:

{ "authData": { "bcryptPassword": "$2a$1", "createdAt": "2016-06-21T06:42:34.339Z", "membershipStatus": "regular", "objectId": "3ZtUTOQWqW", "sessionToken": "CjyW", "updatedAt": "2016-06-26T08:40:56.011Z", "username": "LNt5x5NfpYKha4FjAHBHNaQfT" }
becomes
{ "authData": { "bcryptPassword": "$2a$1", "createdAt": "2016-06-21T06:42:34.339Z", "membershipStatus": "regular", "_id": "3ZtUTOQWqW", "objectId": "3ZtUTOQWqW", "sessionToken": "CjyW", "updatedAt": "2016-06-26T08:40:56.011Z", "username": "LNt5x5NfpYKha4FjAHBHNaQfT" }

after inserting the updated data into mongodb, everything works fine on parse dashboard.

**Comment by flovilmart** [comment]
@genhau how did you import the data to Mongo?

**Comment by genhau** [comment]
I used mongoimport to import my json file.

**Comment by flovilmart** [comment]
That’s what I suspected, as you’ll probably notice, authData, createdAt, updatedAt, ACL etc... are now malformed and unusable by the client, the data structure in mongoDb is slightly different from the one in a JSON file.

**Comment by genhau** [comment]
I couldn't find any better way to import my data now. Is there any other way/tools available to import my data? I could have missed some other default schema as well, like _PushStatus, which seems to be causing problem when sending push notification.

**Comment by genhau** [comment]
my apology, the table exists, should be some other problems.

**Comment by mohanadshaban** [comment]
Same Issue here ! 
so how colud i migrate my old database ? if mongoimport will malform my data !
