### ISSUE TITLE
Getting "Unable to connect to server" Blocked by client.

### ISSUE THREAD

**Issue by ryderjack** [parse-community/parse-dashboard#479]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ YES ] You're running version >=2.1.4 of Parse Server.
- [ YES ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Successfully installed the latest version of parse-dashboard, however, I'm getting the "unable to connect to server" error on the dashboard. I'm also getting ERR_BLOCKED_BY_CLIENT in the console. - see screenshot

<img width="1275" alt="screen shot 2016-07-26 at 15 56 12" src="https://cloud.githubusercontent.com/assets/10326229/17143136/57f9e2c8-534a-11e6-96af-417d2b29b864.png">

I'm starting Parse Dashboard using the following:

`parse-dashboard --appId "MYAPPID" --masterKey "MYMASTERKEY" --serverURL "http://parseserver-3q4w2-env.us-east-1.elasticbeanstalk.com/parse" --appName bump
`

Any ideas on where I'm going wrong?

Cheers

**Comment by Rioner123** [comment]
Do you have an ad blocker? Try turning it off

**Comment by rahilsharma** [comment]
You need to put allowInsecureHTTP = true , if ur backend does not support https
