### ISSUE TITLE
Cant add any values into custom audience for push

### ISSUE THREAD

**Issue by gateway** [parse-community/parse-dashboard#481]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [ x] You're running version >=2.1.4 of Parse Server.
- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Environment Setup

Heroku 
#### Steps to reproduce

API Send push, select iOS, condition = user -> equals --> cant add anything into the value box

![image](https://cloud.githubusercontent.com/assets/519563/17195986/3d694940-5416-11e6-99e6-5cbc9cfa3e3b.png)
#### Logs/Trace

Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by gateway** [comment]
Any thoughts on a fix for this?

**Comment by MobileVet** [comment]
This is interesting because both `objectId` and `appName` allow entry of an *equals* clause... assuming this is some kind of issue with a custom property not registering its type

**Comment by gateway** [comment]
Yea, the form entry box element seems to be empty.. I havent had any time to look at it :(

**Comment by shahas1** [comment]
Hi all, any updates on this issue?

**Comment by NatanRolnik** [comment]
@gateway is this still an issue?
