### ISSUE TITLE
Access parse-dashboard logs when in used as a middleware?

### ISSUE THREAD

**Issue by mbt-jeremy-r** [parse-community/parse-dashboard#484]
#### Environment Setup

ubuntu 5.3.1-14 / Linux 4.4.0-28-generic in a VirtualBox setup.
node v.5.11.1
parse v3.0.5
parse-dashboard npm module v1.0.15
nginx 1.10.0
#### Steps to reproduce

Create a express app which authentify and protect parse-dashboard middleware from unauthorized access.
When logged in and accessing the dashboard, I am stuck on the three bublle loading screen.

As I do not know if the problem lies in parse-dashboard, nginx, parse-server, my code or a combination of thoses, I d like to be able to see the logs of parse-dashboard.

Is such a option exist?

**Comment by bohemima** [comment]
Start with looking at the browser console for any errors.
