### ISSUE TITLE
Missing parse.com feature: show errors in dashboard

### ISSUE THREAD

**Issue by rihadavid** [parse-community/parse-dashboard#492]
If I edit a row in parse dashboard and my cloud code beforeSave hook does not allow this operation and throws exception for this attempt, I don't have any visual feedback of the error.

I can edit 10 rows and it seems like the edit was successful, but then I leave and come back later and see that the update did not happen.

I can find the errors logged in logs, but on parse.com it used to show the error message right away in the dashboard when I attempted the forbidden action - and I knew that the update was unsuccessful. Now I don't know there is an error and I assume that it was successful.

Would it be possible to implement this "instant dashboard errors" in parse server dashboard? Or at least, don't show the row updated if the update was unsuccessful, keep the previous values?

**Comment by markmssd** [comment]
In your cloud code, before returning the response, you could try to log the error, or even mail it to yourself, so you will know exactly what is not working.

As for the rest, it may be a bug it may not. You can also send us a code snippet of your cloud code, maybe someone of the community will be able to better help.

**Comment by rihadavid** [comment]
I think you don't fully understand what I mean - if I purposely have `response.error()` or `throw "Forbidden action"` in beforeSave hook to disable certain edit actions on the object, the dashboard does not visualy reflect this and it looks like the edit was successful. Even if I edit many rows, all of them look successfully edited until I refresh the table.

In the original parse.com dashboard (the older, I newer used the newer), it always showed the error right in the dashboard and the row visually reverted back to the state before the forbidden update.

**Comment by natanrolnik** [comment]
This was implemented in #718 and is available in the latest version.
