### ISSUE TITLE
Suggestion for dashboard authentication

### ISSUE THREAD

**Issue by kajensen** [parse-community/parse-dashboard#522]
I think there should be a way to have some type of custom defined authentication (instead of static user/pass dictionary passed on instantiation). For example, if a website is built on top of the parse-server with logins and pfusers, it would be helpful to check if the current logged in user is an "admin" and grant them access to the dashboard.

**Comment by araskin** [comment]
I was just working on the same issue today. Nice to see I am not the only one. 

The only issue I see with what you suggested is that you need the dashboard in order to create an admin. Unless you do this programmatically? So you need an admin user in order to log in and create the admin user!

**Comment by araskin** [comment]
Also this: https://github.com/ParsePlatform/parse-dashboard/issues/506

**Comment by nyxee** [comment]
looks like we have to give up on the proper https, yeah?

**Comment by flovilmart** [comment]
@nyxee you can very well contribute to the project as well if you feel more features should be developed!

**Comment by nyxee** [comment]
I will. I am currently not profficient with JavaScript. When I'm done, will be contributing to the much needed https.

**Comment by nyxee** [comment]
On studying the index.js file, i saw these lines:

```
rogram.option('--allowInsecureHTTP [allowInsecureHTTP]', 'set this flag when you are running the dashboard behind an HTTPS load balancer or proxy with early SSL termination.');
program.option('--sslKey [sslKey]', 'the path to the SSL private key.');
program.option('--sslCert [sslCert]', 'the path to the SSL certificate.');
program.option('--trustProxy [trustProxy]', 'set this flag when you are behind a front-facing proxy, such as when hosting on Heroku.  Uses X-Forwarded-* headers to determine the client\'s connection and IP address.');
```

but I havent see a way of using them well.

**Comment by flovilmart** [comment]
yes options are here, and also, you can run your parse-dashboard behind a reverse proxy so node doesn't need to handle HTTPS itself

**Comment by nyxee** [comment]
I am already running behind a reerse proxy (nginx), i had been running without fulfilling those options. so, using 
```baash
parse-server --allowInsecureHTTP AAA --sslKey  /path/to/key \
     --sslCert  /path/to/cert --trustProxy  BBB
```
is all we have to do, yeah?
how do I fill in the AAA and BBB please or which one should be blank in case i misunderstood something..

**Comment by flovilmart** [comment]
In this case https should probably only be between your clients and nginx, not nginx and parse-server
