### ISSUE TITLE
When appName has a '#', dashboard doesn't work.

### ISSUE THREAD

**Issue by yomybaby** [parse-community/parse-dashboard#529]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!
- [O] You're running version >=1.0.18 of Parse Dashboard.
- [O] You're running version >=2.2.18 of Parse Server.
- [O] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
#### Steps to reproduce
1. make config.json.
   Make sure appName has a '#' letter.

```
{
  "apps": [
    {
      "serverURL": "https://api.server.com/parse",
      "appId": "myappid",
      "masterKey": "mymasterkey",
      "appName": "#[REAL] Parse",
      "production": true
    }]
}
```
1. run dashboard `parse-dashboard --config config.json`
2. click your "#[REAL] Parse" app on your dashboard app list.

BUT, it doesn't work. there is no error.

**Comment by timpler** [comment]
I think it's quite normal to assume that name and slug should not include special characters.

**Comment by gowridev** [comment]
its doesn't even takes spaces

**Comment by flovilmart** [comment]
Spécial chars are not supported like # and ? As the app name is not encoded. Does someone want to take a knock at it?

**Comment by dvanwinkle** [comment]
@flovilmart Would the better solution be to not allow the `appName` to include these characters or to support them?

**Comment by flovilmart** [comment]
We could do that too. I don't have a strong opinion on that one.
