### ISSUE TITLE
Delete row does nothing

### ISSUE THREAD

**Issue by agordeev** [parse-community/parse-dashboard#531]
Dashboard version 1.0.18. When I select a row and press "Delete row" nothing is happening.
Browser: Firefox 48.0.1, JS enabled.

**Comment by zouzoux** [comment]
Same here!

**Comment by andrew8712** [comment]
Browser request:
 
{"requests":[{"method":"DELETE","path":"/parse/aviotrader/classes/Image/IpbAnhMNaS","body":{}}],"_ApplicationId":"xxxx","_ClientVersion":"js1.6.14","_MasterKey":"xxxx","_InstallationId":"f12ac580-4690-2f04-ed7e-f834d662b129"}

Response:

{"code":107,"error":"cannot route DELETE /aviotrader/classes/Image/IpbAnhMNaS"}

**Comment by softmastx** [comment]
Same here!  Parse Dashboard Version **1.0.19**

> PROBLEM ONLY WHEN DELETING!!

code: 107,
message: 'cannot route batch path /test/classes/Publications/g2kSNKBIoH'

**Comment by coryshaw** [comment]
Same here, seems to have to do with using nginx and the mount path.

parse server is mounted behind a local url:
http://dev-parse-server:1337/parse

and nginx exposes it to clients via
https://mydomain.com/p/dev/

**Comment by rjpalermo1** [comment]
This is an old issue not sure if been fixed but have same problem.  on 1.20.  PM2 log on my server reports:

`1|npm  | error: cannot route batch path /xxxxxxxxx-sandbox.com/api/api/classes/Phones/UAxPKoNJ62404O99 code=107, message=cannot route batch path /app4app.payment-sandbox.com/api/api/classes/Phones/UAxPKoNJ62404O99` 

Please note the double `api/api` 

Creating objects and classes no problems.  Just delete is getting the 107 error

**Comment by flovilmart** [comment]
Do you want to have a look? Seems that the fix should be feasible with this info

**Comment by rjpalermo1** [comment]
wow that was fast!  You need something from me?

**Comment by flovilmart** [comment]
If you want to have a look, i’ll Gladly review the PR and merge the fix :)

**Comment by rjpalermo1** [comment]
Ah...no I am sorry, I have no coding skills.  Working on it, though.  I will take a look.  I have a couple js guys I will see if I can break them free to take a look on Monday.  I will reply if I get anything.   Thanks man....

**Comment by flovilmart** [comment]
You found the issue, that’s half of the work :)

**Comment by rjpalermo1** [comment]
Ok I have a local setup exactly the same that deletes rows no problem.  It is my remote server (Nginx) giving the problems.  Here is my 

```
server {

        server_name app4app.payment-sandbox.com www.app4app.payment-sandbox.com;

        root /home/admin01/server/public;
        index index.html index.htm;

        location /api {

            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-NginX-Proxy true;
            proxy_pass http://localhost:4444;
            proxy_ssl_session_reuse off;
            proxy_set_header Host $http_host;
            proxy_redirect off;

         #    proxy_pass http://localhost:4444/;
         #    proxy_http_version 1.1;
         #    proxy_set_header Upgrade $http_upgrade;
         #    proxy_set_header Connection 'upgrade';
         #    proxy_set_header Host $host;
         #    proxy_cache_bypass $http_upgrade;
        }
```

The location `api` is my mountpath.  Like I said only double the mountpath on DELETE.  POST and PUT have no problems.  Hope that helps.

**Comment by flovilmart** [comment]
It’s possible that your remote dashboard isn’t at the right version. What version is it?

**Comment by rjpalermo1** [comment]
1.2.0 did an npm -g install yesterday using terminal to launch dashboard.  Same parse-server 2.82 code on local and remote.  Only difference is web server nginx on remote (digital ocean).

- RP

**Comment by flovilmart** [comment]
I don't see how nginx could be the culprit as you mentioned all other routes work properly.

**Comment by flovilmart** [comment]
Glad you found it!
