### ISSUE TITLE
Missing bundles / parse-dashboard not working

### ISSUE THREAD

**Issue by mohannad-abwah** [parse-community/parse-dashboard#545]
I've been trying to get parse-dashboard running on Azure for a few days now with no luck. I get an empty white page. After looking into it a little bit more it seems it's not set up correctly as the entire bundles folder is missing in wwwroot/Parse-Dashboard/public.
#### Environment Setup / repro steps
1. Go to Azure portal
2. Deploy a new web app
3. Go to Deployment options
4. Hook it up to this repo directly using external repository
5. Add the following environment variables in Application Settings:
   PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: 1  
   PARSE_DASHBOARD_SERVER_URL: <server URL>  
   PARSE_DASHBOARD_MASTER_KEY: <master key>  
   PARSE_DASHBOARD_APP_ID: <app id>  
   PARSE_DASHBOARD_APP_NAME: <app name>  
   PARSE_DASHBOARD_USER_ID: "user1"  
   PARSE_DASHBOARD_USER_PASSWORD: "pass"
6. Restart

Try it here: [http://brokenparsetest.azurewebsites.net/](http://brokenparsetest.azurewebsites.net/)
(don't worry that's just a test server with no important information whatsoever)
#### Logs/Trace

It says deployment went fine. In fact even the request for the dashboard.bundle.js returns a 200, but since the file doesn't exist the content doesn't make any sense. It's actually identical to the HTML that comes back, which doesn't work.

If I go into the App Service Editor and run "npm run dev" in the console manually I get this:

```
\> npm run dev

> parse-dashboard@1.0.18 dev D:\home\site\wwwroot
> node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch


D:\home\site\wwwroot\Parse-Dashboard\index.js:10
const path = require('path');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
'webpack' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\0.10.29\\node.exe" "D:\\Program Files (x86)\\npm\\3.9.5\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v0.10.29
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! parse-dashboard@1.0.18 dev: `node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-dashboard@1.0.18 dev script 'node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-dashboard package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./Parse-Dashboard/index.js & webpack --config webpack/build.config.js --devtool eval-source-map --progress --watch
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-dashboard
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-dashboard
npm ERR! There is likely additional logging output above.
```

**Comment by nyxee** [comment]
please people, is there no way of hacking this?
I see no complaints n this issue for 2017.
did people give up on Parse?

**Comment by flovilmart** [comment]
```
'webpack' is not recognized as an internal or external command,
operable program or batch file.
```

Seems that either web pack is not installed, npm install hasn't been run or else...
