### ISSUE TITLE
unable to filter by boolean field in the installation table

### ISSUE THREAD

**Issue by Francesca85** [parse-community/parse-dashboard#581]
Hi,
we noticed that is not possible to target a push by a boolean field of the installation table via dashboard.
To be more specific, we run a freemium app for which we save on parse the information about subscription status with a column "subscribed" accepting"true" or "false" as values.
We wanted to send a push to not subscribed users but when we select the filter option
installation condition > subscribed > equals to
a drop down menu appears where is not possible to select anything.

Thanks

**Comment by marcospolanco** [comment]
@Francesca85 where you able to solve this? I am having the same experience in dashboard.parse.com.

**Comment by Francesca85** [comment]
Unfortunately no, we were not able to solve it

**Comment by mrmarcsmith** [comment]
This is a problem for us too! Please remove /wontfix as it's important this is fixed.

**Comment by dplewis** [comment]
@mrmarcsmith Would you like to do a PR to fix the issue?

**Comment by alencarlucas** [comment]
Guys, I sent a [PR](https://github.com/parse-community/parse-dashboard/pull/1221) to fix this. Can we close the issue?
