### ISSUE TITLE
Editing an array of dates converts these to an array of Strings

### ISSUE THREAD

**Issue by glentregoning** [parse-community/parse-dashboard#590]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.19 of Parse Dashboard.

- [X] You're running version >=2.2.24 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.2.24
Parse Dashboard 1.0.19

#### Steps to reproduce

1. Add an object that includes an array of Dates to parse-server using something other than the dashboard. E.g. via CURL:
```
curl -X POST -H "X-Parse-Application-Id: <your-app-id>"\
 -H "Content-Type: application/json" \
 -d '{"dates": [{ "__type": "Date", "iso": "2013-11-14T07:37:49.838Z" }] }' http://localhost:1337/parse/classes/TestObject/
```

2. Open up the parse dashboard, go to Browse, select 'TestObject', then double click on the 'dates' row entry.

Observe:

Dashboard makes the following request to the database updating the record with an array of strings instead of dates:
E.g. (taken from verbose parse server logs)

```
verbose: REQUEST for [PUT] /parse/classes/TestObject/5QtnjZmFnC: {
  "dates": [
    "2016-11-14T07:37:49.838Z"
  ]
} method=PUT, url=/parse/classes/TestObject/5QtnjZmFnC, host=localhost:1337, connection=keep-alive, content-length=248, origin=http://localhost:4040, user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36, content-type=text/plain, accept=*/*, referer=http://localhost:4040/apps/App/browser/TestObject, accept-encoding=gzip, deflate, br, accept-language=en-US,en;q=0.8, dates=[2016-11-14T07:37:49.838Z]
verbose: RESPONSE from [PUT] /parse/classes/TestObject/5QtnjZmFnC: {
  "response": {
    "updatedAt": "2016-11-17T06:24:42.619Z"
  }
} updatedAt=2016-11-17T06:24:42.619Z
```

Expected:
You should be able to edit an array of dates without it corrupting the structure. 

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by hipwelljo** [comment]
I too see this issue. Tripped me up for a long time!
