### ISSUE TITLE
 Uncaught SyntaxError: Unexpected token < login:1

### ISSUE THREAD

**Issue by lblfantasy** [parse-community/parse-dashboard#593]
And when I click on login:1 I get this:

<!DOCTYPE html>
      <head>
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico" />
        <base href="/"/>
        <script>
          PARSE_DASHBOARD_PATH = "/";
        </script>
      </head>
      <html>
        <title>Parse Dashboard</title>
        <body>
          <div id="login_mount"></div>
          
          <script id="csrf" type="application/json">"UyutJVez-y9abysuhJHFIWG_XeQ8vqod3kjY"</script>
          <script src="/bundles/login.bundle.js"></script>
        </body>
      </html>

**Comment by jaimeagudo** [comment]
duplicated of https://github.com/ParsePlatform/parse-dashboard/issues/201

**Comment by f0ster** [comment]
This is not fixed @jaimeagudo by https://github.com/ParsePlatform/parse-dashboard/issues/201

Steps to reproduce,
 - use parse-server sample project
 - add parse dashboard to package.json 
`       "parse-dashboard": "git://github.com/ParsePlatform/parse-dashboard.git",`
- modify index.js to use parse dashboard on same express app
`var dashboard = new ParseDashboard({
  "apps": [
    {
      "serverURL": publicServerUrl,
      "appId": appId,
      "masterKey": masterKey,
      "appName": "whatever"
    }
  ]
}, true);

app.use('/dashboard', auth, dashboard);`


This will reproduce error, and conflicts with https://github.com/ParsePlatform/parse-dashboard/issues/201 resolution which says this is a non issue with npm install.  

Am I missing something, shouldn't this work with `npm install` off of the master branch of `parse-dashboard` ?
