### ISSUE TITLE
Parse dashboard deploying to amazon AWS - Elastic Beanstalk

### ISSUE THREAD

**Issue by kanersan** [parse-community/parse-dashboard#594]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.19 of Parse Dashboard.

- [ ] You're running version >=2.2.24 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Below is my error log. I actually ran npm uninstall parse-dashboard before deploying to amazon but the server still doesn't seem to deploy properly with my current configuration. And I changed a bunch of stuff over time that I don't recall exactly what but for instance, I am using the S3 Adapter so setting that up was kinda painful as well since I'm not a server dev.

I found this post basically telling me it's not a good idea to upload parse dashboard, so I will create a dashboard locally that connects to my server sitting on amazon. I am able to run parse server locally with a dashboard attached to it. But when i upload that exact config to amazon, it fails. Health of server becomes "degraded" whatever the fuck that means. I wish amazon used better and easier terminology for their stuff... For example what kinda name is Elastic Beanstalk???? Anyway, here are the logs:

-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the parse-server-example@1.4.0 start script 'node index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the parse-server-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs parse-server-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls parse-server-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log

> parse-server-example@1.4.0 start /var/app/current
> node index.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'parse-dashboard'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/app/current/index.js:5:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Linux 4.4.23-31.54.amzn1.x86_64

There is more to it but i figure this is the important part. I dunno why it still finds this after running "npm uninstall parse-dashboard".

Thanks in advance.

**Comment by kanersan** [comment]
And another error log but I haven't actually installed parse-dashboard at all in this instance:
/var/log/nodejs/nodejs.log
-------------------------------------
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log

> my-parse-server@1.0.1 start /var/app/current
> node index


/var/app/current/node_modules/parse-server/lib/requiredParameter.js:8
  throw errorMessage;
  ^
You must provide a serverURL!

npm ERR! Linux 4.4.23-31.54.amzn1.x86_64
npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.9.1-linux-x64/bin/npm" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! my-parse-server@1.0.1 start: `node index`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-parse-server@1.0.1 start script 'node index'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the my-parse-server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs my-parse-server
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls my-parse-server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/app/current/npm-debug.log

> my-parse-server@1.0.1 start /var/app/current
> node index


/var/app/current/node_modules/parse-server/lib/requiredParameter.js:8
  throw errorMessage;
  ^
You must provide a serverURL!

Any help is appreciated.

**Comment by kanersan** [comment]
And this is my config of index.js:



var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var serverURL = "https://api.parse.com/1";
var databaseUri = 'mongodb://...';
var appId = '...';
var masterKey = '...';

// nconf.argv().env().file({file: './config/default.json'});

// Specify the connection string for your mongodb database
// and the location to your Parse cloud code
var api = new ParseServer({
  databaseURI: databaseUri,
  appId: appId,
  masterKey: masterKey,
  serverURL : serverURL
});

var app = express();

// Serve the Parse API on the /parse URL prefix
app.use('/public', express.static(path.join(__dirname, '/public')));

// Hello world
app.get('/', function(req, res) {
  res.status(200).send('Express is running here.');
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
  console.log('parse-server-example running on port %s', port);
});

ParseServer.createLiveQueryServer(httpServer);

**Comment by kanersan** [comment]
I'm honestly ready to give up on the dashboard however, I can't even upload my server and my previous work without the amazon server degrading now. Help please?

**Comment by flovilmart** [comment]
I'm not sure where to start. First, can you run everything correctly on a local machine?

**Comment by kanersan** [comment]
Not everything everything for example, images from my new S3 on amazon aren't loading properly even though I added 
"filesAdapter: new S3Adapter(
    S3_ACCESS_KEY,
    S3_SECRET_KEY,
    "bookupapp",
    {directAccess: true}
  ),"

But facebook login and actually fetching objects from Parse running on my local machine works. So yes, things are actually working.

But when I deploy this config to amazon with EB, it's always degraded with the errors I posted above :( Any thoughts?

If I don't get any help, I'll have to redownload parse and re-configure everything again and hope that it works.

**Comment by flovilmart** [comment]
I'm no expert with elastic beanstalk... I would recommend you use another method for deploying, heroku for example or that you get started with deploying correctly simple node app.

**Comment by flovilmart** [comment]
Also, note that livequery wont work right away on Eb either

**Comment by kanersan** [comment]
Anything tutorials or such for deploying a simple node app? I wish I could deploy the simple parse app properly. Then I could get somewhere but that used to work. After installing dashboard it stopped working. Or maybe it stopped working after I updated the EB and AWS client tools. I'm not 100% sure.

Livequery being querying the parse server? Why wouldn't it work right away? It works locally.

**Comment by flovilmart** [comment]
Live query is the realtime module for parse server, if you don't need it it should not be in your configuration. Also, I believe you can find plenty of elastic beanstalk examples in AWS docs

**Comment by kanersan** [comment]
Oh right that, hmmm ok I'll take it out thanks for your help so far.

**Comment by flovilmart** [comment]
I'm not sure how to help further. Try using another deployment target (app engine, heroku etc...) many users reported issues with EBay, and as far as I recall, EB is not really nicely playing :)

**Comment by kanersan** [comment]
yeah it really isn't. Just deployed parse-server-example to heroku! Super simple. Actually EB wasn't that hard either, until this error happened and I've been stuck on it for 5-6 days now :/

**Comment by flovilmart** [comment]
My best recommendation around that is to fully understand the deployment targets. I find app engine the easiest of all.
