### ISSUE TITLE
Dashbord error "object not found"

### ISSUE THREAD

**Issue by teamu** [parse-community/parse-dashboard#595]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse 

- [ ] 

- [X] Dashboard!

- [x] You're running version >=1.0.19 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Local linux sever

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

#### issue 
I setup the parse-server,parse-dashboards and mongodb in my linux server. I created a new user and database  with admin privilege in mongodb database and import the database .

After migrating the app, we are able to add new entry in the dashboard and also can update and delete the data from dashboard.As we have some previous data in Parse Hosted server, we have successfully migrate that data into new local server as well but that imported data behaves abruptly.We are not able to update any column neither from code nor from dashboard and while doing through code,we found following error:- "[Error]: No results matched the query. (Code: 101, Version: 1.12.0)"

and also not able to delete the data from dashboard.

**Comment by teamu** [comment]
Please review my issue and suggest the solution .

#Environment Setup
Local linux sever
# issue 

I setup the parse-server,parse-dashboards and mongodb in my linux server. I created a new user and database with admin privilege in mongodb database and import the database .

After migrating the app, we are able to add new entry in the dashboard and also can update and delete the data from dashboard.As we have some previous data in Parse Hosted server, we have successfully migrate that data into new local server as well but that imported data behaves abruptly.We are not able to update any column neither from code nor from dashboard and while doing through code,we found following error:- "[Error]: No results matched the query. (Code: 101, Version: 1.12.0)"

and also not able to delete the data from dashboard.

**Comment by genhau** [comment]
I encountered similar error when importing backup data directly into mongodb. I managed to resolve this issue by adding _id field into each record with same value as objectId, ex:

`{
        "authData": {
        "bcryptPassword": "$2a$1",
        "createdAt": "2016-06-21T06:42:34.339Z",
        "membershipStatus": "regular",
        "objectId": "3ZtUTOQWqW",
        "sessionToken": "CjyW",
        "updatedAt": "2016-06-26T08:40:56.011Z",
        "username": "LNt5x5NfpYKha4FjAHBHNaQfT"
    }`
becomes
`{
        "authData": {
        "bcryptPassword": "$2a$1",
        "createdAt": "2016-06-21T06:42:34.339Z",
        "membershipStatus": "regular",
       "_id": "3ZtUTOQWqW",
        "objectId": "3ZtUTOQWqW",
        "sessionToken": "CjyW",
        "updatedAt": "2016-06-26T08:40:56.011Z",
        "username": "LNt5x5NfpYKha4FjAHBHNaQfT"
    }`

after inserting the updated data into mongodb, everything works fine on parse dashboard.
