### ISSUE TITLE
Parse-Dashboard doesn't work with Nginx

### ISSUE THREAD

**Issue by hedoudou** [parse-community/parse-dashboard#598]
Hi Team,

I'm try setup Parse-Dashboard on our cloud servers. But we do have some issue and not sure how to fix it. Any help would appreciate

The request flow is: Nginx(Locate at Server A)->Parse-Dashboard(Locate at Server B)->Parse-Server(Locate at Server B)

Here is dashboard configuration
>  {
  "apps": [{
    "serverURL": "http://my.app.domain/magictext",
    "appId": "my appid",
    "masterKey": "my masterkey",
    "appName": "MagicText"
  }],
  "users": [{
     "user":"gpower",
     "pass":"gpower"
   }
  ],
  "useEncryptedPasswords": false
}

Here is nginx configuration
>server {
        listen                  443;
        server_name             my.app.domain;

        ssl                     on;
        ssl_certificate_key     /opt/gpower/certs/my.app.key.unsecure;
        ssl_certificate         /opt/gpower/certs/my.app.crt;
        ssl_protocols           TLSv1 TLSv1.1 TLSv1.2; 
        ssl_prefer_server_ciphers on;
        ssl_ciphers             'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:AES256+ECDHE';

 
        access_log              logs/parseapi.net_ssl_access.log;
        error_log                logs/parseapi.net_ssl_error.log;

        location /apps/ {
            proxy_redirect off;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto https;
            proxy_pass http://localhost:4040/;
        } 
    }

Parse-Dashboard startup witch command:
parse-dashboard --config parse-dashboard-config.json --allowInsecureHTTP=1

When i access dashboard with IP(http://xx.xx.xx.xx:4040), it worked.
But it shows me blank page when access it via Nginx(https://my.app.domain/apps/), and i got follow log from nginx
>2016/11/24 03:57:45 [error] 12532#0: *2622993 open() "/opt/gpower/server/webserver/nginx//html/bundles/dashboard.bundle.js" failed (2: No such file or directory), client: 36.45.164.55, server: parseapi.gpowers.net, request: "GET /bundles/dashboard.bundle.js HTTP/1.1", host: "parseapi.gpowers.net", referrer: "https://parseapi.gpowers.net/apps/"

**Comment by vuraltuna** [comment]
I am living same problem on DigitalOcean  :(

**Comment by flovilmart** [comment]
try to mount you dashboard on / instead of /apps/

**Comment by kwstasna** [comment]
In digitalocean you have to find the file /etc/nginx/sites-enabled/default

and edit it.

My `default` file is the following


```
# HTTP - redirect all requests to HTTPS
server {
    listen 80;
    listen [::]:80 default_server ipv6only=on;
	server_name EXAMPLE.COM www.EXAMPLE.COM;
    return 301 https://$host$request_uri;
}

# HTTPS - serve HTML from /usr/share/nginx/html, proxy requests to /parse/
# through to Parse Server
server {
        listen 443 ssl;
        server_name EXAMPLE.COM www.EXAMPLE.COM;
		
        root /usr/share/nginx/html;
        index index.html index.htm;

        ssl on;
        # Use certificate and key provided by Let's Encrypt:
        ssl_certificate /etc/letsencrypt/live/EXAMPLE.COM/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/EXAMPLE.COM/privkey.pem;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

        # Pass requests for /parse/ to Parse Server instance at localhost:1337
location /parse {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:1337;
    proxy_set_header Host $http_host;
    proxy_redirect off;
}
		location /public/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/public/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
		location /test/ {
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-NginX-Proxy true;
                proxy_pass http://localhost:1337/test/;
                proxy_ssl_session_reuse off;
                proxy_set_header Host $http_host;
                proxy_redirect off;
        }
		location /dashboard {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/dashboard/;
    proxy_set_header Host $http_host;
    proxy_redirect off;

    }       
}
```

@flovilmart  although the `/login` is not working.
even if i put the following lines

```
location /login {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/login/;
    proxy_set_header Host $http_host;
    proxy_redirect off;
}
```
I get an error `Cannot GET /login/`

any idea?

**Comment by HaveF** [comment]
Is it needed to set `"trustProxy": 1` when using nginx?

**Comment by mrmarcsmith** [comment]
+1

**Comment by tossp** [comment]
+1

**Comment by shaifulcce** [comment]
+1

**Comment by timam** [comment]
Just don't forward any header information. I fixed with the following 

'''

server {
    listen 80;
    server_name dashboard.staging.dealsonear.com;

    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
	location / {
                proxy_pass http://localhost:4040;
        }

}

'''

**Comment by JEKos** [comment]
Any news about that? I have the same problem, after adding :
```
location /dashboard {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://localhost:4040/dashboard/;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    }    
```   
I get 404 page for the `/login`

**Comment by JEKos** [comment]
I find it!
You have to use dashboard in subdomain, like `dashboard.my-domain.com` instead of `my.domain.com/dashboard`, and in nginx config:

```
location / {
     proxy_pass http://localhost:4040;
}
```
without the `try_files $uri $uri/ =404;`
