### ISSUE TITLE
"Trust Proxy" parameter has no effect

### ISSUE THREAD

**Issue by danepowell** [parse-community/parse-dashboard#610]
- [x] You're running version >=1.0.21 of Parse Dashboard.
- [ ] You're running version >=2.2.24 of Parse Server.
- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Heroku hosted (piggybacking on Heroku SSL, i.e. https://example.herokuapp.com)

#### Steps to reproduce
The README indicates that the trusted proxy parameter can be used when hosting behind a proxy (i.e. Heroku). I've set PARSE_DASHBOARD_TRUST_PROXY = 1 in the server configuration, but still get this error when accessing the dashboard over HTTPS:

> Parse Dashboard can only be remotely accessed via HTTPS

Looking through the code, I can't see that the trusted proxy parameter is actually used anywhere. I would expected it to cause Parse Dashboard to look for the X-Forwarded-Proto header.

**Comment by rooswelt** [comment]
+1

**Comment by mrmarcsmith** [comment]
+1

**Comment by jaredalexander** [comment]
+1

**Comment by mortezaalizadeh** [comment]
+1

**Comment by TigPT** [comment]
+1
