### ISSUE TITLE
Dashboard thrashes database when sorting large class by arbitrary field

### ISSUE THREAD

**Issue by airdrummingfool** [parse-community/parse-dashboard#612]
I have a collection (Parse Class) with a lot of data (4m+ documents). This collection has standard and appropriate indexes based on how I query it in Parse. Obviously it is a bad idea to load the collection (without any filters) and then try to sort it by a non-indexed field. However, if I perform the following steps, I get into a scenario where the Dashboard is requesting a collection be sorted by an arbitrary (potentially non-indexed) field, without me explicitly telling it to.

1. Load the collection in Dashboard (collection is sorted by Dashboard default, i.e. createdAt)
1. Filter the collection down to just a few rows
1. Sort those rows by an arbitrary, non-indexed field (this is performant, because the sort query is limited by the filter)
1. Load a different collection in the Dashboard
1. Return to the original (large) collection in the Dashboard

Due to the Dashboard remembering the previous sort method - _but not the previous filter_ - the Dashboard attempts to load the large collection sorted by whatever field I sorted the filtered collection by earlier. On a large enough collection, this can cause serious CPU and disk thrashing (in my case, the db CPU usage jumps from 5% to 45% and sits there for minutes).

This is compounded by the fact that, upon receiving a 504 (Gateway Timeout) or even 503 (Service Unavailable: Back-end server is at capacity), Dashboard simply retries the same query again immediately.

I suppose that one solution is simply indexing my large collection by every conceivable sort method, but that seems like overkill; perhaps the Dashboard can "forget" the custom sort method when it is used in conjunction with filters? Ideally the filter might persist and be restored the next time the collection is viewed along with the sort method, but that seems less straightforward.

**Comment by woodardj** [comment]
I'll second this — we're also seeing that just loading the dashboard page for a large collection can lead to repeated 503s against the parse-server.

**Comment by flovilmart** [comment]
I believe we already cache the row orders, why not a filter.

We could also very well add a user defined option for allowing certain sorts.

**Comment by johanarnor** [comment]
We also see this issue quite often. A simple solution would just be to not cache _sort order_. I could take a shot at a PR, if that would be a viable solution @flovilmart.

Also, sometimes when we sort by an indexed field, we still thrash the DB since parse dashboard always sort by createdAt as a second parameter. I.e if you sort by a field called _status_ the following is sent to the Parse backend `order: "-status,-createdAt"`. I guess this is more difficult to remove since it is sometimes nice to have, but it could maybe be disabled in a config parameter?
