### ISSUE TITLE
Parse.com - Wanted to export my Data from Parse but error. Now can´t see any data on browse

### ISSUE THREAD

**Issue by VladimirMotta** [parse-community/parse-dashboard#615]
Please, help!

After execute migration, I tried to export my Data from Parse but error. Now can´t see any data on browse!

Help!
Thanks,
Vladimir.

Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.21 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by dvanwinkle** [comment]
Sounds like you could've just changed your mongodb uri from Parse.com. In the new dashboard on Parse.com, you should be able to change your server uri.
