### ISSUE TITLE
parse file names are not shown correctly in dashboard

### ISSUE THREAD

**Issue by lucaosten** [parse-community/parse-dashboard#625]
I don't know how the file name is exactly determined, but I noticed that the first four letters of all my Parse files in my own MongoDB are cut off.

name in the new MongoDB
86a4abdb045c11c4e9e2467e37f7da10_route.croute
32 letters before the underscore
dashboard shows "e.croute"

name in the original Parse MongoDB
tfss-6de5356d-0c01-44cd-9b09-86d740f00b0f-route.croute
36 letters until the last "minus" ("minus" not counted)
dashboard shows "route.croute"

the difference of 4 letters is also what is cut off by the dashboard

**Comment by fcoufour** [comment]
Hi Luca,

The same thing happens to me.

If we look at the source code which determines the filename (getFileName.js):

```
export default function getFileName(name) {
  if (name instanceof Parse.File) {
    return getFileName(name.name());
  }
  let offset = 37;
  if (name.indexOf('tfss-') === 0) {
    offset += 5;
  }
  return name.substr(offset);
}
```

This is still based on the original Parse.com full filename format: (5 chars "tfss-"") + 37 chars "-" separated UUID + filename

According to Parse Server FilesController, new created files are now named as follows:
`filename = randomHexString(32) + '_' + filename;`

This explains the 4 chars diff you noticed.

Considering files.parsetfss.com has been now shutdown, it's probably not necessary to keep the legacy filename rule.

A good thing would be to make the filename format defined in Parse Server shared to Parse Dashboard. I don't know if there is already such a mechanism for other stuff.

**Comment by natanrolnik** [comment]
@lucaosten @fcoufour are you still seeing this bug?

**Comment by fcoufour** [comment]
@natanrolnik Yes but I'm still on version 1.0.22. Is this fixed by a newer version?

**Comment by natanrolnik** [comment]
Can you give us more information? A screenshot, the full name of the file in your storage service, etc?

**Comment by fcoufour** [comment]
@natanrolnik Luca has already given an example: "86a4abdb045c11c4e9e2467e37f7da10_route.croute" is displayed as "e.croute" and my long comment explains the theory.

I checked the source code again and there is no change. I was wondering if we could share the file naming policy between Parse Server and Parse Dashboard instead of having 2 different hard-coded prefix length values in both places.

**Comment by natanrolnik** [comment]
So I imagine a fix is shouldn't be complicated. Regarding sharing the file naming policy, I'm not sure.  
@flovilmart what do you think about this issue in general?

**Comment by flovilmart** [comment]
the offset value look wrong.

If parse.com files have a prefix of 37 and ours have one of 32, offset should be 32
