### ISSUE TITLE
Parse Dashboard Automatically deleted installation table data

### ISSUE THREAD

**Issue by jainhemant** [parse-community/parse-dashboard#627]
I have installed parse server and parse dashboard on my own server since 2.5 month for sending push notification purpose. I was shocked when I saw yesterday the installation table is empty. I also  checked today then It is same thing happened again. (Before Today all table data are empty)

As I have checked Mongodb connection but it is working fine since last 2.5 months. Could suggest me what is going wrong with parse.Please update fast as my project is live and I am not able to send push notification.

Thanks in advance.

**Comment by flovilmart** [comment]
Are you only using the _Installation table? Parse don't delete classes on itself, perhaps you've been a victim of a widespread mongodb ransom hack http://www.theregister.co.uk/2017/01/09/mongodb/
