### ISSUE TITLE
Save is triggered when removing focus from object/array fields

### ISSUE THREAD

**Issue by flovilmart** [parse-community/parse-dashboard#649]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.21 of Parse Dashboard.

- [x] You're running version >=2.2.24 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

- App Engine
- Docker image

#### Steps to reproduce

- open the dashboard
- Create a class with object or array column
- Enter data for the object/array column
- Re-focus the field (to enter edit mode)
- Select outside the field (lose focus)

Expected:
- No network request is sent
- Note that this doesn't affect strings, booleans, numbers  (AFAICT)
- This may affect other types.

Actual:
- A PUT request is sent with the contents of the editing field

#### Logs/Trace

No particular logs are available for that behaviour, the best way to notice the issue, is to open a chrome / safari inspector and notice the outgoing network requests.

**Comment by natanrolnik** [comment]
Looking into existing issues, I think this is related to #579, if not duplicate.
