### ISSUE TITLE
This notification will be sent to 1 device

### ISSUE THREAD

**Issue by kamioon** [parse-community/parse-dashboard#662]
- [X] You're running version >=1.0.24 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Every things are normal, but in sending push, when i select audiences the total numbers of selected is not right, always i got:

>  This notification will be sent to 1 device

![imgimg](https://cloud.githubusercontent.com/assets/3734100/22977985/120955b2-f3a6-11e6-8f09-968e0525b6fa.png)

what's wrong?

**Comment by kamioon** [comment]
others have right value?

**Comment by eduardbosch** [comment]
I'm seeing the same message as you

**Comment by c040120** [comment]
Got to the same issue
