### ISSUE TITLE
Login form is displayed over http even though allowInsecureHTTP=false

### ISSUE THREAD

**Issue by johanarnor** [parse-community/parse-dashboard#664]
I'm running version 1.0.24 of Parse Dashboard.

#### Steps to reproduce
- Set allowInsecureHTTP=false (or disregard it, defaults to false).
- Deploy somewhere else than localhost (I'm using Heroku).
- Access the login page over http
- Type usename/password and "form tampered with" error is displayed

Anyone else experiencing this issue?

**Comment by richard4339** [comment]
I'm actually getting the form tampered with suddenly period, regardless of what's going on, and without upgrading. I tried upgrading and downgrading and everything in between, and can't get around the form tampered with message.

**Comment by flovilmart** [comment]
@JeremyPlease seems to be an issue with the CSRF protection right?

**Comment by JeremyPlease** [comment]
The "form tampered with" error would indeed indicate that the CSRF token isn't valid. See [code here](https://github.com/ParsePlatform/parse-dashboard/blob/master/Parse-Dashboard/app.js#L69-L74).

@johanarnor @richard4339 Can you provide your full configuration (with any sensitive info redacted)?

Hypothetically, you shouldn't be able to use the dashboard over http without having `allowInsecureHTTP` set to true.

**Comment by johanarnor** [comment]
@JeremyPlease sorry for the late response, but here is a config which displays the strange behaviour.

A dashboard is live at https://some-parse-dashboard.herokuapp.com/login if you want to reproduce the bug.

parse-dashboard-config.json
```
{
  "apps": [
    {
      "serverURL": "https://some-parse-server.herokuapp.com/parse",
      "appId": "APP_ID",
      "masterKey": "MASTER_KEY",
      "appName": "Parse App"
    }
  ],
  "users": [
    {
      "user": "admin",
      "pass": "password"
    }
  ]
}
```

package.json
```
{
  "private": true,
  "scripts": {
    "start": "parse-dashboard --config parse-dashboard-config.json --trustProxy=1"
  },
  "dependencies": {
    "express": "^4.14.1",
    "parse-dashboard": "^1.0.25"
  },
  "engines": {
    "node": "7.5.X"
  }
}
```

**Comment by JeremyPlease** [comment]
@johanarnor Thanks for setting up the heroku instance and config files.

The thing that needs to be fixed here is ensure that the login page is served over https when allowInsecureHTTP=false. Just like the subject of this issue says 😁 

@johanarnor Want to take a stab at a pull request for this? Probably just need a simple middleware added to [`Parse-Dashboard/app.js`](https://github.com/ParsePlatform/parse-dashboard/blob/master/Parse-Dashboard/app.js) that redirects http to https if allowInsecureHTTP=false.

**Comment by monajafi** [comment]
The issue has been resolved by downgrading parse-dashboard installation to version 1.1.0
npm install parse-dashboard@1.1.0
this is a bug in latest version 1.1.2
