### ISSUE TITLE
Data browser automatically scrolls indefinitely

### ISSUE THREAD

**Issue by bendigi** [parse-community/parse-dashboard#668]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Parse on Google compute engine
Dashboard on Google compute engine
Mongo on a separate machine

#### Steps to reproduce

The issue has appeared suddenly without any updates to parse or the dashboard. When using the data browser and you scroll past say 40 rows, the data browser automatically scrolls indefinitely without stopping. The only way to stop it is to scroll back up. 

Here is a video to show the issue. https://youtu.be/VqY4K9jJ3yM

Is it possible that something in the DB is causing this?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by JacerOmri** [comment]
well i'm facing the same issue, been working on this the whole day. I know it has to do with handleScroll method in BrowserTable.
It's a bit complicated. I think the virtual scrolling logic there is flawed.
I don't have an answer yet, once i have something I will open a PR.

**Comment by JacerOmri** [comment]
Actually, the height of the spacer above the actual table shown is changing, and i think this fires the scroll event again.
I changed this 
```
      if (this.state.offset !== offset) {
        this.setState({ offset });
      }
```
to this
```
      if (this.state.offset !== offset) {
        this.setState({ offset });
        this.refs.table.scrollTop = rowsAbove * ROW_HEIGHT;
      }
```
I was able to make it stop, it feels a bit laggy, but at least it's usable.

**Comment by sandeep2242** [comment]
Hey I am also facing this issue, can you please tell me that how to fix this ?

**Comment by EricNetsch** [comment]
Same issue here. Would love to know the fix as this is a super frustrating issue. Thanks

**Comment by JacerOmri** [comment]
@sandeep2242 @EricNetsch did you try my suggestion above? it worked for me

**Comment by bendigi** [comment]
In which file do we do the change you suggested?

**Comment by sandeep2242** [comment]
Where do we have to make this change you suggested ?

**Comment by JacerOmri** [comment]
follow this commit https://github.com/ParsePlatform/parse-dashboard/pull/671/commits/a9f189b3b9ef6a6e4cafde5d16b3b5bda7d91335

it's in src/dashboard/Data/Browser/BrowserTable.react.js

**Comment by toddgower** [comment]
Any update on this PR being accepted? It's causing issues for me too.

**Comment by jackdewhurst** [comment]
Ditto on a release for this please, makes large datasets unmanageable in the current build

**Comment by sjmerel** [comment]
I am seeing this on Chrome on a Mac.  It doesn't happen for me on Safari, so that's a workaround for now.

**Comment by toddgower** [comment]
Yes, I can confirm that using Safari prevents this from happening too. Thank you!

**Comment by sandeep2242** [comment]
Anything for windows

**Comment by pivanov** [comment]
Sorry for the late PR guys ... Hope you will like the results :)

**Comment by sandeep2242** [comment]
Where to make this change?

**Comment by pivanov** [comment]
You can check my [pull request](https://github.com/ParsePlatform/parse-dashboard/pull/676).

**Comment by sandeep2242** [comment]
I mean where to make changes in my dashboard. I am new to git hub so any suggestions or link would be greatly accepted. Thank you
