### ISSUE TITLE
Version number too low, serverInfo going for POST when it should be using GET

### ISSUE THREAD

**Issue by kfwerf** [parse-community/parse-dashboard#674]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

- Using parse-server-example with Parse 1.9.x and Parse server 2.3.6
- Dashboard 1.0.25

#### Steps to reproduce
Every single request that goes to the server seems to be specified in the wrong format

E.g. 
curl 'https://api.datefordate.com/parse/serverInfo' -H 'Pragma: no-cache' -H 'Origin: https://api.datefordate.com' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: nl-NL,nl;q=0.8,en-US;q=0.6,en;q=0.4,sv;q=0.2,fr;q=0.2' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Content-Type: text/plain' -H 'Accept: */*' -H 'Cache-Control: no-cache' -H 'Referer: https://api.datefordate.com/dashboard/' -H 'Cookie: session=xxx; session.sig=xxx' -H 'Connection: keep-alive' -H 'DNT: 1' --data-binary '{"_method":"GET","_ApplicationId":"xxx","_ClientVersion":"js1.6.14","_MasterKey":"xxx","_InstallationId":"xxx"}' --compressed

Should be
curl -X GET -H "X-Parse-Application-Id: xxx" -H "X-Parse-Master-Key: xxx" -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H "https://api.datefordate.com/parse/parse/serverInfo"

Or something similar, it seems to be specifying its get request in its DATA for whatever reason. Am i missing something here, the normal way is below, is there somewhere a config i missed or is it bugging out on me?

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by jboss001** [comment]
Hello,

I have the same problem with the following configuration:
parse-server 2.4.1
parse-dashboard 1.0.27
parse 1.9.2
Did you have make progress to solve this ?
Thanks,
Kr.
Jamal.
