### ISSUE TITLE
Feature Request: Add Header X-Parse-Dashboard-User

### ISSUE THREAD

**Issue by chrillo** [parse-community/parse-dashboard#675]
This is releated to these issues #322 #259, where we want a read only access for certain users. While I understand that this will be difficult to achieve, for us it would suffice to have some way to derive the dashboard user from the request. That way I can simply catch any POST requests for a given user and block it on our parse server. This is not secure but I really only want to prevent user errors so its enough. If the X-Parse-Dashboard-User header is not generic enough, we could have a more generic X-Parse-Dashboard-Meta header which can be configured on the config for the user. In general this solution would allow for anybody who needs this to handle it on their and without major modifications to parse server. If this is acceptable I am happy to submit a PR for this.

**Comment by lastMove** [comment]
You should use http://adminca.com
It's a very nice solution.

**Comment by flovilmart** [comment]
@lastMove, that's out of context.

@chrillo, I'm open for improvements regarding the dashboard, like role based authentication etc... this may require a major refactor as all calls are run with the masterKey but I believe there is value there.

**Comment by erikbZhang** [comment]
Hi, I'm with a group of high schoolers who are willing to try and tackle this problem. We've been looking at quite a few different ways to do this, but would love for some advice from you to figure out how exactly we should do this.
