### ISSUE TITLE
PFConfig / Date Converted to Object

### ISSUE THREAD

**Issue by Treverr** [parse-community/parse-dashboard#679]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

When adding a PFConfig with the type of Date, it sets properly, however when reloading the dashboard at a later date the dashboard sets it as just an object:

{"__type":"Date","iso":"2017-01-01T00:00:00.000Z"}

instead of being a Date it converts it, is this expected? This can't be modified with the Date popup that originally comes up so its inconsistent so it seems like it might be a bug

**Comment by flovilmart** [comment]
What version of parse-server / parsse-dashboard are you using?
