### ISSUE TITLE
Connection fails: error: role "spectrum" does not exist It will be retried for the next request.vents.js:160       throw er; // Unhandled 'error' event       ^  error: role "spectrum" does not exist     at Connection.parseE (/Users/naveedzafardurrani/projects/spectrum-api/node_modules/pg/lib/connection.js:569:11)     at Connection.parseMessage (/Users/naveedzafardurrani/projects/spectrum-api/node_modules/pg/lib/connection.js:396:17)     at Socket.<anonymous> (/Users/naveedzafardurrani/projects/spectrum-api/node_modules/pg/lib/connection.js:132:22)     at emitOne (events.js:96:13)     at Socket.emit (events.js:188:7)     at readableAddChunk (_stream_readable.js:176:18)     at Socket.Readable.push (_stream_readable.js:134:10)     at TCP.onread (net.js:548:20)

### ISSUE THREAD

**Issue by TonyAziz** [parse-community/parse-dashboard#685]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [ ] You're running version >=2.3.2 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by hhanesand** [comment]
You really expect to get any sort of reply for this?

You didn't even bother to click the boxes....

**Comment by natanrolnik** [comment]
Closing due to insufficient information. Please fill the issue template correctly and it will be reopened.
