### ISSUE TITLE
Is it possible to create new parse app on my server?

### ISSUE THREAD

**Issue by hilal-m** [parse-community/parse-dashboard#692]
I have a self hosted parse server (open source parse server + parse dashboard)
How to create new app?
And how can I get new app key and master key?

**Comment by felipemobile** [comment]
You can run multiple instances of Parse-Server on different node processes.

https://github.com/Colubris/parse-server-example/blob/master/colubris_start.sh

You can create random values for app keys.

**Comment by natanrolnik** [comment]
Creating a new app with the dashboard is not supported yet.

You can run this in your terminal and it will help you generating what you need for a new app:

`curl https://raw.githubusercontent.com/parseplatform/parse-server/master/bootstrap.sh | sh`

Alternatively, you can take a look at this npm package: [`parse-server-generator`](https://www.npmjs.com/package/parse-server-generator). You can install it with `npm install --g parse-server-generator`
