### ISSUE TITLE
Doesn't load more users on scroll in User class

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [parse-community/parse-dashboard#695]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ x ] Running version 1.0.25 of Parse Dashboard.

- [ x ] You're running version >=2.3.2 of Parse Server.

- [ x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=)

#### Environment Setup
Running Parse Dashboard locally, I'm seeing an issue where scrolling down in the Users class is not loading more rows upon reaching the bottom. We have 500+ users but I'd guess only ~100 are showing in the list. Scrolling down doesn't load more.

#### Steps to reproduce
1. Run the dashboard locally
2. Click Users
3. Scroll down
Result: It doesn't load more users
Expected: It should load more users, until all users are displayed after scrolling down through them all

#### Logs/Trace
None

**Comment by dangerdan** [comment]
Can you provide a console log/browser details? Working for me on 1.0.27.

**Comment by jordanhbuiltbyhq** [comment]
Yes, Safari 10.1.1 (12603.2.4). I upgraded the dashboard to 1.1.0 and this is still occurring for me. No console errors or warnings though. Working as expected in Chrome.
