### ISSUE TITLE
how to change table's date colunm displayed time zone?

### ISSUE THREAD

**Issue by akg1234** [parse-community/parse-dashboard#696]
as convenience , i want display the date as the local timezone

**Comment by edson-gaspar** [comment]
+1

**Comment by beiguancyc** [comment]
+1

**Comment by beiguancyc** [comment]
you can try it
https://github.com/beiguancyc/parse-dashboard

**Comment by flovilmart** [comment]
I would not recommend to try a fork of the project without fully checking the diff and ensuring it is safe to use

**Comment by beiguancyc** [comment]
well,I add a function in DateUtil
export function dateStringLocale(date) {
  let month=date.getMonth()+1
  let date2=date.getDate()
  if(month<10){
    month = "0" + month;
  }
  if(date2<10){
    date2 = "0" + date2;
  } 
  let full=String(String(date.getFullYear()+'-'+month+'-'+date2 +' '))
  let time = {
    hours: String(date.getHours()),
    minutes: String(date.getMinutes()),
    seconds: String(date.getSeconds())
  };
  for (let k in time) {
    if (time[k].length < 2) {
      time[k] = '0' + time[k];
    }
  }
  full += time.hours + ':' + time.minutes + ':' + time.seconds;
  return full;
}

**Comment by imana97** [comment]
+1

**Comment by flovilmart** [comment]
Closing as we won't work on it.

**Comment by imana97** [comment]
Why not?

**Comment by flovilmart** [comment]
Because we won’t work on it. I don’t believe I need to justify my choices and priorities. If it’s an important feature for you, open a pull request

**Comment by aldochaconc** [comment]
> Because we won’t work on it. I don’t believe I need to justify my choices and priorities. If it’s an important feature for you, open a pull request

haha, what a dick. he was just asking, a question, not a justification. sensitive guy
