### ISSUE TITLE
Parse-dashboard has no App-Settings

### ISSUE THREAD

**Issue by CharlesLim0721** [parse-community/parse-dashboard#697]
Good evening,
I have deployed a Parse server and I want to enable email verification setting but I found that my parse dashboard has only core tab instead of all other tabs like Push, Analytics and most importantly App-Setting which is the setting for email verification and others.

<img width="680" alt="screen shot 2017-04-22 at 8 36 58 pm" src="https://cloud.githubusercontent.com/assets/26108682/25304567/75387508-279c-11e7-9718-47d854521f5f.png">

but I watched some toturial that's have all of it like below

<img width="597" alt="screen shot 2017-04-22 at 8 36 36 pm" src="https://cloud.githubusercontent.com/assets/26108682/25304585/d1bd2576-279c-11e7-8071-cd868c87b6cc.png">

Is that because of using free trial version so that dont have all function or need to do some set up for this? 

Any one can help, thank a lot~

**Comment by felipemobile** [comment]
App-Setting is not supported in Parse-Dashboard.

https://github.com/parse-community/parse-server/blob/master/README.md#configuration

'''customPages - A hash with urls to override email verification links, password reset links and specify frame url for masking user-facing pages. Available keys: parseFrameURL, invalidLink, choosePassword, passwordResetSuccess, verifyEmailSuccess.'''

**Comment by CharlesLim0721** [comment]
@felipemobile Thank for your replied~
