### ISSUE TITLE
Mounting parse dashboard on to a router won't work.

### ISSUE THREAD

**Issue by tomasgvivo** [parse-community/parse-dashboard#698]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
```
var express = require('express');
var ParseDashboard = require('parse-dashboard');

var dashboard = new ParseDashboard({
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMasterKey",
      "appName": "MyApp"
    }
  ]
});

var app = express();

// Here is where the problem starts...
var router = express.Router();

// make the Parse Dashboard available at /dashboard
router.use(dashboard);

// mount the router.
app.use('/dashboard', router);

var httpServer = require('http').createServer(app);
httpServer.listen(4040);
```

#### The problem:
ParseServer doesn't care where you mount it to.
It allways use app.
```
module.exports = function(config, allowInsecureHTTP) {
  var app = express(); //   <----------------------------------------- The problem
  // Serve public files.
  app.use(express.static(path.join(__dirname,'public')));

  // Allow setting via middleware
  if (config.trustProxy && app.disabled('trust proxy')) {
    app.enable('trust proxy');
  }

  // wait for app to mount in order to get mountpath
  app.on('mount', function() { // <--------------------------------- More prblems
    const mountPath = getMount(app.mountpath);
    const users = config.users;
    const useEncryptedPasswords = config.useEncryptedPasswords ? true : false;
    const authInstance = new Authentication(users, useEncryptedPasswords, mountPath);
    authInstance.initialize(app);

    // CSRF error handler
    app.use(function (err, req, res, next) {
      if (err.code !== 'EBADCSRFTOKEN') return next(err)

      // handle CSRF token errors here
      res.status(403)
      res.send('form tampered with')
    });

[...]
```

I have some idea of how to solve this.. but maybe there is a better one.

Btw, sorry for my bad english.

**Comment by flovilmart** [comment]
And if you use:

app.use('/dashboard', parseServer)

?

**Comment by tomasgvivo** [comment]
@flovilmart 

That's not the case.
Is not allways posible to mount ```parseDashboard``` onto the ```app```, especially when you have multiple frontend applications in the same project. That's why routers exists... so all the mounted middlewares don't need to share the same application singleton.

**Comment by flovilmart** [comment]
Not sure when calling app = express() returns a singleton. 

Also, can you expand on what 'won't work', because I personally would have done:

var router = express.Router()
router.use('/dashboard', dashboard)
app.use(router)

**Comment by tomasgvivo** [comment]
@flovilmart 

Thanks, now I understand better the problem.
When you mount a sub-app onto a router, the sub-app's ```app.on('mount, [...])``` is never called.
I don't know if it's a express bug or parse-dashboard bug.

**Comment by flovilmart** [comment]
I would say an express one, or you can probably forward the router on mount call to the dashboard by emitting the mount event back.

**Comment by tomasgvivo** [comment]
It's seams it's a feature..
[https://github.com/expressjs/express/issues/3285](https://github.com/expressjs/express/issues/3285)

But now I know how to solve my problem.

Thanks.

**Comment by flovilmart** [comment]
I don't believe there is any need to use a Router unless 100% necessary.
