### ISSUE TITLE
Files in GCS do not delete when using "delete row" in dashboard

### ISSUE THREAD

**Issue by henrytkirk** [parse-community/parse-dashboard#699]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ X] You're running version >=1.0.23 of Parse Dashboard.

- [ X] You're running version >=2.3.2 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Running dashboard locally. I am using the parse-server-gcs-adapter for files in my parse server (hosted on Google App Engine)

#### Steps to reproduce
1. Add a class and a column that has a file type.
2. Upload file and create row.
3. Observe the file is present in the row by clicking it, and also in the GCS bucket (looking at GCS dashboard file browser)
4. Delete the row using the dashboard.
5. Observe row is deleted from dashboard, but file still remains in GCS bucket when looking at the GCS dashboard file browser.

Am I missing something to support this? Thanks for the help.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by markmssd** [comment]
If I remember correctly, it is the same thing when hosting files on AWS S3...

**Comment by flovilmart** [comment]
Files are never deleted when deleting an object it refernces as they can be referenced in multiple objects.

**Comment by natanrolnik** [comment]
@henrytkirk you can read more about it here: https://github.com/parse-community/parse-server/issues/1023
