### ISSUE TITLE
Wrong Content-Type when uploading html file

### ISSUE THREAD

**Issue by mmarshak** [parse-community/parse-dashboard#700]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.
I am running 1.0.22 but I looked at what change in 1.0.23 and those changes do not impact this issue.

- [ ] You're running version >=2.3.2 of Parse Server.
I am using Parse server 2.2.25, and again since 2.2.25 till 2.3.2 according to the release note there was not changes in this area.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.
The only thread I found was - https://github.com/parse-community/Parse-SDK-JS/issues/311
And it does an issue with Parse way to set the content type for files.

#### Environment Setup
AWS ELB,

#### Steps to reproduce
I have an html file, that open just fine and displayed as html any browser, but when I upload it via the dashboard, I can not display it as an html. It is displayed as text file, so I saw that in AWS S3 the content-type was set to text/plain instead of text/html. After changing it on AWS the file open like an html file.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by natanrolnik** [comment]
@flovilmart do you think the issue here is in the server or dashboard?

**Comment by flovilmart** [comment]
depends how the content type is specified by the client see: 

http://parseplatform.org/Parse-SDK-JS/api/classes/Parse.File.html

http://parseplatform.org/Parse-SDK-iOS-OSX/api/Classes/PFFile.html#/c:objc(cs)PFFile(cm)fileWithData:contentType:

if no content type is specified, this will fallback

**Comment by mmarshak** [comment]
I do not use any client for this, I just went to the dashboard and uploaded an html file.
The dashboard does not ask for type, it only present an upload button. Is there a way to specify the content type in the dashboard?

If the file ends with html or html, it will be nice that they content type will set as html.

**Comment by flovilmart** [comment]
Can you open the issue on Parse server, we could probably infer the content type based on extensions

**Comment by mmarshak** [comment]
Sure -
The Parse server issue  is -
https://github.com/parse-community/parse-server/issues/3782

**Comment by flovilmart** [comment]
Thanks!
