### ISSUE TITLE
Cannot acess Dashboard

### ISSUE THREAD

**Issue by lipesmile** [parse-community/parse-dashboard#704]
I've set up of Parse-Server with mongodb on same instance, in amazon, EC2.

I can't get acess to parse-dashboard because I didn't install SSL certificate, so I used nginx + Let's Encrypt to solve this.

But now when I try to acess parse-server I get:

Cannot Get login

How to solve this ? Here is my dashboard config:

```
{
  "apps": [
    {
        "serverURL": "http://mysvrurl/parse", 
        "appId": "myappid",
        "masterKey": "mykey",
        "appName": "appname"
    }
  ],
  "users": [
    {
      "user":"user", 
      "pass":"p@ssw0rd"
    }

```
I looked the issues like this, but I didn't find the awnser

**Comment by r1cebank** [comment]
Can you provide more info? like what error are you getting, what happens when you try to login, etc.
