### ISSUE TITLE
How to select multiple rows without clicking on each one?

### ISSUE THREAD

**Issue by mmarshak** [parse-community/parse-dashboard#705]
I researched online and did not find away to do it.

In the old parse.com dashboard there was away to pick 20 rows at the time without the need to click each row separately. The use case is when I want to delete few consecutive row, with the parse-dashboard I need to click one by one, and then to go to delete those rows.

Is there away to select the top X row, or just the rows on the screen?

Thank you in advance.

**Comment by adammlevy** [comment]
Would also like a way to select multiple/all rows based on some filer.
