### ISSUE TITLE
Need Release for New Links

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-dashboard#706]
Recently contacted Bitnami to discuss an issue regarding their version of parse-dashboard. Most of the support links are out of date. Those links were corrected in mid April, but since they only track releases they have not pulled up changes since [1.0.25](https://github.com/parse-community/parse-dashboard/releases/tag/1.0.25).

I suspect that other hosted services that utilize this dashboard are using a similar mechanism. So there may be multiple services using dashboards with bad links.

I'm requesting if we can push out a new release (assuming no work is pending) so these providers can be up to date.

**Comment by flovilmart** [comment]
@natanrolnik would you have time to craft a changelog and a release?

**Comment by natanrolnik** [comment]
@flovilmart Only saw now, sorry! Will do it today/tomorrow
