### ISSUE TITLE
unable to see cloud logs after upgrading dashboard to 2.0.0

### ISSUE THREAD

**Issue by Canna59** [parse-community/parse-dashboard#708]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup

Centos 7
dashboard: 2.0.0
parse-server: 2.4.0
node: 7.10.0

This is my parse dashboard configuration

```
{
  "apps": [
    {
          "appId": "APP_ID",
          "masterKey": "MASTER_KEY",
          "restKey": "REST_KEY",
          "serverURL": "http://WWW_WEBSITE:8081/parse",
          "appName":"APP_NAME"
        }
  ],
 "users": [
        {
          "user": "ADMIN",
          "pass": "ADMINXXXXXXX"
        }
 ]
}
```

This is my cloud code test function:

```
Parse.Cloud.define("hello", function(request, response) {
  response.success("Hello world!");
});
```

When i call it with a curl i have:

```
curl -X POST -H "X-Parse-Application-Id: APP_ID" -H "X-Parse-REST-API-Key: REST_KEY" -H "Content-Type: application/json" -d '{ }' http://WWW_WEBSITE:8081/parse/functions/hello

{"result":"Hello world!"}
```
the result is correct and on the parse server i have the trace:

```
verbose: REQUEST for [POST] /parse/functions/hello: {} method=POST, url=/parse/functions/hello, user-agent=curl/7.29.0, host=WWW_WEBSITE:8081, accept=*/*, x-parse-application-id=APPID, x-parse-rest-api-key=REST_KEY, content-type=application/json, content-length=3,
info: Ran cloud function hello for user undefined with:
  Input: {}
  Result: "Hello world!" functionName=hello, , user=undefined
verbose: RESPONSE from [POST] /parse/functions/hello: {
  "response": {
    "result": "Hello world!"
  }
} result=Hello world!
```

I have seen this topic: https://github.com/parse-community/parse-dashboard/issues/281 and i have try to set the verbose export variable on my parse-server and dashboard

i think i have miss some configuration but i can't find which one,

Thanks a lot,

Canna

#### Steps to reproduce

https://i.stack.imgur.com/Br1cs.png
As you can see i dont have the log item to display cloud code log

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by flovilmart** [comment]
The latest version of the dashboard is [1.0.25](https://www.npmjs.com/package/parse-dashboard) not sure where you got the version 2.0 of it!

**Comment by Canna59** [comment]
Hello @flovilmart,

i'am not sure how to check the version here is a little extract of my package.json in parse-dashboard

{
  "_args": [
    [
      {
        "raw": "parse-dashboard@2.0.0",
        "scope": null,
        "escapedName": "parse-dashboard",
        "name": "parse-dashboard",
        "rawSpec": "2.0.0",
        "spec": "2.0.0",
        "type": "version"
      },
      "/usr/lib/node_modules/parse-dashboard"
    ]
  ],
  "_from": "parse-dashboard@2.0.0",
  "_id": "parse-dashboard@2.0.0",
  "_inCache": true,
  "_location": "/parse-dashboard",
  "_nodeVersion": "5.5.0",
  "_npmOperationalInternal": {
    "host": "packages-13-west.internal.npmjs.com",
    "tmp": "tmp/parse-dashboard-2.0.0.tgz_1458006742772_0.4714089557528496"
  },
  "_npmUser": {
    "name": "drewgross",
    "email": "drewgross@fb.com"
  },
  "_npmVersion": "3.5.3",
  "_phantomChildren": {},
  "_requested": {
    "raw": "parse-dashboard@2.0.0",
    "scope": null,
    "escapedName": "parse-dashboard",
    "name": "parse-dashboard",
    "rawSpec": "2.0.0",
    "spec": "2.0.0",
    "type": "version"
  },
  "_requiredBy": [
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/parse-dashboard/-/parse-dashboard-2.0.0.tgz",
  "_shasum": "b8e8c81cdd7c44e764125f19577a6714b3865763",
  "_shrinkwrap": null,
  "_spec": "parse-dashboard@2.0.0",
  "_where": "/usr/lib/node_modules/parse-dashboard",
  "bin": {
    "parse-dashboard": "./bin/parse-dashboard"
  },
  "bugs": {
    "url": "https://github.com/ParsePlatform/parse-dashboard/issues"
  },
  "dependencies": {
    "babel-runtime": "~5.8.25",
    "basic-auth": "^1.0.3",
    "commander": "^2.9.0",
    "express": "^4.13.4",
    "history": "~1.9.1",
    "immutable": "~3.7.5",
    "json-file-plus": "^3.2.0",
    "marked": "^0.3.5",
    "parse": "1.6.14",
    "prismjs": "~1.2.0",
    "react": "^0.14.0",
    "react-dnd": "~2.0.2",
    "react-dnd-html5-backend": "~2.0.0",
    "react-dom": "^0.14.0",
    "react-router": "2.0.0"
  },
  "description": "The parse dashboard",
  "devDependencies": {
    "babel-core": "~5.8.12",
    "babel-loader": "~5.3.0",
    "babel-plugin-remove-proptypes": "~1.0.0",
    "css-loader": "~0.18.0",
    "file-loader": "^0.8.5",
    "http-server": "~0.8.5",
    "immutable-devtools": "~0.0.4",
    "jest-cli": "^0.7.1",
    "js-beautify": "~1.5.0",
    "node-sass": "~3.4.2",
    "react-addons-test-utils": "^0.14.2",
    "sass-loader": "~3.1.2",
    "style-loader": "~0.12.3",
    "svg-prep": "~1.0.0",
    "transform-jest-deps": "^2.1.0",
    "webpack": "~1.12.0"
  },
  "directories": {},
  "dist": {
    "shasum": "b8e8c81cdd7c44e764125f19577a6714b3865763",
    "tarball": "https://registry.npmjs.org/parse-dashboard/-/parse-dashboard-2.0.0.tgz"
  },
  "engines": {
    "node": ">=4.3"
  },

Regards,

**Comment by flovilmart** [comment]
I'm not sure how you got that version, but this is not the latest, as we're at 1.0.25

**Comment by Canna59** [comment]
Thanks a lot @flovilmart i have downloaded the right version and know everything is ok, i don't know what happens with my previous `npm install -g parse-dashboard`

Sorry for the wrong issue and thanks for your help,

Regards,
C
