### ISSUE TITLE
Parse file column can not be edited in dashbaord

### ISSUE THREAD

**Issue by monajafi** [parse-community/parse-dashboard#713]
It's not possible to edit and update existing parsefile coulmn in dashbaord. Just new file can be uploaded .

**Comment by r1cebank** [comment]
You can already do something like this, is this what you are trying to find?
<img width="387" alt="screenshot at may 27 23-20-02" src="https://cloud.githubusercontent.com/assets/261671/26526531/120c2bac-4333-11e7-8b34-8de460ea3fdb.png">

**Comment by monajafi** [comment]
In my dashboard I can't find those delete and Replace file. My dashbaord version is 1.0.25
here is my image file screenshot, when I click it is opening image file:
<img width="149" alt="screen shot 2017-05-29 at 19 18 05" src="https://cloud.githubusercontent.com/assets/6666486/26554134/f5c83568-44a3-11e7-9de2-335069129a60.png">

**Comment by natanrolnik** [comment]
Try double clicking twice in the white part of the cell

**Comment by monajafi** [comment]
Thanks a lot man. you saved my day

**Comment by natanrolnik** [comment]
Glad I could help, @monajafi. I'll try to make a PR to improve this.

**Comment by natanrolnik** [comment]
@monajafi I've did a few changes to improve this behavior:

#716
