### ISSUE TITLE
Updating Dashboard on Heroku

### ISSUE THREAD

**Issue by nah0y** [parse-community/parse-dashboard#714]
Hello,

I'm sorry to ask this here as this is maybe not relevant, but I think it is.
I've already set up the Parse Dashboard on Heroku a few months ago, and want to update to the latest version. I've just retrieved the last 1.0.26 commit on my local machine, and pushed all that to my heroku git repository on the master branch. Everything seems to be deployed, but when I access my Dashboard, I still see the "Parse Dashboard 1.0.22" on the top left... 

Is there something special to do on Heroku? Like restart the dashboard or something? :/

PS: I've successfully updated my list of apps and icons in the parse-dashboard-config.json file, so this file modification works...

Thanks :)

**Comment by natanrolnik** [comment]
How is your package.json file? What version do you see there?

**Comment by nah0y** [comment]
You're right, it's 1.0.22 in there... weird.
For some reason it's not appearing as a modified file in SourceTree (it's not in .gitignore).

This would mean I have all the bug fixes but not the correct version number.
I thought this was not the case because I still have the chrome scrolling issue.

**Comment by nah0y** [comment]
Just opened it and it's 1.0.26 :/

**Comment by OpConTech** [comment]
I am having same issue where my package.json shows: 1.1.2
"dependencies": {
    "parse-dashboard": "^1.1.2",
}

But when I open the dashboard is shows older version in top left of dashboard view. 

So wondering if this is the same issue on this thread and how it was resolved.
