### ISSUE TITLE
Not able to edit or add row in mobile devices

### ISSUE THREAD

**Issue by monajafi** [parse-community/parse-dashboard#717]
It's not possible to enter new item or edit existing rows in mobile devices. by tapping in edit fields nothing happens and keyboard doesn't show to enter data

**Comment by mrmarcsmith** [comment]
+1

**Comment by ramiro-ciocca** [comment]
+1

**Comment by ramiro-ciocca** [comment]
+1

**Comment by ramiro-ciocca** [comment]
Hello, any news on this feature? It is very important to be able to edit data on mobile browsers.  Thanks!
