### ISSUE TITLE
Can’t search within an `Object` type column

### ISSUE THREAD

**Issue by oferRounds** [parse-community/parse-dashboard#720]
Would be great if we’d be able to search for a specific key/value pair within an `Object` type column (same as we can do with `Array`).

**Comment by oferRounds** [comment]
@natanrolnik

**Comment by ssamuli** [comment]
I have a working prototype for this. Will clean up and submit a PR later so you can have a look if it fits this purpose.

**Comment by natanrolnik** [comment]
Closed in #727
