### ISSUE TITLE
Eerror in opening the second relation in same table

### ISSUE THREAD

**Issue by akshaychauhan7737** [parse-community/parse-dashboard#723]
If I add two relations in the same table then I am not able to view the second relation from Parse dashboard

with error: 
https://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bparent%2C%20key%2C%20targetClassName%7D&args[]=

**Comment by dplewis** [comment]
I also received the same error when I added one relation to table.
Error received on both version 1.0.27 and 1.1.0


Invariant Violation: Minified React error #31; visit http://facebook.github.io/react/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B_objCount%2C%20className%2C%20id%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
