### ISSUE TITLE
I can't entrance parse dashboard on aws (amazon web service)

### ISSUE THREAD

**Issue by wisitb** [parse-community/parse-dashboard#733]
I can't entrance parse dashboard on aws (amazon web service)

It ask Username and Password

**Comment by dangerdan** [comment]
In your parse-dashboard-config.json file you can add the users as follows:

data: {
  "apps": [],
  "users": [
    {
       "user":"",
       "pass":""
    }
]
}

**Comment by Shalto** [comment]
I have my user and pass set, and still can;t login, tells me invalid username password

**Comment by gsoftinteractive** [comment]
The answer you are looking for is right here:
https://docs.bitnami.com/aws/faq/#using-aws-community-amis
