### ISSUE TITLE
Logging into parse dashboard

### ISSUE THREAD

**Issue by chriswill21** [parse-community/parse-dashboard#744]
I'm working on a project and have been able to log in to parse dashboard to monitor the users that were being generated in addition to the other parse objects created. I now need to grant another member of my team access to this dashboard. How can I do this?

**Comment by natanrolnik** [comment]
Have you read the Readme? It’s there:

https://github.com/parse-community/parse-dashboard/blob/master/README.md#configuring-basic-authentication
