### ISSUE TITLE
Parse-dashboard modifies the data of an array containing pointers into a different format

### ISSUE THREAD

**Issue by Apptation** [parse-community/parse-dashboard#756]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [ ] You're running version >=2.3.2 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
- Parse Server v2.5.3 on AWS EB
- NodeJS v4.2.0 (also tested on NodeJS v3.3.1)
- Parse Dashboard v1.1.0
- mongod version: 3.2.14 (MMAPv1) on MLAB
- Safari 10.1.1 on MacOS 10.12.5

#### Steps to reproduce
In cloud code, I'm storing data in the __User table as an array of pointers with a createdDate like this:
`var newsPointer = {"__type":"Pointer","className":"News","objectId":"5hRuMhTxFz"};
var todayNow = new Date();
var userEvent = 
{
	"news": newsPointer,
	"createdAt": todayNow
};
userObject.add("newsEvents", userEvent);`

**1.** This saves the data as expected when viewed in MLAB, or another raw data viewer:
![img_4217](https://user-images.githubusercontent.com/7025214/28554268-91abf016-70c6-11e7-938e-42102be6c054.PNG)

**2.** Then if viewed in Parse-Dashboard, the data appears in this format (no longer a pointer)
![screen shot 2017-07-24 at 10 56 51 pm](https://user-images.githubusercontent.com/7025214/28554312-ca48c48a-70c6-11e7-9e0e-c19885da7ed0.png)

**3.** If you then double click the cell data in "newsEvents", the data will be saved in that incorrect, modified format (screenshot taken with Parser app, after viewing the cell data in Parse-Dashboard):
![img_4218](https://user-images.githubusercontent.com/7025214/28554455-8a4edd0a-70c7-11e7-88fe-14413d021f65.PNG)

I can reproduce the above every time using Parse-Dashboard. To make things worse, intermittently the "news" data is shown as the whole object (showing all fields/data in the "news", where I expect to see the pointer data only).

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by Apptation** [comment]
Here's a screenshot of Parse Dashboard showing the full object data when hovering over the same field "userEvents":
![screen_shot_2017-07-25_at_10_30_15_pm](https://user-images.githubusercontent.com/7025214/28602144-72614250-718a-11e7-8158-927af2ce16b2.png)

This is how the raw data is stored when viewed in MLab, and Parser app for the same user:
![img_4240](https://user-images.githubusercontent.com/7025214/28602175-a59ab5de-718a-11e7-96d6-23fc908ab519.PNG)

**If the userEvents column/cell is opened up in Parse Dashboard, it will save the data in the incorrect format (the way it displays it in the preview**

**Comment by rihadavid** [comment]
I have the same problem with Date array, opening the cell followed by pressing enter or clicking somewhere else makes array of dates like `{"__type":"Date","iso":"2017-09-05T21:06:06.943Z"}` an array of strings like `"2017-09-05T21:06:06.943Z"`.

Can be avoided by pressing escape to leave the cell, but not easy to remember do it every time ..thus still a very dangerous side effect...

**Comment by ferrinho** [comment]
I'm having the exact same issue, and when working on dashboard, its corrupting data when column contains an array with pointers inside.  Any news on this?
