### ISSUE TITLE
Parse Dashboard Custom Login

### ISSUE THREAD

**Issue by nidhinprathap** [parse-community/parse-dashboard#760]
I have setup parse dashboard in aws server. I'm using it for sending push notifications. We have multiple apps in same server with individual apps for different users. Right now i have to modify my server.js for adding new apps and new users to Parse. Is there any possible way to do it from dashboard. 

Even if any one can throw some light what to modify to replace the existing login with an api based login. The 3rd party api will return if user is valid and which all apps are linked to his account.

Thanks in advance

**Comment by flovilmart** [comment]
this is not supported for the moment and not something we're looking forward to integrate. For now manage your users through the configuration files.

You could also use a parse-server to manage your parse-dashboard instances with a bit of creativity :)

**Comment by nidhinprathap** [comment]
Can u guide me a bit on customizing the dashboard to my req.
