### ISSUE TITLE
parse-dashboard: command not found

### ISSUE THREAD

**Issue by oligazar** [parse-community/parse-dashboard#761]
I installed parse dashboard with this command:

```
npm install -g parse-dashboard
/Users/Admin/.npm-global/bin/parse-dashboard -> /Users/Admin/.npm-global/lib/node_modules/parse-dashboard/bin/parse-dashboard
/Users/Admin/.npm-global/lib
└─┬ parse-dashboard@1.1.0 
  ├─┬ body-parser@1.17.2
  │ ├── depd@1.1.1 
  │ └── http-errors@1.6.2 
  └─┬ express@4.15.3
    ├─┬ finalhandler@1.0.4 
    │ └── debug@2.6.8 
    └─┬ proxy-addr@1.1.5 
      └── ipaddr.js@1.4.0 
```
But when I'm trying to run 
`parse-dashboard --appId myAppId --masterKey myMasterKey --serverURL "http://localhost:1337"`
after that I'm getting 
`-bash: parse-dashboard: command not found`

What am I missing here?

**Comment by agwl-saurabh** [comment]
you should install npm and node js to run this commend

**Comment by sobinsunny** [comment]
I also faced this issue. Please install `parse-dashboard` package with global tag
`npm install -g parse-dashboard`. it is working for me
Cheers

**Comment by montymxb** [comment]
Closing as installing globally with `-g` has no know issues as of this time. To be certain I double checked this myself, it does work as expected. This is likely an issue with your local install of npm, where the packages you are installing globally are not exported for use in your terminal.

**Comment by errazki1995** [comment]
> I also faced this issue. Install `parse-dashboard` npm package with global tag
> `npm install -g parse-dashboard`. it is working for me
> Cheers

if you look well , he was already using the command you stated , i have the same problem as him

**Comment by dplewis** [comment]
@errazki1995 Can you open a new issue so that we can track it?

**Comment by errazki1995** [comment]
> @errazki1995 Can you open a new issue so that we can track it?
  sure i think it's a vs code bug , to be honest

**Comment by errazki1995** [comment]
> @errazki1995 Can you open a new issue so that we can track it?

i just did now
