### ISSUE TITLE
Loads with "You don't have any apps"

### ISSUE THREAD

**Issue by timworx** [parse-community/parse-dashboard#762]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] You're running version >=1.0.23 of Parse Dashboard.

- [X] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I'm using Parse Server and Parse Dashboard, both run as express middleware. 

Parse Serve is up and running well, now I'm working on Parse Dashboard. 
The parse dashboard loads up to the point of telling me there are no apps. I can confirm that it is fetching the `parse-dashboard-config.json`, with a result of 

```json
{
 "apps": [ {
    "serverUrl": "http://localhost:1337/parse",
    "appId":"ParseServer",
    "masterKey":"ReplaceThisKey",
    "appName":"TheAppName"
}],
"newFeaturesInLatestVersion":[]}
```

Middleware initialization looks like: 

```javascript
const api = new ParseServer({
  databaseURI: databaseUri,
  cloud: __dirname + '/cloud/main.js',
  appId: appId,
  masterKey: masterKey, // Determine how to handle master key. Keep it secret!
  serverURL: serverUrl,
});

const dashboard = new ParseDashboard({
  apps: [
    {
      serverUrl: serverUrl,
      appId: appId,
      masterKey: masterKey,
      appName: 'TheAppName',
    },
  ],
}, true)

```

From what I can tell of the source code, it should attempt to then fetch information on the app, yet there are no network requests for that, and no console errors or otherwise visible errors. 

Any thoughts?

**Comment by timworx** [comment]
Every now and again, I'm reminded of what I love and don't love about Javascript. Its ability to fail so very, very silently falls into the don't love category. 

The issue above is that `serverUrl` should be `serverURL`. Interestingly, the dashboard doesn't put out any kind of errors when an app is missing a `serverURL`, if maintainers are open to changing that, I'd submit a PR.

**Comment by natanrolnik** [comment]
Go ahead @timworx!
