### ISSUE TITLE
n.map is not a function

### ISSUE THREAD

**Issue by lOCKemM** [parse-community/parse-dashboard#763]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ √] You're running version >=1.0.23 of Parse Dashboard.

- [ √] You're running version >=2.3.2 of Parse Server.

- [ √] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
I just click 【add a new column】and choice a wrong data-type,then bad things  happend.
The other class is running well，but this class which I choice wrong data-type。
what should I do ？like roll back?
#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by cruiser12** [comment]
Hello i have the same issue, and it seams the column is treated as "Array" and not as "Relation". But why?
