### ISSUE TITLE
css issue cannot scroll

### ISSUE THREAD

**Issue by evannamon** [parse-community/parse-dashboard#764]
.empty__1FYZ3 {
    position: fixed;
    left: 300px;
    top: 0;
    bottom: 0;
    right: 0;
}

make the position relative to scroll

**Comment by natanrolnik** [comment]
PRs are welcome

**Comment by AnikoV** [comment]
just add any row data

**Comment by montymxb** [comment]
The original issue referenced generated css, but I believe the associated src is in [Browser.scss starting at line 34](https://github.com/parse-community/parse-dashboard/blob/8db091a0092d05c55dbe120904f79e54f0deabc9/src/dashboard/Data/Browser/Browser.scss#L33...L39). Not really sure if this is actually an issue still though?
