### ISSUE TITLE
How can I see File class in the Browser of dashboard?

### ISSUE THREAD

**Issue by hzw1199** [parse-community/parse-dashboard#768]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.1.0 of Parse Dashboard.

- [x] You're running version >=2.6.0 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

How can I see File class in the Browser of dashboard?

**Comment by flovilmart** [comment]
File is not a class, just a type that we use in the schema / objects
