### ISSUE TITLE
Cannot change Basic auth password for DashBoard User.

### ISSUE THREAD

**Issue by spsingh** [parse-community/parse-dashboard#777]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ Y] You're running version >=1.0.23 of Parse Dashboard.

- [Y ] You're running version >=2.3.2 of Parse Server.

- [ Y] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse server 2.3.8, and Parse Dashboard 1.0.25 as Express(4.15.2) middleware. Node js 6.9.3 . Have supplied a Users[] to ParseDashboard() constructor.

#### Steps to reproduce
No way to change the password from UI/ config.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by flovilmart** [comment]
No, passwords need to be configured by an administrator and are not stored in a database, only on your dashboard configuration file.
