### ISSUE TITLE
I am working on project in node js for outlook api, code works great on localhost but when i run it on ec2 server it is not giving me any response can anyone help with this issue 

### ISSUE THREAD

**Issue by saurabhbandawar3** [parse-community/parse-dashboard#779]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [ ] You're running version >=2.3.2 of Parse Server.

- [ ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by agwl-saurabh** [comment]
Not able to understand the issue at all. Provide full details with code log etc what exactly your doing and what should be the result. 
if this is issue is specific to EC2 then seach in AWS form.

**Comment by flovilmart** [comment]
Closing as unrelated to parse-dashboard.
