### ISSUE TITLE
Either localhost nor 0.0.0.0 are valid addresses for local dashboard and parse server

### ISSUE THREAD

**Issue by MichelBahl** [parse-community/parse-dashboard#782]
- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Issue
Run parse dashboard without users works fine with localhost as serverURL,
if users were defined localhost break the dashboard, to fix this I have to enter a
static ip.

#### Environment Setup
Raspberry pi jessie 8.0
node 7.4.0
Parse Server 2.6.3
Parse Dashboard 1.1.0

#### Steps to reproduce

This won't work:

```json
{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMaster",
      "appName": "myAppTest"
    }
  ],
  "users": [
    {
      "user":"test",
      "pass":"test",
      "apps": [{"appId": "myAppId"}]
    }
  ]
}
```

This will work as expected:
```json
{
  "apps": [
    {
      "serverURL": "http://192.168.0.2:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMaster",
      "appName": "myAppTest"
    }
  ],
  "users": [
    {
      "user":"test",
      "pass":"test",
      "apps": [{"appId": "myAppId"}]
    }
  ]
}
```

This will work too:
```json
{
  "apps": [
    {
      "serverURL": "http://localhost:1337/parse",
      "appId": "myAppId",
      "masterKey": "myMaster",
      "appName": "myAppTest"
    }
  ]
}
```

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by somq** [comment]
@MichelBahl @natanrolnik Any news on this one ?
