### ISSUE TITLE
Image files not opening from dashboard

### ISSUE THREAD

**Issue by core2root** [parse-community/parse-dashboard#783]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by core2root** [comment]
Hi, about 3-4 weeks ago i noticed that i can't open image files thorough the dashboard, the files is not broken for sure because in my app i can see the images and all good, the only problem is to see them through the dashboard.
I updated parse-dashboard and parse-server to latest versions, also i use AWS and Mlab as my services.
Thank you.

**Comment by core2root** [comment]
Hi, about 3-4 weeks ago i noticed that i can't open image files thorough the dashboard, the files is not broken for sure because in my app i can see the images and all good, the only problem is to see them through the dashboard. I updated parse-dashboard and parse-server to latest versions, also i use AWS and Mlab as my services. Thank you.

**Comment by akshit-zaveri** [comment]
+1

**Comment by core2root** [comment]
for everyone who have this problem just update version of dashboard
