### ISSUE TITLE
How to add icon to app

### ISSUE THREAD

**Issue by zhanswift** [parse-community/parse-dashboard#786]
I try add icon and configure `conifg.json`:

    {
    "apps": [
      {
        "serverURL": "http://IP:1337/parse/kazepos",
        "appId": "",
        "masterKey": "",
        "appName": "MyApp",
        "iconName": "my-icon.png",
        "production": false
      }
    ],
    "users": [
      {
        "user":"myUser",
        "pass":"myPas"
      }
    ],
    "iconsFolder": "/home/myUser/parse-server-example/icon"
    }

And i got error when start dashboard: 

> Iconsfolder at path: home/myUser/parse-server-example/icon not found!

**Comment by acinader** [comment]
the icon folder needs to be relative.  if you are running the dashboard from the directory: `/home/myUser/parse-server-example`

then make `iconsFolder` simply `icon`

**Comment by acinader** [comment]
oooh, better yet, I read the [doc](https://github.com/parse-community/parse-dashboard#app-icon-configuration) ;) "The path of the iconsFolder is relative to the configuration file."

**Comment by acinader** [comment]
i'm gonna close this, feel free to re-open if you're still having problems.
