### ISSUE TITLE
docker image for parse-dashboard on docker hub

### ISSUE THREAD

**Issue by ctrongminh** [parse-community/parse-dashboard#789]
Hi all,

This is not an issue.
I just want to ask a question. 

For parse-server, we have the docker image at https://hub.docker.com/r/parseplatform/parse-server/, which will build the image with new release.

How about the parse-dashboard, I only see the image up to tag 1.0.22 at https://hub.docker.com/r/parseplatform/parse-dashboard/

Where can I find the parse-dashboard's docker image on the net with the latest release ?

Thanks

**Comment by flovilmart** [comment]
It’s probably a mis configuration on docker hub. I’ll have a look.

**Comment by flovilmart** [comment]
@ctrongminh I've setup parse-dashboard on docker hub so everything is built automatically. I had to rip-out the existing repo, to set it up I'll re-build the old images

**Comment by ctrongminh** [comment]
Thanks @flovilmart,
I saw the build tag 1.1.2 on docker hub.
However, I got the pull access denies as below.
"ERROR: pull access denied for parse-community/parse-dashboard, repository does not exist or may require 'docker login"

The error still occurs after I run docker login to login to docker hub.
Thanks

**Comment by ctrongminh** [comment]
Update
I'm able to pull the image now.

Thanks

**Comment by ctrongminh** [comment]
@flovilmart thank you for your help.
I got the image 1.1.2
