### ISSUE TITLE
Cannot build docker image with release 1.1.1

### ISSUE THREAD

**Issue by ctrongminh** [parse-community/parse-dashboard#790]
Hi,

I cannot build the docker image with the release 1.1.1. 
source: https://github.com/parse-community/parse-dashboard/archive/1.1.1.zip

I can build the docker image with the 1.1.0 version.

Please look at the log file for more details.

[parse-dashboard-1.1.1-image.log](https://github.com/parse-community/parse-dashboard/files/1420732/parse-dashboard-1.1.1-image.log)
Thanks

**Comment by ctrongminh** [comment]
Add more info.
Before pull request #709 with [commit](https://github.com/parse-community/parse-dashboard/commit/cf6ed6ff0c6da0fa00e2ac7f9c839b856b72ad25), I was able to build docker image.
After that, it throws error as above log file,

Thanks

**Comment by montymxb** [comment]
Looks like there is an issue with this release as stated in #792 . We'll be providing a patch shortly, but in the meantime I would recommend you roll back to the last stable release, i.e. in your case **1.1.0**.

Once a patch is in place we'll come back here to let you know!

**Comment by montymxb** [comment]
@ctrongminh Release [1.1.2](https://github.com/parse-community/parse-dashboard/releases/tag/1.1.2) contains a patch for the issues observed. This _should_ rectify your problems regarding your docker build. However, I'm leaving this open so we can have your confirmation on the matter. 

If it is _not_ resolved please let us know so we can look more directly at the underlying issue affecting docker builds specifically.

**Comment by flovilmart** [comment]
@ctrongminh building locally should be good now. Let us know if there's any issue.

**Comment by ctrongminh** [comment]
Thanks @montymxb and @flovilmart for quick response.
I was able to build the docker image locally,
