### ISSUE TITLE
readOnly apps and users: Missing guide or bug ?

### ISSUE THREAD

**Issue by ctrongminh** [parse-community/parse-dashboard#798]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version =1.1.2 of Parse Dashboard.

- [x] You're running version =2.6.5 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

I found two guideline issues when following the guide for new feature readonly users:

1. I followed the https://github.com/parse-community/parse-dashboard#makings-users-read-only but the error occurs in the parse-dashboard container.
```
"users": [
     {
       "user":"user1",
       "pass":"pass1",
       **"readOnly": true,**
       "apps": [{"appId": "myAppId1"}, {"appId": "myAppId2"}]
```
```
Error: You need to provide a readOnlyMasterKey to use read-only features.
    at /src/Parse-Dashboard/app.js:111:19
    at Array.map (native)
    at /src/Parse-Dashboard/app.js:108:39
```
After logging in to the parse-dashboard, it says server error as image below
![server_error](https://user-images.githubusercontent.com/28387246/32153218-bcd9e3d8-bd5b-11e7-89cb-c0a8ae73a2d9.png)

 After I specify the readOnlyMasterKey (same readOnlyMasterKey as when we start parse-server) in the "apps": [{"...": "..."}], the error is gone. I think we need to update the guide line.

2. I followed https://github.com/parse-community/parse-dashboard#making-users-apps-readonly, but after logging in the the parse-dashboard I receive message: You dont have any apps.
```
"users": [
     {
       "user":"user1",
       "pass":"pass1",
       "apps": [{"appId": "myAppId1", **"readOnly": true**}, {"appId": "myAppId2"}]
     } ]
```
![parse-dashboard-no-apps](https://user-images.githubusercontent.com/28387246/32153296-2c9b0bc0-bd5c-11e7-8d11-7e09d552f602.png)

After I specify the readOnlyMasterKey (same readOnlyMasterKey as when we start parse-server) in the "apps": [{"...": "..."}], the error is gone. I think we need to update the guide line

So in both cases, I think we need to update the guideline to include the readOnlyMasterKey in the "apps": [{"...": "..."}]. Do I understand correctly ?

Thanks

**Comment by flovilmart** [comment]
Closing as documented in the README ;)
