### ISSUE TITLE
Past Pushes Won't Display

### ISSUE THREAD

**Issue by adammlevy** [parse-community/parse-dashboard#801]
- [x ] You're running version >=1.0.23 of Parse Dashboard.

- [x ] You're running version >=2.3.2 of Parse Server.

- [x ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse-Dashboard running on Heroku 

#### Steps to reproduce
 - Send push notification from worker dyno.
 - Log into parse-dashboard to see Past Pushes
 - Click on push that was sent or not sent
 - Nothing shows up

#### Logs/Trace
Here is the push status object as stored in mLab:

```
{
    "_id": "RxjNFEgFRQ",
    "pushTime": "2017-10-09T03:20:09.586Z",
    "query": "{\"channels\":\"CHPIncident-SantaFeSprings\"}",
    "payload": "{\"alert\":{\"title\":\"CHP Incident Santa Fe Springs\",\"body\":\"Santa Fe Springs: Traffic Hazard at I605 N   Firestone Blvd\"},\"chpIncident\":{\"area\":\"Santa Fe Springs\",\"logType\":\"1125-Traffic Hazard\",\"location\":\"I605 N / Firestone Blvd\"},\"expiration_time\":\"2017-10-09T07:20:09.069Z\",\"sound\":\"chp_incident.caf\",\"PushType\":\"CHPIncident\"}",
    "source": "rest",
    "status": "succeeded",
    "numSent": 0,
    "pushHash": "a7c6e986a076e9e8ced26dcc8d4eea56",
    "_wperm": [],
    "_rperm": [],
    "_acl": {},
    "_created_at": {
        "$date": "2017-10-09T03:20:09.587Z"
    },
    "_updated_at": {
        "$date": "2017-10-09T03:20:10.119Z"
    },
    "numFailed": 1,
    "failedPerType": {
        "ios": 1
    }
}
```

**Comment by alexblack** [comment]
Happens for me too, seems like something that should be fixed?

**Comment by alexblack** [comment]
We're running parse dashboard 1.2.0.  Not sure what the repro steps are.  Where should I look for the error to help narrow this down? Is there a log?

<img width="1399" alt="screenshot 2018-05-14 21 10 38" src="https://user-images.githubusercontent.com/148930/40036268-54753734-57bb-11e8-8118-b4d187f072b0.png">

**Comment by alexblack** [comment]
We also run on Heroku and mLab like the OP.

**Comment by alexblack** [comment]
Screenshot of all network XHR (I couldn't find a way to export it all.. anyone know one?)

<img width="1579" alt="screenshot 2018-05-14 21 19 15" src="https://user-images.githubusercontent.com/148930/40036471-7bc7ea4c-57bc-11e8-92fb-1cac2f724d07.png">

**Comment by alexblack** [comment]
All other parts of the dashboard seem to work fine, including listing past pushes... But this problem appears to happen for every past push

**Comment by alexblack** [comment]
Here's the HAR file for the POST to `https://data.staging.getinvoicesimple.com/parse/classes/_PushStatus`

[parse-dashboard.getinvoicesimple.com.har.zip](https://github.com/parse-community/parse-dashboard/files/2003471/parse-dashboard.getinvoicesimple.com.har.zip)

Here's the response

```
{"results":[{"objectId":"vT77c6QI3W","pushTime":"2018-05-14T14:44:09.484Z","query":"{\"user\":{\"$inQuery\":{\"where\":{\"account\":{\"__type\":\"Pointer\",\"className\":\"Account\",\"objectId\":\"Qq6tfNsUoR\"}},\"className\":\"_User\"}},\"objectId\":{\"$ne\":\"Y1jVkY4LZp\"},\"deviceType\":{\"$ne\":\"web\"},\"lastSeenAt\":{\"$gt\":{\"__type\":\"Date\",\"iso\":\"2018-04-14T14:44:09.444Z\"}}}","payload":"{\"pushType\":4,\"pushVer\":1,\"fromInstallation\":\"Y1jVkY4LZp\",\"timestamp\":1526309053323,\"aps\":{\"content-available\":1},\"isId\":\"4299c240-5785-11e8-9be6-a7fdcaf3dcac\"}","source":"rest","status":"succeeded","numSent":0,"pushHash":"d41d8cd98f00b204e9800998ecf8427e","createdAt":"2018-05-14T14:44:09.484Z","updatedAt":"2018-05-14T14:44:09.770Z","numFailed":1,"failedPerType":{"android":1},"ACL":{}}]}
```

**Comment by alexblack** [comment]
Happy to give you a login to our dashboard if you'd like to see it in action.

**Comment by alexblack** [comment]
Does that give you the info you'd need?

**Comment by flovilmart** [comment]
I havent had a chance to dig further with the given info. You’re adamant there’s no rendering issue on the react side?

Do you have the payload / Object that is failing to display?

**Comment by alexblack** [comment]
Oh, i was asking if the info looked like what you needed (before digging in).

I'm not adamant about anything :)  How would I check if its a "rendering issue on the react side"?  

I think the payload is in the comment above https://github.com/parse-community/parse-dashboard/issues/801#issuecomment-389040005

**Comment by flovilmart** [comment]
@alexblack there are warnings in the console, in one of the screenshots you just posted. Can you setup the push locales as recommended in the warnings, and try again?

**Comment by alexblack** [comment]
Sure, I configured push locales. I'm still able to repro the problem.

![screen shot 2018-06-11 at 5 42 24 am](https://user-images.githubusercontent.com/148930/41211844-623f8646-6d3a-11e8-8b64-e3f48457dbb5.png)

**Comment by flovilmart** [comment]
Can you show the network tab please, more particularly, the request / responses relative to push.

**Comment by alexblack** [comment]
I did provide the entire response in a comment above, and I provided a HAR export of all the network activity.  Does that help?

**Comment by alexblack** [comment]
Here is a screenshot.

![screen shot 2018-06-11 at 1 59 46 pm](https://user-images.githubusercontent.com/148930/41230351-c06d763e-6d7f-11e8-89fe-d266d5365a70.png)

**Comment by flovilmart** [comment]
Can you post also the request / response for the _PushStatus call?

**Comment by alexblack** [comment]
![screen shot 2018-06-11 at 2 10 23 pm](https://user-images.githubusercontent.com/148930/41230734-34a8ecda-6d81-11e8-887c-2e31098e45d6.png)

**Comment by alexblack** [comment]
![screen shot 2018-06-11 at 2 11 23 pm](https://user-images.githubusercontent.com/148930/41230787-5e0c4428-6d81-11e8-9a98-2ea3d0680186.png)

**Comment by flovilmart** [comment]
Cam you provide the full payload for the response please?

**Comment by alexblack** [comment]
It's already provided in a previous comment

**Comment by alexblack** [comment]
```
{"results":[{"objectId":"vT77c6QI3W","pushTime":"2018-05-14T14:44:09.484Z","query":"{\"user\":{\"$inQuery\":{\"where\":{\"account\":{\"__type\":\"Pointer\",\"className\":\"Account\",\"objectId\":\"Qq6tfNsUoR\"}},\"className\":\"_User\"}},\"objectId\":{\"$ne\":\"Y1jVkY4LZp\"},\"deviceType\":{\"$ne\":\"web\"},\"lastSeenAt\":{\"$gt\":{\"__type\":\"Date\",\"iso\":\"2018-04-14T14:44:09.444Z\"}}}","payload":"{\"pushType\":4,\"pushVer\":1,\"fromInstallation\":\"Y1jVkY4LZp\",\"timestamp\":1526309053323,\"aps\":{\"content-available\":1},\"isId\":\"4299c240-5785-11e8-9be6-a7fdcaf3dcac\"}","source":"rest","status":"succeeded","numSent":0,"pushHash":"d41d8cd98f00b204e9800998ecf8427e","createdAt":"2018-05-14T14:44:09.484Z","updatedAt":"2018-05-14T14:44:09.770Z","numFailed":1,"failedPerType":{"android":1},"ACL":{}}]}
```

**Comment by alexblack** [comment]
Is that what you're looking for?

**Comment by flovilmart** [comment]
Found the issue, this occurs when sending silent push / when the alert is not properly set in the push payload.

I've opened a PR and this will be part of next release.

**Comment by alexblack** [comment]
Great stuff!
