### ISSUE TITLE
Issue with Node 8 - `SyntaxError: Unexpected token ...` in browser

### ISSUE THREAD

**Issue by gianpaj** [parse-community/parse-dashboard#804]
- [x] You're running version >=1.1.2 of Parse Dashboard.

- [x] You're running version >=2.6.5 of Parse Server (using docker image from Docker hub)

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Using latest LTS Node release.
```
node --version
v8.9.0

npm --version
5.5.1
```

#### Steps to reproduce

Using the latest git repo from master or downloading from npm as global cli:
```
$ npm start

> parse-dashboard@1.1.2 start /Users/gianfranco/temp/parse-dashboard
> node ./Parse-Dashboard/index.js

Iconsfolder at path: /Users/gianfranco/temp/parse-dashboard/Parse-Dashboard/icons not found!
The dashboard is now available at http://0.0.0.0:4040/
```

```
$ parse-dashboard --appId snowflake --masterKey Master --serverURL "http://localhost:1337/parse" --appName optionalName
The dashboard is now available at http://0.0.0.0:4040/
```

#### Logs/Trace
In the browser Dev console you get:
```
Uncaught SyntaxError: Unexpected token <
```
Looks like the JS bundle is returning an HTML webpage `<script src="/bundles/dashboard.bundle.js"></script>` instead of the JS file.

**Comment by flovilmart** [comment]
Can you run `npm run build` and check if there are any errors?

**Comment by gianpaj** [comment]
That worked! Not sure if I messed up the packages installation while switching Node versions or misunderstood the build/installation process.

**Comment by flovilmart** [comment]
yep that's odd, `build` should have been run part of `npm install` but perhaps it's not run on node 8.

**Comment by gianpaj** [comment]
I don't see any `postinstall` script in the [package.json](https://github.com/parse-community/parse-dashboard/blob/master/package.json#L84-L93).

https://docs.npmjs.com/misc/scripts

**Comment by flovilmart** [comment]
it's `prepublish`
