### ISSUE TITLE
support requiresAuthentication for class security

### ISSUE THREAD

**Issue by jadsonlourenco** [parse-community/parse-dashboard#805]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [YES] You're running version >=1.0.23 of Parse Dashboard.

- [YES ] You're running version >=2.3.2 of Parse Server.

- [YES ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Node 8.9.0
macOS 10.13

#### Steps to reproduce
I can't set the rule `requiresAuthentication` from the security modal, only by the REST API.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by yomybaby** [comment]
I think this is very handy.

**Comment by santiagosemhan** [comment]
+1

**Comment by henninghorn** [comment]
+1

**Comment by beiguancyc** [comment]
+1

**Comment by davimacedo** [comment]
I think https://github.com/parse-community/parse-dashboard/pull/1478 closed this one.
