### ISSUE TITLE
Prompt form tampered with, what is the problem?

### ISSUE THREAD

**Issue by lxq20081128** [parse-community/parse-dashboard#806]
Prompt form tampered with, what is the problem?

**Comment by lxq20081128** [comment]
v1.1.2 version of the problem, with the https prompt tampered with form, with http and added to allow set, suggesting that must be https

**Comment by fxchou123** [comment]
same issue here, I'm using Heroku as server

**Comment by stage88** [comment]
In my case I fixed it by changing from 

```
let dashboard = new ParseDashboard({
  ...
}, true);
```

to 

```
let dashboard = new ParseDashboard({
  ...
}, {
  allowInsecureHTTP: true
});
```

**Comment by mmarshak** [comment]
Same issue, I get that error. And it does not allow me to access the dashboard.

**Comment by lxq20081128** [comment]
Hi, I used what you said, still does not work in v1.1.2 version.






------------------
              
         公司网址：http://www.mengsens.com/
         
         
                      广东梦森信息科技有限公司 -              廖晓清
             公司地址：广州市海珠区新港西路135号中山大学国家大学科技园B座1308室
         
         手机号码：139 2609 5308
         QQ号码 ：187 2117 737
         主营业务：快递鸽 - 快递物流综合解决方案
     
     
     
     祝：生活愉快！一切顺利！
 

 
 
 
------------------ Original ------------------

**Comment by stage88** [comment]
@lxq20081128 Sorry that was my mistake, it actually doesn't work even if you what I suggested, which is why I deleted my comment :)

Hopefully we can get a response from one of the contributors as this is currently preventing me from upgrading.

**Comment by montymxb** [comment]
@lxq20081128 I'm assuming you're referrig to #810? There were some pretty good details provided in that issue, I'm following up there currently. Let me know if this is something else though.

**Comment by stage88** [comment]
Hi @montymxb, I think this issue is a different one, here is my config:
```
// configure Parse dashboard
let dashboard = new ParseDashboard({
  'apps': [{
    'serverURL': env.parseServerUrl,
    'appId': env.appId,
    'masterKey': env.masterKey,
    'appName': 'APP NAME'
  }],
  'users': [{
    'user': 'whatever',
    'pass': env.dashboardAdminPassword
  }],
  'useEncryptedPasswords': false,
  'trustProxy': true
}, {
  allowInsecureHTTP: true // HTTPS terminated by NGINX
});
```

Here is what displays after I successfully log in:
![image](https://user-images.githubusercontent.com/9906800/33016061-27d04bb4-ce41-11e7-9950-895476c5c5f6.png)

On localhost this works fine, however in Development which is hosted in the cloud where the dashboard is behind NGINX that terminates HTTPS, I get the above message.

**Comment by montymxb** [comment]
This looks like this is [CSRF](https://github.com/parse-community/parse-dashboard/blob/66d087e22ccddfd2a0b613743238d9cc028d6e3e/Parse-Dashboard/app.js#L74) protection coming into play, specifically triggered when an error code of **EBADCSRFTOKEN** is reported. I'll look into this further when I have a moment.

**Comment by tjlian616** [comment]
I started to have the same issue with aws hosted server (v1.1.2) since yesterday. It was working fine before. I don't remember making any changes to my configuration or app version.

**Comment by dovewi** [comment]
same issue v1.1.2,parse-dashboard and parse-server  in same server

**Comment by montymxb** [comment]
Has anyone seen this via localhost by any chance? Or is the exclusively on remote services?

**Comment by gearsion** [comment]
Same issue v. 1.1.2 on Google App Engine. Though I can finally log in after few attempts.

**Comment by tcha-tcho** [comment]
I'm still having problems with this `form tampered with`. Someone found any workaround on Heroku?

**Comment by ali-dev** [comment]
We are also experiencing the same issue on v.1.1.2

**Comment by montymxb** [comment]
@ali-dev Noted regarding **1.1.2**. Until we can replicate this we won't be able to do to much. It does _seem_ like a bug, but it could be a server config issue still. This is considering that all reports are coming from 3rd parties hosting a dashboard. 

Once we can reproduce this we can start moving onto a solution. In the meantime if anyone can provide further details as to conditions that triggered this it would be much appreciated. As well as any suspected changes that may have triggered this to pop up.

**Comment by tcha-tcho** [comment]
Hi, @montymxb! It seems to be an issue with the CSRF protection token that isn't valid (even with allowInsecureHTTP set to true). You can replicate this firing a Heroku free server with dashboard. This already happened before: https://github.com/parse-community/parse-dashboard/issues/664
Thank you!

**Comment by tcha-tcho** [comment]
@montymxb, couldn't this be a problem related with csurf?

**Comment by montymxb** [comment]
@tcha-tcho as mentioned [above](https://github.com/parse-community/parse-dashboard/issues/806#issuecomment-345805254) we are aware this is a CSRF token issue. As for the details regarding heroku & the duplicate issue thanks for bringing that to my attention. I'll see if we can replicate this on heroku.

**Comment by montymxb** [comment]
Keeping this open for now as this (and the older issue #664) both contain details that may be helpful in resolving this.

**Comment by monajafi** [comment]
The issue has been resolved by downgrade parse-dashboard installation to version 1.1.0
npm install parse-dashboard@1.1.0
this is a bug in latest version 1.1.2

**Comment by montymxb** [comment]
I'll have to verify that when i look into testing against heroku's setup.

**Comment by JeremyPlease** [comment]
I ran into this issue after upgrading to 1.1.2 and I hunted down the root cause.

As per PR #774 ([this line of code](https://github.com/parse-community/parse-dashboard/pull/774/files#diff-9096cff027b63dca795e83c6d4140021R47)), the cookie secret will be set to a random value if you do not set it yourself. This is intentional and [documented in the CLI](https://github.com/parse-community/parse-dashboard/pull/774/files#diff-7a1c52248764301345435dccf3ec051eR28).

So, if you are running in a load balanced environment (or in using NodeJS cluster) be sure to set your `cookieSessionSecret`:

From CLI:
`--cookieSessionSecret "your-secret-here"`

From NodeJS (`options` is the 2nd argument of constructor):
```
new ParseDashboard({
// settings here
}, {
  cookieSessionSecret: 'your-secret-here'
});
```

**Comment by montymxb** [comment]
Anyone can confirm setting the above ^ helps with the issue here?

**Comment by monajafi** [comment]
Hi @JeremyPlease 
Thanks a lot for your great help , I've updated from version 1.1.0 to latest version in ubuntu vps
by setting the cookieSessionSecret as ParseDashboard 2nd argument of constructor the problem has solved
I love parse server and dashboard and gets happier when I see an active contribution on it
many thanks

**Comment by shkesar** [comment]
@JeremyPlease You found it. Thanks.

**Comment by shkesar** [comment]
This can be closed now.

**Comment by montymxb** [comment]
Glad to see it's resolved 👍

**Comment by EricNetsch** [comment]
@montymxb  @JeremyPlease This fix worked for me using node.js Throng clustering on Heroku. 
What is the best practice for the `cookieSessionSecret`? Generate a new key? Use Master Key? Use whatever ex. 'magic'?

Thanks

**Comment by flovilmart** [comment]
There is no need to use clusterting in the dashboard as it’s just a client app. The server side should only be hit with the authentication.

The cookieSessionSecret can be anything, but long chain of characters are preferred. See this thread https://stackoverflow.com/questions/5343131/what-is-the-sessions-secret-option

**Comment by Gowtham029** [comment]
Hi All,

Still, I am unable to fix this issue.

Please let me know what I am missing in this config

parser-dashabord - @1.2.0
parse-server - @3.1.2

Parse-Dashboard
var express = require('express');
var ParseDashboard = require('parse-dashboard');

var options = {
allowInsecureHTTP: true,
cookieSessionSecret: '***'
};

var dashboard = new ParseDashboard({
"apps": [{
"serverURL": "http://parseserver:1337/parse",
"appId": "my-mobile-apps",
"masterKey": "***,
"appName": "First App"
}],
"users": [{
"user": "user1",
"pass": "pass",
"apps": [{
"appId": "my-mobile-apps"
}]
}],
"trustProxy": 1
}, options);

var app = express();

// make the Parse Dashboard available at /dashboard
app.use('/dashboard', dashboard);

var httpServer = require('http').createServer(app);
httpServer.listen(4040,function(){
console.log("listening")
});

Parse Server
var express = require('express');
var path = require('path');
var ParseServer = require('parse-server').ParseServer;
var app = express();

var api = new ParseServer({
databaseURI: 'mongodb://mc-mongo/my-mobile-apps', // Connection string for your MongoDB database
cloud: '../../app/src/cloud/main.js', // Absolute path to your Cloud Code
appId: 'my-mobile-apps',
masterKey: '***', // Keep this key secret!
serverURL: 'http://localhost:1337/parse', // Don't forget to change to https if needed
liveQuery: {
classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
}
});

// Serve the Parse API on the /parse URL prefix
app.use('/parse', api);

app.use('/public', express.static(path.join(__dirname, '/public')));

app.listen(1337, function () {
console.log('parse-server-example running on port 1337.');
});

**Comment by JeremyPlease** [comment]
@Gowtham029 From your code I can see:

```
var options = {
  allowInsecureHTTP: true,
  cookieSessionSecret: '***'
};
var dashboard = new ParseDashboard({
  // ...
}, options);
```

That is all that is needed to fix the "form tampered with" error that is reported in this issue. 

If you are still getting the same error, there must be something else going on. Check to make sure your new code is actually being used and make sure you don't have any browser extensions that could change hidden form values.

**Comment by pkhutal** [comment]
@JeremyPlease  Same issue. After adding the loadBalancer  the server is working but the dashboard is giving same error "form tampered with".  Any idea what i am missing? 

Thank you.

**Comment by pkhutal** [comment]
> Hi All,
> 
> Still, I am unable to fix this issue.
> 
> Please let me know what I am missing in this config
> 
> parser-dashabord - @1.2.0
> parse-server - @3.1.2
> 
> Parse-Dashboard
> var express = require('express');
> var ParseDashboard = require('parse-dashboard');
> 
> var options = {
> allowInsecureHTTP: true,
> cookieSessionSecret: '***'
> };
> 
> var dashboard = new ParseDashboard({
> "apps": [{
> "serverURL": "http://parseserver:1337/parse",
> "appId": "my-mobile-apps",
> "masterKey": "***,
> "appName": "First App"
> }],
> "users": [{
> "user": "user1",
> "pass": "pass",
> "apps": [{
> "appId": "my-mobile-apps"
> }]
> }],
> "trustProxy": 1
> }, options);
> 
> var app = express();
> 
> // make the Parse Dashboard available at /dashboard
> app.use('/dashboard', dashboard);
> 
> var httpServer = require('http').createServer(app);
> httpServer.listen(4040,function(){
> console.log("listening")
> });
> 
> Parse Server
> var express = require('express');
> var path = require('path');
> var ParseServer = require('parse-server').ParseServer;
> var app = express();
> 
> var api = new ParseServer({
> databaseURI: 'mongodb://mc-mongo/my-mobile-apps', // Connection string for your MongoDB database
> cloud: '../../app/src/cloud/main.js', // Absolute path to your Cloud Code
> appId: 'my-mobile-apps',
> masterKey: '***', // Keep this key secret!
> serverURL: 'http://localhost:1337/parse', // Don't forget to change to https if needed
> liveQuery: {
> classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
> }
> });
> 
> // Serve the Parse API on the /parse URL prefix
> app.use('/parse', api);
> 
> app.use('/public', express.static(path.join(__dirname, '/public')));
> 
> app.listen(1337, function () {
> console.log('parse-server-example running on port 1337.');
> });

@Gowtham029 I am getting the same error, did you find the solution?

Thank you.

**Comment by flovilmart** [comment]
The trust proxy flag does into the options object, not in the configuration 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pkhutal** [comment]
> The trust proxy flag does into the options object, not in the configuration
> 
> Sent with [GitHawk](http://githawk.com)

@flovilmart  thank you for your quick response.

Actually the problem solved by downgrading the parse dashboard version and then npm install.!

**Comment by flovilmart** [comment]
If you downgraded, this is not solved, you are potentially exposed to security issues. You should always run the latest available version.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pkhutal** [comment]
Thats right, will work on the latest version.  
@flovilmart  thank you!

**Comment by syampsijk** [comment]
So only change i need to do is add cookieSessionSecret value in options ?

Should session secret value be a fixed value 
var options = {
allowInsecureHTTP: true,
cookieSessionSecret: 'fixedvalue'
};
