### ISSUE TITLE
allowInsecureHTTP not working after release 1.1.2

### ISSUE THREAD

**Issue by omarkhaled11** [parse-community/parse-dashboard#810]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
    "parse": "~1.8.0",
    "parse-dashboard": "^1.1.0",
    "parse-server": "2.5.3",

#### Steps to reproduce
- set parse-dashboard version to "^1.1.0" or "1.1.2", with allowInsecureHTTP: true in config
- go to the dashboard link, you will get the message that the dashboard is only available on secure connections

- Changing it back to "1.1.0" fixes the issue

**Comment by stage88** [comment]
Maybe related to #806...

**Comment by montymxb** [comment]
@omarkhaled11 the code responsible for this is a security check in [app.js](https://github.com/parse-community/parse-dashboard/blob/66d087e22ccddfd2a0b613743238d9cc028d6e3e/Parse-Dashboard/app.js#L91).
```js
if (!requestIsLocal && !req.secure && !allowInsecureHTTP) {
  //Disallow HTTP requests except on localhost, to prevent the master key from being transmitted in cleartext
  return res.send({ success: false, error: 'Parse Dashboard can only be remotely accessed via HTTPS' });
}
```
If the request is not local (localhost, 127.0.0.1, ::1, etc) it is subjected to a subsequent check on the 'secure' status of the request and against whether the config allows insecure http.

Thanks for the details you provided. Setting the `allowInsecureHTTP` option to true and shifting between versions **1.1.0** and **1.1.2** did _not_ show any evidence of the problem for me. Here is the config that I used.
```js
var dashboard = new ParseDashboard({
  apps: [
    {
      serverURL: 	'http://localhost:1337/parse',
      appId: 		'app-id-here',
      masterKey: 	'master-key-here',
      appName: 		'app-name-here',
      production: false
    }
  ],
  users: [
    {
      user:"user",
      pass:"__some_password_hash__"
    }
  ],
  useEncryptedPasswords: true
}, {
  allowInsecureHTTP: true
});
```
Note that although I _did use localhost (which would negate the secure check) I did remove the `requstIsLocal` condition. From there setting `allowInsecureHTTP` to **false** did properly negate my requests, while settting it to **true** worked just fine.

It's possible that there might be some other issue going on related to your config specifically. If you could provide your config (stripped of sensitive info of course) that would be helpful in diagnosing this.

**Comment by omarkhaled11** [comment]
@montymxb  Here's my config:
```
var dashboardConfig = {
  allowInsecureHTTP: true,
  apps: [
    {
      serverURL: 	'http://localhost:1337/parse',
      appId: 		'app-id-here',
      masterKey: 	'master-key-here',
      appName:          'app-name-here',
    }
  ],
  users: [
    {
      user:"user",
      pass:"__some_password_hash__"
    }
  ]
}
var dashboard = new ParseDashboard(
  dashboardConfig,
  dashboardConfig.allowInsecureHTTP
)
```

**Comment by flovilmart** [comment]
@omarkhaled11 you need to pass the second parameter of the `ParseDashboard` constructor as an object `{allowInsecureHTTP: true}` as @montymxb is suggesting.

**Comment by montymxb** [comment]
Yep, goes as second argument independent of the first object.

**Comment by omarkhaled11** [comment]
I tried the config you pasted with passing `{allowInsecureHTTP: true}` as an object in the second argument and it worked with version 1.1.2  :) I guess the issue was with my config, it's strange that it worked before with version 1.1.0. I re-checked the documentation and it's properly documented as well. I guess I got my old config from some blog. Thanks!

**Comment by montymxb** [comment]
@omarkhaled11 No problem!
