### ISSUE TITLE
Readme Table of Contents Missing Parts

### ISSUE THREAD

**Issue by montymxb** [parse-community/parse-dashboard#815]
The [navigation section](https://github.com/parse-community/parse-dashboard#parse-dashboard) for the README is missing some new sections that have since been added. This is just making a note of it so that we don't forget to update it to properly represent what sections are available in the README. 

This is up for grabs if anyone wants to help us out, pretty straight forward and it would be greatly appreciated!

**Comment by Himanshu-Mishr** [comment]
Hi @montymxb, I have submit a PR for this, please review it and let me know if any changes are required.

**Comment by natanrolnik** [comment]
Thanks for the PR, @Himanshu-Mishr ! Merged!
