### ISSUE TITLE
Show all uploaded files.

### ISSUE THREAD

**Issue by step4** [parse-community/parse-dashboard#817]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [*] You're running version >=1.0.23 of Parse Dashboard.

- [*] You're running version >=2.3.2 of Parse Server.

- [*] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Hi,

is there a way to show all uploaded files on the Parse Dashboard?
I can find them via a MongoDB Client, so maybe there is plugin for that.

**Comment by joshuadiezmo** [comment]
I think Parse server should have this features first before parse dashboard. Parse dashboard just fetching api from parse server.
