### ISSUE TITLE
use shouldComponentUpdate on stateful components

### ISSUE THREAD

**Issue by aweary** [parse-community/parse-dashboard#82]
I looks like there's only [one component](https://github.com/ParsePlatform/parse-dashboard/blob/b7efb406769eeb9c586225060167a5e045299b80/src/dashboard/Push/PushAudiencesData.react.js) that uses `shouldComponentUpdate`.

React provides the `shalowCompare` addon which provides functionality similar to the `react-addons-pure-render-mixin` for ES6 classes.

https://facebook.github.io/react/docs/shallow-compare.html

``` js
var shallowCompare = require('react-addons-shallow-compare');
export class SampleComponent extends React.Component {
  shouldComponentUpdate(nextProps, nextState) {
    return shallowCompare(this, nextProps, nextState);
  }

  render() {
    return <div className={this.props.className}>foo</div>;
  }
}
```

If the parse team would be open to adding these checks to stateful components, it's a simple implementation which usually comes with decent performance benefits.

**Comment by peterdotjs** [comment]
@Aweary thanks for bringing this up! 

As the add on is still considered experimental I'm hesitant to add it in our other components for a perf gain which may be unnoticeable for end user.

**Comment by Aweary** [comment]
Have you guys done any performance testing using the `react-addons-perf` package? I well implemented `shouldComponentUpdate` function can have a very noticeable impact on performance in some cases.

React considers essentially all their addons experimental from what I can see, in the sense that they are more likely to change on a more frequent basis. Even `PureRenderMixin` is considered experimental but it has been heavily adopted by the community for a while now. I would say that in this case experimental !== unstable.

You can read over the [source of `shalowCompare`](https://github.com/facebook/react/blob/3b96650e39ddda5ba49245713ef16dbc52d25e9e/src/addons/shallowCompare.js), it's very simple.

Baring all this, @peterdotjs we could always implement `shouldComponentUpdate` functions manually per component.

**Comment by peterdotjs** [comment]
Yup they're all considered experimental and agreed that it doesn't equate to being unstable. My hesitancy is more from ensuring we've proved there are noticeable benefits before adding it in.

We haven't done much performance testing but if we can show performance improvement in the component heavy pages (data browser for one) we would totally be open to using it :)

**Comment by Aweary** [comment]
I have a feeling that it would definitely bring some performance gains, but I haven't tested it either. I'll try to get a report up when I get a chance.
