### ISSUE TITLE
ANALYTICS. dismiss

### ISSUE THREAD

**Issue by xingyinbuli** [parse-community/parse-dashboard#822]
hi~can i find analytics in dashboard?
<img width="526" alt="2017-12-07 4 58 08" src="https://user-images.githubusercontent.com/16410050/33706813-45e22ed8-db70-11e7-9ba8-927b3b8f936a.png">
我没有发现那个😭求解答

**Comment by flovilmart** [comment]
Analytics are not part of parse-server anymore. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
