### ISSUE TITLE
Cloud jobs and verbose logging are not displayed.

### ISSUE THREAD

**Issue by step4** [parse-community/parse-dashboard#823]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

[*] You're running version >=1.0.23 of Parse Dashboard.

[*] You're running version >=2.3.2 of Parse Server.

[*] You've searched through existing issues. Chances are that your issue has been reported or resolved before.

Hi,

I'm using the parse-server and parse-dashboard in an express app.

`

    var express = require('express');
    var ParseServer = require('parse-server').ParseServer;
    var ParseDashboard = require('parse-dashboard');

    var api = new ParseServer({
    	"appId":"testapp",
        "masterKey":"masterkey",
        "restAPIKey":"restapikey",
        "serverURL": "http://localhost/parse",
        "databaseURI":"mongodb://localhost/parse",
        "cloud":"./cloud/main.js",
        "logLevel":'VERBOSE'
    });
    
    var options = { allowInsecureHTTP: true };
    
    var dashboard = new ParseDashboard({
        "apps": [
            {
              "serverURL": "http://localhost/parse",
              "appId": "testapp",
              "masterKey": "masterkey",
              "appName": "MyTestApp",
              "useMasterKey":"true",
            }
          ],
          "users": [
              {
                "user":"admin",
                "pass":"admin"
              }
          ],
          "useEncryptedPasswords": false,
    }, options);
    
    var app = express();
    
    // make the Parse Server available at /parse
    app.use('/parse', api);
    
    // make the Parse Dashboard available at /dashboard
    app.use('/dashboard', dashboard);
    
    
    var httpServer = require('http').createServer(app);
    httpServer.listen(80);
`

It's working fine with  the REST-API. 
I have two problems:
1. It seems the Loglevel is set to Verbose but I do not get verbose outputs. In fact i won't get any logs unless an error occurs.

2. I have a simple Cloud job but it is not displayed in the dashboard:
    Parse.Cloud.define("checkOnlineUsers", function(req, res) {
      console.log("hallo")
    });

**Comment by flovilmart** [comment]
Try with `verbose: true` instead of `logLevel: VERBOSE`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qqli007** [comment]
same problem
