### ISSUE TITLE
Able to execute "delete all rows" with readonly user.

### ISSUE THREAD

**Issue by ovdevops** [parse-community/parse-dashboard#827]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version =1.1.2 of Parse Dashboard.

- [x] You're running version =2.6.5 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
- Bring up parse-dashboard version 1.1.2 with readonly and master users. 
- Use master user to create a custom class with some rows. 
- Then re-login with readonly user. Go to Edit --> "Delete all rows". enter the class name, press "Yes, delete"

Result: all rows of the class are deleted.

More, there's a small GUI problem. When I click on the Edit --> "Delete a column", select the column to delete and press "Remove column", the action is proceeded without warning/error, although the selected column is not delete. But I think it should prompt the warning/error like "Read-only masterKey isn't allowed to delete a schema."  (the error appears when I select Edit --> "Delete this class", enter the class name and press "yes, delete" )

![image](https://user-images.githubusercontent.com/32085750/34373903-9c78c810-eb10-11e7-9fe2-a56d0a58fab6.png)

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by danielchangsoojones** [comment]
I also was able to delete all of my rows as a read only user. And they were permanently deleted! That is scary...

**Comment by flovilmart** [comment]
That’s probably an issue with parse server i’ll Have a look

**Comment by ovdevops** [comment]
This issue was fixed in parse-server:2.7.3
