### ISSUE TITLE
Docker hasn't been building

### ISSUE THREAD

**Issue by JonDum** [parse-community/parse-dashboard#830]
https://hub.docker.com/r/parseplatform/parse-dashboard/builds/

> The command '/bin/sh -c cd /src  && npm install  && npm run build  && npm cache clear  && rm -rf ~/.npm  && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 1

Running it locally results in tons of module not found errors related to lodash: 

```
..  ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/without' in '/src/node_modules/react-dnd-html5-backend/lib'
  ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/memoize' in '/src/node_modules/react-dnd-html5-backend/lib'
...
 ModuleNotFoundError: Module not found: Error: Can't resolve 'disposables' in '/src/node_modules/react-dnd/lib'
...
ModuleNotFoundError: Module not found: Error: Can't resolve 'lodash/isArray' in '/src/node_modules/react-dnd/lib/utils'
      at factoryCallback (/src/node_modules/webpack/lib/Compilation.js:264:39)
      at /src/node_modules/webpack/lib/NormalModuleFactory.js:247:20
      at /src/node_modules/webpack/lib/NormalModuleFactory.js:65:21
      at /src/node_modules/webpack/lib/NormalModuleFactory.js:138:21
      at /src/no
...
etc
```

I'm guessing that has something to with what how NPM installs deps in node:argon-slim.
Perhaps using node:latest or node:alpine-latest will result in a clean build.

I will try and submit PR if successful.

**Comment by flovilmart** [comment]
Thanks!

**Comment by JonDum** [comment]
Ok I updated the Dockerfile to be much leaner and faster. 73mb total vs 396mb from the old one.
I also added non pid 1 (root) exec, proper signal handling via tini and node_env prod as a default.

https://github.com/JonDum/parse-dashboard/commit/9fc72a2b4211c52001117e0ce1430e13ab6565f9

I'm not entirely sure that I have the proper set up though. What's the relationship between ./Parse-Dashboard and production/bundles? Ideally you'd `npm run build` before hand and commit the results in the docker image, but I'm not sure if that would work. Need some guidance there.

you can play around with the resultant files like this:

```
docker-build -t parse-db .
docker-run -it parse-db sh
```
Everything is in /home/node as is custom from the `node:<>` images from upstream.

**Comment by flovilmart** [comment]
Ideally, we should build the code and provide an image with the code pre built. I don’t like separating the build from the docker ‘context’ as a general rule as the machine that builds has a different setup from the one that runs. Perhaps a multi stage docker build would do the trick?

**Comment by JonDum** [comment]
A multi stage is a good idea. I'm still blocked by what exactly should be included in the build after `npm run build`. What resultant files should be includes? How does the `./Parse-Dashboard` folder relate to the build process? etc

**Comment by montymxb** [comment]
@flovilmart perhaps it would be helpful to publish the build instructions for docker in our README? Would help to clarify the process for future contributors and devs. I can't remember but I'm _pretty_ sure you've done this to another parse community repo not too long ago.

**Comment by flovilmart** [comment]
yep , in the server actually, it boils down to checking if we want the docker image to have all build system or just the artifacts.

**Comment by vmartins** [comment]
Works with this Dockerfile:

```
FROM node:8-slim
ENV NPM_CONFIG_LOGLEVEL error
WORKDIR /src
ADD . /src
RUN cd /src \
 && npm install \
 && npm run build \
 && npm cache clear --force \
 && rm -rf ~/.npm \
 && rm -rf /var/lib/apt/lists/*
ENTRYPOINT ["npm", "run", "dashboard"]
```
