### ISSUE TITLE
Restoring deleted objects?

### ISSUE THREAD

**Issue by nharbo** [parse-community/parse-dashboard#833]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X ] You're running version >=1.0.23 of Parse Dashboard.

- [X ] You're running version >=2.3.2 of Parse Server.

- [X ] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce
I deleted all rows in a table, as I thought it was on my development environment. But it was production :( Are there any ways to get back the deleted objects in my table, or are they for ever lost?

**Comment by montymxb** [comment]
Unfortunately if you've deleted it, it's gone. Unless you maintain backups of your database itself there's really not much you can do. I would be very careful about deleting objects in the future.
