### ISSUE TITLE
Master Read Only Key Not Working

### ISSUE THREAD

**Issue by danielchangsoojones** [parse-community/parse-dashboard#839]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x ] You're running version >=1.0.23 of Parse Dashboard.

- [x ] You're running version >=2.3.2 of Parse Server.

- [ x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Read Only Master Key does not work with the newest Parse Server version. I tried setting up a read only Parse Dashboard with a Read Only Master Key. However, it continually would give me the error that I needed a Master Key to be authorized, even though I was passing the Master Key and the Read Only Master Key. I then changed my actual Parse Server's project version to "parse-server": "~2.7.2" in the dependencies of the package.json file. Then, when I ran the Parse Dashboard again, it finally worked. So, the Parse Server was the actual problem when using Read Only Master Keys. I hope this gets fixed one day, but for now I will just stay on the 2.7.2 version of Parse Server for read only keys.

**Comment by flovilmart** [comment]
Can you provide you double check your server configuration please?

**Comment by flovilmart** [comment]
@danielchangsoojones in order to have a properly functional read only setup in the dashboard you need.

Parse Dashboard Config:

```
{
  "apps": [
    {
      "serverURL": "https://my-parse.com/1",
      "appId": "APP_ID",
      "javascriptKey": "JS_KEY",
      "restKey": "REST_KEY",
      "masterKey": "MASTER_KEY",
      "readOnlyMasterKey": "READ_ONLY_MASTER_KEY",
      "appName": "My Parse App",
      "supportedPushLocales": []
    }],
   {
      "user":"readonly",
      "pass": ".....",
      "readOnly": true,
      "apps": [{"appId": "APP_ID"}]
    }
}
```


Then on parse-server:

```
{
   "applicationId": "APP_ID",
   "masterKey": "MASTER_KEY",
   "readOnlyMasterKey": "READ_ONLY_MASTER_KEY"
    ...
}
``` 

Can you double check this is the case?

**Comment by adolfdsilva** [comment]
Getting same issue...
Below is my parse-server-example .js snippet...
```

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || '1',
  masterKey: process.env.MASTER_KEY || 'QkRBFtZmfYdloLznf***', //Add your master key here. Keep it secret!
  readOnlyMasterKey: process.env.READ_ONLY_MASTER_KEY || 'lbcyGdlBgJ***',
  serverURL: process.env.SERVER_URL || 'http://192.168.17.32:1337/mpwt',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  }
```
Dashboard config:
```

{
  "apps": [
    {
      "serverURL": "http://192.168.17.32:1337/mpwt",
      "appId": "1",
      "masterKey": "QkRBFtZmfYd***",
      "readOnlyMasterKey":"lbcyGdl***,
      "appName": "MPWT",
      "primaryBackgroundColor": "#215e97",
      "secondaryBackgroundColor": "#286CB5"
    },
    {
      "serverURL": "http://192.168.17.32:1338/dragon",
      "appId": "2",
      "masterKey": "QkRBFtZmfYd***",
      "readOnlyMasterKey":"lbcyGdl***",
      "appName": "Dragon",
      "primaryBackgroundColor": "#D50000", 
      "secondaryBackgroundColor": "#286CB5"
    }
  ],
  "users": [
    {
      "user":"admin",
      "pass":"$2y$10$DsLAb8SlV2dhgGpJ0ApRnu3W9oDL9t5TDLlMCsEfua2.DOOI8TKTS",
      "apps": [{"appId": "1"}, {"appId": "2"}]
    },
    { 
      "user":"test",
      "readOnly":true,
      "pass":"$2y$10$I/G0oy.n4XY6TAtfxTF0y.UyMOk.Bw4veHUIow4iUycVp80Z9qtKS",
      "apps": [{"appId": "1"}, {"appId": "2"}]
    }
  ],
  "useEncryptedPasswords": true
}
```

**Comment by flovilmart** [comment]
@adolphdsilva what version of the dashboard and the server are you running?

**Comment by adolfdsilva** [comment]
hi parse-server 2.7.4 and parser dashboard 1.2.0

<img width="439" alt="screen shot 2018-04-20 at 4 08 29 pm" src="https://user-images.githubusercontent.com/6647993/39042501-2d1bedf4-44b5-11e8-9903-67489b9ae75b.png">
<img width="546" alt="screen shot 2018-04-20 at 4 07 29 pm" src="https://user-images.githubusercontent.com/6647993/39042502-2d7b66e4-44b5-11e8-828e-5546fc4b3d2e.png">

**Comment by adolfdsilva** [comment]
Hey @flovilmart can you please help...I'm still stuck here :(

**Comment by flovilmart** [comment]
Can you provide a screenshot of the dashboard at the app selector page? 

Also, can you provide the screenshots of the errors you see?

I find it curious as we’re running it in production without any issue.

**Comment by adolfdsilva** [comment]
<img width="1280" alt="screen shot 2018-04-25 at 10 54 35 am" src="https://user-images.githubusercontent.com/6647993/39225667-dff71776-4877-11e8-92b7-618764dba5ff.png">
<img width="1280" alt="screen shot 2018-04-25 at 11 00 08 am" src="https://user-images.githubusercontent.com/6647993/39225668-e0472400-4877-11e8-9c90-562783501cad.png">

I have created 2 users "admin" and "test". Test has readOnly for Dragon App.
The logs screenshot I've taken with admin login.
