### ISSUE TITLE
Is there other permission which can limit user to update but not be able to remove from Parse dashboard?

### ISSUE THREAD

**Issue by skinner2012** [parse-community/parse-dashboard#847]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [ ] You're running version >=1.0.23 of Parse Dashboard.

- [*] You're running version >=2.3.2 of Parse Server.

- [*] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

I know how to have 2 or more accounts to login in Parse dashboard with specific apps. But so far I only see *readOnly* this permission. Is there more permission type I can use to limit an account to only be able to read/update but not be able to remove/delete in Parse dashboard? Thanks.

**Comment by flovilmart** [comment]
We don't support this granularity on parse-server so at the moment, that's not supported on the dashboard. If this is an enhancement you'd like to see, feel free to open an issue on the parse-server repository.

**Comment by skinner2012** [comment]
Thanks for the quick reply.
