### ISSUE TITLE
Confirmation dialog icons offset vertically

### ISSUE THREAD

**Issue by mightymango** [parse-community/parse-dashboard#851]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Deployed to Heroku
Browser Safari Version 11.1 (13605.1.33.1.2)

#### Steps to reproduce
Open a database
Select a Class
Select Edit|Delete this class

When the confirmation dialog is displayed the icon is offset vertically and only half is displayed. This happens for all modal dialog boxes.

<img width="565" alt="screenshot 2018-04-17 11 31 35" src="https://user-images.githubusercontent.com/1525576/38864777-aa642882-4233-11e8-8b11-7ac7c616dc71.png">

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

**Comment by camdagr8** [comment]
I'm experiencing the same.

**Comment by nafplann** [comment]
same issue here
