### ISSUE TITLE
Server Not Reachable: unable to connect server Error

### ISSUE THREAD

**Issue by iremkorkmaz** [parse-community/parse-dashboard#852]
Hello all, 

I have checked many isssues including this error but I am not able to get dashboard working. 
My server & dashboard is installed on a digitalocean server.

My Parse Server is working properly, I have even post data from my local computer to my server and that worked properly as well.

I am running my parse server with default values. And the output is :

```
masterKey: ***REDACTED***
masterKeyIps: []
logsFolder: ./logs
databaseURI: mongodb://localhost/test
userSensitiveFields: ["email"]
enableAnonymousUsers: true
allowClientClassCreation: true
maxUploadSize: 20mb
customPages: {}
sessionLength: 31536000
expireInactiveSessions: true
revokeSessionOnPasswordReset: true
schemaCacheTTL: 5000
cacheTTL: 5000
cacheMaxSize: 10000
objectIdSize: 10
port: 1337
host: 0.0.0.0
mountPath: /parse
scheduledPush: false
collectionPrefix: 
verifyUserEmails: false
preventLoginWithUnverifiedEmail: false
enableSingleSchemaCache: false
jsonLogs: false
verbose: false
level: undefined
serverURL: http://localhost:1337/parse

[30889] parse-server running on http://localhost:1337/parse
```

And to run my parse dashboard :

> parse-dashboard --appId XXXXXXXX --masterKey XXXXXXXXX  —serverURL "http://localhost:1337/parse"

I also made proxy pass on my nginx to directly open my dashboard which means redirecting 
80 port / path to
my 4040 port which opens directly when I open my domain.

I have tried a lot of different things like changing my serverURL for parse-server , putting another redirection for parse-server and so on but nothings working.

Anyone can help me with that?

Thanks in advance.

**Comment by on3nx** [comment]
Try to change databaseURI: mongodb://localhost/test to: databaseURI: mongodb://ip/test

**Comment by simonecogno** [comment]
Have you tries `--allowInsecureHTTP` option?

**Comment by SepehrJb** [comment]
If you're accessing the dashboard from your local computer , replace your server's ip with of "localhost"  . Because the dashboard is living inside your browser , and it is desperately searching for a parse app on your laptop .
