### ISSUE TITLE
Improving security using 2FA

### ISSUE THREAD

**Issue by indiandragon** [parse-community/parse-dashboard#856]
Hi team,
Have any of you implemented Two factor authentication (2FA) for Parse dashboard, it's very crucial that we have better security implemented for the dashboard.

Would love to hear any security augmentations you've made for your parse-dashboard.

**Comment by flovilmart** [comment]
At the moment we haven’t but I believe this should be possible with a custom passport authentication or else.

**Comment by mnlbox** [comment]
Guys you can see some link about implement 2FA in node.js in this issue:
https://github.com/strapi/strapi/issues/786

Maybe useful foe someone.

**Comment by flovilmart** [comment]
@mnlbox if we implement 2FA this is probably gonna go through a passport.js plugin as this project is already in used in the dashboard.

**Comment by mnlbox** [comment]
@flovilmart is it possible to implement 2FA with cloud code and web-hook?

**Comment by dblythy** [comment]
If you'd like to reopen this, I'm happy to work on it @TomWFox.

**Comment by mtrezza** [comment]
Maybe this can now be easily achieved with https://github.com/parse-community/parse-server/pull/7079.

**Comment by parseplatformorg** [comment]
🎉 This pull request has been released in version [3.3.0-alpha.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-alpha.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0-beta.1](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0-beta.1)

**Comment by parseplatformorg** [comment]
🎉 This change has been released in version [3.3.0](https://github.com/parse-community/parse-dashboard/releases/tag/3.3.0)
