### ISSUE TITLE
Can't see Push Bar on Parse Dashboard to set up PushNotifications

### ISSUE THREAD

**Issue by finntom123** [parse-community/parse-dashboard#857]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

Hi, 

I've been trying to set up PushNotifications with Parse, however I'm having an issue with my Parse Dashboard in that I am only able to see the Core tab on my dashboard and not the Push tab as well as you can see from my screenshots. I don't know where this error stems from and I've been struggling to try to figure out an answer for this for a while now. If anyone could help me get that Push tab set up that would be great as it's the only thing keeping me from submitting to the app store.

I appreciate the help thank you!

*running server version 2.3.5 & dash 1.0.25

<img width="297" alt="screenshot 2018-05-26 14 54 00" src="https://user-images.githubusercontent.com/26051873/40580088-b583be50-60f4-11e8-9ece-5e79785ca43d.png">
<img width="127" alt="screenshot 2018-05-26 14 54 25" src="https://user-images.githubusercontent.com/26051873/40580089-b8dbba6c-60f4-11e8-9a12-f49379ec333b.png">

**Comment by finntom123** [comment]
Okay how do I go about updating?

**Comment by flovilmart** [comment]
@finntom123 this completely depends how you installed / setup your server and dashboard and where you deploy it.

**Comment by finntom123** [comment]
So I redownloaded the file and just edited the parse-dashboard-config.json file with my server url which is a link to Heroku, my app ID & masterkey. However, when I try running the dashboard and going to the localhost:4040 it displays a blank webpage with this in the console: I thought all you needed to do to set it up was update your serverURL and keys into that file, or am I wrong and is there more to do?


<img width="550" alt="screenshot 2018-05-26 15 43 56" src="https://user-images.githubusercontent.com/26051873/40580455-9edd6de8-60fb-11e8-96f9-a09c09aa513c.png">

**Comment by finntom123** [comment]
@flovilmart My old dash runs completely fine when I try running it again but this new one won't

**Comment by finntom123** [comment]
Do you think it's a problem with not pushing this new file to my heroku/github or what?

**Comment by flovilmart** [comment]
@finntom123 I am not sure what you’re doing, if you ran `npm install‘. Can you be clear about the steps you’re running as well as what you have on your machine and on heroku? I guess you used the deploy to heroku button which makes it easy to deploy the 1st time and hard to update and keep track. Your versions are likely to be 2 years old

**Comment by finntom123** [comment]
Originally I did use the deploy to heroku button which was over a year ago when I initially set this up. Now the steps I took were to simply download the zip for the parse-dashboard rather than use 'npm install' and complete the steps of adding my Heroku server url and Keys as stated above. Do you know what I need to do to in order to get this all up to date? I have lots of data on my dashboard that's connected to Heroku right now, so I'd just like to update my version of the dashboard while keeping all my existing data

**Comment by flovilmart** [comment]
I am sorrry but I am not familiar with the heroku update procedures. You should probably ask on stackoverflow tagging nodejs, heroku, deploy, upgrade

**Comment by finntom123** [comment]
Okay well how would you go about setting it up without Heroku? I just need some direction

**Comment by flovilmart** [comment]
Have you checked the documentation and the README at the root of this repository?

**Comment by finntom123** [comment]
Yup, as seen from my screenshot above I get a blank screen after entering my credentials and attempting to open the dash using the link localhost:4040

**Comment by flovilmart** [comment]
Did you run npm install? Usually, you see this issue when you have improperly installed the dashboard or that you missed a step

**Comment by flovilmart** [comment]
Also whatever the state of the dashboard, you’ll need to upgrade the server too. And you should probably do that first

**Comment by finntom123** [comment]
Okay so I just ran npm install and set everything up and got the dashboard to work. However, I continue to encounter the same problem of the Push section not showing up under Core.....

**Comment by flovilmart** [comment]
Yes because you need to upgrade and properly configure your parse server. Please visit http://docs.parseplatform.org/parse-server/guide/#push-notifications

**Comment by finntom123** [comment]
Okay but that shouldn't explain the fact that a fundamental part of my dashboard is missing

**Comment by finntom123** [comment]
I've done all that stuff

**Comment by flovilmart** [comment]
He features of the dashboard are defined by the backing server or is out of date; this explains it all. So please; update all to the latest versions.

**Comment by finntom123** [comment]
okay I've installed the new parse-server. Only problem I'm encountering is after I install when I paste parse-server --appId APPLICATION_ID --masterKey MASTER_KEY --databaseURI mongodb://localhost/test it says command not found. Is there a certain directory I need to be within for this to work?

**Comment by flovilmart** [comment]
How did you ‘install’ the new parse server? What steps did you follow?

If you installed the new parse server you’ll want to deploy it on heroku. Also, it’s unlikely your database is hosted on localhost/test.

**Comment by finntom123** [comment]
npm install -g parse-server mongodb-runner

Can you just tell me what file to put my appKey, MasterKey and mongoDBUI link into? I've been trying to use that command for hours and it hasn't worked.

**Comment by finntom123** [comment]
9+ hours, still no solution. That's rough

**Comment by finntom123** [comment]
I installed which worked fine and thought I was close to a solution but have been following these steps for hours to no avail. Please help me.

<img width="1087" alt="screenshot 2018-05-26 20 12 59" src="https://user-images.githubusercontent.com/26051873/40581886-43fd2582-6121-11e8-8825-c48ec14cada9.png">

**Comment by flovilmart** [comment]
@finntom123 we call that learning, and yes sometimes it’s rough. If you deployed to heroku then you don’t need to follow whatever getting started guide is there for parse-server. Get the setup that is running on heroku, update the configuration and deploy again. If you still have trouble, use stackoverflow please.

**Comment by finntom123** [comment]
All I need is to just put in my keys and databaseURI but have no way of doing so

**Comment by finntom123** [comment]
Inputing those are necessary before I can deploy to heroku.....

**Comment by flovilmart** [comment]
No they are not! They are configured on heroku, you are likely running parse-server-example on heroku.

**Comment by flovilmart** [comment]
Please, ask on stackoverflow. We use github issues for code level issues. As mentioned many times.

**Comment by flovilmart** [comment]
Also, consider the gitter channel: https://gitter.im/ParsePlatform/Chat

**Comment by finntom123** [comment]
Okay ill check it out. It's still a problem with linking keys as I can't link the parse-server to heroku without them in an index.js folder. When I add an index.js folder that was in my parse-server-example it just creates a bunch of errors
