### ISSUE TITLE
PushStatus not showing in dashboard

### ISSUE THREAD

**Issue by pargu** [parse-community/parse-dashboard#858]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Environment Setup
Parse Server 2.6.3
Parse Dashboard 1.2.0
MongoDB 3.0.3

#### Steps to reproduce
1. Click "Create a Class"
2. Choose PushStatus as alternative in drop-down menu
3. Result: Table's not shown. And console says 400 (Bad request)
4. Try to access table from url. Same error code.

----
Updated Parse Dashboard version from 1.0.28 -> 1.2.0. Saw there were a new feature to see _PushStatus as a table. Tried adding class trough "Create a Class" with no success. 
Going into UI-tool on MongoDB I can see the table and all past pushes. I know there's an Past Pushes in the Push section, but you can't query on this, which is what I'm after.
 
Below image shows error log when trying to access the PushStatus table through browser.
![push status](https://user-images.githubusercontent.com/19467727/40587509-273b9e60-61d0-11e8-859a-24c6ba199054.png)

If some further information is required, please let us know 🙂

**Comment by flovilmart** [comment]
The _PushStatus is an internal class and should not be created. What you’re experiencing is the expected behavior.

**Comment by pargu** [comment]
According to this https://github.com/parse-community/parse-dashboard/pull/701 , this should now be possible?

**Comment by natanrolnik** [comment]
I missed this one a few months ago. 
When creating a new class, it shows PushStatus as one of the options.
I believe we don't want this, correct? `_PushStatus` is a completely internal class and shouldn't be available in the Data Browser.

<img width="568" alt="captura de tela 2018-07-17 as 10 21 04" src="https://user-images.githubusercontent.com/1164565/42802372-68104f32-89ab-11e8-9360-9aa65ac93741.png">
