### ISSUE TITLE
Localhost: "Server Not Reachable: Unable to Connect to Server" after deleting relation column on object

### ISSUE THREAD

**Issue by KileyCaravella** [parse-community/parse-dashboard#859]
My localhost froze when I removed a relation column from my user table, crashed whenever I refreshed, and now shows `Server Not Reachable: Unable to Connect to Server` when I refresh my dashboard homepage. The backend seems to still be up because I can access it from my applications, but now I cannot view it locally. 

**Steps to reproduce the issue:**
1. start localhost via `parse-dashboard --config parse-dashboard-config.json` and choose project
2. add relation column to User table that's a relation to other users
3. add users to relation
4. remove column via dropdown on right side
5. observe column is not removed and screen has frozen

**Steps to Debug:**
1. refresh and observe dots that show view is loading are frozen on screen after a few moments
2. go back to main dashboard view
3. observe backend cell says `Server Not Reachable: Unable to Connect to Server`
4. close out of dashboard and reopen via `parse-dashboard --config parse-dashboard-config.json`
5. observe no change

**Version**
- _parse:_ originally 1.9.2 then updated to 1.10.2 to see if it would fix the issue
- _parse-server:_ ^2.4.2
- _parse-dashboard:_ ^1.0.26

Is there any way to refresh the localhost's connection to the backend or even refresh the localhost? This looks like a bug but for now I would like to still be able to use it to access data

**Comment by flovilmart** [comment]
@KileyCaravella you should probably upgrade both the dashboard and the server as you're running very old versions.

**Comment by KileyCaravella** [comment]
@flovilmart what versions should I update them to? And will that solve the crashing issue?

**Comment by flovilmart** [comment]
Usually we recommend to stay up to date with the latest versions, and I'm not sure what's crashing in your case, but without being on the latest version it's tough to know and follow through.

**Comment by KileyCaravella** [comment]
@flovilmart I updated `parse-dashboard` to `^1.2.0` and `parse-server` to `^2.8.1` but it still shows the same issue

**Comment by KileyCaravella** [comment]
@flovilmart I added steps to reproduce -- are you able to reproduce the issue or find a way for me to refresh my localhost?

**Comment by flovilmart** [comment]
Is your parse server running properly? Can your provide the logs? Also, is it possible do you to check the networking tab of your debug tools in the web browser? The server unreachable issue arises when the server can’t respond, so it can be because the serverURL is wrong, or because the server can’t start

**Comment by KileyCaravella** [comment]
@flovilmart The URL is correct because I made the change from inside the server (localhost as said above). It looks like I'm now receiving 404 server errors whenever I try to access User objects: `The data couldn’t be read because it isn’t in the correct format`, but all other objects can be accessed fine. My guess is the crash corrupted my User file. Any idea on how to fix it?

**Comment by flovilmart** [comment]
Can you provide the _Schema objec  from the DB as well as the result of a curl call to your users table?

**Comment by KileyCaravella** [comment]
@flovilmart sorry I'm not exactly sure what a _Schema object is and we don't make curl calls, but our logs show this in heroku:

```2018-05-28T16:46:24.607288+00:00 heroku[router]: at=info method=POST path="/api/login" host=xxx.herokuapp.com request_id=zzz fwd="yy.yy.yy.yy" dyno=web.1 connect=0ms service=1ms status=404 bytes=393 protocol=http```

and the frontend message is:
`The data couldn’t be read because it isn’t in the correct format`

not sure how much either help you though

**Comment by flovilmart** [comment]
Have a look in your database directly, you’ll see there is a _SCHEMA table, I need to contents of that to help you. Also, he curl call will help me understand what is wrong with your user results.

**Comment by KileyCaravella** [comment]
@flovilmart sorry I meant I didn't know how either of what I gave you as a response to your last comment would help with what you were looking for. Again, we don't make curl calls but here is the _schema table:

```
{
    "_id": "_User",
    "objectId": "string",
    "updatedAt": "date",
    "createdAt": "date",
    "username": "string",
    "email": "string",
    "emailVerified": "boolean",
    "authData": "object",
    "relationPeople": "relation<_User>",
    "relationAddresses": "relation<Address>",
    "relationFriends": "relation<_User>",
    "groups": "relation<Group>",
    "userDescription": "string",
    "_metadata": {
        "indexes": {
            "_id_": {
                "_id": 1
            },
            "email_1": {
                "email": 1
            },
            "username_1": {
                "username": 1
            }
        }
    }
}

**Comment by flovilmart** [comment]
Also, on your dashboard, can you provide a screenshot of the request / responses that the dashboard makes to the server?

**Comment by KileyCaravella** [comment]
Actually looking at the `_schema` it seems like the password field doesn't exist on the `User` object -- is there a chance the dashboard deleted the `password` field instead of the one I wanted? Could that have caused the crash?

**Comment by flovilmart** [comment]
> ere a chance the dashboard deleted the password field instead of the one I wanted? 

It depends if you typed password as the field to delete. 

Which Relation field is supposed to be deleted in your _User schema?

And I would need the request / responses from the dashboard that yield your: `The data couldn’t be read because it isn’t in the correct format` .

**Comment by KileyCaravella** [comment]
I did not type anything it was from a pull-down menu on the right side (as stated above)

Here are images of what I did:

![screen shot 2018-05-28 at 1 22 44 pm](https://user-images.githubusercontent.com/11179948/40624373-3e5c80fa-627a-11e8-8d56-c5bdb7e437f7.png)

![screen shot 2018-05-28 at 1 17 33 pm](https://user-images.githubusercontent.com/11179948/40624265-8f85ff8e-6279-11e8-846a-d85ca40e0b23.png)

I selected `relationPeople` as the field to delete, pressed `remove column`. After, `relationPeople` remained in the view and a couple seconds later the dashboard froze.

As for the backend function that results in  `The data couldn’t be read because it isn’t in the correct format`, the function call was from the frontend in swift for iOS:

    class func signUp(username: String, password: String, completion: @escaping (Bool) -> Void) {
        let user = User()
        user.username = username
        user.password = password
        user.signUpInBackground { (success, error) in
            print(error?.localizedDescription)
            completion(error == nil)
        }
    }

Log:
```2018-05-28T16:46:24.607288+00:00 heroku[router]: at=info method=POST path="/api/login" host=xxx.herokuapp.com request_id=zzz fwd="yy.yy.yy.yy" dyno=web.1 connect=0ms service=1ms status=404 bytes=393 protocol=http```

There have been a few instances where I have selected rows to delete and the dashboard has deleted the wrong rows, but I have not had this issue with columns yet. Is it based off the same code? Is there a chance this is the issue?

**Comment by KileyCaravella** [comment]
Are there other required fields that are missing from the `_SCHEMA` code I sent you?

**Comment by flovilmart** [comment]
Look, I'm trying to help here, and I've asked for the request / responses from your dashboard. It looks like the schema is corrupted somehow, I'm not sure what happened nor how it could have happened or anything.

Everything is getting mixed now that you put iOS onto the mix. Please, let's focus on one thing, which is the dashboard, that you say you can't access the data.

relationPeople is still there in your _SCHEMA table which is wrong, you should probably edit the object in the DB so relationPeople is not there anymore in the _SCHEMA object.

I will also need the request / response from your dashboard that fail, as requested, otherwise I can't debug or help you.


ALSO, the logs your provide are not with the server running with VERBOSE=1 those are just the default heroku logs.

**Comment by KileyCaravella** [comment]
@flovilmart I'm not trying to argue I'm trying to respond the best way I know how -- I just took over this backend so I'm not 100% up to date with how it's setup. 

I know our backend does not use curl calls and is written in Node.js, and we use some built-in Parse frontend calls to the backend like `signUpInBackground`, `fetchInBackground`, etc. These calls all worked perfect before this event (I was using `signUpInBackground` minutes before the crash happened so I know it's setup correctly and works correctly). 

I removed `relationPeople` from the _SCHEMA table and all other relation variables just in case they were what caused the issue, and localhost still cannot connect to the server.

What exactly do you need me to send you for the logs? I sent you the request and responses I receive with my current setup like you requested, but I did not realize there was a specific type of log you wanted -- how do I set up the logs to show VERBOSE=1 the way you'd like?

**Comment by flovilmart** [comment]
Is your server up?

> I know our backend does not use curl

I'm not asking for that, I,m asking for you do run a `curl -H 'X-Parse-Application-Id: ...' -H 'X-Parse-Master-Key: ...' YOUR_PARSE_SERVER_URL/classes/_User` To see what the response is.

**Comment by flovilmart** [comment]
and also `curl -H 'X-Parse-Application-Id: ...' -H 'X-Parse-Master-Key: ...' YOUR_PARSE_SERVER_URL/serverInfo` 

Also, can you please provide the screenshot I asked about (4 times now) of the chrome developer console network calls? That would really help... I mean, really...

**Comment by KileyCaravella** [comment]
Apologies I have never worked with curl before so I did not realize there was a specific manual call you were asking for -- I just saw you wanted a call to the backend and response so that's what I sent.

I ran the curl functions in the format you mentioned setup like below:

    curl -H 'name' -H 'master_key' https://name.herokuapp.com/api/classes/_User```
    curl -H 'name' -H 'master_key' https://name.herokuapp.com/serverInfo```

Unfortunately I'm not sure if my setup was wrong or if the response means the server is down: 

![screen shot 2018-05-28 at 2 03 37 pm](https://user-images.githubusercontent.com/11179948/40625406-43e773a8-6280-11e8-9cc8-4ec6168fd2d7.png)
![screen shot 2018-05-28 at 2 03 45 pm](https://user-images.githubusercontent.com/11179948/40625407-43f75e80-6280-11e8-9394-e2edc0058b4a.png)

As for the screenshot, I apologize if I missed it but I did not see you ask for any "chrome developer console network calls" -- where can I find them and how can I get them to you?

**Comment by flovilmart** [comment]
That indicates your backend is down, what is your api domain for your backend?

**Comment by KileyCaravella** [comment]
`https://visit-app-api.herokuapp.com`

**Comment by flovilmart** [comment]
try with::

```
curl -vvv https://visit-app-api.herokuapp.com/parse/classes/_User
curl -vvv https://visit-app-api.herokuapp.com/parse/serverInfo
```

It seems that your parse-server is not mounted on the rigth path, `api` but on `parse`  which indicates  a misconfiguration serverside.

**Comment by flovilmart** [comment]
You should configure your server correctly, please refer the the documentation or stackoverflow as this is not an issue with the dashboard.

**Comment by KileyCaravella** [comment]
@flovilmart everything was working perfectly for the 4 months I've had access to this backend and dashboard, and only stopped when I went to delete a column and it removed the password column/messed up something with the User class.

**Comment by KileyCaravella** [comment]
@flovilmart I don't think my issue is just with the url. I grabbed the url from the logs I was seeing which included `/api/` but that does not mean that's the path to my data and the underlying issue.

**Comment by flovilmart** [comment]
Please @KileyCaravella , I'm telling you, your parse-server is not mounted on `/api` but on `/parse` which is likely wrong, because you keep telling me the proper URL to your parse-server is on /api. which clearly is not because heroku responds with a 404 there and not a 401 (unauthorized).

If you configure your dashboard with the serverURL set to `https://visit-app-api.herokuapp.com/parse/`what does it do?

**Comment by KileyCaravella** [comment]
yes I updated it and it works, but what I'm saying is that the underlying issue to the original problem was the dashboard deleting the wrong column on the object. I would test the latest versions of the dashboard to make sure this is not a problem anymore.

**Comment by KileyCaravella** [comment]
I'm guessing the `/api/` v. `/parse/` happened when I updated the server and dashboard and it jumped over versions where this change occurred, but again it's not the issue on this thread

**Comment by flovilmart** [comment]
Are you able to reproduce the issue with the latest version of the dashboard and the server? Please provide the server logs when running with VERBOSE=1 when doing so

**Comment by flovilmart** [comment]
As I mentioned initially, we are asking for you to be on the latest version of parse server and the dashboard to ensure you’re not subject to an old bug. Then your server being unreachable can be explained by the misconfuguration. If it occurs again, feel free to ping me here
