### ISSUE TITLE
Parse Dashboard: server not reachable: unable to connect to server

### ISSUE THREAD

**Issue by on3nx** [parse-community/parse-dashboard#860]
I'm Running Parse Server 2.8.2 and Parse Dashboard 1.2.0

#### Environment Setup
I install both parse server and parse dashboard inside one Docker container inside Synology NAS.
Docker using PM2
with network config:
- Docker using bridge network
- Docker container (both Parse server & parse Dashboard) IP: 172.17.0.2
- parse server running on 1337 and parse dashboard running on 4040
- my synology nas IP: 192.168.1.2
- my pc IP: 192.168.1.100

configuration:
PM2 ecosystem.json:
```
{
  "apps" : [{
    "name"        : "parse-wrapper",
    "script"      : "/usr/bin/parse-server",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse",
    "args"        : "--serverURL http://localhost:1337/parse",
    "env": {
      "PARSE_SERVER_CLOUD_CODE_MAIN": "/home/parse/cloud/main.js",
      "PARSE_SERVER_DATABASE_URI": "mongodb://localhost/test",
      "PARSE_SERVER_APPLICATION_ID": "aeb932b93a9445c19df2fcaf3fd69fcc",
      "PARSE_SERVER_MASTER_KEY": "358898148f354f8db593ea004ee88fcc",
    }
  },{
    "name"        : "parse-dashboard-wrapper",
    "script"      : "/usr/bin/parse-dashboard",
    "watch"       : true,
    "merge_logs"  : true,
    "cwd"         : "/home/parse/parse-dashboard",
    "args"        : "--config /home/parse/parse-dashboard/config.json --allowInsecureHTTP=1"
  }]
}
```
parse dashboard config json:
```
{
  "apps": [{
    "serverURL": "http://172.17.0.2:1337/parse",
    "appId": "aeb932b93a9445c19df2fcaf3fd69fcc",
    "masterKey": "358898148f354f8db593ea004ee88fcc",
    "javascriptKey": "NOT USED",
    "restKey": "NOT USED",
    "appName": "Parse Server",
    "iconName": "",
    "primaryBackgroundColor": "",
    "secondaryBackgroundColor": ""
  }],
  "iconsFolder": "icons",
  "users": [{
    "user": "kemel",
    "pass": "qa11qa"
  }]
}
```

pm2 parse server log (after it run):
```
0|parse-wr | cacheMaxSize: 10000
0|parse-wr | objectIdSize: 10
0|parse-wr | port: 1337
0|parse-wr | host: 0.0.0.0
0|parse-wr | mountPath: /parse
0|parse-wr | scheduledPush: false
0|parse-wr | collectionPrefix:
0|parse-wr | verifyUserEmails: false
0|parse-wr | preventLoginWithUnverifiedEmail: false
0|parse-wr | enableSingleSchemaCache: false
0|parse-wr | jsonLogs: false
0|parse-wr | verbose: false
0|parse-wr | level: undefined
0|parse-wr |
0|parse-wr | [1318] parse-server running on http://localhost:1337/parse
```
pm2 parse dashboard log (after it run):
`1|parse-da | The dashboard is now available at http://0.0.0.0:4040/`

#### Steps to reproduce
from my pc (192.168.1.100) access:

- http://192.168.1.2:1337/parse
-- result --> {"error":"unauthorized"} <-- which is correct

- http://192.168.1.2:4040
-- result:
---- Login page -> login -> success
---- see ball animation quite long loading time appx. 2 mins
---- and get return "server not reachable: unable to connect to server"

#### 

I've seen nothing wrong with my settings, but i've been stuck here for quite few days..
is there any miss configuration that i do here?

**Comment by flovilmart** [comment]
In the Parse-dashboard config, you’re pointing to 172.17.0.2 for parse-server and it seems that it’s the wrong IP address as you access it through 192.168.1.2

**Comment by on3nx** [comment]
Thanks Flovilmart, that's solve the problem...

but let me try to understand further, so it's pointing to my end-point machine (which is my pc) - why? what's the rationale behind this?

is that means I can only access parse dashboard through 192.168.1.2 machine?
how if i have multiple end-point to access parse-dashboard?

**Comment by on3nx** [comment]
Aaahh I see, thats solve my problem.
Thanks!
