### ISSUE TITLE
more feature like Strapi

### ISSUE THREAD

**Issue by mnlbox** [parse-community/parse-dashboard#862]
Hi guys,
[Strapi](https://github.com/strapi/strapi) is a Headless CMS with a beautiful admin dashboard. I think it's better to add some of that feature to parse-dashboard too.
For example Strapi handle relation types very well:
* one to many
* many to many
* one to one
* has one
* ...

Or Strapi support Media as a separate Media Library menu.
I think maybe we can borrow some code and idea from that in parse-dashboard.
Let's talk about this features here.

**Comment by flovilmart** [comment]
parse-server and dashboard already implement all of those through relations and pointers, there is no need to add a new paradigm.

As for the media library, I am not against adding a _File class, through the server and add a browser inside the dashboard. If this is a feature you'd like to work on, please let us know if we ca provide any guidance.

**Comment by mnlbox** [comment]
@flovilmart Media library like you say (browser in dashboard) can be useful. Are you any plan for add this feature to parse-dashboard?
