### ISSUE TITLE
Add PARSE_DASHBOARD_ALLOW_INSECURE_HTTP to README.md

### ISSUE THREAD

**Issue by NathanGrimaud** [parse-community/parse-dashboard#863]
Hi team :) 

It may be by choice but I can't see PARSE_DASHBOARD_ALLOW_INSECURE_HTTP in the "environement variables" section of the readme. I know that using the dashboard without https isn't a good practice but it can be usefull ;)

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/parse-dashboard/issues/863

Look here for your answer. https://github.com/parse-community/parse-dashboard/issues/810

Please feel free to open a PR on the update the readme or improve docs
