### ISSUE TITLE
Title of browser tab should be the class name currently selected

### ISSUE THREAD

**Issue by otmezger** [parse-community/parse-dashboard#868]
If you work with several tabs open, using the parse dashboard like a management console to your application, it is difficult to identify which class is open on which tab. The title of the tabs in the browser are always the same: "Parse Dashboard". It would be cool if I could see the class name, something like "<ClassName> - Parse Dashboard". 

the other functions could be called "Jobs - Parse Dashboard", etc... 

<img width="624" alt="new_issue_ _parse-community_parse-dashboard" src="https://user-images.githubusercontent.com/2758346/42495499-892c23fe-8423-11e8-812a-35f5458f549e.png">

**Comment by otmezger** [comment]
I can give it a try! Could you point me to the location where this needs to
be done?

Thanks
Olmo

**Comment by flovilmart** [comment]
I don’t have much a clue, perhaps each component that is part of the routing logic should expose it’s title. I’m not sure.
