### ISSUE TITLE
Any way that we can have data export and import from Parse Dashboard?

### ISSUE THREAD

**Issue by haroot** [parse-community/parse-dashboard#870]
I'd like to be able to backup my MongoDB Cloud data and restore it from Parse dashboard, so far from studying parse most of the issues are from User or DB error... 

https://cloudacademy.com/blog/parse-server-migration-on-aws/

this is from 2016 i'm missing the features it mentions were they coded out? I'd like to be able to export my Parse data using the GUI like in the above post

**Comment by flovilmart** [comment]
Originally, parse didn’t let you access your data right in the database. This is why they provided an interface with the dashboard. Now that you have control over the database, it’s better and more efficient to use the database tools like mongodump and mongorestore. If you are not familiar with database hosting and management, I recommend you use a service like mongodb atlas or mlab that will host the DB for you. They will also provide restore/dump user interfaces that are well suited for you.

We will not provide such interface in the dashboard as reasonable alternatives exist.

**Comment by haroot** [comment]
Yah i'm mostly a Seuqelize guy, def not a NoSQL expert but I created a Mongo Cloud Sharded Cluster, wouldn't I have to export and import into every cloud etc etc? Wouldn't it be easier to export and import using Node functions aka promises instead of the command line tools for a sharded cluster?

**Comment by flovilmart** [comment]
I don’t believe so, you should be able to export every shard at once.

The process of running mongo export, then uploading to a bucket then notifying you the download is ready, then letting you download securely (and I’m not talking about importing 1Tb of data here) is way better if you do it with the DB tools than with a small nodejs process.

**Comment by haroot** [comment]
yah I think im using Studio3T so far so good
