### ISSUE TITLE
incomplete documentation

### ISSUE THREAD

**Issue by noyessie** [parse-community/parse-dashboard#876]
The documentation is not complete.

I have a sereous problems with parse under http. I know it is possible to bypass the remote security restriction with parameter allowInsecureHttp, but in the documenation, i don't see mention of someone who can help me. But the source code use environment variable `PARSE_DASHBOARD_ALLOW_INSECURE_HTTP`. but no mention of it in documentation.

**Comment by dplewis** [comment]
Duplicate https://github.com/parse-community/parse-dashboard/issues/863

Look here for your answer. https://github.com/parse-community/parse-dashboard/issues/810

Please feel free to open a PR on the update the readme or improve docs
