### ISSUE TITLE
Impossible to filter by a ParseFile column

### ISSUE THREAD

**Issue by DanGTZ** [parse-community/parse-dashboard#894]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard.

- [x] You're running version >=2.3.2 of Parse Server.

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

Is it planned to add such a filter? In order to display only objects that have a ParseFile attribute set.

#### Environment Setup
parse v1.11.1
parse-dashboard v1.2.0
parse-server v2.7.4

#### Steps to reproduce
- Create a class with a ParseFile column (let say 'picture') and instantiate some objects for this class
- Set a picture file for only a part of the objects
- Try to filter objects to display only those with  a picture => the 'picture' column doesn't appear in the filter choice list

**Comment by flovilmart** [comment]
Queries on files is not supported on parse-server besides for existence IIRC. Therefore, it won’t be added to the dashboard unless the contrib is made on the server in the 1st place. Feel free to go ahead, we can assist if you need to.

**Comment by DanGTZ** [comment]
Ok thanks for the info @flovilmart. Will let you know!

**Comment by richardgroves** [comment]
> Queries on files is not supported on parse-server besides for existence IIRC. 
A filter that just queried existence / doesn't exist would be useful enough.

**Comment by cjosepha** [comment]
> > A filter that just queried existence / doesn't exist would be useful enough.

@richardgroves do you mean this one doesn't require parse-server modification?
