### ISSUE TITLE
Can't get users email in Rest api used parse dashboard

### ISSUE THREAD

**Issue by anupmaurya484** [parse-community/parse-dashboard#897]
I was used parse dashboard package with parse.query and get users  details. i have get all users record and parse.query to used, i getting the response but email key can't show each and every used record , the email field is show parse dashboard and mongodb table.

If your know that solution so please give me help. blow my code

`
   var fetchUserWithIdentifier = function (userIdentifier) {
    let query = new Parse.Query(User)
    query.equalTo(User.Field.objectId, userIdentifier)
    return query.first()
    };

    class User extends Parse.Object {
    /**
     * @return {string}
     */
    get firstName() {
        return this.get(User.Field.firstName)
    }

    /**
     * @param {string} firstName
     */
    set firstName(firstName) {
        this.set(User.Field.firstName, firstName)
    }

    /**
     * @return {string}
     */
    get email() {
        return this.get(User.Field.email)
    }

    /**
     * @param {string} email
     */
    set email(email) {
        this.set(User.Field.email, email)
    }

    /**
     * @return {string}
     */
    get googleId() {
        return this.get(User.Field.googleId)
    }

    /**
     * @param {string} googleId
     */
    set googleId(googleId) {
        this.set(User.Field.googleId, googleId)
    }

    /**
     * @return {string}
     */
    get facebookId() {
        return this.get(User.Field.facebookId)
    }

    /**
     * @param {string} facebookId
     */
    set facebookId(facebookId) {
        this.set(User.Field.facebookId, facebookId)
    }

    /**
     * @return {string}
     */
    get facebookEmail() {
        return this.get(User.Field.facebookEmail)
    }

    /**
     * @param {string} facebookEmail
     */
    set facebookEmail(facebookEmail) {
        this.set(User.Field.facebookEmail, facebookEmail)
    }

    /**
     * @return {boolean} 
     */
    get isAnonymous() {
        return this.get(User.Field.isAnonymous)
    }

    /**
     * @param {boolean} isAnonymous
     */
    set isAnonymous(isAnonymous) {
        this.set(User.Field.isAnonymous, isAnonymous)
    }

    /**
    * @return {number} 
    */
    get deviceToken() {
        return this.get(User.Field.deviceToken)
    }

    /**
     * @param {number} deviceToken
     */
    set deviceToken(deviceToken) {
        this.set(User.Field.deviceToken, deviceToken)
    }

    /**
    * @return {boolean} 
    */
    get isActivityVisible() {
        return this.get(User.Field.isActivityVisible)
    }

    /**
     * @param {boolean} friendActivity
     */
    set isActivityVisible(isActivityVisible) {
        this.set(User.Field.isActivityVisible, isActivityVisible)
    }

    /**
    * @return {string} 
    */
    get deviceType() {
        return this.get(User.Field.deviceType)
    }

    /**
     * @param {string} deviceType
     */
    set deviceType(deviceType) {
        this.set(User.Field.deviceType, deviceType)
    }

    /**
     * @return {string}
     */
    get inviterIdentifier() {
        return this.get(User.Field.inviterIdentifier)
    }

    /**
     * @param {string} inviterIdentifier
     */
    set inviterIdentifier(inviterIdentifier) {
        this.set(User.Field.inviterIdentifier, inviterIdentifier)
    }

    /**
     * @return {MeditationTime}
     */
    get meditationTime() {
        return this.get(User.Pointer.meditationTime)
    }

    /**
     * @param {MeditationTime} meditationTime
     */
    set meditationTime(meditationTime) {
        this.set(User.Pointer.meditationTime, meditationTime)
    }

    /**
     * @return {Parse.Relation<User, Goal>}
     */
    get goals() {
        return this.relation(User.Relation.goals)
    }

    /**
     * @return {Parse.Relation<User, UserMeditationCourse>}
     */
    get meditationCourses() {
        return this.relation(User.Relation.meditationCourses)
    }

    /**
     * @return {Parse.Relation<User, Friendship>}
     */
    get friendships() {
        return this.relation(User.Relation.friendships)
    }

    /**
     * @return {Parse.Relation<User, UserGroupSession>}
     */
    get groupSessions() {
        return this.relation(User.Relation.groupSessions)
    }

        constructor() {
            super('_User');
        }
    }

    User.SocialType = class SocialType extends Enum { }

    User.SocialType.initEnum(['facebook',
        'google']);

    User.Field = {
    objectId: 'objectId',
    email: 'email',
    username: 'username',
    password: 'password',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    firstName: 'firstName',
    // lastName: 'lastName',
    googleId: 'googleId',
    facebookId: 'facebookId',
    facebookEmail: 'facebookEmail',
    avatarPath: 'avatarPath',
    isAnonymous: 'isAnonymous',
    socialType: 'socialType',
    inviterIdentifier: 'inviterIdentifier',
    deviceToken: 'deviceToken',
    deviceType: 'deviceType',
    isActivityVisible: 'isActivityVisible',
}
    User.Pointer = {
        meditationTime: 'meditationTime'
    }

    User.Relation = {
        goals: 'goals',
        meditationCourses: 'meditationCourses',
        socialAccounts: 'socialAccounts',
        friendships: 'friendships',
        groupSessions: 'groupSessions'
    }

    module.exports = User;`

**Comment by flovilmart** [comment]
email is a protected field and can only be retrieved using the masterKet.

**Comment by flovilmart** [comment]
Consider using stackoverflow for code related questions. We do not provide such support here.

**Comment by anupmaurya484** [comment]
Already i have post stakoverflow this question, https://stackoverflow.com/questions/52362691/cant-get-users-email-in-rest-api-used-parse-dashboard, but i have not getting answer.
Thank you.

**Comment by flovilmart** [comment]
We try to provide support for bugs and when the issues are correctly formatted according to the issue template with logs etc... 

Can you provide the logs of your server when running your latest snippet?

**Comment by anupmaurya484** [comment]
Thank you for given the support , i am send you my server log.

![image](https://user-images.githubusercontent.com/36541002/45686085-18fd1700-bb69-11e8-8865-5675c579ef29.png)
![image](https://user-images.githubusercontent.com/36541002/45686129-3d58f380-bb69-11e8-8530-990880895ee8.png)

**Comment by flovilmart** [comment]
I guess you’ll be waiting a long time.

**Comment by anupmaurya484** [comment]
Can you ask me? , how many time waiting 
please ask.

**Comment by anupmaurya484** [comment]
okay i will try to found this solution but i will also wait your reply. 
If you free so please help because i'm again ask,  this issue i am face before three day.
Thank you for given time.

**Comment by flovilmart** [comment]
We do not provide support for code related questions, and your issue cannot be reproduced. Locking the thread now.
