### ISSUE TITLE
[BUG] Error message with HTTPS

### ISSUE THREAD

**Issue by stepanic** [parse-community/parse-dashboard#898]
#### Environment Setup

parse-dashboard 1.2.0, hosted on Dokku 0.12.12 on Google Cloud micro instance 

#### Steps to reproduce

Run parse-dashboard 1.2.0 on Dokku with Let's Encrypt plugin, the application is available in the browser over HTTPS but still message `Parse Dashboard can only be remotely accessed via HTTPS`

![screen shot 2018-09-17 at 11 18 15](https://user-images.githubusercontent.com/315282/45615130-f0dbbe00-ba6b-11e8-9a5c-2178a88a0d31.png)

**Comment by flovilmart** [comment]
You didn’t configure your dashboard to trust the proxy before it, as the proxy is likely to connect through HTTP. 

See https://github.com/parse-community/parse-dashboard/blob/master/README.md#deploying-parse-dashboard
