### ISSUE TITLE
Is it possible to change dashboard metrics from default (total users/installations) classes

### ISSUE THREAD

**Issue by sethpjohnson** [parse-community/parse-dashboard#929]
Less of an issue and more of a feature request, perhaps? 

I don't use the built-in `user` and `installation` classes for my projects so I was curious if there was a way to specify a specific class to count on the dashboard. With what little I know about React I was able to find this area:

https://github.com/parse-community/parse-dashboard/blob/45837b3c4b7f3eeeea7ff9b08a3f76e5a74216fc/src/dashboard/Apps/AppsIndex.react.js#L85

We can set the `Appbadge` on the previous line (84) and number of other things (background color, etc) in the configuration but I was wondering if it was possible to do this with the metrics. Adding `users` and `installations` to an apps configuration doesn't seem to do the trick.

**Comment by mtrezza** [comment]
Closing due to missing details about the expected feature; if anyone can give more details we can reopen this issue.
