### ISSUE TITLE
-bash: parse-dashboard: command not found

### ISSUE THREAD

**Issue by Wizzel1** [parse-community/parse-dashboard#942]
Hi i am getting an error after i try to access the parse-dashboard command : 

-bash: parse-dashboard: command not found

I installed node via homebrew and parse-dashboard with the command line of this git.
I have no idea whats wrong

**Comment by sidyakinian** [comment]
Same thing

**Comment by jcorlettjoe** [comment]
I'm having the same issue. Attempted to install using `npm install -g parse-dashboard` which threw up an EACCESS error. I then tried with Sudo which appeared to be more successful, until I tried to launch the dashboard and got a `-bash: parse-dashboard: command not found`

I have tried both creating a json/config file AND the single command to launch the dashboard, both with the same error?

**Comment by kzaytsev** [comment]
Same thing ((

**Comment by davimacedo** [comment]
@kzaytsev have you tried this sequence?

```
npm install -g parse-dashboard
parse-dashboard --dev --appId yourAppId --masterKey yourMasterKey --serverURL "https://example.com/parse" --appName optionalName
```

What's the error message that you have?
