### ISSUE TITLE
Parse Dashboard Hover Issue on Mobile Browsers

### ISSUE THREAD

**Issue by imnvs** [parse-community/parse-dashboard#953]
I can't edit the values on mobile browsers. 
I think it's a hover issue in the dashboard.bundle.js file.

**Comment by dplewis** [comment]
I think it’s a double click / tap issue. 

Single click selects a field

Double click edits

I guess we can change it to do single click edit for mobile.

**Comment by ramiro-ciocca** [comment]
Hi, any news on this feature? Its very important to be able to edit data on mobile browsers.  Thanks!

**Comment by davimacedo** [comment]
I think nobody has taken it yet. Would you be willed to help on this?

**Comment by ramiro-ciocca** [comment]
Sure, but wouldn't know where to start :(

**Comment by davimacedo** [comment]
I guess it is something that can be improved in this file here: https://github.com/parse-community/parse-dashboard/blob/master/src/components/BrowserCell/BrowserCell.react.js

**Comment by ramiro-ciocca** [comment]
Yes! I think the answer is in the following lines in that file:

onClick={onSelect}
onDoubleClick={() => {
if (type !== 'Relation') {
onEditChange(true)
}
For mobile, onClick should return what onDoubleClick does.
The qiestion is how to know when mobile and when desktop.
Desktop should mantain current behavior.

What do you think?

**Comment by ramiro-ciocca** [comment]
Sorry couldnt format that last comment from my phone 🤷‍♂️

**Comment by ramiro-ciocca** [comment]
Or maybe better, on mobile, onLongClick should return the edition.

**Comment by davimacedo** [comment]
It maybe a good idea. Would you be able to test it and in case it works, send a PR? If you want to go with the web browser detection approach, here it goes a very good guide: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent
