### ISSUE TITLE
substancial differences in parse-dashboard docker image sizes

### ISSUE THREAD

**Issue by drormik** [parse-community/parse-dashboard#961]
I'm assuming the docker image for parse dashboard is also supported here - 

the issue im reporting - 
the most recent parse-dashboard is 26MB in size
docker image is 76MB

a recent docker image (3 mnths ago) was much larger - 320 MB (for imageID- 7e0c6abc3d58)

was there a significant architecture change in the dashboard  ? or is there an issue here ?

Thx

**Comment by flovilmart** [comment]
We changed based images to node alpine and also used multistage image.

It considerably slims down the result image, and we’re very happy about it!

**Comment by drormik** [comment]
the improvement is very noticeable. both small imprint and fast 
great work

**Comment by flovilmart** [comment]
Glad you appreciate it!
