### ISSUE TITLE
Node Clustering results in prompt 'form tampered with' even with cookieSessionSecret set

### ISSUE THREAD

**Issue by MobileVet** [parse-community/parse-dashboard#970]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [X] Running version = 1.2.0 of Dashboard.

- [X] Running version = 2.8.2 of Parse Server.

- [X] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before. **Lots on CSRF but NONE related to Clustering w/ Throng when `cookieSessionSecret` is set or similar**

#### Environment Setup

Heroku or any other load balanced system

Node clustering via the **Throng** module
Dashboard Option `cookieSessionSecret` set

#### Setup

Setup a Parse Server w/ the Dashboard grafted on to the Express app and pass it to **Throng**

```
const dashboardConfig = ({
  apps: [{
    appId: config.APP_ID,
    appName: config.APPLICATION_NAME,
    masterKey: config.MASTER_KEY,
    production,
    serverURL: config.SERVER_URL,
    supportedPushLocales: ["en"]
  }],
  port: config.PORT,
  trustProxy: 1,
  users: [{
    user: config.DASHBOARD_USERNAME,
    pass: config.DASHBOARD_PASSWORD
  }]
})

const dashboardOptions = ({
  options: {
    allowInsecureHTTP: false,
    cookieSessionSecret: config.DASHBOARD_SECRET
  }
})

throng({
  workers: config.WORKERS,
  lifetime: Infinity
}, start)

function start() {

  // Create our Express app and force HTTPS
  const app = express()
  app.use(requireHTTPS)

  app.use('/dashboard', dashboard(dashboardConfig, dashboardOptions))
  app.use(config.MOUNT_PATH, parseServer.create())
  app.listen(config.PORT, displayEnvironment)
}
```

#### Steps to reproduce

I have found that `cookieSessionSecret` will resolve the CSRF issue when running >1 dyno on Heroku or other distributed systems... UNLESS you are Clustering.

If you are clustering, via Throng for example, even if you only use a single 'worker' you will NOT be able to use >1 dyno.  Additionally, if you cluster with >1 worker, you can't access the Dashboard.

So, if Clustering, the only way the dashboard will be accessible is if you have a **single** dyno with a **single** worker.  Otherwise you get **'form tampered with'**

It is definitely tied to the clustering because if I leave everything the same and comment out the call to Throng and replace it with *start()* the dashboard is accessible for more than 1 dyno using `cookieSessionSecret`.

**Comment by flovilmart** [comment]
Did you try using the `cookieSessionSecret` option? This should solve the issue.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MobileVet** [comment]
@flovilmart Apologies for not being more clear, I have `cookieSessionSecret` set... that is actually how it works on Heroku with >1 dyno prior to attempting Node Clustering.

Unfortunately, adding clustering changes something... and I haven't narrowed it down very far.

**Comment by dblythy** [comment]
See https://github.com/parse-community/parse-dashboard/issues/806#issuecomment-357577517

**Comment by mtrezza** [comment]
@dblythy should this comment go into the docs?
