### ISSUE TITLE
Move lib/PropTypes into its own repo?

### ISSUE THREAD

**Issue by aweary** [parse-community/parse-dashboard#98]
I really like what you guys have with [`src/lib/PropTypes.js`](https://github.com/ParsePlatform/parse-dashboard/blob/master/src/lib/PropTypes.js), especially the `describe()` option.

Would you be open to moving this to a separate repo so others could use it in their own projects?

Thanks! :tada:

**Comment by peterdotjs** [comment]
@Aweary just to keep you updated we're looking into making this happen :)
