### ISSUE TITLE
The dashboard does not work well with nested objects

### ISSUE THREAD

**Issue by dannywolfmx** [parse-community/parse-dashboard#983]
Hi.

I have the next issue:

When I save a list of generic objects and one of their children is a Parse.Pointer the dashboard does not interpret it well

Example
Original array with nested object
```JSON
[
    {
        "text": "Hello",
        "myPointerObject": {
            "__type": "Pointer",
            "className": "Producto",
            "objectId": "K4vUSfxkMx"
        }
    }

]
```

And parse dashboard made the next evaluation:

Bad formed array with nested object

```JSON
[
    {
        "text": "Hello",
        "myPointerObject":{
            "objectId": "K4vUSfxkMx"
        }
    }

]
```

The problem comes when you try to see the whole json, and the auto-save sistema of dashboard overwrite the original object to the bad formed.

I already fix the issue in the parse dashboard code, tomorrow i will make a PR with the solution.

**Comment by masonlee** [comment]
I am running into this same issue.  It looks like the Parse Dashboard is simply making "__type" and "className" properties invisible.  They are present in the mongodb entry.

**Comment by dannywolfmx** [comment]
Hi, I already made a PR solving the issue, but is still waiting to revision.

**Comment by douglasmuraoka** [comment]
@dplewis can't we just render and edit the array/object just as it was stored in the database?
It sounds like a mistake to handle Parse.Objects inside the generic array/object, since, well... that's generic and could store anything.
