### ISSUE TITLE
conflict in appName in ParseDashboard

### ISSUE THREAD

**Issue by nasermirzaei89** [parse-community/parse-dashboard#998]
Make sure these boxes are checked before submitting your issue -- thanks for reporting issues back to Parse Dashboard!

- [x] You're running version >=1.0.23 of Parse Dashboard. (1.2.0)

- [x] You're running version >=2.3.2 of Parse Server. (3.1.3)

- [x] You've searched through [existing issues](https://github.com/ParsePlatform/parse-dashboard/issues?utf8=%E2%9C%93&q=). Chances are that your issue has been reported or resolved before.

#### Steps to reproduce

1- Create 2 parse servers
2- Add both in Parse dashboard with the same appName
3- goto dashboard and you will see a conflict on app info and data, because of same name
for example
`https://parse-dashboard/apps/AppName/browser/_Role`
for both servers

#### Logs/Trace
Note: If you get a browser JS error please run `npm run dev`. This will provide source maps and a much more useful stack trace.

#### Suggestion
use app id in URL for avoiding conflict!

**Comment by acinader** [comment]
Is this really a bug?  I don't think so.  This is really more of a JSON issue than a parse dashboard issue.

We don't want to get into pre-processing the JSON to check for duplicate keys: 

https://esdiscuss.org/topic/json-duplicate-keys

We could add something to the docs to warn if someone wants to take that on...

I'd like to close this.
